### ISSUE TITLE
Error Adding MonoGame Content Builder Project

### ISSUE THREAD

**Issue by mort8088** [mono/MonoGame#1037]
STEPS TO REPRODUCE
Clean install of MonoGameInstaller-3.0.exe

Start VS2010 - 10.0.40219.1 SP1 Rel
Click new project...
Select "MonoGame" from Installed Templates
Select "MonoGame Application for Windows"
keep defaults
click "OK"

Right Click Solution in Solution Explorer
select ADD > New Project...
Select "MonoGame" from Installed Templates
Select "MonoGame Content Builder Project"
keep defaults
click "OK"

Error Shown
Microsoft Visual Studio dialog box
Message
The project file '<Path to content project file>' cannot be opened.
The project type is not supported by this installation.

ADDITIONAL
The content folder is created but empty.

**Comment by tgjones** [comment]
I think this can be closed - it's outdated now that MG has its own content pipeline.
