### ISSUE TITLE
Graphics state objects appear mutable but are applied in an immutable fashion

### ISSUE THREAD

**Issue by 7sharp9** [mono/MonoGame#1042]
The graphics state objects, for example `RasterizerState` has mutable properties like `FillMode` etc but setting these properties has no effect as the `RasterizerState` property on the `GraphicsDevice` is only ever applied if the entire property is reassigned.   

Either that state change on the graphics state objects should propagate up to the `GraphicsDevice` to make its parent property dirty or the graphics state objects themselves are immutable objects i.e. no setters.

**Comment by tgjones** [comment]
This is fixed by #3511, #3516, #3472 (and a yet-to-be-submitted PR for `SamplerState`).
