### ISSUE TITLE
MonoGame.Samples.*.MacOS samples do not work in release mode. 

### ISSUE THREAD

**Issue by andykorth** [mono/MonoGame#1043]
This  seems to be a configuration project. In Debug configuration, the symbols are correctly set to both DEBUG and MONOMAC:

http://kortham.net/temp/upshot_ZlQSorXY.png

However in the Release configuration, MONOMAC is not set, but it should be. Without MONOMAC defined, a lot of examples don't compile correctly, due to preprocessor platform checks.

**Comment by DDReaper** [comment]
Is this still an issue @andykorth 
only just come across this by chance.  If it is can you log the issue on the MonoGame.Samples project itself and I'll pick it up (if you'd be willing to test, I don't have a mac :D)

**Comment by andykorth** [comment]
There are definitely some issues, but they might be new ones. I'll make an issue at https://github.com/Mono-Game/MonoGame.Samples

**Comment by cra0zy** [comment]
@tomspilman This is an issue that's for MonoGame samples, not for the main repo, plus it's been reported there as well.
