### ISSUE TITLE
GraphicsDeviceManager Problems 

### ISSUE THREAD

**Issue by stebyrne04** [mono/MonoGame#1053]
when i  try to resize window while it is running on my mac it closes it when i ApplyChanges()

Found the Problem in MacGamePlatform.cs

in EnterFullScreen() and ExitFullScreen()
it needs line below what
//_mainWindow.MakeKeyAndOrderFront(Window);

**Comment by tomspilman** [comment]
This should be fixed with the SDL2 switch.   https://github.com/mono/MonoGame/issues/4399
