### ISSUE TITLE
GamePadState constructor with DPad state not respected in IsButtonDown

### ISSUE THREAD

**Issue by nfurtwangler** [mono/MonoGame#1055]
I'm using GamePadState constructor that takes in DPad state:

```C#
public GamePadState(GamePadThumbSticks thumbSticks, GamePadTriggers triggers, GamePadButtons buttons, GamePadDPad dPad)
```

And later checking State.IsButtonDown(Buttons.DPadUp) expecting it to be true but it never is.

Looking at the GamePadState at this time I can see that its Buttons are all "Released" but its DPad.Up is pressed.

I expect State.IsButtonDown(Buttons.DPadUp) to be true in this case.

Looking at the exact same setup running against XNA for Windows Phone I can see my expected behavior is true, and the Buttons and DPad state are identical to MonoGame at this point.

This is also how XNA behaved on Windows.

So, IsButtonDown in XNA must be checking other internal state besides just Buttons such that it can handle DPad buttons correctly.

For some background, the game engine used for Taptitude has evolved over many years and has had a keyboard input mapper that acts like a gamepad for use on Windows.  This was mostly used for testing without  needing to plug a 360 controller in during XBLIG development a while back.  We haven't used it much since then as Taptitude has been a Windows Phone game without a need for keyboard support.

Now, we want to use the same keyboard mapper to simulate a gamepad for Windows 8 development as our UI system already supports navigation via GamePad (from our Xbox 360 days) and this would give us Keyboard navigation in Windows for free.

So while hooking the keyboard input mapper back up I noticed that the keyboard mapper no longer generated input events because we used IsButtonDown to see if a button had become pressed/released and under MonoGame it isn't detecting DPad button state.

I can certainly work around the issue on our end by explicitly checking the DPad state in certain cases but this is an incompatibility worth noting.

**Comment by tomspilman** [comment]
Need someone to add this unit test into our tests and fix any issues it uncovers.

**Comment by mrhelmut** [comment]
FYI #4385 fixed the original issue.

**Comment by tomspilman** [comment]
Thanks @mrhelmut .   Let's still get this into the unit tests to ensure it doesn't creep back in again.

**Comment by mrhelmut** [comment]
I'll try to push the unit test anytime soon.

**Comment by tomspilman** [comment]
We have tests for this now.
