### ISSUE TITLE
 3.0 Beta: Window 7 Airo runs at half framerate(30Fps), non-airo at full (60Fps)

### ISSUE THREAD

**Issue by MikeNL** [mono/MonoGame#1067]
Dear MonoGame developers.

I'm currently porting an existing XNA project to MonoGame. Most is running fine, my compliments for the ease of porting!.

Now I'm running into some small things, that may be related or not related, therefore I created separate 'issues' for these.

Platform is windows 7-64, VS express 2010 and the latest develop3d build for 3.0 Beta.

-------
I have a framerate-counter running in the Draw() method, which tells me the amount of draws per second. 
When I run my application in  'graphics.IsFullScreen' set to 'false' and in non-airo mode, I get stable 60 FPS, the refresh rate of my monitor.

However when I swtich to Airo, framerate drops mostly to 30 FPS, sometimes jumping back to 60 or giving me around 45.

Doing the same in XNA4.0 keeps framerate at 60 in Airo and non-airo.

Mike.

P.S. Also when running in dual-screen mode with the  'graphics.IsFullScreen' set to 'true' and clicking in the second screen, I get a 'flash' from jumping over and framerate may then even drop to 15 FPS.

**Comment by tgjones** [comment]
I think this can be closed - without more hardware specs, it's impossible to do anything here.
