### ISSUE TITLE
NullReferenceException on game.Run();

### ISSUE THREAD

**Issue by SonicTTH** [mono/MonoGame#1084]
Hello,

I'm just trying out to convert my current xna project to the monogame framework, and it worked out very well so far, I get to compile without any errors (I followed this tutorial: http://crankgaming.blogspot.de/2012/02/xna-to-monogame.html). I needed to change some names because the names of enumerators differ a little, but thats not a problem. When I run now, I get  a nullreference exception in my Program.cs file's Main() function. It looks like this:

        static void Main(string[] args)
        {
            Nuker game = new Nuker();
            game.Run();
        }

The exception occurs on game.Run();.
I set a breakpoint at Nuker game = new Nuker();. and I saw that it was hit twice before the exception occurs, so somehow this main function is executed repeadedly?

I hope someone can help :)

I'm really much interested in this and it would be great to have this running independendly :)

**Comment by Shqrdx** [comment]
@tomspilman Outdated, obsolete,uninformative issue. the user should use standart notation(and probably dont touch Program.cs)

using (var game = new Game1())
                game.Run();

and there will not problems like this.
