### ISSUE TITLE
(iOS) OpenTK  vs OpenTK-1.0

### ISSUE THREAD

**Issue by RayBatts** [mono/MonoGame#1091]
On iOS, is there a specific reason that we're using the older OpenTK assembly?

http://docs.xamarin.com/ios/releases/MonoTouch_5/MonoTouch_5.3#OpenTK

The docs say that the API isn't backwards compatible, but with us moving fully to GLES 2.0 I don't see a reason not to make the switch. Moving to this new OpenTK-1.0 will allow us access to some newer Oes extensions that should allow us to make some more optimizations. (Such as glGenVertexArrays).

Locally I tested swapping the two out and making the necessary API changes to match the new assembly. I didn't notice any differences in a couple of test scenes I ran, but wanted to run it by everyone else before making a PR.

**Comment by tgjones** [comment]
> so this issue might be worth revisiting in a few weeks.

A "few weeks" have passed now... Is this still an issue?

**Comment by tomspilman** [comment]
So more than a year later...  what is the state of the merge between mono/opentk and opentk/opentk ?

When can we unify our OpenTK code paths on mobile and desktop?

@dellis1972 @thefiddler @Frassle @KonajuGames ?

**Comment by tgjones** [comment]
I think this is superseded by #4399.

**Comment by KonajuGames** [comment]
Yes. It has been using 1.0 for a while now. Closing.
