### ISSUE TITLE
BasicEffect state matrix bug (Linux)

### ISSUE THREAD

**Issue by jameswilddev** [mono/MonoGame#1116]
I have two separate BasicEffect objects.  At the moment they are identical save for their transformations; while one has the camera matrices (view/projection) set, the other BasicEffect is all identity as it's used for drawing some batched billboards with lots of CPU-side processing in NDC space.

The specific combination of properties is:
LightingEnabled = false;
TextureEnabled = false;
VertexColorEnabled = true;

If I Apply the first BasicEffect, draw my world geometry, then Apply the other BasicEffect and draw my billboards, they're transformed by the matrices in the first.  Had a look at the code, and making any change to either BasicEffect that changes its shaderIndex (such as disabling vertex color) fixes it.  I assume that something somewhere is looking at the two BasicEffects, believing them to be equal and skipping the Apply calls completely rather than just the shader switch.

**Comment by tgjones** [comment]
Looks like this was fixed by @KonajuGames back in December 2012.
