### ISSUE TITLE
Windows template is missing for Visual Studio 2012

### ISSUE THREAD

**Issue by patriksvensson** [mono/MonoGame#1132]
The "MonoGame Application For Windows" template should be added to the Visual Studio 2012 project template folder, and not only to the Visual Studio 2010 project template folder. Just because you're using Visual Studio 2012 it doesn't mean that you want to target Windows Store.

**Comment by tgjones** [comment]
This can be closed - MG's templates have been working in VS2012 and VS2013 for a while now.
