### ISSUE TITLE
Mouse.SetPosition in WinRt

### ISSUE THREAD

**Issue by tpastor** [mono/MonoGame#1160]
Hi,

i was looking for the implementation of the function Mouse.SetPosition in Winrt, and it is empty (actually there is no way (and no mean) to set a Mouse position in WinRt).
My question is, those kind of functions that exists on XNA by have no mean in other platforms will still exist with empty body ?
I suggest to put a deprecated message on them or simply remove where it does make sense.

**Comment by Shqrdx** [comment]
@tomspilman Since it is not possible the issue above is redundant ? Maybe release fix for restrict from using this method on WinRT platform ?

**Comment by tomspilman** [comment]
@dellis1972 @KonajuGames @cra0zy 

How should we deal with platforms where `Mouse.SetPosition()` is not possible?

**Comment by cra0zy** [comment]
> How should we deal with platforms where Mouse.SetPosition() is not possible?

For the web platform there is also no way to set mouse position, but there was a way to capture mouse(which would just give me it's relative movement), so I did something like: https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Web/WebGameWindow.cs#L88

Maybe something like: https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.uielement.capturepointer can be used?

**Comment by tomspilman** [comment]
There is no fix for this issue... it just isn't allowed on WinRT and UWP apps.  So i'm closing this.

What we are going to do is this instead https://github.com/mono/MonoGame/issues/4718.

**Comment by cra0zy** [comment]
Is UIElement.CapturePointer not working? Now I am interested... will try to set it up tomorrow.

**Comment by tomspilman** [comment]
> Is UIElement.CapturePointer not working?

I don't think that would work the same as it would under XNA.

Also `SetPosition` on the mouse is a bad idea anyway... which is why UWP and WinRT stopped supporting it.

**Comment by cra0zy** [comment]
> I don't think that would work the same as it would under XNA.
> 
> Also SetPosition on the mouse is a bad idea anyway... which is why UWP and WinRT stopped supporting it.

If we don't support it we are breaking all the FPS games...

That said we could expose a new API to allow capturing a cursor, that would solve everything (people would be able to use GetPosition to retrieve relative position when the cursor is captured).

**Comment by tomspilman** [comment]
> That said we could expose a new API to allow capturing a cursor,

That sounds like a good plan.  We can even note this new API in `Mouse.SetPosition()` as the preferred way to get relative mouse input.

**Comment by quixoticaxis** [comment]
@cra0zy also Mouse.SetPosition(int,int) can fail with NullReferenceException when closing the game which is probably not good for a static method.
