### ISSUE TITLE
Where is the comments ?

### ISSUE THREAD

**Issue by Shqrdx** [mono/MonoGame#1195]
I dont see any comment in code. I found it very frustrating. They will be included in framework ? Please answer me - I really want to know.

**Comment by tgjones** [comment]
I think at this point MG's approach to docs has pretty much been decided on (inline + SharpDoc for external docs) - can this issue be closed?

**Comment by tomspilman** [comment]
Yes... so the wrap this up.  We didn't use MonoDoc, we kept all reference docs within the code which makes it easier to write and maintain (not out of sight and out of mind), and we used the excellent [SharpDoc](https://github.com/xoofx/SharpDoc) tool.
