### ISSUE TITLE
Install MonoGame on Ubuntu 12.10

### ISSUE THREAD

**Issue by aprilrocks92** [mono/MonoGame#1197]
Hello, 

I have tried to install MonoGame on Ubuntu 12.10, but I am running into problems. 

Is there a detailed guide on how to do this, as the tutorial provided on these pages does not work for me. 

Thank you in advance!

**Comment by cra0zy** [comment]
The new xs addin is beeing worked on #3361, there are 2 things that you can do at this stage:
1) http://community.monogame.net/t/how-to-install-monogame-3-2-in-ubuntu-14-04/983/17
2) Do "sudo apt-get install monodevelop-monogame"

@tomspilman This can be closed.
