### ISSUE TITLE
GraphicsDeviceManager.ApplyChanges() on OSX exits (no crash/exception thrown)

### ISSUE THREAD

**Issue by flibitijibibo** [mono/MonoGame#1199]
On OSX I can set the resolution properly when we initialize the Game, but whenever we attempt to change the display settings (or I guess, just calling ApplyChanges()) the application will exit immediately.

I'd try to give a backtrace, but oddly the game exits gracefully without any error output.

I looked into the method in the source, and I'm not even sure where it even changes the settings. It's pretty clear where we initialize the NSWindow, but what about changing it in-game?

**Comment by prime31** [comment]
I am seeing the same issue on this one. No backtrace, no logs, nothing. The following code called anywhere outside of Initialize causes the issue:

```
			graphicsManager.PreferredBackBufferWidth = 400;
			graphicsManager.PreferredBackBufferHeight = 400;
			graphicsManager.ApplyChanges();
```

**Comment by tomspilman** [comment]
This will be fixed in https://github.com/mono/MonoGame/issues/4399.
