### ISSUE TITLE
XNA to MonoGame Conversion Errors

### ISSUE THREAD

**Issue by Reelix** [mono/MonoGame#1229]
Tried to convert my main project - These seem to be the main errors.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

Error	3	Cannot implicitly convert type 'Microsoft.Xna.Framework.Matrix[]' to 'Microsoft.Xna.Framework.Matrix[] [c:\Program Files (x86)\MonoGame\v3.0\Assemblies\WindowsGL\MonoGame.Framework.dll]'	C:\Reelix\C# Projects\XNA 4\Kal'Thoria\KTMono\GameObject.cs	241	30	Kal_Thoria

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

Error	7	'Microsoft.Xna.Framework.Graphics.GraphicsDevice' does not contain a definition for 'SetVertexBuffers' and no extension method 'SetVertexBuffers' accepting a first argument of type 'Microsoft.Xna.Framework.Graphics.GraphicsDevice' could be found (are you missing a using directive or an assembly reference?)	C:\Reelix\C# Projects\XNA 4\Kal'Thoria\KTMono\Game1.cs	1329	36	Kal_Thoria

(Note: SetVertexBuffer DOES exist - Just not the ability to set multiple at once)

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

Error	8	The type or namespace name 'VertexBufferBinding' could not be found (are you missing a using directive or an assembly reference?)	C:\Reelix\C# Projects\XNA 4\Kal'Thoria\KTMono\Game1.cs	1330	29	Kal_Thoria

(Note: https://github.com/mono/MonoGame/issues/483 )

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

Error	10	'Microsoft.Xna.Framework.Graphics.GraphicsDevice' does not contain a definition for 'DrawInstancedPrimitives' and no extension method 'DrawInstancedPrimitives' accepting a first argument of type 'Microsoft.Xna.Framework.Graphics.GraphicsDevice' could be found (are you missing a using directive or an assembly reference?)	C:\Reelix\C# Projects\XNA 4\Kal'Thoria\KTMono\Game1.cs	1350	40	Kal_Thoria

**Comment by tgjones** [comment]
I think this can be closed. The issues here already exist as separate issues:

* `SetVertexBuffers` and `VertexBufferBinding` are covered in #914
* `DrawInstancedPrimitives` is covered in #913

I don't know what Error 3 is about, but it looks like a wrong-DLL-reference issue to me.

**Comment by tomspilman** [comment]
Yep .... closing.
