### ISSUE TITLE
EnvironmentMapEffect, RenderTargetCube

### ISSUE THREAD

**Issue by XpectIT** [mono/MonoGame#1231]
I am currently porting one of my games from WP7 to Windows 8. My game uses a lot of EnvironmentMapEffect instances and the used cube maps are generated by using a RenderTargetCube. Unfortunately it seems none of this is supported with monogame.
 
First, there is no RenderTargetCube at all. I've seen that there is no RenderTargetCube at all, are there any plans to implement this class?

Second, I've tried a simple workaround by simply loading the cubemap from a file. Also this does not work (null pointer is thrown as the cubemap is null). Is that feature currently supported or not`?

Thx!

**Comment by tgjones** [comment]
`RenderTargetCube` has been implemented for a while now, so I think this issue can be closed?

**Comment by KonajuGames** [comment]
It can.  Thanks @tgjones.
