### ISSUE TITLE
No Templates in VS 2012

### ISSUE THREAD

**Issue by DVaughan** [mono/MonoGame#1296]
Hi guys, I installed what seems to be the latest updated release of MonoGame from http://monogame.codeplex.com/releases/view/100041
VS2010 templates are to be found in the Add New Project dialog, but not in VS2012. I've verified that the template zips are being deployed to 
C:\Users\Daniel\Documents\Visual Studio 2012\Templates\ProjectTemplates\Visual C#\MonoGame

I'm not sure why VS2012 Ultimate isn't picking them up. Any ideas?
I'm using Windows 8.

Cheers,
Daniel

**Comment by Shqrdx** [comment]
@tomspilman This issue should be closed. All templates are installable and vs2012 is deprecated.
