### ISSUE TITLE
Build has failed. Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ghost** [mono/MonoGame#1305]
Hello everybody,

Can you help me?
I am using monogame + monodevelop. And I get a issue that I don't know.

Well, my project has not erros neither warnings, but when I launch it, I get the message: "Build has failed. Object reference not set to an instance of an object."

Anyone knows this issue?

Thanks

**Comment by tomspilman** [comment]
I see nothing actionable here... closing.
