### ISSUE TITLE
Win8 SoundEffect crash

### ISSUE THREAD

**Issue by Korinel** [mono/MonoGame#1358]
The following code crashes SharpDX in Windows 8 with Mono 3 Stable (& beta), in XNA 4 it works as expected, it appears SoundEffect.Play always causes a crash when it uses a buffer rather than via content load.

Even correctly formed samples cause a crash (and doesn't in XNA4).

********************************************************************************
An exception of type 'SharpDX.SharpDXException' occurred in SharpDX.DLL was not handled is user code.

Additional information: HRESULT:[0x88960001], Module[Unknown],ApiCode:
[Unknown/Unknown], Message Unknown
********************************************************************************
Even playing a simple empty buffer causes a crash (works fine on XNA 4) e.g.

                byte[] sampleBufferTwo = new byte[0x4];
                SoundEffect soundEffectDynamic = new SoundEffect(sampleBufferTwo , 48000, AudioChannels.Mono);
                soundEffectDynamic.Play(); // Crash here...

********************************************************************************

**Comment by Shqrdx** [comment]
@tomspilman This issue is fixed, I tested it in Windows 8, all buffers are worked perfect.
