### ISSUE TITLE
Platform-specific internals should be public

### ISSUE THREAD

**Issue by kg** [mono/MonoGame#1391]
This is probably controversial, but I think all the platform-specific monogame internals should, where it makes sense, be publicly accessible - either as public readonly fields, or public getters, or whatever.

To give a specific example, right now using MonoGame on PSM has required me to aggressively fork the code because *all* the PSM-specific handles were private. This made it impossible to call PSM-specific APIs where required, especially in cases where what I needed to do was impossible to express through the XNA API.

I understand that this might create a risk of people writing games that are no longer 'Just XNA', but I think now that XNA is officially dead and buried this is less of a concern - especially since MonoGame can be run natively on windows. Perhaps you could set it up so a warning is generated by each line of code using these internals from outside?

**Comment by tgjones** [comment]
I don't think this issue will ever be "resolved." It's more likely that each platform-specific need will be dealt with in separately-logged issues. Since the original issue here is PSM-specific, I vote to close it.

**Comment by KonajuGames** [comment]
Closing.
