### ISSUE TITLE
Problem with  MonoDevelop AddIn on MacOSX

### ISSUE THREAD

**Issue by lavz24** [mono/MonoGame#1404]
Hi, i have a problem i use the  repo http://www.infinitespace-studios.co.uk/monodevelop/main.mrep and i have two problem:

Firts: when i create the project i get this problem: File not found: /$(ProjectName)Game.cs   , this for ios and macos template.

Second: i build and when i try run the project i have this error: 

Unhandled Exception: System.TypeLoadException: A type load exception has occurred.
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: A type load exception has occurred.

Loaded assembly: /Users/lavz24/Desktop/Hola/Hola/bin/Debug/Hola.app/Contents/MonoBundle/Hola.exe
Loaded assembly: /Users/lavz24/Desktop/Hola/Hola/bin/Debug/Hola.app/Contents/MonoBundle/MonoMac.dll [External]
//-------

I use mono Mono 2.1, MonoDevelop 3.1.1 and Mountain Lion.

**Comment by cra0zy** [comment]
The new monodevelop/xs addon is being worked on: #3361

**Comment by cra0zy** [comment]
@tomspilman This can be closed, #3698
