### ISSUE TITLE
[WinGL/Linux] Window to center

### ISSUE THREAD

**Issue by xanather** [mono/MonoGame#1414]
The WinGL/Linux window is not in the center when it is initially displayed. This creates issues when programmically changing the window (render) size, especially if the window is borderless and you are trying to create a full-screen borderless window. You would need to move the top-left position of the window to 0, 0, in order for it to be "fullscreen borderless".

I tried debugging this and it seems like the window is re-sized after the inital load, making it so whatever bounds you enter for the width/height the window will always be off-center.

Ill try fix this later but the thing is I don't know where to start, I don't know underlying MonoGame well enough. Ideas?

Some References:
http://monogame.codeplex.com/discussions/432923

**Comment by tomspilman** [comment]
@cra0zy - Is this fixed for 3.5?

**Comment by cra0zy** [comment]
Unfortunately no, OpenTK is too broken for this to work properly.

It is however fixed in the SDL branch.

**Comment by tomspilman** [comment]
Ok...  this will be fixed in https://github.com/mono/MonoGame/issues/4399.
