### ISSUE TITLE
null Parameter: xnaPlatform

### ISSUE THREAD

**Issue by SeanMoss** [mono/MonoGame#1426]
As I was going through the Content Processing tutorial at the wiki and I got to the point where you edit the .csproj to include the content pipeline target file using the <Import> field. However, I received this error upon reloading the project:

C:\VS\Projects\EffectLoadingTest\EffectLoadingTest\EffectLoadingTest.csproj : error : Value cannot be null.
Parameter name: xnaPlatform

What is this error and how to I get around it? I do not see any other examples of people having this issue, so either I am not looking hard enough or I have somehow completely messed up something.

**Comment by tomspilman** [comment]
This is no longer relevant now that we have our own content pipeline.
