### ISSUE TITLE
Test Framework Improvements

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#1476]
The current way tests are setup is cumbersome for development:

 - It is hard to find a test for a class as it is so distant from the location where the code is.
 - The tests are not included in the platform solution files... most developers probably have no clue they exist.
 - The tests are in separate submodule making it impossible to commit a fix+test together.

I suggest we consider a few things:

 1. ~~Consider moving at least the basic unit tests into the MonoGame.Framework folder itself:  Ray.cs and Ray.Test.cs.  This probably would only be beneficial if using wildcards in the test project.~~  DONE

 2. ~~Move the Tests folder into the main repository removing the old submodule.  Move the test art ("Tests/Assets" folder) into a new submodule.  Move the binaries in "Tests/Libs" into the existing thirdparty libs.~~ DONE

 3. ~~Get the tests into the automated build ASAP.  At the very least on Windows~~ and Mac.  If any tests fail we should fix them or disable them.

 4. Start making unit tests a requirement for all changes to easily testable classes like math.

 5. ~~Add unit tests for the 2MGFX tool.~~

**Comment by tgjones** [comment]
I've started to have a look at the WindowsGL tests too. Lots of them hit this assertion:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/States/SamplerState.OpenGL.cs#L36

If you ignore the assertion, the tests continue and pass. Is that a known issue?

**Comment by tomspilman** [comment]
> Lots of them hit this assertion

That is the issue where the static render states like `SamplerState` and `BlendState` don't get reset correctly after the `GraphicsDevice` shuts down.

I think pushing thru on your work in https://github.com/mono/MonoGame/pull/3472 should move is towards fixing this issue.

**Comment by tgjones** [comment]
Oops - I forgot that `SamplerState` is one of the ones affected by that :)

(Talking of which - I'm holding fire until there's a decision in #3472. If we decide to have fewer reference images, then I'll modify my last commit.)

**Comment by tomspilman** [comment]
This is pretty much done...  anything that remains should be opened as new issues.
