### ISSUE TITLE
Content.Load<Model> messes with my effect lighting

### ISSUE THREAD

**Issue by AdamDawes** [mono/MonoGame#1516]
In my Game class, I use the Initialize method to set up my lighting, including setting my effect object's DirectionalLight0 properties. I set the DirectionalLight0.DiffuseColor and .SpecularColor both to White, and these colours are applied to the objects that I render in my game.

Then I add a call to Content.Load<Model> in my LoadContent method. Just by doing this, all the lights go out, and everything in the game appears as a black silhouette. If I query the DirectionalLight0.DiffuseColor and .SpecularColor after calling Content.Load, they both still report themselves as being white, but if I then actually assign white to them again, the lights switch back on.

I've worked around this for now by adding the following code to the end of my LoadContent method:

    _effect.DirectionalLight0.DiffuseColor = _effect.DirectionalLight0.DiffuseColor;
    _effect.DirectionalLight0.SpecularColor = _effect.DirectionalLight0.SpecularColor;

i.e., setting the light colours to be their existing values. This resolves the problem. I'm not sure why loading a model is causing my lights to stop working, but it'd be great if they didn't do this.

An example of this can be seen in the example project here: http://adamdawes.com/private/MonoGameXFile.zip . The code as provided displays the model as a totally black silhouette. By adding the lines of code shown above to the end of the LoadContent method (after the call to Content.Load), the lighting begins to work again. (Ignore the fact that the texture doesn't appear and there's a hole in the house model, those are separate issues.)

Tested against MonoGame 3.0.0.0 in Windows 8 and Windows Phone 8.

**Comment by tgjones** [comment]
#1542 has been merged now, so this can probably be closed. Seems like other people should have noticed it by now if it's still an issue.
