### ISSUE TITLE
says XNA not found when trying to build iOS project through xamarin studio

### ISSUE THREAD

**Issue by Mmarzex** [mono/MonoGame#1564]
I keep trying to build the default iOS monogame template on xamarin studio and it just says that 
"The type or namespace name 'XNA' does not exist in the namespace 'Microsoft'"

Why would this be?

**Comment by tgjones** [comment]
@dellis1972 Is this still an issue? If it's not fixed already, I guess it's very likely to be fixed as part of your work on the new XS addin.

**Comment by cra0zy** [comment]
#3361
