### ISSUE TITLE
Suggestion: Add basic shape primitives for quick and easy prototyping

### ISSUE THREAD

**Issue by adamkdean** [mono/MonoGame#1584]
I think it would be a great idea to add some basic shape primitives to MonoGame to assist in quick and easy prototyping. For example: Circle, Rectangle, and Triangle shapes.

They should be easy to use; the easier, the better. This allows for rapid development.

    // easy to create
    var circle = new Circle(100f, 100f, 50f, Color.Violet, graphics);

    // easy to draw
    circle.Draw();

An example can be found here: http://www.adamkdean.co.uk/blog/read/54/circle-primitive-class-for-xna-monogame

**Comment by LithiumToast** [comment]
@adamkdean We have basic shapes for 2D in https://github.com/craftworkgames/MonoGame.Extended

**Comment by adamkdean** [comment]
Thanks for the response, @LithiumToast, but I'm not actually working on this any more, being three years on. Now I've got a son on the way and really the only shapes I'm going to be needing will be wooden ones!

All the best.

**Comment by LithiumToast** [comment]
@adamkdean Could you close this issue then? Thanks

**Comment by KonajuGames** [comment]
Closing.
