### ISSUE TITLE
OpenAL - DllnotFound is fatal

### ISSUE THREAD

**Issue by totallyeviljake** [mono/MonoGame#1654]
If openal is not installed or not accessible, then the cal to Alc.OpenDevice in OpenALSoundController (WindowsGL project for testing) will throw DllNotFoundException, which is not handled.

This should have been handled when the OpenALSoundController was ractored to handle openAL open failures.

**Comment by manio143** [comment]
I know it's an old issue, but I'm experiencing a similar problem and was wandering: has it been fixed?

**Comment by mrhelmut** [comment]
The fix is pending in the pull request #4874.
I believe you can use cra0zy:NewSDL branch if need be, or grab the development installer from the PR tests.

**Comment by Jjagg** [comment]
Fixed in #4874.
