### ISSUE TITLE
WinForms And MonoGame

### ISSUE THREAD

**Issue by twoski** [mono/MonoGame#1714]
Hello all!

This is not an "issue" per se. I read somewhere a while ago that MonoGame was going to have added support for WinForms eventually. I am just checking to see what progress has been made thus far. I am working on a little game project and I want to create child forms/elements for my game window. I've seen tutorials on getting WinForms and XNA working together but they're all hacky/outdated. 

Any input/suggestions/help is greatly appreciated.

**Comment by tgjones** [comment]
I think this can be closed - MG's `SwapChainRenderTarget` now enables interop with WinForms.
