### ISSUE TITLE
Linux and sprite fonts

### ISSUE THREAD

**Issue by thelinuxlich** [mono/MonoGame#1717]
I see there is a lot of work on content pipeline, but I'm not able to find anywhere if Monogame on Linux is ready to process .spritefont files, if it is, how should I proceed? I've tried compiling MGCB with the Linux solution, but the executable can't build spritefont files. Is this feature implemented?

**Comment by cra0zy** [comment]
This should be fixed:
#3298
https://github.com/Mono-Game/MonoGame.Dependencies/pull/34
