### ISSUE TITLE
Visual C# 2010 does not copy SDL.dll

### ISSUE THREAD

**Issue by flamedra** [mono/MonoGame#1720]
Whenever I create a new MonoGame Windows OpenGL Project, and then try to run it in debug mode, I get the following error :

Error	1	Unable to copy file "C:\Users\Program Files (x86)\MonoGame\v3.0\Assemblies\WindowsGL\SDL.dll" to "bin\WindowsGL\Debug\SDL.dll". Could not find a part of the path 'C:\Users\Program Files (x86)\MonoGame\v3.0\Assemblies\WindowsGL\SDL.dll'.	GameName1

So I have to delete the SDL.dll file from the Solution Explorer and then manually add it, every time I create a new project.

How can I make it so it does this automatically?

**Comment by misu-pwnu** [comment]
Yes.

Thanks to kelathor for his solution.

**Comment by cra0zy** [comment]
@tomspilman This can be closed, sdl isn't even used anymore because of #3832

**Comment by Celarix** [comment]
@kelathor got it. Turns out copying an existing MonoGame project to a new folder can cause a few problems.
