### ISSUE TITLE
GameWindow.Handle returns IntPtr.Zero when compiled with the Linux solution.

### ISSUE THREAD

**Issue by ClassicThunder** [mono/MonoGame#1736]
Currently the property Handle in the class OpenTKGameWindow looks like below. 

```
public override IntPtr Handle { get { return IntPtr.Zero; } }
```

However if you add the below to Initialize() you can actually set the pointer and return it. Very very useful to people like me making 3rd party libraries to compliment MonoGame. 

```
var ii = window.WindowInfo;
object inf = window.WindowInfo;
var pi = (inf.GetType()).GetProperty("WindowHandle");
_windowHandle = ((IntPtr)pi.GetValue(ii, null));
```

And now the handle property can be useful.

```
public override IntPtr Handle { get { return _windowHandle; } }
```

I hope this is helpful and can be added in. Access to the underlying window when working with Linux would be very nice.

**Comment by cra0zy** [comment]
@tomspilman This has been fixed.
