### ISSUE TITLE
Cannot build for MacOSX platform

### ISSUE THREAD

**Issue by robcowell** [mono/MonoGame#1743]
Using the standard MonoGame project template for MacOS, I cannot build, instead I get :-

Build failed. Could not find a part of the path "/Platforms/MacOSX.platform/info.plist"

MonoDevelop : 3.0.5
MonoGame: 3.0.1
Mono 3.0.10
XCode: 4.6.2

I *can* build MonoMac apps, which hints at dependencies existing, but I'm kinda lost from here

**Comment by cra0zy** [comment]
The new monodevelop/xs addon is being worked on: #3361

**Comment by cra0zy** [comment]
@tomspilman This can be closed, it's been fixed with #3698
