### ISSUE TITLE
Drawing a texture with a source rect does not render correctly on PSM

### ISSUE THREAD

**Issue by AlanDavies** [mono/MonoGame#1753]
Hi, when rending a texture with a source rectangle the texture does not always render  correctly on PSM e.g. the gaps between the gray tiles should not be there.

![screenshot010](https://f.cloud.github.com/assets/4532526/565303/ca7d56c0-c600-11e2-88f7-adcd2a8853e9.png)

**Comment by tgjones** [comment]
@tomspilman PSM support was removed in #4016, so this can be closed.

**Comment by KonajuGames** [comment]
Closing.

**Comment by tomspilman** [comment]
Thanks for finding these @tgjones !  :)

**Comment by tgjones** [comment]
@tomspilman I have a dream that one day we'll have < 500 issues :)

**Comment by tomspilman** [comment]
I wish the same...  but just not enough people contributing to catch up at this time.

**Comment by tgjones** [comment]
@tomspilman I'm not casting blame! Sorry if that's how it sounded. I suspect that a lot of open issues are obsolete in some way, like this one; I'll keep picking them out when I have time.

**Comment by tomspilman** [comment]
I didn't think you were blaming anyone.  I just feel the same way about it.
