### ISSUE TITLE
[Linux] Window bounds not reset on fullscreen. 

### ISSUE THREAD

**Issue by ghost** [mono/MonoGame#1769]
The issue looks to be right here. https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Desktop/OpenTKGamePlatform.cs#L183

The parameter here should be true. 

Right now, what it's doing, is making a 640x480 box in the lower left corner that is usable. The origin for this box is in its upper left corner.
 
![Illustration](https://f.cloud.github.com/assets/1864940/607496/6197207c-cd45-11e2-9ef1-a6fa72df18e5.png)

**Comment by cra0zy** [comment]
@tomspilman This has been fixed.
