### ISSUE TITLE
How to build MonoDevelop AddIn on GNU/Linux?

### ISSUE THREAD

**Issue by simendsjo** [mono/MonoGame#1780]
I'm unable to find any documentation on how to build the MonoDevelop AddIn for Linux.

The addin.xml references dlls in the assemblies directory, but it by default adds all platforms.
Seems the main files added are the ones in the WindowsGL directory.

It would be great if someone could write a short instruction for building the addin.

Thanks.

**Comment by cra0zy** [comment]
The new monodevelop/xs addon is being worked on: #3361

On how to build the existing one, well you have to create assembly folder in bin/Debug\Release, copy all the assemblies to assembly folder, add all of them to addin.xml file for runtime and Extension > Package, fix a little bit of broken code in MonoGameProject, change MonoDevelop.Core and other 4 references in addin.xml to whatever version of monodevelop you use and that's about it.

Also I try to keep monogame updated until the new xs addin is ready: http://community.monogame.net/t/how-to-install-monogame-3-2-in-ubuntu-14-04/983/17

**Comment by cra0zy** [comment]
@tomspilman This can be closed since #3698 , also the XS/Monodevelop addin is now only buildable from OS X.
