### ISSUE TITLE
Multi-Device Rendering

### ISSUE THREAD

**Issue by nightst4r** [mono/MonoGame#1823]
I'm testing out having multiple sub windows each with their own GraphicsDevice.  I was able to locate a bunch of places where monogame isn't multi-device friendly, static cache in Effect, Sampler States, RenderStates ( Blend, Raster, etc).  I've managed to get around all of them, but now I seem to crash on one I can't figure out. Does anyone know what could cause this to crash:

```C#
//In TextureCollection.cs

#elif DIRECTX
                if (_textures[i] == null || _textures[i].IsDisposed)
                    pixelShaderStage.SetShaderResource(i, null);
                else
                    //HERE
                    pixelShaderStage.SetShaderResource(i, _textures[i].GetShaderResourceView());
```

It seems to me like the texture is loaded from the previous device context, but I was able to see it for one frame before it crashed.

Any ideas?

Also, would my multi-device rendering changes be useful to check in? As it stands, without them the Debug.Assertions just fail.

**Comment by christallire** [comment]
I'm working on this to host multiple 'Game' in single process.

I prefer @nightst4r 's initial approach with GraphicsDeviceContext @tomspilman mentioned.
although more defensive code is required to prevent multi threading issues, so far so good w/o any problem in windows.

**Comment by tgjones** [comment]
I think this can be closed now. There are already separate issues for making it easier to embed the `Game` class - i.e. #2856 - so I think this one was really just about removing the `static` per-GraphicsDevice stuff, which is now done.
