### ISSUE TITLE
Ability to write directly to the pixel back buffer

### ISSUE THREAD

**Issue by adamrezich** [mono/MonoGame#1839]
(Or, failing that, directly manipulate texture or render target pixel data.)

I'm fairly inexperienced with game development in general, but I've done some stuff with XNA in the past, and now I'm trying to get back into it with MonoGame. I want to make a game that uses [Cairo](http://cairographics.org/) to draw some vectory goodness, but I'd like to use MonoGame as a framework because of how easy it makes the game loop and input functionality and stuff. Plus it can work cross-platform, sorta! So yeah, I'd like to not only make a game with Cairo and MonoGame, but also a framework to make other games like this. I'm a programmer and not an artist, so the idea of just drawing 2D stuff with math appeals to me.

[The problem I'm running up against](https://github.com/adamrezich/arena/blob/master/VGame/VGame.cs) is that it's just too darn slow to do what I'm doing, which is:

- Draw the scene with Cairo through a Cairo.Context to a Cairo.Surface every frame
- Copy the data from the Cairo.Surface to a Texture2D using SetData()
- Draw the Texture2D using SpriteBatch

Every single frame.

This is hecka slow, as it turns out! I've looked everywhere I can, but I can't seem to find any way of directly accessing the screen buffer and writing pixel data to it using MonoGame or XNA. Is there any chance at all that there could end up being a way of directly accessing the pixel buffer data to more easily facilitate this? I know it's kind of a niche issue, but hey, it never hurts to ask, right?

I see that XNA provides [GraphicsDevice.GetBackBufferData](http://msdn.microsoft.com/en-us/library/microsoft.xna.framework.graphics.graphicsdevice.getbackbufferdata.aspx)... is there any chance that this data could just be exposed and directly read from/written to?

I eventually also found [this](https://github.com/kevingadd/Fracture/blob/master/Squared/RenderLib/Evil.cs) (from [this article](http://www.altdevblogaday.com/2011/10/02/copying-pixels-from-a-pointer-to-an-xna-texture2d/), which a.) I'm assuming won't work in MonoGame because DirectX and b.) wouldn't be cross-platform because of the System.Reflection and such.

**Comment by tomspilman** [comment]
There was no consensus on a feature here, so I am closing this.  The most we could do if this comes up again is allow for a faster `SetData` on the texture/target but it likely still would not be fast enough for what the developer required.  This just isn't how you work with modern GPUs.
