### ISSUE TITLE
Dynamically created textures are drawn upside down in PSMobile

### ISSUE THREAD

**Issue by jalf** [mono/MonoGame#1843]
If you create a render target and put it on screen, it's shows upside down!

Sample:

renderTarget = new RenderTarget2D(...
device.SetRenderTarget(renderTarget);
// draw stuff
graphicsdevice.SetRenderTarget(null);
myTexture = (Texture2D)renderTarget;
spritebatch.Draw(myTexture..

Something with the transformation matrix, perhaps?

**Comment by tgjones** [comment]
@tomspilman PSM support was removed in #4016, so this can be closed.

**Comment by KonajuGames** [comment]
Closing.
