### ISSUE TITLE
Solving the OpenTK mess

### ISSUE THREAD

**Issue by prollin** [mono/MonoGame#1863]
While experimenting with multisampled rendertargets on Android and iOS for our game Infinite Flight, I found that a good option to solve the OpenTK mess (implementation differences on each platform, extension support always behind ... etc) would be to simply create the bindings ourselves where we need them instead of having to rely on yet another external dependency.
OpenGL bindings are usually only needed in one place which would make things very simple to debug and maintain. Below is an example of how it could look for the RenderTarget2D class.

```
public class RenderTarget2D : Texture2D, IRenderTarget
{
#if GLES
    [DllImport(Platform.LibGLES, EntryPoint = "glRenderbufferStorageMultisampleIMG")]
    private extern static void GLRenderbufferStorageMultisampleIMG(All target, int samples, All internalformat, int width, int height);
    [DllImport(Platform.LibGLES, EntryPoint = "glRenderbufferStorageMultisampleEXT")]
    private extern static void GLRenderbufferStorageMultisampleEXT(All target, int samples, All internalformat, int width, int height);
```
I would even recommend to declare the necessary OpenGL enums in place to make it easy for more contributors to understand the code.

MonoGame/XNA is already a wrapper ... it would probably be best for it to directly access the native API instead of relying on another wrapper (OpenTK or whatever comes next).

The great thing about this is that it is a change that could happen gradually with small and focused pull requests, starting with current missing functionality in MonoGame.

**Comment by tgjones** [comment]
I think this is superseded by #4399?

**Comment by KonajuGames** [comment]
Closing.
