### ISSUE TITLE
DynamicSoundEffectInstance unimplemented

### ISSUE THREAD

**Issue by absurdhero** [mono/MonoGame#1875]
The Xna.Framework.Audio.DynamicSoundEffectInstance class is stubbed out but is almost entirely unimplemented.

It needs an OpenAL implementation for Mac, iOS, and other platforms.
Pull request #1796 is for a Windows implementation but we are not targeting that platform for our application.

**Comment by tomspilman** [comment]
We dropped the ball on this completely... closing in favor of new issue https://github.com/mono/MonoGame/issues/4700.
