### ISSUE TITLE
Song issue seems to persist on WinDX.

### ISSUE THREAD

**Issue by Hardycore** [mono/MonoGame#1954]
I saw pull #1874 had apparently fixed this on the WinDX project.  However I'm still getting the exact same error occurring on the catch call.  Same exact issue.  It'll play occasionally, but usually just throws the exception referenced in #1874.

Brought it up here.  https://monogame.codeplex.com/discussions/453847

Could someone confirm this this should be fixed, and if so, what would cause it to still occur for me?  I even went as far as to delete and re-download the whole repo just to make sure I was all up to date.  I'm hoping to release a windows title in a few weeks so I really appreciate any input on this.

**Comment by MichaelDePiazzi** [comment]
FYI - This was fixed by PR #4044
