### ISSUE TITLE
StorageRoot on PSM

### ISSUE THREAD

**Issue by ghost** [mono/MonoGame#1957]
I Used StorageRoot on PSM would throw a Error of Win32.io
The returned Code is 1168 Dir not found
Then I found some topic like this in PSM DevPortal
I saw "/Documents" in this Topic
http://community.eu.playstation.com/t5/General/Write-text-file/td-p/15887357

i try to use "/Documents" as StorageRoot, it works

sorry for my english

**Comment by tgjones** [comment]
@tomspilman Presumably this issue is obsolete, given #3607?

**Comment by KonajuGames** [comment]
Closing.
