### ISSUE TITLE
Texture2D.GetData not working when SurfaceType is Texture

### ISSUE THREAD

**Issue by jnewc** [mono/MonoGame#1983]
When calling Texture2D.GetData, the returned color array is empty (zero-filled) due to the following commit:

https://github.com/mono/MonoGame/pull/1709/commits

If I remove the condition of the SurfaceType being RenderTarget (i.e. because the SurfaceType is Texture) I am able to retrieve color data as I do on any other platform.

Additionally, I also had to change line 604 of Texture2D.cs to the following:

```
frame_buffer.SetColorTarget(_texture2D, 0);
```

**Comment by tgjones** [comment]
This can be closed - the code has changed a lot since then, and I can't see any platforms still doing the `== SurfaceType.RenderTarget` check.
