### ISSUE TITLE
[PSM] Texture2D instances are not disposed correctly.

### ISSUE THREAD

**Issue by jnewc** [mono/MonoGame#2013]
When attempting to free resources (which is a frequent task given the limited resource heap) using Content.Unload, textures are not released because Dispose is never called on the native Sce.Playstation.Core.Graphics.Texture2D object.

I'm using the following workaround (added to Texture2D.cs):

```
        protected override void Dispose (bool disposing)
        {
            base.Dispose (disposing);
    
            if(_texture2D != null)
                _texture2D.Dispose();
        }
```

**Comment by tgjones** [comment]
@tomspilman PSM support was removed in #4016, so this can be closed.

**Comment by KonajuGames** [comment]
Closing.
