### ISSUE TITLE
GamePad-API-compatible GamePadEx?

### ISSUE THREAD

**Issue by groundh0g** [mono/MonoGame#2139]
It looks like GamePad.Visible is a MonoGame extension. How would you feel about a parallel extension for keyboard mapping so that games can just target the GamePad? 

When the mapping is not present, GamePad would ignore key states -- just like it ignores the virtual GamePad logic when Visible is false.

*This suggestion stems from my frustration at GamePad support on Mac.* I have to write a mapper anyway (unless you guys have already done it).

I could get really fancy and allow the mapping to include the mouse position and buttons as mappable entities.

Thoughts?

**Comment by tomspilman** [comment]
We have no plans to support any of this... closing.
