### ISSUE TITLE
PS3 Controller Mappings on OS X?

### ISSUE THREAD

**Issue by groundh0g** [mono/MonoGame#2154]
Has this already been addressed by another PR? To get my PS3 controllers working, I had to tweak the logic / mappings in Desktop/Input/GamePad.cs:AutoConfig().

Closest I saw in existing issues were for:

* 360 controller on OS X (https://github.com/mono/MonoGame/issues/1614) and 
* official PS3 controller on Linux (https://github.com/mono/MonoGame/pull/177).

I've tested the fix with 3rd-party and official controller. If someone's not already working the issue, I can do a branch and PR for this.

**Comment by cra0zy** [comment]
@tomspilman This can be closed because of #3633.
