### ISSUE TITLE
Monogame Effect loading problem

### ISSUE THREAD

**Issue by mitko9000** [mono/MonoGame#2189]
Hello guys I have this effect :
http://dox.bg/files/dw?a=77dc768bfc
and I am trying to load it but it fails with unhandled exception.
This file is inside Assets/Content/Shader
and thats the way I am loading it:
Effect bloomExtractEffect = Content.Load<Effect>(@"Shaders/GaussianBlur");

**Comment by tgjones** [comment]
Can this be closed? There aren't really enough repro steps here to figure out what the problem is - but it doesn't seem to be an actual bug with MG, more likely an issue with getting the content pipeline up and running.
