### ISSUE TITLE
Proposal / Request for Feedback: Transition to a rolling release model

### ISSUE THREAD

**Issue by hach-que** [mono/MonoGame#2281]
So I was looking at the new MonoGame site and I've realised that the latest official release was 3.0.1, which is now quickly approaching over a year ago.  Looking at the differences between master and develop on GitHub reveals:

"This branch is 26 commits ahead and 1993 commits behind develop"

Originally I used to use the official releases, but transitioned to using development builds and eventually went to using MonoGame as a Git submodule.  While I've found that the latter option offers far more flexibility in terms of updating to get bug fixes, I still understand that some people like just referencing DLLs or binaries.

That said, I don't think the official versioned releases are offering a lot of value right now.  Although they're promoted on the downloads page, they've 1993 commits behind the latest development head.  That is **a lot** of work, both functionality and bug fixes, which aren't right now being promoted to people who are new to MonoGame.  A prime example of this is the work being done on the content pipeline, which is now reasonably usable (I use the APIs in my higher-level engine without issue) but is not available to users of 3.0.1.  I believe the last release date (3rd March 2013) also creates a perception of "no longer developed", even though this is far from the case.  

So the general proposal is something like this:

  * Promote "develop" as the new stable, official version for people to be using.  That is, the installers and DLLs that are generated from the develop branch are the ones promoted on the website.
  * The current official versioning is moved to an "older releases" section on the download page, with a note that MonoGame uses rolling releases (and hence there is no explicit versioning).
  * This has the added advantage that any bug reports that are coming through are going to be relevant and up-to-date, and bug fixes can likely be fixed by people grabbing the latest DLLs (or updating the Git submodule).

What do people think of this proposal?

**Comment by tomspilman** [comment]
So this is finally happening...

 - I settled on a Major.Minor.0.Build version number.
 - The versioning is now controlled by the TeamCity setting.
 - All assemblies and installers now show the version.
 - We added unit tests into the build process.
 - Working on getting the Windows installer EXE signed.
 - Added new Linux and Mac installers.

I plan to release 3.3 next week as the first of our more frequent release schedule.  Somewhere between Monthly and Quarterly... depending on the activity on the project.

**Comment by tomspilman** [comment]
Thanks to @DDReaper who pushed me on this in https://github.com/mono/MonoGame/issues/3300.

**Comment by DDReaper** [comment]
Fantastic effort @tomspilman you are an awesome machine at getting this all out there!

**Comment by hach-que** [comment]
Yay rolling release :D
