### ISSUE TITLE
Mixed Licenses (MIT, Dual MSPL/LGPL, GPL!)

### ISSUE THREAD

**Issue by flibitijibibo** [mono/MonoGame#2282]
So we've been doing a full sweep of the MG-SDL2 code, as part of the process of making FNA:

https://github.com/flibitijibibo/MonoGame

We're noticing a LOT of various files with varying licenses. Here are the ones we've found so far:

- LzxDecoder.cs is released under a dual MSPL/LGPL license. This one's fine, but I only noticed it once we were editing all the files in `Content/`. Might need to be noted somewhere.
- Various files throughout the project, particularly the ContentReaders, have the Mono.Xna license, the MIT license. Was this all re-licensed under the MSPL when the MonoGame project became a thing, or are these license headers accurate? In the latter case, this may need to be noted in the main LICENSE file.
- Vector4, SpriteFont and ReflectiveReader have code from SilverSprite, another MIT-licensed project. Same question as the Mono.Xna project, basically.

And while this doesn't quite affect the FNA project in the same way, now that I've rewritten the Audio engine there, I figured the MonoGame team ought to know: The XACT WaveBank implementation in MonoGame right now is a C# copy of Luigi Auriemma's unxwb project... which is released under the GPL. Far as I know, there's been no re-licensing of that code, so this could be a serious legal problem for a LOT of projects out there. I'm actually still auditing everything in MG-SDL2's XACT reimplementation to be sure that everything I got was from either MonoGame as brand new information (for instance, the byte-to-float volume calculation) or from a different source altogether (i.e. various wikis with bits and pieces of XACT binary info, published under a permissive license). But yeah, that was a fun discovery.

Anyway, this is what we've found so far; I'll update if we find any more oddities regarding licenses.

**Comment by tomspilman** [comment]
Closing the loop on this issue.

I did hear back from the old MonoXNA team... they have no issue with our use of their code in this project.   What we have done in our license:

https://github.com/mono/MonoGame/blob/develop/LICENSE.txt

Is acceptable and this issue can be closed.
