### ISSUE TITLE
Mouse.SetPosition moves the mouse to the wrong position when the cursor is hidden on Linux

### ISSUE THREAD

**Issue by csantosbh** [mono/MonoGame#2283]
**The problem**
If the window border is visible, the cursor drifts on the y coordinate to the bottom. If the borders are not visible, the cursor is not internally moved to the requested position.

**Local information**
This was tested on Ubuntu 12.04 x86 with gnome 3.4.2.1, on a MSI gx660r (a notebook with an ATI HD5870 video card).

**To reproduce**
Run the following code. Click to set the mouse on the requested position.
```c#
using System;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;

namespace MouseTest {
	public class Game1 : Game {
		GraphicsDeviceManager graphics;
		SpriteBatch spriteBatch;
		private Texture2D _cursor;
		private Vector2 cursorPos;

		public Game1 () {
			graphics = new GraphicsDeviceManager (this);
			Content.RootDirectory = "Content";
			graphics.IsFullScreen = false;		
			graphics.PreferredBackBufferWidth = 640;
			graphics.PreferredBackBufferHeight = 480;
			//Window.IsBorderless = true;
			IsMouseVisible = false;
		}

		protected override void LoadContent () {
			spriteBatch = new SpriteBatch (GraphicsDevice);
			_cursor = Content.Load<Texture2D>("cursor3");
		}

		protected override void Update (GameTime gameTime) {
			KeyboardState _kbs = Keyboard.GetState ();
			if (_kbs.IsKeyDown (Keys.Escape)) {
				Exit ();
			}

			MouseState _mouseState = Mouse.GetState ();
			if (_mouseState.LeftButton == ButtonState.Pressed) {
				Mouse.SetPosition (graphics.PreferredBackBufferWidth / 2, graphics.PreferredBackBufferHeight / 2 - 1);
			}
			_mouseState = Mouse.GetState ();
			cursorPos = new Vector2 (_mouseState.X, _mouseState.Y);

			base.Update (gameTime);
		}

		protected override void Draw (GameTime gameTime) {
			graphics.GraphicsDevice.Clear (Color.CornflowerBlue);
		
			// Draws cursor
		    spriteBatch.Begin();
		    spriteBatch.Draw(_cursor, cursorPos, Color.White);
		    spriteBatch.End();
            
			base.Draw (gameTime);
		}
	}
}
```

**Solution**
This is a two step solution issue. When the cursor is hidden, it seems that OpenTK's OpenTK.Input.Mouse.SetPosition expects the coordinates to be specified as an offset with respect to the previous mouse position (which must be translated to the center of the screen). This can be fixed in Input/Mouse.cs.

The second issue is that the cursor centering on OpenTK is made with respect to the whole window (including its borders), which means it cannot be computed as (width/2, height/2), and depends on the windowing system. This needs to be fixed in OpenTK, on Platform/X11/X11GLNative.cs.

I'll be submitting patches for these issues shortly.

**Comment by cra0zy** [comment]
@tomspilman This has been fixed. I've even tested it just to make sure.
