### ISSUE TITLE
PortraitOrLandscape support for Wp8

### ISSUE THREAD

**Issue by Alphapage** [mono/MonoGame#2332]
Hello,
I'm running the last beta develop version of Monogame for wp8.
When I run my game in Portrait or Landscape mode, no problem.
But as soon as I try PortraitOrLandscape mode, only Portrait is displayed correctly and when orientation changed to landscape, the Window.ClientBounds remains in portrait size and CurrentOrientation is still Portrait.
Maybe I'm missing something.
Thanks in advance for your help.

**Comment by rboelen** [comment]
I have simular problems on WP8.

I noticed that when you explicitly specify the supported orientations like:<pre><code>
 graphics.SupportedOrientations = DisplayOrientation.LandscapeRight | DisplayOrientation.LandscapeLeft | DisplayOrientation.Portrait | DisplayOrientation.PortraitDown;</pre></code>

the orientation changes according to the actual orientation. But Viewport width & height remain the same, which is not expected, might be a bug.

I did some comparing of the code between WP8 and Win8 and there is some significant difference. The Win8 stuff viepwort changes as expected when changing orientation.
