### ISSUE TITLE
Impelement RenderTargetCube for OpenGL

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#2411]
Implement the OpenGL version of RenderTargetCube.

See [RenderTargetCube.cs](https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/RenderTargetCube.cs).

Should probably do the same platform abstraction as we have on RenderTarget2D.

**Comment by tgjones** [comment]
I'm going to have a go at this.

**Comment by tomspilman** [comment]
Thanks @tgjones !
