### ISSUE TITLE
3.2 release assembly info was not updated, still at 3.1.2

### ISSUE THREAD

**Issue by DDReaper** [mono/MonoGame#2467]
In some testing today I noted that the assembly version for the 3.2 release was not updated.  It is still at 3.1.2

Minor thing but something to be aware of when people log issues about MG versions

**Comment by tomspilman** [comment]
We've addressed these issues... closing.

**Comment by DDReaper** [comment]
Just double checked on my local machine and the assembly version is updated.
However, the installer and the install folder are still the old releases.

The installer is the big one as when devs download the dev MSI, they see no difference.

**Comment by tomspilman** [comment]
I am aware...  and it is being solved right this second.

https://github.com/mono/MonoGame/pull/3408

**Comment by DDReaper** [comment]
Fair enough, thanks Tom
