### ISSUE TITLE
PSM platform calls Net.Session.Exit in PSSGamePlatform.cs 

### ISSUE THREAD

**Issue by DDReaper** [mono/MonoGame#2513]
Whilst doing the NET separation I came across a reference to the .NET namespace in PSSGamePlatform.cs

On line 105/106 it calls:
Net.NetworkSession.Exit();

This isn't done on any other platform except Android and Angle

It has been commented out as part of the .NET work, can this be investigated to ensure it is not needed.

**Comment by tgjones** [comment]
@tomspilman PSM support was removed in #4016, so this can be closed.

**Comment by KonajuGames** [comment]
Closing.
