### ISSUE TITLE
Building a spritefont crashes MonoDevelop

### ISSUE THREAD

**Issue by mcjohnalds** [mono/MonoGame#2521]
If I do the following steps with the content pipeline addin, MonoDevelop crashes.

* Create a MonoGame Content Project
* Create a spritefont file (using the wizard thing)
* Set the FontName node to the name of a ttf file
* Build project

I'd like to add, if the FontName isn't valid (and therefore building gives an error), or if there's no spritefiles. MonoDevelop doesn't crash on build.

I'm using MonoDevelop 4.0.12 on Ubuntu 13.10.

**Comment by cra0zy** [comment]
@tomspilman This is connected to the old pipeline, and since it has been removed in #3617 this can be closed.
