### ISSUE TITLE
MonoDevelop addin doesn't work

### ISSUE THREAD

**Issue by mcjohnalds** [mono/MonoGame#2530]
I can't get the project templates working, here's the steps I took:

1. Built MonoDevelop.MonoGame.Linux project from MonoDevelop.MonoGame.sln from monogame 3.2 (stable release) successfully.
2. Placed resulting files (icons dir, templates dir, MonoDevelop.MonoGame.dll) into ~/.local/share/MonoDevelop-4.0/LocalInstall/Addins/MonoDevelop.MonoGame/
3. Restarted MonoDevelop. No new solution templates are available, also, nothing new is in the addin manager.
4. Moved MonoDevelop.MonoGame directory into /usr/lib/monogame/
5. Restarted MonoDevelop. Still not working.
6. Repeated steps for monogame's develop branch. with same result.

I'm using MonoDevelop 4.2.2 on Ubuntu 13.10.

**Comment by cra0zy** [comment]
The new monodevelop/xs addon is being worked on: #3361

**Comment by cra0zy** [comment]
@tomspilman This can be closed, it has been fixed with #3698
