### ISSUE TITLE
MacOS GUID Mixups

### ISSUE THREAD

**Issue by totallyeviljake** [mono/MonoGame#2560]
Old MacOS Project GUIDs (ref 6/21/2013)

Framework: 36C538E6-C32A-4A8D-A39C-566173D7118E
LIdgren : AE483C29-042E-4226-BA52-D247CE7676DA

Today:

Framework: 1294038B-66C2-4359-AFE9-EA06A758CA94
Framework.Net : 36C538E6-C32A-4A8D-A39C-566173D7118E
Lidgren : 5C3DC4FF-FE5A-4B94-B4A6-6F79E63F3130

Help us understand the reasoning behind changing the UIDs which will break the project connectivity for projects that use MonoGame.....

**Comment by tgjones** [comment]
I guess this can be closed - even if it wasn't fixed, it's too late to revert the GUIDs now.
