### ISSUE TITLE
SDL_mixer on Linux platform

### ISSUE THREAD

**Issue by thefiddler** [mono/MonoGame#2598]
What is the use of [SDL_mixer](https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Desktop/OpenTKGamePlatform.cs#L111-L112) on the Linux platform? This appears to be initialized on startup but never actually used.

Is there a reason to keep this here, or is it just a dead dependency that was never removed?

**Comment by cra0zy** [comment]
This can be closed, sdl mixer has been replaced by NVorbis with #3832

**Comment by dellis1972** [comment]
The templates still need to be updated.

**Comment by cra0zy** [comment]
I updated nuget packages and VS templates for it, the only thing I didn't update is XS addin templates, which only have to is disable including of Tao.Sdl.config.

**Comment by dellis1972** [comment]
ok I'll take care of the XS addin

**Comment by cra0zy** [comment]
@dellis1972 since nuget packages are automatically generated, can you somehow connect it to https://github.com/mono/MonoGame/blob/develop/IDE/MonoDevelop/default.build ?
