### ISSUE TITLE
MonoGame_3.0.0.mpack for Xamarin Studio not installing

### ISSUE THREAD

**Issue by stebyrne04** [mono/MonoGame#2631]
I tried to install monogame addin, "MonoGame_3.0.0.mpack for Xamarin Studio" to Xamarin Studio 5, on a mac but it could not be installed because of dependencies conflicts of "Core v4.0" and "Ide v4.0". please help

**Comment by cra0zy** [comment]
The new monodevelop/xs addon is being worked on: #3361

**Comment by jason-shi** [comment]
...... me to

**Comment by cra0zy** [comment]
@tomspilman This can be closed, it has been fixed with #3698
