### ISSUE TITLE
Implement Missing Render States In 2MGFX

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#2641]
We are missing support for a bunch of the render states in the 2MGFX compiler.  This includes:

 - StencilEnable
 - StencilFail
 - StencilFunc
 - StencilMask
 - StencilPass
 - StencilRef
 - StencilWriteMask
 - StencilZFail
 - TextureFactor
 - ZFunc

We need to extend the MGFX parser to support them and hook them up to the existing render state initialization.

See the Effect States docs for details:

 http://msdn.microsoft.com/en-us/library/bb173347(v=vs.85).aspx

**Comment by arsmanyuk** [comment]
These render states are very important for me (and i believe for others).
I want them working but i dont know where to start, any suggestions?
I know that i can somehow do it in the code itself, but i dont know how either.
Seeking for help.

Vlad.

**Comment by tomspilman** [comment]
I'm actually working on the MGFX code now for another issue.  I'll see if I can hook these up as well.

**Comment by arsmanyuk** [comment]
Many thanks! can i help somehow?

**Comment by tomspilman** [comment]
Short of writing the code... not really. :)

**Comment by arsmanyuk** [comment]
Any news about these issues?

**Comment by arsmanyuk** [comment]
...

**Comment by humanapp** [comment]
Hello! An additional datapoint in case it helps prioritize this bug: This is impacting our project. We have more than 100 fx files we're porting over from XNA. Nearly all of them set ZFunc. A handful also set stencil state.

**Comment by tomspilman** [comment]
@humanapp - Great to hear!  I pushed up a fix here: https://github.com/mono/MonoGame/pull/3680.  Just working out a good unit test for verifying it works.  Should be a few more days.

**Comment by humanapp** [comment]
Fantastic! Thank you! I'm pretty new to Git, how to I integrate this change
into my local install? I'm on Windows, and installed MonoGame from the 3.3
installer. Do I need to build from source with your change?

Thanks again
Eric

**Comment by tomspilman** [comment]
@humanapp - You can grab the development build with this change included from the build server here:

http://teamcity.monogame.net/viewLog.html?buildId=5942&buildTypeId=MonoGame_DevelopWin&guest=1&tab=artifacts#!ossgocr

**Comment by humanapp** [comment]
@tomspilman - thank you! grabbing it now.

**Comment by humanapp** [comment]
Tom, I tried this build, but it gave me problems. After installing the new
build my content project would not attempt to build any shaders. I wonder
if the content processor could not be found. I happened to notice in the
properties of the fx file that the name of the content processor changed
from "MonoGame Effect" to "MGEffectProcessor", but when I open the list of
options for this setting, no MonoGame processors were listed.

I'm using VS2010.

**Comment by tomspilman** [comment]
> After installing the new build my content project would not attempt to build any shaders. 

Are you using a `.contentproj` project within VS or the new `.mgcb' content project?

We have dropped support for `.contentproj` in MonoGame 3.4 and only the new `.mgcb' content projects are supported.

Create a new MonoGame project from the templates to see how the new pipeline projects work.

**Comment by humanapp** [comment]
Ah, ok. Sounds like I will need to figure out how to port over our custom
content processors.

**Comment by humanapp** [comment]
Hi Tom, Would you be able to point me to documentation or a tutorial on how
to integrate a custom content processor into Pipeline.exe's build process?
Thanks for your help!

**Comment by tomspilman** [comment]
@humanapp - The recording for this presentation should be up in the next week or so:

http://www.microsoftvirtualacademy.com/liveevents/advanced-monogame-for-windows-phone-and-windows-store-games

**Comment by humanapp** [comment]
@tomspilman - Just checking in, do you have a more concrete idea now of when the recording will be up? What is the best way for me to be notified when it goes up? Thanks!

**Comment by tomspilman** [comment]
@humanapp - Looks like it just went up...

http://www.microsoftvirtualacademy.com/training-courses/advanced-monogame-for-windows-phone-and-windows-store-games
