### ISSUE TITLE
Windows GL Tests Crash

### ISSUE THREAD

**Issue by totallyeviljake** [mono/MonoGame#2664]
Running through the Windows GL tests and I get a NullReferenceException on line 304 of OpenTKGamePlatform.cs. I think some memory corruption has occurred at this point in the testing and the NRE is happening inside of the Dispose.

The exception stack trace:

at OpenTK.Toolkit.Dispose(Boolean manual) in c:\temp\opentk\Source\OpenTK\Toolkit.cs:line 174
   at OpenTK.Toolkit.Dispose() in c:\temp\opentk\Source\OpenTK\Toolkit.cs:line 162
   at Microsoft.Xna.Framework.OpenTKGamePlatform.Dispose(Boolean disposing) in c:\github\MonoGame\MonoGame.Framework\Desktop\OpenTKGamePlatform.cs:line 304
   at Microsoft.Xna.Framework.GamePlatform.Finalize() in c:\github\MonoGame\MonoGame.Framework\GamePlatform.cs:line 123

**Comment by tgjones** [comment]
I think this is outdated - some of the tests in the OpenGL test suite certainly still fail, but (at least on my machine) they fail for "valid" reasons (i.e. not yet implemented, or an image comparison mismatch).

**Comment by cra0zy** [comment]
@tomspilman This is resolved due to #4755

**Comment by Tzenchor** [comment]
I have just run the tests after rebasing, and the test project is missing the SDL2.dll. If added manually the tests crashed with this output:
```
D:\proyectos\MonoGame\Test\bin\WindowsGL\AnyCPU\Debug>MonoGameTests.exe
Run Started: MonoGameTests
FF......................................................................................................................................................E
Excepción no controlada: System.InvalidOperationException: Failed to delete buffer. (Reason: Invalid Name)
   en Microsoft.Xna.Framework.Audio.ALHelper.CheckError(String message, Object[] args) en D:\proyectos\MonoGame\MonoGame.Framework\Audio\OpenALSoundController.cs:línea 44
   en Microsoft.Xna.Framework.Audio.OALSoundBuffer.Dispose(Boolean disposing) en D:\proyectos\MonoGame\MonoGame.Framework\Audio\OALSoundBuffer.cs:línea 107
   en Microsoft.Xna.Framework.Audio.OALSoundBuffer.Finalize() en D:\proyectos\MonoGame\MonoGame.Framework\Audio\OALSoundBuffer.cs:línea 38
```

**Comment by cra0zy** [comment]
Place SDL2 at the same location as OpenAL. I think for Windows thats System32. Both will be added to both templates and as the main Framewok dependencies in the future PR.

**Comment by Tzenchor** [comment]
> Place SDL2 at the same location as OpenAL. I think for Windows thats System32. Both will be added to both templates and as the main Framewok dependencies in the future PR.

No matter where I place both libraries I get the same crash. OpenAL version comes from the bundled installer, and SDL2 is version 2.0.4 which is the latest stable one

**Comment by mrhelmut** [comment]
Dependencies look fine. Yes, try using the Linux project, WindowsGL is legacy stuff (but should be working).
Do you mind sharing your test app?

**Comment by Tzenchor** [comment]
I was running the nUnit tests.
If DesktopGL is generated through the Linux solution, renaming or even dropping WindowsGL can be very useful to avoid these mistakes

**Comment by mrhelmut** [comment]
You're right, this is planned.
I don't know what's going on then. Do you have the same issue with a project? Most probably something that must be preventing sound from working in your test environment.
