### ISSUE TITLE
Mouse scroll is inverted on Linux

### ISSUE THREAD

**Issue by csantosbh** [mono/MonoGame#2686]
The value from Mouse.GetState().ScrollWheelValue is inverted (that is, multiplied by -1) on Linux. A quick debug led me to Input/Mouse.cs, which revealed that the source of the problem is OpenTK: OpenTK.Input.Mouse.GetCursorState().Scroll.Y is already multiplied by -1.

I've tried to update to the latest version of OpenTK (from the github repository), and it went back to normal. However, I only tested it on Linux; also, the upgrade required me to make some changes in the MonoGame framework (for instance, OpenTK.Input.MouseState.Scroll.Y doesn't exist anymore, so I used OpenTK.Input.MouseState.Wheel).

**Comment by cra0zy** [comment]
@tomspilman This should be fixed:
https://github.com/opentk/opentk/pull/134
https://github.com/Mono-Game/MonoGame.Dependencies/pull/23
