### ISSUE TITLE
Cache ContentReader/ContentTypeReader

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#2687]
This discovery was made by @RayBatts.  He was able to more than half the loading times on a game we're porting by caching the reflection work that `ReflectiveReader<T>` does.

Currently for every `ContentManager.Load<>()` the runtime does the following:

  - Allocates a new `ContentReader`.
  - Allocates a new `ContentTypeReader` for each type encountered.
  - The `ReflectiveReader<T>` will use reflection on every property/field read from disk.
  - When done loading we destroy all this stuff and start over.

This is VERY bad for games on mobile with limited CPUs, games that have 1000s of content files, or games with content files that have 100s of properties repetitively read via `ReflectiveReader<T>`.  The current implementation does a ton more work than it has to and generates a bunch of garbage in the process.

 What needs to happen is the following:

  - We should try to reuse `ContentReader` if at all possible.
  - We need to cache all the `ContentTypeReader`s and reuse them across content files (reusing `ContentReader` will do this automatically).
  - `ReflectiveReader<T>` needs to precache the getters for properties/fields that it can read during initialization.

All this together should give us a 2x or more performance improvement in reflection heavy content files and/or games with lots of content.

We will use the work @RayBatts did as a starting point and get a PR up soon that cleans up this mess.

**Comment by tgjones** [comment]
I think this one can be closed, since the PR for it was merged - unless there's more to do.
