### ISSUE TITLE
Can't load FBX file

### ISSUE THREAD

**Issue by ChazAshley** [mono/MonoGame#2760]
Hello, I have watching [this](https://www.youtube.com/playlist?list=PL227AA9E94C6837A7) tutorials and do all the same. But when I trying to load my terrain's mesh I get an error - 
Could not load Models\terrain asset as a non-content file!
so why?

**Comment by Shqrdx** [comment]
@tomspilman @KonajuGames I think this issue is unclear and could be safely closed.

**Comment by tomspilman** [comment]
> Could not load Models\terrain asset as a non-content file!

The one thing to take from this is that we really have to remove that old feature soon.  It is crazy confusing to users and horrible for performance.
