### ISSUE TITLE
Support PSM SDK 2.0

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#2777]
We need to update the PSM platform to take advantage of PSM SDK 2.0 targeting PS Vita and PlayStation TV.   The release notes:

https://psm.playstation.net/static/general/all/psm_sdk/2/doc/en/release_note_en.html#ver-2-00-00

We don't need to support older PSM SDK releases moving forward.

**Comment by tgjones** [comment]
I guess this is obsolete, given the news in #3607.
