### ISSUE TITLE
MediaPlayer.Volume affects all sounds

### ISSUE THREAD

**Issue by braddabug** [mono/MonoGame#2780]
It seems like whenever I try to use MediaPlayer.Volume to change the volume of a background song it affects all sounds (sounds playing via SoundEffect). This is on Windows 7 using an unstable build I just downloaded from TeamCity. The stable 3.2 build does this too. My code works fine using XNA.

**Comment by BenMakesGames** [comment]
this remains an issue, as I just discovered today. the MediaPlayer's volume setting doesn't seem to effect non-music volume levels until/unless a song is playing.

**Comment by KonajuGames** [comment]
I have a local fix for this that I will be pushing up soon.  I replaced
MediaPlayer with one that uses XAudio2 to play the streaming music.​  I
hadn't noticed the stream controller volume fix above.  Whichever one we
use, we'll get a fix in soon.

**Comment by BenMakesGames** [comment]
oh, awesome! thanks :)

**Comment by tomspilman** [comment]
@KonajuGames - I know you spent a bunch of time on the XAudio2 streaming fix for this.  How does the fix @MarkoBL posted look like?

**Comment by KonajuGames** [comment]
I'll give it a test.  If it works fine, I'm happy to use it.​

**Comment by CrashLotus** [comment]
Can we please get a new build with this fix?  Thanks.

**Comment by KonajuGames** [comment]
Fix submitted as #3629
