### ISSUE TITLE
Refactor GraphicsDeviceManager

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#2859]
We need to apply the same platform abstractions as we have in `VertexBuffer`, `GraphicsDevice`, or `SoundEffectInstance` to the `GraphicsDeviceManager`.  

This would leave us with one core GraphicsDeviceManager.cs for the common bits and separate partial classes for each platform/api that requires differences.

These changes need to take special care not to break existing functionality.

**Comment by tomspilman** [comment]
So i'm working on this now... it will take a bit to cleanup the behavior for all the platforms as `GraphicsDeviceManager` is a huge tangled mess.

**Comment by cra0zy** [comment]
If you have a branch somewhere I'll help out
