### ISSUE TITLE
MGCB Mp3 to Platform Specific Audio File Conversion Error

### ISSUE THREAD

**Issue by eumario** [mono/MonoGame#2947]
To whom it may concern,

I have started working with the MonoGame Pipeline tool, to create a MGCB file for building my game content.  When attempting to compress Music, the SongProcessor has an unexpected Failure, with a System.Runtime.InteropServices.COMException (0xC00D4A44), which runs back to NAudio.MediaFoundation.IMFSinkWriter.DoFinalize().  Came across this error searching on Google, that falls back to the NAudio library that is being used by MGCB to build Audio Content.

The error is basically: MF_E_SINK_NO_SAMPLES_PROCESSED,  There is a Solution on the NAudio site, to add in a bool check for finishing of the writing, before actually Finalizing the IMFSinkWriter.  Ticket can be viewed here: http://naudio.codeplex.com/workitem/16439

It only happens on some of my songs, not all of them.

**Comment by cra0zy** [comment]
@tomspilman I think this can be closed considering naudio has been replaced by ffmpeg for audio compilation.

**Comment by tomspilman** [comment]
That is probably true...  a whole new pipeline for audio processing now.
