### ISSUE TITLE
NullReferenceException on Game.EndDraw()

### ISSUE THREAD

**Issue by ShadowTM** [mono/MonoGame#2950]
![enddrawex](https://cloud.githubusercontent.com/assets/3037711/4032907/425f4136-2c75-11e4-93c5-6e57bf939d63.jpg)

 this.GraphicsDevice.PlatformDeleteRenderTarget(this);
GraphicsDevice is null.

Thanks for your work!

**Comment by tgjones** [comment]
The sample file no longer exists on OneDrive. @ShadowTM, is this still an issue?

**Comment by ShadowTM** [comment]
:) Thank you for your response problem has been solved.
