### ISSUE TITLE
Loading cubemaps from multi-face DDS maps

### ISSUE THREAD

**Issue by Vodacek** [mono/MonoGame#2955]
MGCB is not supporting that feature. It loads these files as single-face files. I try to implement this with FreeImage multipage bitmap (as seen here http://sourceforge.net/p/freeimage/discussion/36110/thread/40294256/) but I havent any luck. Perhaps use of NVidia DS library should be right way.

**Comment by tgjones** [comment]
Implemented by #4136.

**Comment by KonajuGames** [comment]
Closing.
