### ISSUE TITLE
Microsoft.Xna.Framework.Vector2 serializes incorrectly

### ISSUE THREAD

**Issue by joncloud** [mono/MonoGame#2968]
Use [Json.NET](http://json.codeplex.com/) to convert `Microsoft.Xna.Framework.Vector2.One` to text.  The following Assemblies will output varying results.

**Microsoft.Xna.Framework.dll, v4.0.0.0**
`"1, 1"`

**MonoGame.Framework.dll, v3.1.2.0**
`{"X":1.0,"Y":1.0}`

*Code Sample*
`Console.WriteLine(JsonConvert.SerializeObject(Vector2.One));`

**Comment by tgjones** [comment]
Looks like this was fixed by #3485.
