### ISSUE TITLE
Pipeline tool throwing FileNotFoundException

### ISSUE THREAD

**Issue by theZMan** [mono/MonoGame#2985]
Could not find file 'C:\Users\{username}\AppData\Local\IsolatedStorage\1ndooq3u.k3k\eum3vvgr.4z3\Url.ou0hyoqw4kkrk5nqgfjdx1bawkrtwea1\AssemFiles\ProjectHistory.txt'.

at

        public void Save()
        {
            using (IsolatedStorageFileStream isoStream = new IsolatedStorageFileStream(ProjectHistoryPath, FileMode.Create, _isoStore))

The path C:\Users\{username}\AppData\Local\IsolatedStorage\1ndooq3u.k3k\eum3vvgr.4z3\Url.ou0hyoqw4kkrk5nqgfjdx1bawkrtwea1\AssemFiles\ exists though the file does not - which is correct as this is the first time running

This is only happening on one of our computers. The MSDN docs state that FileNotFound should only be thrown when using FileMode.Open so this makes no sense to us. Maybe smarter folk have an idea

I tried .CreateNew and that worked just fine and after the file exists then .Create also worked fine. I've deleted the file and tried .Create again and it fails in the same way.

**Comment by tgjones** [comment]
@theZMan Is this still an issue?

**Comment by theZMan** [comment]
I do not remember the exact steps I used to repro this one and whatever it was its not affecting our build process.

So close this until I accidentally make it happen again, or someone else finds it!
