### ISSUE TITLE
GraphicsDevice.Reset missing

### ISSUE THREAD

**Issue by ebatiano** [mono/MonoGame#2991]
GraphicsDevice.Reset is missing in Windows. 

I use GraphicsDevice alone inside my Windows Forms Control. The XNA version of GraphicsDevice had Reset method.

Is there any other way to handle window resize? 

Currently I get resized content inside the window after resize and sometimes device resets itself after resize, but I don't know when and why.

**Comment by tomspilman** [comment]
Closing this in favor of the new issue https://github.com/mono/MonoGame/issues/4429.
