### ISSUE TITLE
MonoGameContentProcessors does not compile WindowsGL effects.

### ISSUE THREAD

**Issue by ala53** [mono/MonoGame#3004]
`MonoGameContentProcessors` crashes when you try to compile an effect under `libmojoshader`, the error being that it cannot find `libmojoshader_64.dll`. If you add `libmojoshader_64.dll`, it crashes with a `BadImageFormatException`:
```c#
Building content threw BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at TwoMGFX.MojoShader.NativeMethods.MOJOSHADER_parse(String profile, Byte[] tokenbuf, Int32 bufsize, IntPtr swiz, Int32 swizcount, IntPtr smap, Int32 smapcount, IntPtr m, IntPtr f, IntPtr d)
   at TwoMGFX.ShaderData.CreateGLSL(Byte[] byteCode, Boolean isVertexShader, List`1 cbuffers, Int32 sharedIndex, Dictionary`2 samplerStates, Boolean debug)
```
This only happens on the development builds and only under OpenGL versions (Windows DirectX works fine).

**Comment by tgjones** [comment]
This does seem like a problem - looks like `MojoShader.cs`, which is referenced by `MonoGameContentProcessors`, but is really part of `TwoMGFX`, has been updated with:

``` csharp
const string mojoshader_dll = "libmojoshader_64.dll";
```

But the `MonoGameContentProcessors` project only references `libmojoshader_32.dll`.

I know the new content pipeline is 64-bit - but do we need to fix the now-deprecated `MonoGameContentProcessors` project for the v3.3 release?

**Comment by tomspilman** [comment]
> but do we need to fix the now-deprecated MonoGameContentProcessors project for the v3.3 release?

Lame...  I guess we should as much as I really really don't want to.

All we need to do is something like:
```
#if OLD_CONTENT_PROCESSORS
   const string mojoshader_dll = "libmojoshader_32.dll";
#else
   const string mojoshader_dll = "libmojoshader_64.dll";
#endif
```
I plan to kill those old processors as soon as possible.
