### ISSUE TITLE
GraphicsDevice.ScissorRectangle ignored on Windows(DirectX)

### ISSUE THREAD

**Issue by ebatiano** [mono/MonoGame#3021]
I have set ScissorRectangle and set RasterizerState.ScissorTestEnable to true, but there's no scissoring.

**Comment by tgjones** [comment]
Is this still an issue? There's even a test specifically for `ScissorRectangle`, so I'd be surprised if it isn't working...

**Comment by ebatiano** [comment]
@tgjones 
I don't know. I don't have Windows DX project anymore because of this issue. But if you're saying it should work now, I'll create DX version of my project to check it.

**Comment by tgjones** [comment]
Let me try it out first (I already have a Windows DX project) and I'll post my findings here.

(I think it should work, looking at the MG code for it, but I haven't actually tested it myself yet!)

**Comment by tgjones** [comment]
@ebatiano I've tested this - it works fine for me (in the Direct3D version of MonoGame). To confirm, I set `GraphicsDevice.ScissorRectangle`, and also set `GraphicsDevice.RasterizerState` to a state object which had `ScissorTestEnable` set to `true`.

So do you mind testing it again? If it works for you, then we can close this issue.

**Comment by ebatiano** [comment]
Great! I've checked it and it works, so I'm closing this issue.
