### ISSUE TITLE
ModelMesh and tessellation

### ISSUE THREAD

**Issue by Zoldike** [mono/MonoGame#3047]
I'm working on a tessellation project using SharpDX Toolkit and had a problem with the ModelMesh/ModelMeshPart classes. These classes were designed for triangles only, but tessellation requires patches.

this.graphicsDevice.DrawIndexedPrimitives(PrimitiveType.TriangleList, part.VertexOffset, 0, part.NumVertices, part.StartIndex, part.PrimitiveCount);

I think we should replace the hard coded PrimitiveType.TriangleList with a property.

**Comment by tgjones** [comment]
@tomspilman I think this can be closed, unless you want to change the title to "Add support for geometry shaders".

**Comment by tomspilman** [comment]
Yeah...  I opened a new issue for that.  https://github.com/mono/MonoGame/issues/4567
