### ISSUE TITLE
Content Pipeline is not setting the correct Effect for SkinnedModels

### ISSUE THREAD

**Issue by theZMan** [mono/MonoGame#3057]
Effects on a model processed with the SkinnedModel pipeline example are set to BasicEffect when they should be set to SkinnedEffect

The skinned content processor has this code 
```
        /// <summary>
        /// Force all the materials to use our skinned model effect.
        /// </summary>
        [DefaultValue(MaterialProcessorDefaultEffect.SkinnedEffect)]
        public override MaterialProcessorDefaultEffect DefaultEffect
        {
            get { return MaterialProcessorDefaultEffect.SkinnedEffect; }
            set { }
        }
```
However this appears to have no effect on the XNB output. In fact I can't find any references to the `MaterialProcessorDefaultEffect` in the MonoGame codebase.

Any ideas where this is normally used to set the correct material?

**Comment by RaffeMaffe** [comment]
Any idea when this could be fixed? Or have a work around?

**Comment by tomspilman** [comment]
@RaffeMaffe - Have you tested with the latest 3.3 release?  There were a lot of fixes with models and FBX... we might have fixed this and didn't realize.

**Comment by RaffeMaffe** [comment]
Hi,
I think installed the latest 3.3.0.2238. I downloaded it again today, just to make sure, and recompiled, but problem remains.
I had a quick look in my generated xnb file for the fbx model and also compared this with an much older file generated by the 'old' MS xna (see below).

The header  looks something like this:

Microsoft.Xna.Framework.Content.ModelReader,
Microsoft.Xna.Framework.Content.StringReader2
Microsoft.Xna.Framework.Content.VertexBufferReader7
Microsoft.Xna.Framework.Content.VertexDeclarationReader
Microsoft.Xna.Framework.Content.IndexBufferReader, 
MonoGame.Framework, 
Version=3.3.0.2238, 
Culture=neutral, 
PublicKeyToken=null1
Microsoft.Xna.Framework.Content.BasicEffectReader

The 'old' file has an header that looks like this:

Microsoft.Xna.Framework.Content.ModelReader, 
Microsoft.Xna.Framework.Graphics, 
Version=4.0.0.0, Culture=neutral, 
PublicKeyToken=842cf8be1de50553,
Microsoft.Xna.Framework.Content.StringReader—
Microsoft.Xna.Framework.Content.VertexBufferReader, 
Microsoft.Xna.Framework.Graphics, 
Version=4.0.0.0, 
Culture=neutral, 
PublicKeyToken=842cf8be1de50553œ
Microsoft.Xna.Framework.Content.VertexDeclarationReader, 
Microsoft.Xna.Framework.Graphics, 
Version=4.0.0.0, 
Culture=neutral, 
PublicKeyToken=842cf8be1de50553–
Microsoft.Xna.Framework.Content.IndexBufferReader, 
Microsoft.Xna.Framework.Graphics, 
Version=4.0.0.0, 
Culture=neutral, 
PublicKeyToken=842cf8be1de50553
Microsoft.Xna.Framework.Content.SkinnedEffectReader,
Microsoft.Xna.Framework.Graphics,
 Version=4.0.0.0, Culture=neutral, 
PublicKeyToken=842cf8be1de50553

I have tried different settings for the processer, including trying AlphaTestEffect and SkinningEffect, but the game seem always to load a Model with a BasicEffect. 
below my setting:
![monogame1](https://cloud.githubusercontent.com/assets/11855807/7072259/32b04928-deeb-11e4-8e0b-87cc136fcb6e.png)

Please tell me if you want me to try something out to help solve the problem :)

**Comment by RaffeMaffe** [comment]
By the way, I'm using VS2013 on Windows 7, could that be an issue here?

**Comment by bloodyswamp** [comment]
Hello,
I can confirm what RaffeMaffe said about that issue. Our application is based on a Skinned Model and so now we have a big problem with MonoGame 3.3 and the MonoGame Pipeline tool. Even if the DefaultEffect is set to ANY effect, it returns to BasicEffect in runtime. I'm also using VS2013, Update 5. Also Windows 8.1 x64 (if this has anything to do with that issue).

**Comment by tgjones** [comment]
Looks like there's a couple of missing pieces.

The first is in `ModelProcessor.ConvertMaterial`. We should be passing passing the `DefaultEffect` from `ModelProcessor` through to `MaterialProcessor`.

The second is in `MaterialProcessor`, which currently ignores `DefaultEffect`. But if we just create a new material based on `DefaultEffect`, we'll lose the properties from the imported material. So we might be missing something else here.

**Comment by Vangos** [comment]
Same issue here.

Is there a scheduled update?

Should we use an older version? Are there any alternatives/workarounds?

Thank you in advance.

**Comment by Vangos** [comment]
This is mostly a business question: we have invested on MonoGame to develop 3D avatar animation. This issue indicates that avatar animation is not feasible right now.

So, I would like to ask you the following:
1) Can we perform avatar animation using MonoGame with an alternative/workaround?
2) Should we use a different engine, other than MonoGame?

Please let us know, since we have invested quite a lot of money on this during the past few years. I would like to know whether there is a planned update, or we should invest on another engine.

Kind regards,
Vangos Pterneas

**Comment by tgjones** [comment]
@Vangos The actual fix should be fairly straightforward - initially, just a 1-line change to `ModelProcessor` and a 1-line change to `MaterialProcessor`, as I mentioned in my previous comment. Then a few more lines in `MaterialProcessor` to preserve material properties when a new material is created.

I would suggest (politely, although I realise it might sound sarcastic; I don't mean it to) that if you've invested that much in MonoGame, the extra investment needed to help fix this issue would be minimal.

**Comment by Vangos** [comment]
@tgjones Thank you very much for your fast reply. We didn't need to modify the source code before. We'll definitely give it a try. Since Microsoft killed XNA, MonoGame has been an incredibly good solution for us.

**Comment by bloodyswamp** [comment]
Hi @tgjones,

I tried to trace back those parts you suggested with no luck. Just "initially, just a 1-line change to ModelProcessor... ." is not helping at all. For me who just got into the MonoGame's source code is a difficult thing to do.

I added the DefaultEffect as a parameter in both the ModelProcessor and MaterialProcessor but that wasn't sufficient. Well, I don't even know if I was in the right track. I can't figure out how the DefaultEffect is being set in both Processors.

Thanks in advance.

**Comment by tgjones** [comment]
Admittedly, I hadn't actually written out the code at that point, but it's not far off my estimate. Here's a more detailed version of what I think needs to happen:

In `ModelProcessor`, add this to `ConvertMaterial`:

``` csharp
parameters.Add("DefaultEffect", DefaultEffect);
```

In `MaterialProcessor`, add this to the beginning of `Process`:

``` csharp
// Apply specified default effect.
if (input is BasicMaterialContent && DefaultEffect != MaterialProcessorDefaultEffect.BasicEffect)
{
    var newMaterial = CreateDefaultMaterial(DefaultEffect);

    // Preserve material properties.
    foreach (var item in input.OpaqueData)
        newMaterial.OpaqueData.Add(item.Key, item.Value);
    foreach (var item in input.Textures)
        newMaterial.Textures.Add(item.Key, item.Value);

    input = newMaterial;
}
```

**Comment by Vangos** [comment]
Thank you for your kind reply. We tried the workaround and it didn't work. Seems there's something missing.
