### ISSUE TITLE
Bgra5551

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#3076]
Add the struct `Bgra5551`.

 http://msdn.microsoft.com/en-us/library/microsoft.xna.framework.graphics.packedvector.bgra5551.aspx

Extend the current `PackedVectorTest`s to ensure compatibility with XNA:

 https://github.com/mono/MonoGame/blob/develop/Test/Framework/PackedVectorTest.cs

**Comment by cra0zy** [comment]
This can be closed.

**Comment by tomspilman** [comment]
Fixed in https://github.com/mono/MonoGame/pull/3622.
