### ISSUE TITLE
fx technique preprocessor defines

### ISSUE THREAD

**Issue by jamesford42** [mono/MonoGame#3096]
Looks like whatever custom parsing we do to support the .fx syntax for defining a technique / pass / etc is not setup to obey one or more of the following: #if, #elif, #endif. Alternately the problem could be that defines from the processor are not being passed down to this step.

**Comment by tgjones** [comment]
This can be closed once #3489 is merged.

**Comment by KonajuGames** [comment]
> This can be closed once #3489 is merged.

Since you added the comment in that PR that it fixes this issue, GitHub should automatically close this issue when that PR is merged.

**Comment by tgjones** [comment]
Okay, noted - I know that happens for my own repos, but I didn't know if it happens for PRs from non-repository-owners.
