### ISSUE TITLE
[Pipeline tool] Drag and drop

### ISSUE THREAD

**Issue by Nezz** [mono/MonoGame#3157]
It would be nice to be able to add files and directories using drag and drop to the content project, just like in Visual Studio with the XNA content projects. Adding lots of directories is hard work without this as you can only add files, not directories.

**Comment by cra0zy** [comment]
I have time so I can setup the code for drag and drop, the only question is how will undo/redo work? Also I think it would be nice to add something like in monodevelops/xamarin studios add files section, where when you drag and drop stuff you can select to link it or to copy it.

**Comment by nkast** [comment]
Implemented as described by @jamesford42. 
 "... including a content item that is already beneath the root via drag-drop by allowing a drop directly on the project root tree item to signify 'include in current location'."
https://github.com/mono/MonoGame/pull/3708
