### ISSUE TITLE
Add Content Pipeline Extension Template for VS

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#3164]
We should add a VS template for custom content pipeline extensions (processors, importers, etc).  This would be similar to the XNA "Content Pipeline Extension Library" template except aimed at the new MonoGame content pipeline.

**Comment by tomspilman** [comment]
Anyone have time to write a template or two for this in the next week before Build?

**Comment by mattiascibien** [comment]
I actually wanted to get on this one. Working on it now

**Comment by tomspilman** [comment]
Thanks @mattiascibien !
