### ISSUE TITLE
Add Support for Visual Studio 2013 Community Edition

### ISSUE THREAD

**Issue by joncloud** [mono/MonoGame#3171]
Visual Studio 2013 Community Edition currently does not support the following project types:
* {6D335F3A-9D43-41b4-9D22-F6F17C4BE596}    MonoGame Content Project
* {C089C8C0-30E0-4E22-80C0-CE093F111A43}    MonoGame Windows Phone 8 Project
* {EFBA0AD7-5A72-4C68-AF49-83D382785DCF}    MonoGame Android Project
* {76F1466A-8B6D-4E39-A767-685A06062A39}    MonoGame Windows Phone 8.1 Project

Creating a new solution using a project template results in an error dialog with the following contents:

    ---------------------------
    Microsoft Visual Studio
    ---------------------------
    A problem was encountered creating the sub project 'Game1'.  The project file 'C:\Users\...\AppData\Local\Temp\tri4djb5.r3s\Temp\Game1.csproj' cannot be opened.
    
    There is a missing project subtype.
    Subtype: '{6D335F3A-9D43-41b4-9D22-F6F17C4BE596}' is unsupported by this installation.
    ---------------------------
    OK   
    ---------------------------

**Comment by geoffwild11** [comment]
Any news on whether they will start having support for at least the Content Projects?

**Comment by DDReaper** [comment]
All the 2012/2013 templates include support for the content projects as of the 3.3 release.

Not tried 2013 Community edition but it should work 

No idea when we'll have 2015 templates as yet, guess the team are waiting for the RTM

**Comment by tomspilman** [comment]
We should be able to do 2015 templates now as they officially announced the product and prices.  We would start by simply copying the existing templates to the new 2015 folder in the installer script.

Anyone have time to test and submit that fix?

**Comment by tomspilman** [comment]
So submitting a fix to add templates for VS2015 https://github.com/mono/MonoGame/pull/3712.

Next step is full Win10 support.

**Comment by tgjones** [comment]
Win10 support has been added by #3746, #3747, #3751. I think this can be closed.

**Comment by KonajuGames** [comment]
If there is anything else to be done, a new issue can be raised.  Closing.
