### ISSUE TITLE
Replace NAudio with FFMPEG

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#3181]
This was suggested to me by @hach-que.

We currently use NAudio to do audio format conversions in the pipeline.  The problem with this library is that it only works on Windows.

Since we did that work a couple of years ago we've added some support for shelling out to FFMPEG to do conversions for some platforms including PS4.

So the questions is if we should just switch over to using FFMPEG for all our audio conversion work on Windows, Mac, and Linux?

Thoughts?  @prollin @dellis1972 @KonajuGames

**Comment by cra0zy** [comment]
#3197 has been merged so this should be closed.
