### ISSUE TITLE
Reference OpenTK as NuGet package?

### ISSUE THREAD

**Issue by arthur-peka** [mono/MonoGame#3233]
I've discovered, that when you clone the project, run the Protobuild and then open & build the `MonoGame.Framework.Linux` solution file, build fails, as OpenTK reference is missing.

Could it be added as a NuGet package dependency? I believe that using dependency manager will ease the development (so that solution can be built out of the box).

**Comment by ala53** [comment]
OpenTK doesn't have different assemblies by platform. So, this can be done as all checks are done at runtime.

**Comment by tomspilman** [comment]
We don't plan to use NuGet within the MonoGame build process.

**Comment by arthur-peka** [comment]
@tomspilman Motivation?

**Comment by tomspilman** [comment]
We need to have reliable copies of all the dependencies we use in the build.  We currently store these in the https://github.com/Mono-Game/MonoGame.Dependencies repo.

**Comment by ala53** [comment]
But, isn't NuGet also reliable and doesn't it have versioning too?
And if need be, can't you have MonoGame.Dependencies as a backup, but have the references be nuget by default?

**Comment by tomspilman** [comment]
> But, isn't NuGet also reliable and doesn't it have versioning too?

We already depend on GitHub to provide code and dependencies... we don't need another service.

**Comment by hach-que** [comment]
Not to mention NuGet does not properly distinguish between actual
platforms, which makes it unsuitable for projects that need to P/Invoke.
See the warning on
https://protobuild.readthedocs.org/en/latest/package_management_nuget.html
for an explaination as to why NuGet is not suitable for cross-platform
projects.
