### ISSUE TITLE
iOS .m4a song files load exception

### ISSUE THREAD

**Issue by RamsayGit** [mono/MonoGame#3258]
On previous projects I have loaded songs as raw .m4a files without using the content pipeline since .mp3 has a hefty license cost. A few days ago I updated to the latest MonoGame build from Github and since then I get an exception on loading any .m4a song files "cannot load non-content file" even though the songs are set to 'Content' and 'Output always'. How can I fix this?

**Comment by tgjones** [comment]
@tomspilman I think this can be closed. Songs that aren't sent through the content pipeline should be loaded using `Song.FromUri`, as the most recent comment indicates.

**Comment by tomspilman** [comment]
I'm good with that... thanks @tgjones !
