### ISSUE TITLE
SDL 1.2 deprecated

### ISSUE THREAD

**Issue by CallumDev** [mono/MonoGame#3266]
According to https://wiki.libsdl.org/Support , SDL 1.2 is now deprecated.
Right now (at least on the Linux platform), SDL 1.2 is used in support for Gamepads and the MediaPlayer component. 

The gamepad api between SDL 1.2 and SDL 2.0 is virtually the same, and probably only needs an update of the bindings (perhaps SDL2#?)

The SDL_mixer 2.0 API I'm not quite sure about, but the current implementation leaves a lot to be desired, especially since it means that a game will be opening 2 audio devices which perhaps might not even go through the same backend (OpenAL could go through pulse, and SDL might go through alsa), which on certain systems with multiple sound cards, would be a pain to the user. NVorbis has a sample of integration with OpenTK, and perhaps an implementation could be adapted from that? (I could have a go at that)

**Comment by CallumDev** [comment]
As an experiment, I adapted various code into an Ogg Streamer at  : 
https://github.com/CallumDev/AudioSharp
It uses raw OpenAL for now, but it'd be incredibly easy for me to make an IStreamingAudio implementation that uses DynamicSoundEffectInstance as a backend. This would remove the dependency on SDL_mixer, as well as allowing us to have guaranteed decoders (I believe it may be possible to compile SDL_mixer *without* vorbis support on Linux, though I haven't seen that yet).

Thoughts?

**Comment by cra0zy** [comment]
@tomspilman @flibitijibibo If it's ok with you 2 I could setup several smaller pull request for exchanging sdl1.2 components with sdl2 components.

**Comment by flibitijibibo** [comment]
@cra0zy Unfortunately the SDL2 changes would have to be done in one burst, since mixing SDL 1.2 and SDL2 would cause symbol conflicts at runtime and crash. But the good news is that MonoGame's SDL use is pretty minimal anyway, and I think a lot of those APIs used are 1:1 in C (in C# it's just Tao->SDL2#).

@CallumDev We've got something similar in FNA's `vorbisfile-cs` branch if you want to gank any of it: https://github.com/flibitijibibo/FNA/blob/vorbisfile-cs/src/SDL2/Media/Song.cs

**Comment by CallumDev** [comment]
@flibitijibibo I'll have a go at that if I can figure out how to introduce a new dependency

**Comment by tomspilman** [comment]
>  I could setup several smaller pull request for exchanging sdl1.2 components with sdl2 components.

Our goal is to reduce the SDL dependencies.  I'd rather see us move to OpenTK's controller support and remove SDL controller support first.

For media playback i'm unsure what the path is to replace SDL_mixer, but @thefiddler might know.

**Comment by cra0zy** [comment]
@tomspilman I've started work on replacing sdl1.2 with opentk, I'll split it into 2 branches, first one will replace gamepad/joystick while the 2nd one will replace song. I've already written the replace for the gamepad/joystick here: https://github.com/cra0zy/MonoGame/tree/otk1, but I'll have to remap some stuff.

**Comment by cra0zy** [comment]
@tomspilman It seems I won't have to remap anything, it has the same mapping settings as sdl :D

**Comment by tomspilman** [comment]
That is great news...  thanks @cra0zy !

**Comment by cra0zy** [comment]
This can be closed, last bits of sdl have been replaced in #3832
