### ISSUE TITLE
Mac pipeline tool

### ISSUE THREAD

**Issue by Nezz** [mono/MonoGame#3268]
I haven't found any other issues regarding the pipeline tool on OS X, so I decided to post them.

At launch, there is a warning that says that the fonts are missing (like Consolas). I don't know if this is to be fixed or will be ignored.

Top menus have no titles, but are actually working:
![pipeline top](https://cloud.githubusercontent.com/assets/431167/5423894/0acc5926-82d7-11e4-80df-e9e1f8e69e87.png)

The left side of the UI always stays like this. The right side shows the build output correctly.
![pipeline ui](https://cloud.githubusercontent.com/assets/431167/5423895/0acd02e0-82d7-11e4-922d-725323dc1d14.png)

**Comment by cra0zy** [comment]
Pipeline tool has been ported to gtk#... @tomspilman I hope you don't mind me going over open issues that should actually be closed

**Comment by tomspilman** [comment]
@cra0zy - Great... Go ahead!
