### ISSUE TITLE
Pipeline tool - add ability to manually create folders

### ISSUE THREAD

**Issue by dneelyep** [mono/MonoGame#3291]
It would be useful to be able to add folders to a content project directly from the Pipeline tool. A user should be able to, in the project tree, right-click a node and either include a "Folder" option in the "New Item" popup, or a "New Folder" entry should be added to the context menu. The same should be done in the "Edit" menu.

This would be useful so that, if a user wants to re-structure their project, they can just add new folders and drag content around within the tool.

**Comment by Eversor** [comment]
What about implementing "undo/redo" breaking actions that once invoked break the undo-redo chain and ask the user consent (possibly avoidable via an option) before execution (telling him it will also break the undo/redo chain)?

**Comment by tomspilman** [comment]
> What about implementing "undo/redo" breaking actions 

Interesting idea...  it sort of puts the problem in the users hands, but it seems really annoying to get a popup on each of these actions.

**Comment by cra0zy** [comment]
3604
