### ISSUE TITLE
Pipeline tool - context menu terminology

### ISSUE THREAD

**Issue by dneelyep** [mono/MonoGame#3292]
The difference between the "New Item" and "Add Item" context menu entries in the pipeline tool isn't obvious without clicking through to see what each does.

I suggest renaming "Add Item" to "Add Existing Item". This would be consistent with VS terminology (which I'm guessing a lot of users will be using anyways), and will make it so that you can instantly determine the purpose of both of these menu items.

**Comment by dbeals** [comment]
I hate to add more alternatives, but Resource is pretty common wording for these types of items.

I'm used to the Add/Add Existing as well due to Visual Studio, but I think New/Include pair make sense or maybe New/Import.

**Comment by willmotil** [comment]
this is pretty clear 
Add New Item
Add Existing Item

Alternately maybe 
Add New Item
Add Item

**Comment by cra0zy** [comment]
Wouldn't it be easier to say New File, Existing File or New Item, Existing Item?
