### ISSUE TITLE
Guide doesn't work on WP8.1

### ISSUE THREAD

**Issue by Nezz** [mono/MonoGame#3313]
Because BeginInvoke is not supported.

**Comment by Nezz** [comment]
I will submit a PR with a revised messagebox and keyboard input soon.

**Comment by KonajuGames** [comment]
I would like to see an async/await version of whatever is used to replace
Guide.  Of course this would not be supported on the PSM version, but I
think with the other things that are not supported on the PSM version
(shaders, etc) and no likely updates to the PSM SDK to rectify these, it
may have to be a platform that is relegated to maintenance mode before too
long.

So yes, we should start planning a Guide replacement API for that
functionality.
​

**Comment by Nezz** [comment]
Submitted.
