### ISSUE TITLE
Use nugets packages for SharpDX

### ISSUE THREAD

**Issue by Petoj87** [mono/MonoGame#3321]
Please start using the nugets packages for SharpDX to simplify compilation of MonoGame, or add instruction on how to compile MonoGame.

**Comment by DDReaper** [comment]
I can see the advantage of that, however it could create an unsupported situation if SharpDX updates and MonoGame has not yet been tested with a later version of SharpDX

**Comment by danzel** [comment]
With nuget packages you specify the version to install, so that shouldn't be an issue.

**Comment by DDReaper** [comment]
True @danzel however doesn't stop the user from updating or NuGet informing the user there is a newer version.

Granted we can manage that through documentation with the package.

**Comment by tomspilman** [comment]
We're not going to use NuGet within the MonoGame build process.
