### ISSUE TITLE
Pipeline tool - add indicator for missing files.

### ISSUE THREAD

**Issue by dneelyep** [mono/MonoGame#3322]
It would be useful to add an indicator that a file does not exist in the project structure pane when the Pipeline tool can't find a file

For example:
If I have this project structure:
Models\
    ModelA
    ModelB

and I then move all the files into a new folder like so:
Models2\
    ModelA
    ModelB

it would be useful if a little red circle showed in the Pipeline UI, indicating that the tool can't find the file. Not sure how tricky this would be to implement, but it would just be a nice-to-have thing - not super high priority I wouldn't think.

**Comment by cra0zy** [comment]
This can be closed.
