### ISSUE TITLE
Textures should always be assigned to device, even if they are null

### ISSUE THREAD

**Issue by tgjones** [mono/MonoGame#3351]
I'm not sure if I'm right about this, which is why I'm creating an issue, not a pull request. If it is indeed a bug, then I can create a pull request.

It seems to me that this line is wrong:
https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/Effect/EffectPass.cs#L118

I think we should remove the null check, and always set the texture, even if it is null.

For example, if the previously bound texture is a TextureCube (well, Texture2D array, in Direct3D 11 terminology), and the new texture is a Texture2D, but it just happens to be null, then it's still necessary to set that texture slot to null, otherwise Direct3D will complain that the currently bound texture has the wrong dimension for the current shader. (I have this exact situation, which is how I found this.)

**Comment by tomspilman** [comment]
Well the null check is there to allow the caller to set the `GraphicsDevice.Textures` directly and not be overwritten by an unused effect parameter.  In particular this occurs when using a custom effect with `SpriteBatch`.

It could be the rules are a little different than we have interpreted them.  All we can do is do some tests in XNA and figure out what the correct behavior should be.

**Comment by tgjones** [comment]
That reason makes sense. I've never been entirely clear on the relationship between GraphicsDevice.Textures and setting a texture in an EffectParameter.

I'll have a closer look at XNA's behaviour.

**Comment by tgjones** [comment]
I think the actual issue here is that MonoGame should check `EffectParameter.StateKey` when updating textures (as it does for constant buffer parameters), but it currently doesn't.

If it did check `StateKey`, then when you explicitly call `myTextureParameter.SetValue()` with a `null` texture, it should override whatever is in `GraphicsDevice.Textures`. If you didn't call `myTextureParameter.SetValue()`, then the texture in `GraphicsDevice.Textures` should be preserved, as it is now.

Does that sound reasonable? If so, I'll put together a pull request (although I have actually worked around it for my specific case).

**Comment by tomspilman** [comment]
> I think the actual issue here is that MonoGame should check  EffectParameter.StateKey 

 Interesting thought.  We are using `null` here as a magic value to indicate the user hasn't set the texture, but if they indeed set `null` we should be applying it.

 Still I would like to get a test of XNA behavior here.  We could easily enhance one of the existing `SpriteBatch` unit tests or add a new one with some asserts for what we expect `GraphicsDevice.Textures` to be at different times.

**Comment by tgjones** [comment]
Being a MonoGame no0b, I hadn't noticed that the tests get run against XNA as well - that's really nice! I'll add a test as you suggested.

**Comment by tomspilman** [comment]
> Being a MonoGame no0b, I hadn't noticed that the tests get run against XNA as well 

Yea....  there is a manually maintained XNA project for tests here:

 https://github.com/mono/MonoGame/blob/develop/Test/MonoGame.Tests.XNA.csproj

 It isn't automatically added to the Windows solution because I often find the unit test runners getting confused as to which tests you are running.  I just manually add it when I want to test some things and load/unload the projects as needed.

**Comment by tgjones** [comment]
I just found that - and on a slightly related note, I realised that I didn't add my `PlaneTest` file to that project. I'll do that now.

**Comment by tomspilman** [comment]
> I realised that I didn't add my  PlaneTest  file to that project.

 Hopefully you find the tests all succeed under XNA as well. ;)

**Comment by tgjones** [comment]
The thought had occurred to me too :)

**Comment by tomspilman** [comment]
Was thinking It could be that both the code in `EffectPass.Apply()` is wrong as well as what we do within `SpriteBatch`.  

So to get both parts right...  we need to test separately.  

First test should first focus on the interaction between `EffectPass.Apply()` and `GraphicsDevice.Textures`.  This can be done with just a `BasicEffect`.  Second the test should see how `SpriteBatch` behaves with the user setting `GraphicsDevice.Textures` at different times.
