### ISSUE TITLE
Primitive Type error when compiling

### ISSUE THREAD

**Issue by Mathwe** [mono/MonoGame#3355]
I downloaded the source from this site and then went to try and build the solution generated from the Protobuild.exe in mono. When I try to build I get an error that PrimitiveType does not exist in the namespace "OpenTK.Graphics.OpenGL".  This error occurs on line 18 of file GraphicsDevice.OpenGL.cs on the linux build.  Any help would be appreciated. I hope that I am posting this in the correct spot and that I didn't miss anything obvious. Thanks for your time.

**Comment by tomspilman** [comment]
What platform are you building on?  Linux?

It sounds like maybe you don't have the right OpenTK assemblies.  Did you pull down the ThirdParty/Dependencies submodule as well?

**Comment by Mathwe** [comment]
Yes I am building on Linux.  And yes I did get the ThirdParty/Dependencies as well.

**Comment by tomspilman** [comment]
@cra0zy - Any ideas?

**Comment by cra0zy** [comment]
Try redownloadng dependencies, I remember reading on monogame.net of someone having the same error  on windows and they thought they downloaded the dependencies, but the dependencies weren't fully downloaded.

**Comment by Mathwe** [comment]
OK I will give that a go

**Comment by Mathwe** [comment]
Thanks that worked I missed a couple of files when extracting the dependencies
