### ISSUE TITLE
mgcb build issue

### ISSUE THREAD

**Issue by DDReaper** [mono/MonoGame#3360]
Can't figure out what's going on here.

The MGCB content builds fine in the tool, no issues.

But in the project I just get this error
Error	1	The command ""C:\Program Files (x86)\MSBuild\MonoGame\v3.0\Tools\MGCB.exe" /@:"" /platform:WindowsPhone8 /outputDir:"C:\Development\Sandbox\MonoGamePCL1\MonoGamePCLWP1\Content\bin\WindowsPhone8" /intermediateDir:"C:\Development\Sandbox\MonoGamePCL1\MonoGamePCLWP1\Content\obj\WindowsPhone8" /quiet" exited with code -532462766.	MonoGamePCLWP1

Any ideas how to diagnose this?

**Comment by tomspilman** [comment]
> The MGCB content builds fine in the tool, no issues.

I assume you mean the Pipeline GUI tool?

> But in the project I just get this error

 Does "C:\Program Files (x86)\MSBuild\MonoGame\v3.0\Tools\MGCB.exe" exist on your system?

> Any ideas how to diagnose this?

Open a command line window and cut and paste that command line and run it.  It might give you some more information.

**Comment by DDReaper** [comment]
Right, tested that @tomspilman and it complained about an empty path.

So I removed the **/@:""** and it built successfully

Any ideas why it's adding that when running the MGCB tool?

**Comment by tomspilman** [comment]
> So I removed the /@:"" and it built successfully

 Oh...  I missed that.

 That is where the name of the .mgcb file should be.  Do you not have a .mgcb file in your project?

**Comment by DDReaper** [comment]
Like the samples, my .mgcb file is in a folder alongside the Project folder like this:

* ContentFolder
  * .mgcb
  * Content files
* Game Project
  * Content (folder)
    * link to .mgcb
  * .csproj
  * scripts
* .sln

As the setup is practically identical to the ones I setup in the Samples repo, I'm wondering what the issue could be as they work.

As I'm testing a setup similar to the samples (content shared on multiple platforms) this kind of setup would be essential

**Comment by tomspilman** [comment]
> Like the samples, my .mgcb file is in a folder alongside the Project folder like this

 Did you build this project manually?

 We expect it to use a custom build type...
```
<MonoGameContentReference Include="Content\Content.mgcb" />
```
If instead you have it as `<None>` or `<Content>` it won't be found.

I think we can make some improvements so that isn't necessary, but I haven't had time to work on it.

**Comment by DDReaper** [comment]
Gah, my bad.  That was the issue.

I didn't set the Build Action to "MonoGameContentReference"

That certainly needs better error handling.

TO keep it clean, should I raise a separate **Enhancement** issue for that as this is likely to trip people up @tomspilman ?

**Comment by tomspilman** [comment]
We can just use this issue to track adding an improvement.

Ideally any time you add a .mgcb file it by default gets assigned the "MonoGameContentReference" build action...  but I don't know if I can enforce that thru a simple change in the .targets file.

A fallback would be detecting .mgcb files under "None" and "Content" build actions and spitting out a warning.

**Comment by DDReaper** [comment]
Adding the "MonoGameContentReference" as a default would be good, but those features usually only work in the **index** of the type rather than the name (and you can't use reflection)

The fall-back option is more achievable by adding a better output error from the project when the build action is not set to MonoGameContentReference, informing the user they need to set it properly.

**Comment by marcsamarra** [comment]
I have the same problem. Please, can you tell me how did you solved it?

The command ""C:\Program Files (x86)\MSBuild\MonoGame\v3.0\Tools\MGCB.exe" /@:"C:\Users\Marc\documents\visual studio 2013\Projects\GameName5\GameName5\GameName5.Shared\Content\Content.mgcb" /platform:WindowsStoreApp /outputDir:"C:\Users\Marc\documents\visual studio 2013\Projects\GameName5\GameName5\GameName5.Windows\Content\bin\WindowsStoreApp" /intermediateDir:"C:\Users\Marc\documents\visual studio 2013\Projects\GameName5\GameName5\GameName5.Windows\Content\obj\WindowsStoreApp" /quiet" exited with code -532462766.	GameName5.Windows

**Comment by DDReaper** [comment]
A couple of things you can do:
* Check you have installed the latest "dev" MSI build of MonoGame
* Go to the location where you MGCB file is and open it in the GUI tool (double click on the file, check it's the correct project, do File -> open to select correct project if it isn't)
* In the GUI too do Build -> Build in the menu (or hit F6)
* Check the build completes without errors.

If everything is OK, return to your project, select the MGCB file in solution explorder and check n the Properties window that you have selected "MonoGameContentReference" as the Build Action.

Hope that helps

**Comment by marcsamarra** [comment]
I've installed the latest "dev" MSI build (3.3.0.253) and it works. Thank you!

**Comment by craig9670** [comment]
To solve this issue, I had to put quotes around all of the paths inside of the MonoGame.Content.Builder.Task.targets. 

I did this:

`    <Exec
      Condition="'%(ContentReference.FullPath)' != ''"
      Command="$(DotnetCommand) &quot;$(MGCBPath)&quot; $(MonoGameMGCBAdditionalArguments) &quot;%(ContentReference.FullPath)&quot; /platform:$(MonoGamePlatform) /outputDir:%&quot;(ContentReference.ContentOutputDir)&quot; /intermediateDir:%&quot;(ContentReference.ContentIntermediateOutputDir)&quot; /workingDir:&quot;%(ContentReference.FullDir)&quot;"
      WorkingDirectory="$(MSBuildProjectDirectory)" />`
