### ISSUE TITLE
Ability to choose DirectX with OpenAL

### ISSUE THREAD

**Issue by christallire** [mono/MonoGame#3370]
I have noticed that SharpDX.XAudio is not working with default installation of windows7
Because it bundled DXAudio that slightly lower version of API than expected for SharpDX.XAudio.
This will eventually be solved through installing the newest version of DirectX but I would like to support as many as possible client OSes without installing latest/least prerequisites.

Thus I decided to try out it with OpenAL.

But DirectX / OpenAL not viable without source code modification because two of services (DX Graphics, DX Audio) were coupled in references of ProtoBuild templates and #if DirectX predefined constants.

Except that, I was happy that I can use it with zero deployment packages in windows.

**Comment by tomspilman** [comment]
It might be good to fix the Protobuild definition and the code to support building DirectX with OpenAL or OpenGL with XAudio.  But I don't think we would encourage this usage or spend a lot of effort making it work.  It is hard enough to test MonoGame as it is now.
