### ISSUE TITLE
Linux: mouse coordinates based on screen, not window

### ISSUE THREAD

**Issue by dhasenan** [mono/MonoGame#3381]
Using the sample program that @thefiddler posted in #2464 with development tip (commit 492439c5).

I see that monogame is producing coordinates with the origin at the top left of the *screen* rather than the top left of the *window*. For instance, when I put the cursor at the top left of the window, when the window is on the lower half of my right monitor, I expect it to print mouse coordinates "0, 0" but instead it prints "1975, 760".

**Comment by cra0zy** [comment]
I also use linux, but I don't have that problem. What linux are you using and which desktop environment(Gnome, Unity, xfce...)?

**Comment by WardBenjamin** [comment]
I've never noticed this before with either LXDE or Unity, but it's
certainly possible considering the huge variation in DEs used by people.

On Sun, Jan 11, 2015 at 6:01 AM, Harry <notifications@github.com> wrote:

> I also use linux, but I don't have that problem. What linux are you using
> and which desktop environment(Gnome, Unity, xfce...)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mono/MonoGame/issues/3381#issuecomment-69490509>.
>



-- 
Benjamin Ward

**Comment by dhasenan** [comment]
Originally noticed in spectrwm (tiling window manager like xmonad). Reproduced in MATE. Will try in a couple other WMs. (Toggling compositing in spectrwm had no effect, btw.)

> uname -a
Linux nyarlahotep 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
> cat /etc/issue
Linux Mint 17 Qiana \n \l

**Comment by cra0zy** [comment]
Tested it in Mate, but it worked normally. I can't test it in spectrwm.

**Comment by QuantumFractal** [comment]
gnome works fine here!

**Comment by dhasenan** [comment]
Seems to be my problem only. If I track anything concrete down, I'll reopen.
