### ISSUE TITLE
need simpler fully functional Installation

### ISSUE THREAD

**Issue by willmotil** [mono/MonoGame#3383]
it would be nice if there was a quick download that included the pipeline tool
the 3.2 official download doesn't have it, nor do the dev or nightly builds include it
that's fine if you dont want to use fx files or models but most people do

so then the zip download for the source has the folder. but...
when you dl it, then run protobuild... you get solutions   but .... vs wont compile it
it will give tons of errors instead, im guessing this is because dependancy's are missing
but you find that out after the fact with no instructions or warning

if a new guy feels corralled into using github 
because of constantly failing to get monogame working,  then he must now
learn how to use github and git... before ... installing monogme
the problem with this is he is probably new or solo (xna was for indies) 
additionally he isn't clicking something called
"learn how to use git so you can learn how to install monogame"

basically unlike xna, 
this amounts to jumping thru hoops non stop to load fx files or a model
worse finding the particular instructions is horrible because 
there are so many on the net and here, most are incomplete (missing steps) confusing (leave out requisite steps) or worse simply don't apply or work

most people will simply just give up long before this and go download unity or something else
seriously nothing is worse 
then downloading something that you need to sift thru a unorganized confusing 10 page 
installation instruction manual just to get it to fully install
it makes it very hard to recommend monogame to anyone who wants to do 3d stuff
when you have to tell them there is a bunch of stuff you have to read to install it

so again point is... it would be nice if there was a install download that included the pipeline tool

**Comment by cra0zy** [comment]
1) dev release does have pipeline tool, don't know about 3.2
2) you have to download submodules, daaa, or if you are downloading using "download zip" button,  https://github.com/Mono-Game/MonoGame.Dependencies
3) *caugh* teamcity.monogame.net *caught*
4) that actually is true, I agree on that part

**Comment by willmotil** [comment]
ah i didn't realize the dev release has added it in there .... 
disregard this then

its located here though in windows by default 
"C:\Program Files (x86)\MSBuild\MonoGame\v3.0\Tools\Pipeline.exe"

**Comment by tomspilman** [comment]
> i didn't realize the dev release has added it .... found it here

It installs shortcuts for them...  you should be able to just type Pipeline at the start menu/screen.
