### ISSUE TITLE
Pipeline Menu Hot Keys Causing Issues

### ISSUE THREAD

**Issue by dellis1972** [mono/MonoGame#3389]
@cra0zy People have reported issues with the menu's in the gtk pipeline app on mac. The menu shortcuts seem a bit strange. New is responding to a n instead of CMD+n . I'm not sure how these are defined on linux I assume its in the markup somewhere. Any ideas?

**Comment by dellis1972** [comment]
I found we need to use "<Control>n" for example for  accelerators on Mac. 

Will that tie in with Linux?

**Comment by cra0zy** [comment]
Do the following:
1) Open pipeline project
2) Under user interfaces find main window and open it. If you can'tr find "User Interfaces" folder, just add "New File", "Gtk", "Dialog", name it whatever, but don't delete it immediately. If you had main window opened close it and open it.
3) Go to for example "File" > "New.." and select accelerator
4) Now press the combination of keys that should be pressed for the action to activate

Try it with one action to see if it will fix it, if it doesn't I have another solution. Also if it does work, change all the keys and send me a file that's located under Pipeline/gtk-gui/gui.stetic

**Comment by cra0zy** [comment]
Scratch that, does &lt;Primary&gt;&lt;Mod2&gt;&lt;Control&gt;n work for you?

**Comment by cra0zy** [comment]
Scratch that too, Control + n is fine, I didn't see it when I was wrighting the first comment because github didn't update your change
