### ISSUE TITLE
Content builder - Handling custom data types

### ISSUE THREAD

**Issue by DDReaper** [mono/MonoGame#3403]
Is it possible to handle custom data types in a mgcb importer?

In XNA days we could have a separate class project with custom types defined and then reference that to the content solution.

**Comment by tomspilman** [comment]
I'm not sure exactly what you mean here.

If you mean can you for instance reference a custom type in an XML file and have the XML importer read it...   yes.  The assembly with the custom type it in needs to be something it can find.  An easy way to do that is to add it to the mgcb project as a assembly reference.

**Comment by DDReaper** [comment]
OK, answered the first part myself, although granted it's not ideal.

You have to manually add a reference to the dll that contains the custom types using the:
/reference:<assembly_path> 

Annoying that it has to link to a pre-build DLL but I can understand that

**Comment by tomspilman** [comment]
> You have to manually add a reference to the dll

Technically you did the same thing in XNA.  You had to add the project for the custom type into your solution and it had to be referenced from your content project....  or at least be a reference of a reference.


> Annoying that it has to link to a pre-build DLL 

Yeah...  but last thing we want to do is have the content pipeline start building assemblies.

All you have to do with the new templates is add the custom type project to your solution.  Change the build dependency order to ensure it builds before your game project.  Reference the assembly from the .mgcb file.

**Comment by KonajuGames** [comment]
> All you have to do with the new templates is add the custom type project to your solution. Change the build dependency order to ensure it builds before your game project. Reference the assembly from the .mgcb file.

I've done that myself just in the last few days, though I did notice that it appears to rebuild the data each time.  Once the custom importer and processor stabilized, I removed them from the solution and the content build time dropped dramatically.  All I can think of is that perhaps the assemblies were touched by the build process and the new test in the pipeline to detect updated assemblies is triggering a rebuild.

**Comment by tomspilman** [comment]
>  I did notice that it appears to rebuild the data each time

That should be fixed as of https://github.com/mono/MonoGame/pull/3372.

> All I can think of is that perhaps the assemblies were touched by the build process

Hum... if the build process is changing the "last modified time" when the assembly really isn't really modified that would be really shitty.
