### ISSUE TITLE
D3D compiler dll dependency

### ISSUE THREAD

**Issue by mrhelmut** [mono/MonoGame#3415]
Hello there,

I recently installed a new Win8.1 dev environment from scratch. After installing VS2013 (which includes Windows SDK 8.1 -- which itself include DirectX SDK ---), I tried to compile a MonoGame project targeting Windows DX.

I stumbled upon an mgcb/pipeline error when building shaders: ```Unable to load d3d_compiler_43.dll```

This dll/compiler is present in the discontinued DirectX SDK from June 2010.

Shader compiler are now redistributed with the Windows SDK (the 8.1 SDK packs version 47) since Vista, I believe.

The problem is that mgcb refers to a dll which may not be present on all setup and installing an outdated DirectX SDK may not suit every dev.
Making mgcb to search where the shader compiler is installed may be also tedious since the path is different from every Windows SDK version.

The DirectX SDK EULA and documentation (http://msdn.microsoft.com/en-us/library/windows/desktop/ee663275.aspx) states that any project using run-time shader compilation can be redistributed with the proper compiler dll/version. Would it be safe to do so with MonoGame installer? That would remove any dependencies for setting up MonoGame projects targeting Windows.

Let me know if that makes sense and I'll see if can manage to make the change to mgcb and the installer.

**Comment by tomspilman** [comment]
> The problem is that mgcb refers to a dll which may not be present on all setup and installing an outdated DirectX SDK may not suit every dev.

Here is my problem...  the code doesn't reference `d3d_compiler_43.dll`.  We simply call the DirectX SDK's D3DCompile method via SharpDX.  Within Microsoft's D3DCompile method it selects the correct version of the shader compiler to load...  as far as i know we have no control over that.


> any project using run-time shader compilation can be redistributed with the proper compiler dll/version

We could maybe do that.  

First test is if you simply put `d3d_compiler_43.dll` in the same install folder as 2MGFX.exe and MGCB.exe will it find it?

Still lets wait a few days to do this...  I want to get 3.3 out first.

**Comment by mrhelmut** [comment]
Sure, I just wanted to open the discussion.

Ok, so it's SharpDX who is picking the compiler's dll. I'll take a look at how it does so and come back here.

**Comment by tomspilman** [comment]
>  so it's SharpDX who is picking the compiler's dll

SharpDX does not pick the compiler dll...  Microsoft's `D3DCompile` method call does.

**Comment by mrhelmut** [comment]
That's what I meant to say, sorry. ^^

D3DCompile choose the dll version depending on the target platform.
For non-desktop platforms, the compiler is included with VS, so there is virtually no prerequisites.
For desktop platforms, things are less predictable as you mentioned. Moreover, even though putting the dll next to 2MGFX/MGCB works, there's still a dependency to the corresponding D3DX9_xx.dll.

Sounds like the nicest solution is to mention that building MonoGame projects requires DirectX June 2010 Redist on the download page.

**Comment by tomspilman** [comment]
> Sounds like the nicest solution is to mention that building MonoGame projects requires DirectX June 2010 Redist on the download page.

That sounds like a simple solution...  I just fixed it.

**Comment by theZMan** [comment]
Do you need the whole SDk or does the compiler ship with the D3DX files that get installed by the web installer here http://www.microsoft.com/en-us/download/details.aspx?id=35

Web installer is a lot nicer for people to stomach than the whole SDK.

**Comment by tomspilman** [comment]
All you need is the web installer... that is what I linked from the downloads page.

**Comment by theZMan** [comment]
That will teach me to read the whole thread instead of just the top few posts..
