### ISSUE TITLE
Can't create project with type: IPhone - Xamarin Studio Error

### ISSUE THREAD

**Issue by TheRubble** [mono/MonoGame#3422]
I've downloaded MonoDevelop.MonoGame_3.2.0.100.mpack, and installed into Xamarin Studio 5. However I can't create a project for IOS. Is this still the correct way to do this?

I'm getting Can't create project with type: IPhone as and error message when trying to do this.

**Comment by tomspilman** [comment]
@dellis1972 ?

**Comment by dellis1972** [comment]
Hmm, not sure. This must be an old mpack because the IPhone project type doesn't exist anymore afaik. @TheRubble where did you get the MonoDevelop.MonoGame_3.2.0.100.mpack from?
Can you screen shot the error message?

**Comment by TheRubble** [comment]
I found it in a solution, that someone else suggested from July last year, I've tracked back the file and it was from a user branch of monogame. I've uninstalled the mpack and I'm currently looking for the correct way to use monogame in Xamarin Studio 5.

**Comment by TheRubble** [comment]
I've now got monogame installed via Nuget, I have some other issues but these seem to lie outside of monogame. For anyone interested I created a Universal project under the Classic API IOS project type.
