### ISSUE TITLE
Tests that use Game.RunOneFrame aren't actually executed in XNA

### ISSUE THREAD

**Issue by tgjones** [mono/MonoGame#3423]
A pattern MonoGame uses in some of its tests, specifically the ones in fixtures derived from `VisualTestFixtureBase`, is to register an event handler with `Game.DrawWith`, and then call `Game.RunOneFrame()`. But I noticed while working in `VertexBufferTest.cs` that, when running these tests under XNA, the test window is never shown and the `DrawWith` event handler is never called, and so the test gives a false positive.

Only a few tests use this pattern:

* `IndexBufferTest.cs`
* `Texture2DTest.cs`
* `Texture3DTest.cs`
* `VertexBufferTest.cs`

The simplest fix is to replace these calls to `Game.RunOneFrame()` with `Game.Run()`. This works because the tests use a custom `Game` class, which defines a new `Run` method, which exits the game after some condition evaluates to true. By default, that condition is "exit after drawing one frame". So within the context of these tests, `Game.Run()` does exactly the same thing as `Game.RunOneFrame()`.

If, instead, we want to find the root cause so that we can continue using `RunOneFrame`, then... looking in the debugger immediately after `Game.RunOneFrame()` has been called, I can see that `IsActive`, as well as `doneFirstUpdate`, `doneFirstDraw`, etc. are all `false`. I have tried calling `Initialize` before `RunOneFrame`, but that doesn't help.

I can see in MG's implementation of `RunOneFrame()` that we initialise the game if it hasn't already been initialised. My best guess is that XNA doesn't do this - it expects the game to already be initialised (which it does in `Run`, but apparently not in `RunOneFrame`) . But I don't know enough about the XNA `Game` class to know how to do that initialisation. (Or put another way, I'm not sure how XNA's `RunOneFrame` is intended to be used at all.)

**Comment by tomspilman** [comment]
>  so the test gives a false positive.

Ah... so that was the bit I missed.  For me it seemed the test was running fine...  but yes... it doesn't actually run the `DrawWith` callback so nothing is actually being tested.

> The simplest fix is to replace these calls to `Game.RunOneFrame()` with `Game.Run()`. 

Yes... now that I understand what the issue is, that makes sense to me.

Also I was confusing with the XNA `RunOneFrame` method with the `RunSingleFrameTest` method which is part of the test framework.  I know that `RunSingleFrameTest` sometimes fails (that 0 images captured thing) which is what I was thinking of when you said `RunOneFrame` wasn't working.

> I can see in MG's implementation of `RunOneFrame()`  that we initialise the game if it hasn't already been initialised. 

Yea...  i'm not sure why we do that.  It could be that it was just a mistake thinking XNA did this as well.  That said our implementation is actually more useful this way.

> I'm not sure how XNA's `RunOneFrame` is intended to be used at all.

I don't either then.  In the docs it says it is only for debugging.

**Comment by tgjones** [comment]
> Ah... so that was the bit I missed.

Yeah, sorry, I didn't really explain it coherently before.

> That said our implementation is actually more useful this way.

I agree - I think MG's implementation is more useful.

I've tried a few more things to get `RunOneFrame` to call `Draw` - I've tried calling various combinations of `BeginRun` and `Initialize` before calling `RunOneFrame`, but nothing seems to work. I'm really stumped, I'm not sure how people use this method at all! But then this very issue is already in 4th place on Google for "game.runoneframe", so perhaps it's just not used :-)

>> The simplest fix is to replace these calls to Game.RunOneFrame() with Game.Run().

> Yes... now that I understand what the issue is, that makes sense to me.

Shall I create a PR with this change?

**Comment by willmotil** [comment]
xna's runOneFrame was for internal use if i remember in relation to setting isGameRuning
which was very annoying to me 
in fact i think i tried to make a partial class and extend into game to get at it and rig it but i couldn't
though i did that with other xna class's

the reason for the user or debuging to have it is simple 
you don't want this below in update or draw when testing or needed you want it underneath 
so you don't have to add it everytime you make a new game1
[code]
if(!hasrunonce)
{
// fire delegate calls ExecutedOnlyOnce
FireOnce();
hasrunonce = true;
}
ExecutedOnlyOnce()
{
// for some code that is dynamically loaded or run after everything is set up
// this is called automatically after a successful draw 
// were you expect that both initialize and load have been successfully excecuted. 
}
[/code]

**Comment by tomspilman** [comment]
> Shall I create a PR with this change?

@tgjones - Sure... go for it.
