### ISSUE TITLE
Content Pipeline on Fedora

### ISSUE THREAD

**Issue by dellis1972** [mono/MonoGame#3424]
@cra0zy any chance you could take a look at these issues?

http://community.monogame.net/t/some-issues-with-pipeline-tool-on-fedora/1798

**Comment by cra0zy** [comment]
will do

**Comment by dellis1972** [comment]
thanks

**Comment by cra0zy** [comment]
#3426

**Comment by dellis1972** [comment]
Great work thanks @cra0zy
