### ISSUE TITLE
SpriteFont Texture Color are swapped from RGBA to BGRA even if processor is set to Color

### ISSUE THREAD

**Issue by Eversor** [mono/MonoGame#3430]
This is a reproducible issue in Windows (dx AND gl).

https://www.dropbox.com/s/yuiip7y8nibry9c/FontBuildIssue.zip?dl=0

This is a project that basically shows the issue, the font is a number font from our game, i colored it to show the problem: 
1) at the top you can see the original texture from wich the font should be drawn (SpriteBatch.Draw)
2) the second and third line shows the actual result: R and B are swapped. (SpriteBatch.DrawString)

![colorfontissue](https://cloud.githubusercontent.com/assets/733699/5794467/92a3916c-9f6e-11e4-848a-7bf639cabe3e.png)

**Comment by Eversor** [comment]
Is there any test already in place for spritefont textures?
I'd like add one to solve the issue (even if this is most easily done with a simple change in the assetreader to read Color data instead of BGRA data...
Should i make some trial and error and then submit a pull request once i'm confident with the testing environment? 
I see a lot of references in the help about using "game components" for visual tests, then when i look at the actual code it's all made with plain and fast to write [Test] methods...

**Comment by KonajuGames** [comment]
I've submitted a fix in #3453.

**Comment by tomspilman** [comment]
> I see a lot of references in the help about using "game components" for visual tests

Where do you see that?

**Comment by Eversor** [comment]
https://github.com/kungfubanana/MonoGame-Tests
it's also in the readme.md in the directory with the monogame unit-test csproj:

### Workflow for Implementing a Visual Test

A good visual test, like any good test, should perform the minimum work
necessary to verify that the functionality under test is correct.  As
much as possible, drawing and test code should be made modular by
inheriting from ```GameComponent```, ```DrawableGameComponent```,
```VisualTestGameComponent```, or ```VisualTestDrawableGameComponent```
to encourage reuse, rather than duplication, in other tests.

Sorry, i'm not really used to do open source contribution and i'm the only one at my company that "knows" (that's a big word) what a versioning system is.

**Comment by Eversor** [comment]
Thanks Konaju, i have passed like 5 times over that boolean and i would have never expected it to do such a breaking change...

**Comment by tomspilman** [comment]
>  i have passed like 5 times over that boolean and i would have never expected it to do such a breaking change.

It highlights the evils of Boolean types as arguments to functions.  Unless you look at the function signature you can't tell what it is doing.

**Comment by tomspilman** [comment]
> https://github.com/kungfubanana/MonoGame-Tests
> it's also in the readme.md in the directory with the monogame unit-test csproj:

So I see what you mean.  The tests actually have moved here:

 https://github.com/mono/MonoGame/blob/develop/Test

The old @kungfubanana repo is no longer used, but with him MIA we've not been able to shut it down.

I'll look to fix that readme in the next few weeks.

**Comment by Eversor** [comment]
If i'm not wrong bgr encoding is used on some platforms, any chance this will break ios builds?

**Comment by tomspilman** [comment]
> If i'm not wrong bgr encoding is used on some platforms

Yes... but that isn't why that was there.


> any chance this will break ios builds?

It is always possible, but I suspect not.  The encoding for platform specific formats is done later.
