### ISSUE TITLE
Errors in Texture2D.OpenGL.cs

### ISSUE THREAD

**Issue by greyp** [mono/MonoGame#3435]
Line 423:
            var bitmapContext = new CGBitmapContext(data, width, height, 8, width * 4, colorSpace, CGBitmapFlags.PremultipliedLast);

Error CS1502: The best overloaded method match for `CoreGraphics.CGBitmapContext.CGBitmapContext(byte[], int, int, int, int, CoreGraphics.CGColorSpace, CoreGraphics.CGImageAlphaInfo)' has some invalid arguments (CS1502) (MonoGame.Framework.iOS)

Error CS1503: Argument `#2' cannot convert `System.nint' expression to type `int' (CS1503) (MonoGame.Framework.iOS)

**Comment by prollin** [comment]
You most likely need to update your version of Xamarin and re-run Protobuild.exe. MonoGame now uses the new Xamarin Unified API for iOS (required for new apps submitted to the AppStore starting February 2015 and for updates June 2015)

**Comment by tomspilman** [comment]
Make sure you update Xamarin Studio.  In just the last week we changed the code to support it.

**Comment by greyp** [comment]
Ah I see. Thanks guys! :)

**Comment by tomspilman** [comment]
No prob... it happens.
