### ISSUE TITLE
Pipeline: feature request: tree should expand by default

### ISSUE THREAD

**Issue by vancura** [mono/MonoGame#3443]
Tree should be expanded by default, when adding files they're added to a closed branch, so the user needs to expand it afterwards (an UX problem).

**Comment by KonajuGames** [comment]
I would narrow this down to being the part of the tree being modified should be expanded.  Expanding the entire tree is overkill and will result in an unnecessarily long treeview in most cases.

**Comment by vancura** [comment]
Sure, sorry.

**Comment by dneelyep** [comment]
Noting that this issue should be closed, since it looks like it was fixed in PR #3445.

**Comment by tomspilman** [comment]
Thanks!
