### ISSUE TITLE
Xamarin Unified API Hides MediaPlayer on iOS

### ISSUE THREAD

**Issue by Nezz** [mono/MonoGame#3446]
Xamarin's decision to omit the MonoTouch (or anything else) from the namespaces
in the new API makes it rather inconvenient to use classes that have the same name as
Xamarin's namespaces. One such example is MediaPlayer.

You will get an error like this:
>Error CS0234: The type or namespace name `Play' does not exist in the
namespace `MediaPlayer'. Are you missing an assembly reference?

That's because the compiler will see `MediaPlayer` as a namespace name instead of MonoGame's class.

Using a namespace alias outside your namespace declaration won't work either:
>using MediaPlayer = Microsoft.Xna.Framework.Media.MediaPlayer;
Error CS0576: Namespace `global::' contains a definition with same name as
alias `MediaPlayer'

However, declaring it inside your namespace will work:
```C#
// Not here

namespace MyGame
{
    // But here
    using MediaPlayer = Microsoft.Xna.Framework.Media.MediaPlayer;

    public class MyClass { }
}
```

Due to the very general names in the iOS SDK you will expect similar behavior with other class names like Accounts, Dialog, Photos, Social and Security.

**Comment by tomspilman** [comment]
> However, declaring it inside your namespace will work

Makes sense... we should resort to this whenever we have a conflict like that.

**Comment by danzel** [comment]
Urgh, yeah this sucks.
I've gone for
```c#
using XnaMediaPlayer = Microsoft.Xna.Framework.Media.MediaPlayer;
```
At the top of the file and then using XnaMediaPlayer instead of MediaPlayer.

Not sure if we need an open issue for this? Maybe a note somewhere for people upgrading to unified API.

**Comment by tomspilman** [comment]
> Not sure if we need an open issue for this? 

Naw... i'll close it.

Still if someone doesn't like how this is working they should direct their complaints to Xamarin.  They are making C# harder to use by skipping the general namespacing standards Microsoft and every other C# vender/library follow including MonoGame.
