### ISSUE TITLE
Linux SpriteFont Processor doesn't use family names

### ISSUE THREAD

**Issue by CallumDev** [mono/MonoGame#3447]
When building a spritefont file in Pipeline on Linux, mgcb searches for the font by filename, but not by family name. This means that a spritefont description won't build when asking for 'Arial', as the filename on most Linux systems is 'arial.ttf'. 

A way of fixing this would be to call into fontconfig, but should such a wrapper be implemented inside MonoGame or as a separate project?

**Comment by cra0zy** [comment]
What do you mean by fontconfig?

**Comment by CallumDev** [comment]
Fontconfig as in the library used for font configuration on Linux (libfontconfig.so)
[This](https://gist.github.com/CallumDev/7c66b3f9cf7a876ef75f) is an example of how it would be used

**Comment by cra0zy** [comment]
I found another solution, run in terminal: "fc-list : file family", now the only question is which is better.

**Comment by cra0zy** [comment]
@tomspilman This can be closed.
