### ISSUE TITLE
Request: remove effects from Effect.EffectCache when effect is disposed

### ISSUE THREAD

**Issue by tgjones** [mono/MonoGame#3449]
Effects are cached in a private static field in `Effect.EffectCache`. But the only code that calls the internal `Effect.FlushCache()` is `Game.Dispose()`.

It took me a while to figure out that this is the root cause of why some of my visual tests are failing. I'm not using a `Game` object - I'm just creating lower-level objects like `GraphicsDevice` directly. But because I'm disposing the `GraphicsDevice` and other graphics resources after each test, any effects left in the cache are unusable. Any subsequent tests that use the same `Effect` don't work.

I'm not sure what the best solution is - it seems like cached effects should be removed when the `GraphicsDevice` used to create them (rather than the `Game`) is disposed? Or at least, when the `Effect` itself is disposed (I think `GraphicsDevice.Dispose` already calls `Dispose` on `GraphicsResource` objects, so that may be enough).

For now, I've worked around it with this, but it's not pretty:

``` csharp
typeof(Effect).GetMethod("FlushCache", BindingFlags.NonPublic | BindingFlags.Static).Invoke(null, null);
```

**EDIT**: I've just run into a similar issue with state objects - I get exceptions because they are associated with a different graphics device. Basically, I think I need to be able to [what Game is doing here](https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Game.cs#L120) (or even better, have it happen implicitly when `GraphicsDevice` is disposed):

``` csharp
if (_graphicsDeviceManager != null)
{
    Effect.FlushCache();
    BlendState.ResetStates();
    DepthStencilState.ResetStates();
    RasterizerState.ResetStates();
    SamplerState.ResetStates();

    ...
}
```

**Comment by tomspilman** [comment]
Yeah...  what needs to happen is similar to what https://github.com/mono/MonoGame/pull/3436 is doing.

We need to move the effect cache and the default render states into `GraphicsDevice`.  This should be as simple as moving `Effect.EffectCache` into `GraphicsDevice.EffectCache` and making it non-`static`.

This would be a good first step to better support for multiple `GraphicsDevice`s and would be a good first step towards support for multiple graphics contexts in the future.

**Comment by tgjones** [comment]
Ah, cool. I saw that PR but missed that it included a fix for this. Should I wait until #3436 is resolved one way or another?

**Comment by tomspilman** [comment]
> Should I wait until #3436 is resolved one way or another?

I don't think we'll merge that PR as is.

First his `GraphicsDeviceContext` object isn't what we're looking for moving forward.  We want `GraphicsDevice` to inherit from `GraphicsDeviceContext`.  Still this isn't a priority at the moment... so we would rather see everything in `GraphicsDevice` and no `GraphicsDeviceContext`.

Second we need a better solution for the static states in `BlendState`, `DepthStencilState`, `RasterizerState`, and `SamplerState`.  His solution was to have a global "current" graphics context.  We cannot do that as it boxes us in if we want to support threaded rendering in the future.

I think a simpler solution is a little switch specifically for the default static states like `BlendState.Additive` or `RasterizerState.CullClockwise`.  We need to store a totally separate set of states within `GraphicsDevice` like so:

```
internal BlendState AdditiveBlendState = BlendState.Additive.Clone();
```

Then where we apply blend states we need to do something like this:
```
   if (newBlendState == BlendState.Additive)
       device.AdditiveBlendState.PlatformApplyState(this);
   else
      newBlendState.PlatformApplyState(this);
```

This way we always have per-device default states without any global.

**Comment by tgjones** [comment]
This sounds good - I'm working on a PR with these changes.

**Comment by tomspilman** [comment]
Fantastic!

**Comment by tgjones** [comment]
Here it is - #3472.
