### ISSUE TITLE
Pipeline Tool Gtk# - Save option never enabled after editing.

### ISSUE THREAD

**Issue by dellis1972** [mono/MonoGame#3456]
When altering properties of a Processor or Importer the save button is never enabled. The only way to save changes is to hit the build button or use save as.

**Comment by tomspilman** [comment]
On the Windows version of the tool we never enable/disable the save button, so we've not seen this issue there.  

If the GTK save button tracks the state of `IController.ProjectDirty` then it could be an issue in the common code.

If does its own logic for when it should be enabled then it should be fixed to track `IController.ProjectDirty`.

**Comment by cra0zy** [comment]
Funny thing, this is actually Mac only bug...
