### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by darkoverlordofdata** [mono/MonoGame#3460]
Running on Linux Mint 1, I am following the instructions at https://github.com/mono/MonoGame/wiki/Tutorials:-Getting-Started-on-Linux

After sudo apt-get install monodevelop, I get this issue:

The following packages have unmet dependencies:
 monodevelop-monogame : Depends: monodevelop (< 4.0.12.) but 5.7.0.660-0xamarin2 is to be installed

**Comment by tomspilman** [comment]
Any ideas here @cra0zy ?

**Comment by WardBenjamin** [comment]
Currently, the templates do not work correctly for MonoDevelop versions >=5. This is because of a change in the packaging for the templates/etc. There is progress being made on this by @dellis1972. See pull request https://github.com/mono/MonoGame/pull/3361 for more details.

**Comment by cra0zy** [comment]
I try to keep the newest version of monogame for linux here: http://community.monogame.net/t/how-to-install-monogame-3-2-in-ubuntu-14-04/983/17

**Comment by darkoverlordofdata** [comment]
I tried the link from cra0zy labeled addin for monodevelop 5.7:

Monodevelop froze, so I tried to restart it, and then It wouldn't launch. I
deleted ~/.local/share/MonoDevelop-5.0/LocalInstall/Addins/MonoDevelop.MonoGame.3.2.0,
and then it works again, but of course without the monogame templates.
Definitely not working :)


On Fri, Jan 23, 2015 at 4:21 PM, Harry <notifications@github.com> wrote:

> I try to keep the newest version of monogame for linux here:
> http://community.monogame.net/t/how-to-install-monogame-3-2-in-ubuntu-14-04/983/17
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mono/MonoGame/issues/3460#issuecomment-71289222>.
>



-- 

Bruce Davidson
Schedule a meeting: https://meetin.gs/meet/bruce-davidson

**Comment by cra0zy** [comment]
The addin does work, but on monodevelop 5.7. Try doing:
sudo apt-get remove monodevelop-monogame
sudo apt-get install monodevelop

Also if monodevelop does not start after installing some addin do: after installing disable addin immediately, restart monodevelop, enable it, restart monodevelop.

**Comment by cra0zy** [comment]
I must say I am getting tired of awnsering "how to install monogame on linux", it's getting more and more iritating each time. Tomorow I am so setting up some tutorial for it in monogame documentation...

**Comment by darkoverlordofdata** [comment]
1)  The addin does work, but on monodevelop 5.7. Try doing:
    sudo apt-get remove monodevelop-monogame
    sudo apt-get install monodevelop

I get: Package 'monodevelop-monogame' is not installed, so not removed

As originally stated:
The following packages have unmet dependencies:
monodevelop-monogame : Depends: monodevelop (< 4.0.12.) but 5.7.0.660-0xamarin2 is to be installed


2)  Also if monodevelop does not start after installing some addin do: after installing disable addin immediately, restart monodevelop, enable it, restart monodevelop.

That is exactly what I said I did - I wasn't raising an issue on that. The link I was given suggested trying to install the mpack directly from the download given. When it didn't work, I deleted it, restarted monodevelop, and reported that it didn't work.


Don't worry about it. I've tried installing monogame several times over the past 2 years, on Windows7, Ubuntu, and Mint. It has never installed. Everytime I report an issue to Monodevelop, I am greeted with this kind of rudeness. I don't need this aggravation.

**Comment by tomspilman** [comment]
> I am greeted with this kind of rudeness.

No one has been rude here.  You are simply misinterpreting our frustration of getting the Linux install process working.

**Comment by WardBenjamin** [comment]
> The following packages have unmet dependencies:
monodevelop-monogame : Depends: monodevelop (< 4.0.12.) but 5.7.0.660-0xamarin2 is to be installed

I suggest letting the `sudo apt-get install monodevelop` complete without installing `monodevelop-monogame`. This should install a version of MonoDevelop that is compatible with the MonoGame addin, so it should then work correctly without crashing MonoDevelop.

**Comment by darkoverlordofdata** [comment]
Monodevelop is already installled. I'm currently using monodevelop 5.7.0, that is the latest stable release, and it's been working fine.

I'm just trying to add monogame. On the page I referred to 'Getting Started with Linux' the section Required Packages, after it says that you need both monodevelop and monogame, and goes on with these instructions (being on Mint, I use the Ubuntu instructions):

In order to install the required packages:

Ubuntu
    sudo apt-get install libmonogame-cil-dev monodevelop-monogame


So, when I enter that, I get an error: 


Reading package lists... Done
Building dependency tree       
Reading state information... Done
libmonogame-cil-dev is already the newest version.
libmonogame-cil-dev set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 monodevelop-monogame : Depends: monodevelop (< 4.0.12.) but 5.7.0.660-0xamarin2 is to be installed

**Comment by dellis1972** [comment]
@darkoverlordofdata you can try the "alpha" addin if you like, its a work in problem but it should be compatible with XS 5.7

https://dl.dropboxusercontent.com/u/18881050/MGCB/MonoDevelop.MonoGame_3.2.0.mpack

I can't guarantee it will work, bit its worth a shot.

**Comment by jedabero** [comment]
I'm getting the same problem when trying to install monodevelop-monogame as @darkoverlordofdata. I also tried installing from the Add-in Manager after downloading MonoGame 3.0.1 for MonoDevelop @ http://www.monogame.net/2013/03/03/monogame-3-3/ and get this:

The selected add-ins can't be installed because there are dependency conflicts.
The package 'Core v3.0' could not be found in any repository.
The package 'Ide v3.0' could not be found in any repository.

**Comment by cra0zy** [comment]
For everyone, monodevelop-monogame is a really old package that I do not recomend using. It has monogame 2.X which is really really old.

**Comment by darkoverlordofdata** [comment]
That's this one that didn't work:

I try to keep the newest version of monogame for linux here:
http://community.monogame.net/t/how-to-install-monogame-3-2-in-ubuntu-14-04/983/17

On Sat, Jan 24, 2015 at 4:30 AM, Dean Ellis <notifications@github.com>
wrote:

> @darkoverlordofdata <https://github.com/darkoverlordofdata> you can try
> the "alpha" addin if you like, its a work in problem but it should be
> compatible with XS 5.7
>
>
> https://dl.dropboxusercontent.com/u/18881050/MGCB/MonoDevelop.MonoGame_3.2.0.mpack
>
> I can't guarantee it will work, bit its worth a shot.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mono/MonoGame/issues/3460#issuecomment-71314731>.
>



-- 

Bruce Davidson
Schedule a meeting: https://meetin.gs/meet/bruce-davidson

**Comment by darkoverlordofdata** [comment]
This was helpful:

 For everyone, monodevelop-monogame is a really old package that I do not
recomend  using. It has monogame 2.X which is really really old.

So that means an older version of monodevelop may work? I'm not married to
the 5.7 version, it's just the one recommended on monodevelop.org

So, I reverted to 4.0.12, and voila! Monogame installs per the instructions
in your wiki,

I swear I tried 4.0.12+Monogame several months ago, and it didn't work. I
understand that you can't always keep up with Monodevelop. But I think it
would be helpful if you had some info about  which version you are
compatible with.


Thanks, and close this.




On Sat, Jan 24, 2015 at 10:13 AM, bruce <darkoverlordofdata@gmail.com>
wrote:

> That's this one that didn't work:
>
> I try to keep the newest version of monogame for linux here:
> http://community.monogame.net/t/how-to-install-monogame-3-2-in-ubuntu-14-04/983/17
>
> On Sat, Jan 24, 2015 at 4:30 AM, Dean Ellis <notifications@github.com>
> wrote:
>
>> @darkoverlordofdata <https://github.com/darkoverlordofdata> you can try
>> the "alpha" addin if you like, its a work in problem but it should be
>> compatible with XS 5.7
>>
>>
>> https://dl.dropboxusercontent.com/u/18881050/MGCB/MonoDevelop.MonoGame_3.2.0.mpack
>>
>> I can't guarantee it will work, bit its worth a shot.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mono/MonoGame/issues/3460#issuecomment-71314731>.
>>
>
>
>
> --
>
> Bruce Davidson
> Schedule a meeting: https://meetin.gs/meet/bruce-davidson
>



-- 

Bruce Davidson
Schedule a meeting: https://meetin.gs/meet/bruce-davidson

**Comment by cra0zy** [comment]
> That's this one that didn't work:

No, it's not...

**Comment by darkoverlordofdata** [comment]
So how come it shows up as a duplicate filename when I try to download it?

**Comment by cra0zy** [comment]
> So how come it shows up as a duplicate filename when I try to download it?

Because both me and @dellis1972 have kept the old naming scheme...

**Comment by darkoverlordofdata** [comment]
Ok... So I re-installed Monodevelop 5.7, and installed your version
of MonoDevelop.MonoGame_3.2.0.mpack. That worked. I have 2 selections for
new MonoGame solutions - Shared and OpenGL.

But when I create a app from the OpenGL templaate, it get's en execution
error when I run the new program:
System.DllNotFoundException: SDL.dll
  at at (wrapper managed-to-native) Tao.Sdl.Sdl:__SDL_InitSubSystem (int)
  at Tao.Sdl.Sdl.SDL_InitSubSystem (Int32 flags) [0x00000] in <filename
unknown>:0
  at Microsoft.Xna.Framework.OpenTKGamePlatform..ctor
(Microsoft.Xna.Framework.Game game) [0x00000] in <filename unknown>:0
  at Microsoft.Xna.Framework.GamePlatform.Create
(Microsoft.Xna.Framework.Game game) [0x00000] in <filename unknown>:0
  at Microsoft.Xna.Framework.Game..ctor () [0x00000] in <filename unknown>:0
  at test.Game1..ctor () [0x00000] in /home/bruce/mono/test/test/Game1.cs:21
  at test.Program.RunGame () [0x00001] in
/home/bruce/mono/test/test/Program.cs:30
  at test.Program.Main (System.String[] args) [0x00001] in
/home/bruce/mono/test/test/Program.cs:52


But when it created this solution, the log showed:
Added file 'SDL_mixer.dll'.
Added file 'SDL_mixer.dll' to project 'test'.
Added file 'SDL.dll'.
Added file 'SDL.dll' to project 'test'.




On Sat, Jan 24, 2015 at 11:44 AM, Harry <notifications@github.com> wrote:

> So how come it shows up as a duplicate filename when I try to download it?
>
> Because both me and @dellis1972 <https://github.com/dellis1972> have kept
> the old naming scheme...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mono/MonoGame/issues/3460#issuecomment-71334023>.
>



-- 

Bruce Davidson
Schedule a meeting: https://meetin.gs/meet/bruce-davidson

**Comment by cra0zy** [comment]
The new addin is missing config files for opentk and tao.sdl which I did say above............. You need to download those 2 files from monogane dependencies and copy them to bin dir of your project.

**Comment by darkoverlordofdata** [comment]
Thanks - it's looking for the libSDL.so and libSDL_mixer.so. I copied those to the bin and it worked. This helped sort it out:
http://www.mono-project.com/docs/advanced/pinvoke/dllnotfoundexception/

It all appears to work.

**Comment by saglogog** [comment]
Thanks for your help @cra0zy, the copying of the config files in the bin directory was indeed helpful.
