### ISSUE TITLE
[SharpDX] GraphicsAdapter.DefaultAdapter.CurrentDisplayMode.Width / .Height does not return true desktop resolution

### ISSUE THREAD

**Issue by FantasyVI** [mono/MonoGame#3473]
[Current behaviour]
GraphicsAdapter.DefaultAdapter.CurrentDisplayMode.Width return value of 800.
GraphicsAdapter.DefaultAdapter.CurrentDisplayMode.Height return value of 600.

[Expected behaviour]
GraphicsAdapter.DefaultAdapter.CurrentDisplayMode.Width should return current desktop width  resolution (not window or viewport width resolution). which in my case is 1920.

GraphicsAdapter.DefaultAdapter.CurrentDisplayMode.Height should return current desktop height resolution (not window or viewport height resolution). which in my case is 1080.

**Comment by danzel** [comment]
So this is with the DirectX version of MonoGame?

I've used:
```
GraphicsDevice.DisplayMode.Width;
```
Which works, so interesting that this wouldn't.

**Comment by FantasyVI** [comment]
Yes, this is the DirectX version of MonoGame.

hmm, its weird that it's working for you but not me. I have also tried (GraphicsDevice.DisplayMode.Width) its still returning 800 instead of 1920.

Maybe it has something to do with my hardware?

I'm running on Windows 8.1 pro with VS 2013 and I have a AMD 6970 running two monitors both of which are 1080P. my first monitor running of an HDMI and my second one is running of a Display Port adapter.

**Comment by danzel** [comment]
What version of MonoGame are you using?

**Comment by FantasyVI** [comment]
3.2

**Comment by danzel** [comment]
That'll do it.
Grab a newer build off the build bot:
http://teamcity.monogame.net/repository/download/MonoGame_DevelopWin/5154:id/Windows/MonoGameSetup.exe

**Comment by FantasyVI** [comment]
ok, well perfect. that fixed it ^_^

thank you :)
