### ISSUE TITLE
GamerServices not available on Linux after clean compile

### ISSUE THREAD

**Issue by WardBenjamin** [mono/MonoGame#3478]
After a clean compile of MonoGame with no changes, I have found out that `Microsoft.Xna.Framework.GamerServices` doesn't exist on Linux. The project compiles cleanly on Win8.1 with no errors and MonoGame 3.2, but not in this case. Is this intentional and a part of the changes slated for the next version? I would think not since it would break compatability, but it is always possible.

**Comment by cra0zy** [comment]
GamerServices are located in MonoGame.Framework.Net.dll file, you should have it in bin directory for MonoGame Framework if you compiled from source.

**Comment by WardBenjamin** [comment]
Alright, I thought I had that library file referenced but I may have been
mistaken. I'll try it later today.

On Sat, Jan 31, 2015 at 6:32 AM, Harry <notifications@github.com> wrote:

> GamerServices are located in MonoGame.Framework.Net.dll file, you should
> have it in bin directory for MonoGame Framework if you compiled from source.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mono/MonoGame/issues/3478#issuecomment-72314277>.
>



-- 
Benjamin Ward

**Comment by cra0zy** [comment]
@tomspilman This can be closed.

**Comment by WardBenjamin** [comment]
I got it :)
