### ISSUE TITLE
MonoGame for MonoDevelop <OS> downloads 404ing.

### ISSUE THREAD

**Issue by mpatraw** [mono/MonoGame#3481]
The page I'm specifically talking about is: http://www.monogame.net/downloads/ Clicking any of the links at the bottom for MonoDevelop go to a 404 page.

**Comment by tomspilman** [comment]
@dellis1972 - Is there any good and simple solution for the 3.3 release for this?  Or should we release 3.3 without MonoDevelop/XamarinStudio packages?

**Comment by dellis1972** [comment]
@tomspilman that is the old addin that should be removed from the downloads section. This will be replaced by the new one which I will have sorted this week

**Comment by tomspilman** [comment]
Ok... downloads page updated with note of the pending new addins.
