### ISSUE TITLE
Main thread doesn't stop since 928b1d155120423e74b9056ec0a9caa8039c8545

### ISSUE THREAD

**Issue by mrhelmut** [mono/MonoGame#3486]
Hello =]

Since commit 928b1d155120423e74b9056ec0a9caa8039c8545 the main ```Game``` loop keeps running after ```Game.Exit()```. The Window is correctly hidden/closed but the thread remain active (stuck in the ```Game.Tick()``` method / RetryTick loop).

Tested on Windows / .Net CLR.

@christallire do you think we should separate Mono/.net code paths? Or is there something to do to fix this on both runtimes?

**Comment by tomspilman** [comment]
I was totally nervious about that change.

@KonajuGames can you look to fix this really quick?

**Comment by KonajuGames** [comment]
I'll take a look now.​

**Comment by chris-sung** [comment]
@mrhelmut I just made a quick sample application and ran on both platforms.
It works, this makes me nervous too.

**Comment by mrhelmut** [comment]
Ok, I'll take a closer look at what's going on in my projects and will try to make a minimal test in the coming hours.

**Comment by KonajuGames** [comment]
I found the problem.  Clicking the Close button worked fine, but calling Game.Exit didn't.  I have a solution I'm sending up now.

**Comment by KonajuGames** [comment]
#3488

**Comment by KonajuGames** [comment]
I've merged the fix I put up.  Let me know how it goes.

**Comment by mrhelmut** [comment]
It works! Cookies for such a quick fix.
