### ISSUE TITLE
EffectPassCollection.Count: getting tons of garbage

### ISSUE THREAD

**Issue by KakCAT** [mono/MonoGame#3498]
Hi,

I'm getting a big amount of garbage when using a "'classic' foreach (var eff in  effect.CurrentTechnique.Passes)" loop.

I'm aware that this kind of loops can get garbage, so I decided to do a simple for, getting "Count" before the loop. Weirdly, it seems the garbage is coming from "Count" :

(memory profiler output)
```
    Allocating Method	Instances	Inclusive Size (Bytes)	Exclusive Size (Bytes)	Allocating Module
    System.SZArrayHelper.GetEnumerator<M>()	48347	966940	966940	mscorlib.ni.dll
    Microsoft.Xna.Framework.Graphics.EffectPassCollection. System.Collections.Generic.IEnumerable<Microsoft.Xna.Framework.Graphics.EffectPass>.GetEnumerator()	48347	966940	0	MonoGame.Framework.DLL
    System.Linq.Enumerable.Count<M>(System.Collections.Generic.IEnumerable`1<M>)	48347	966940	0	System.Core.ni.dll
    my function call here
```
I'm drawing a big amount of objects, so the GC hits every 15 seconds or so.

My solution so far is 'caching' the effect.CurrentTechnique.Passes.Count() value for every effect at the start, and use those cached values. This gets rid of the GC for several minutes. However this is a quite dirty hack.

Isn't there a way to get rid of that garbage generation?

Platform is WP8, but I don't know if this is common to all platforms.

EDIT: what I don't understand is why that function could generate garbage. Looking at the code, it seems it's just an Array.Length function...

**Comment by mgarstenauer** [comment]
> Isn't there a way to get rid of that garbage generation?

Yes. ;-)
You are calling the extension method `Enumerable.Count` instead of the property `EffectPassCollection.Count`. Instead of `effect.CurrentTechnique.Passes.Count()` you need to write `effect.CurrentTechnique.Passes.Count`.

**Comment by tomspilman** [comment]
`effect.CurrentTechnique.Passes.Count()`  is a function that internally iterates thru the collection to count up items.  That overhead plus `EffectPassCollection` not having a custom efficient enumerator is the reason for your trouble.

It would be pretty simple to add an efficient `struct` enumerator for `EffectPassCollection`.  If any place in MonoGame needs one that would be it.

**Comment by KakCAT** [comment]
I'm feeling really stupid about the Count() part , specially when I had it in front on my eyes for quite a long time, wondering how on earth could that be generating garbage :) (that's why I hate having vars and funcs being able to have the same name)

@tomspilman: Do you want me to leave this issue open in order for somebody to implement it? (unfortunately I don't think I would be able to do this)


Thanks!
