### ISSUE TITLE
So tutorials....

### ISSUE THREAD

**Issue by cra0zy** [mono/MonoGame#3508]
So, should monogame documentation have it's own tutorials? If the answer is yes, than it would be nice to use this thread as listing for the tutorials that should be written, how to categorize them, etc

**Comment by tomspilman** [comment]
Well I don't think we want any "here is how to make a whole game" like tutorials yet.

I think what we want are small articles that focus on how to use a particular feature.  For example if you look at the old XNA docs:

  https://msdn.microsoft.com/en-us/library/bb198548.aspx

See how they have an article on the game loop, another on basic rendering, another on user inputs, etc.  I think we need to write various individual articles like those.  The big difference for us is that we want to inject information about all the platforms we support.

These articles would be written in MD format and added here:

  https://github.com/mono/MonoGame/tree/develop/Documentation

... then they can be linked into the TOC via he SharpDoc config file:

  https://github.com/mono/MonoGame/blob/develop/Documentation/config.xml

This will then allow us to generate both docs on the website as well as stand alone CHM or PDF docs in the future.

**Comment by tomspilman** [comment]
Note I started an issue almost a year ago hoping to get some sort of high level outline for docs agreed on.  Maybe this issue should be closed and the discussion moved there?

 https://github.com/mono/MonoGame/issues/2520

**Comment by cra0zy** [comment]
Sorry, I did not notice, I'll close this.
