### ISSUE TITLE
TextureUsage still being referenced in MacOS project.

### ISSUE THREAD

**Issue by CartBlanche** [mono/MonoGame#3509]
I just updated to the latest develop and noticed that TextureUsage.cs is still being referenced in the MacOS project. As a result MacOS build is failing. Removing the reference to this file allows the MacOS sln to build successfully.

D.

**Comment by tomspilman** [comment]
Did you run Protobuild first?

**Comment by KonajuGames** [comment]
I've lost count of the number of times I've forgotten to run Protobuild.  Easily rectified though.  The same as I always forget to launch Steam the first time that day I try to run our Steam-enabled game.

**Comment by tomspilman** [comment]
@CartBlanche - So...  did you run Protobuild first?  Can we close this issue?

**Comment by dellis1972** [comment]
I have the latest here, and I can't see this file in my project

**Comment by Shqrdx** [comment]
@dellis1972 This is good or bad sign ?  (I deleted this file from MonoGame.)

**Comment by tgjones** [comment]
I just did a clean checkout / build of the `MacOS` solution, and it compiled fine for me.

**Comment by tomspilman** [comment]
Must have just forgotten to run Protobuild.
