### ISSUE TITLE
WindowsGL project initial window position/location setting?

### ISSUE THREAD

**Issue by 6thVenom** [mono/MonoGame#3512]
Hi, what is the (right) way to set the window position/location in a WindowsGL project?

For instance, in a DX project i use:
            var screen = System.Windows.Forms.Screen.AllScreens.First(e => e.Primary); 
            System.Drawing.Rectangle rect = screen.Bounds;
            //Window.IsBorderless = true;
            Window.Position = new Point(rect.Width / 2 - 640, rect.Height / 2 - 360);

For a GL project, i used to use:
            // Use reflection to center the window on screen.
            OpenTK.GameWindow window = null;
            Type type = typeof(OpenTKGameWindow);
            FieldInfo field = type.GetField("window", BindingFlags.NonPublic | BindingFlags.Instance);
            if (field != null)
            {
                window = (OpenTK.GameWindow)field.GetValue(this.Window);

                window.Location = new System.Drawing.Point(
                    (window.Location.X + 320) - 640,
                    (window.Location.Y + 240) - 360
                    );

                window.WindowBorder = OpenTK.WindowBorder.Hidden;
            }

That was working like a charm 'till 3.3 (or 3.2?), so i wander what's the new way for such a simple but crucial task?

Thanks, Greg.

**Comment by Shqrdx** [comment]
You need to use GameWindow.Position property. In Game it called Window property.

**Comment by 6thVenom** [comment]
Nothing?
Are Linux shipped games suffering from this issue too?
Is that a new OpenTK build related issue?
Anything? ;)

**Comment by Shqrdx** [comment]
@6thVenom Wait when my commit for your issue is merged, than use latest development build installer and you get access to Window.Position on WinGL platform.

**Comment by 6thVenom** [comment]
@Shqrdx That's a great news! i didn't see your commit was still active when i searched few days ago.
I'm looking forward for your fix/pull to be merged into the MG dev source,
You made my day, thank you ;)
