### ISSUE TITLE
Better OpenGL Efficiency

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#3514]
This all stems from the following Khronos Group paper...

  https://www.khronos.org/assets/uploads/developers/library/2014-gdc/Khronos-OpenGL-Efficiency-GDC-Mar14.pdf

Is there any benefit to MonoGame to pursuing these approaches within the existing API?  

What platforms can benefit here?

Could this give us a path towards multi-threaded rendering for OpenGL?

**Comment by KonajuGames** [comment]
That PDF is very light on details, but I believe it is referring to `glMultiDrawArraysIndirect` and `glMultiDrawElementsIndirect`.  Here is better article on how they are used.
http://www.openglsuperbible.com/2013/10/16/the-road-to-one-million-draws/

This would only benefit the desktop platforms at this stage as it is OpenGL 4.2+.  It could help a lot with performance, but how much do we expose to the user and how much do we keep internal?  Within our existing API, it would take some extra research into exactly how these new functions work to see how much benefit it would provide to us.

**Comment by tomspilman** [comment]
> This would only benefit the desktop platforms at this stage as it is OpenGL 4.2+.

Ok... wasn't sure if it could help on Android or not.

I expect for iOS we will be eventually moving to Metal and OpenGL will be dropped there all together.

> how much do we expose to the user and how much do we keep internal? 

I think some of this overlaps with how we enhance the MonoGame APIs for DX12 and Metal support.

**Comment by KonajuGames** [comment]
For future planning, look into support for Vulkan, Khronos' next generation OpenGL.
http://www.anandtech.com/show/9038/next-generation-opengl-becomes-vulkan-additional-details-released
http://blog.imgtec.com/powervr/trying-out-the-new-vulkan-graphics-api-on-powervr-gpus

**Comment by willmotil** [comment]
much of this came from mantle i believe anyways here's the spir-v spec pdf
https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.pdf

**Comment by KonajuGames** [comment]
SPIR-V is related to glNext, now known as Vulkan. A lot of similar concepts
as Mantle, and DirectX12 and Apple's Metal. All of these new graphics APIs
put more responsibility onto the application to lower driver overhead, such
as the application creating command buffers that are then shared with the
driver rather than the driver copying the memory.

**Comment by thefiddler** [comment]
We have a developer with NDA access working on Vulkan C# bindings.

It is quite likely that Linux/MacOS will gain Vulkan support before OpenGL 4.2 drivers are ready available on these platforms, which makes this a desirable backend to support.

**Comment by tomspilman** [comment]
@thefiddler - That is great to hear!

**Comment by CartBlanche** [comment]
@thefiddler Any further info about this C# binding?

**Comment by CartBlanche** [comment]
Nevermind, seems one of the Xamarin guys has already done it - https://github.com/mono/VulkanSharp.
@tomspilman, @KonajuGames ^^

**Comment by tomspilman** [comment]
Closing this and moving discussion to https://github.com/mono/MonoGame/issues/4571.
