### ISSUE TITLE
It would be great to have save as png working on windows dx as well. 

### ISSUE THREAD

**Issue by Eversor** [mono/MonoGame#3521]
As far as i tested it perfectly works already just adding a || WINDOWS 
to the following lines : 

![capture](https://cloud.githubusercontent.com/assets/733699/6167690/3aa5f2bc-b2be-11e4-9e6b-8ae1c63bcb91.JPG)

**Comment by Shqrdx** [comment]
BitmapEncoder.PngEncoderId and Task.Run in these methods available only in WinRT.

**Comment by Eversor** [comment]
Yeah, i'm completely dumb, sorry, remove the issue do as if I didn't say anything.
