### ISSUE TITLE
MonoDevelop/XamarinStudio add-in or high-level steps for "For now build from source for Linux and Mac"

### ISSUE THREAD

**Issue by eindoofus** [mono/MonoGame#3531]
This has nearly caused me to abandon MonoGame altogether. I was attracted to it due to it being cross-platform and was hoping to create a game on my Mac or Linux machine that could later be ported to Windows, but the lack of documentation on a simple environment setup with version 3.2 (which was released nearly a year ago) is making me weary of moving forward with my idea.

Could someone in the community please create an add-in for "The new addins for MonoDevelop/XamarinStudio are coming soon!", or if the building from source workaround is sufficient then please provide extra documentation as to what "For now build from source for Linux and Mac" means at:

http://www.monogame.net/downloads/

There is no mention of building from source in: 

http://stackoverflow.com/questions/10388097/monogame-mac-installation-instructions

Also, any non-bundled, platform-specific, MonoGame sample games with Xamarin build steps would be a great morale booster to newer game developers such as myself. Something this simple could greatly increase adoption of the framework and the growth of the community.

**Comment by tomspilman** [comment]
> Could someone in the community please create an add-in 

The new addins for MonoDevelop/XamarinStudio are coming soon.

> please provide extra documentation as to what "For now build from source for Linux and Mac" means 

Look on...

 http://www.monogame.net/downloads/

... under "Source Code".

> There is no mention of building from source in:

StackOverflow is a great website... but it is unaffiliated with MonoGame.  We don't control what people post there.  That is also a 3 year old post... so any information you get from it is dated.


> Also, any non-bundled, platform-specific, MonoGame sample games with Xamarin build steps 

We have some samples here:

 https://github.com/Mono-Game/MonoGame.Samples

**Comment by cra0zy** [comment]
The new addin is almost complete, it just needs a little bit of testing: #3361

**Comment by eindoofus** [comment]
@cra0zy  great to hear! :)

> Look on...
>
> [http://www.monogame.net/downloads/](http://www.monogame.net/downloads/)
>
> ... under "Source Code".

@tomspilman  I wasn't able to find much more detail under "Source Code" that describes what to use it for. Am I trying to build it to extract the generated dlls for referencing in my own projects? Or am I supposed to reference the project source code from my own project using the csproj files? Or is either acceptable? And if so, what is the best practice? Was hoping for a description on the page that contained some of that information.

> We have some samples here:
>
> [https://github.com/Mono-Game/MonoGame.Samples](https://github.com/Mono-Game/MonoGame.Samples)

Created [MonoGame.Sample Issue 36](https://github.com/Mono-Game/MonoGame.Samples/issues/36) for a more detailed explanation of what I'm envisioning to help attract and assist new game developers, and also demo the cross-platform power of MonoGame.

**Comment by ashes999** [comment]
I just went through exactly this, and agree. The GitHub support for new developers is awesome, though (I got several replies within the first hour and got my builds running).

For anyone else who reads this, correct, current, and working instructions are [here](http://www.monogame.net/documentation/?page=Setting_Up_MonoGame_Linux) for Linux setup.

**Comment by cra0zy** [comment]
@tomspilman This can be closed, it has been fixed with #3698
