### ISSUE TITLE
Newest build does not compile on Linux

### ISSUE THREAD

**Issue by WardBenjamin** [mono/MonoGame#3534]
I have a suspicion that something was overwritten by accident, since after a clean pull and Protobuild, the Linux solution does not compile.

> /usr/lib/mono/4.5/Microsoft.Common.targets: Error: Cannot copy /home/user/workspace/MonoGame/Test/Assets/ReferenceImages/RasterizerState/VisualTestFillMode_Wireframe_.png to /home/user/workspace/MonoGame/Test/bin/Linux/AnyCPU/Release/Assets/ReferenceImages/RasterizerState/VisualTestFillMode_Wireframe_.png, as the source file doesn't exist. (MonoGame.Tests.Linux)

The image does exist, but it named "VisualTestFillMode_Wire**F**rame_.png" rather than what it should be called.

**Comment by WardBenjamin** [comment]
Fixed after deleting and re-adding file.

**Comment by tgjones** [comment]
This should be re-opened - looks like I got the casing wrong on that filename in the Protobuild file.
