### ISSUE TITLE
Model Textures not displaying (just grey), some switched in latest build

### ISSUE THREAD

**Issue by tattries** [mono/MonoGame#3549]
Many weird problems with textures not working on models  after installing recent build (platform is windows desktop). Everything worked fine two weeks ago. Wondering if it has something to do with a recent change in monogame regarding setting texture parameters to null. (3351) .

**Comment by tgjones** [comment]
Looking at #3351 with fresh eyes, I'm thinking there's a bug when texture parameters aren't updated between calls to `EffectPass.Apply`, and you're switching between multiple effects. I'll add a test case for that.

**Comment by tattries** [comment]
Additional note, the problem did start with build 3.0.0.02114.  Build 3.0.0.02113 works fine.






Sent from Windows Mail





From: Tim Jones
Sent: ‎Thursday‎, ‎February‎ ‎19‎, ‎2015 ‎12‎:‎16‎ ‎AM
To: mono/MonoGame
Cc: tattries





Looking at #3351 with fresh eyes, I'm thinking there's a bug when texture parameters aren't updated between calls to EffectPass.Apply, and you're switching between multiple effects. I'll add a test case for that.

**Comment by tgjones** [comment]
I've setup some more tests to tease out XNA's behaviour around this, and I have a potential fix. I'll submit a PR now.
