### ISSUE TITLE
Sporadic draw call timings

### ISSUE THREAD

**Issue by xposure** [mono/MonoGame#3553]
I have put together a small piece of code to reproduce the problem that can be found [here](https://gist.github.com/xposure/bff23116b9e8a2e00644) along with my log output and dxdiag.

The problem is that with a default game window and nothing running on my machine, I get draw calls at a steady 16ms as I would expect. Now if I launch chrome and start playing a youtube video the draw calls go up to 33ms and in addition frequently spike up to 50+ ms and make my game appear jittery.

More Info

*  Chrome 40.0.2214.111 m
*  YouTube HTML5 Video Player
*  Happens in both debug and release and regardless if the window has focus and if the debugger isn't attached
*  Using the latest code from https://github.com/mono/MonoGame.git
*  Project is set to .NET Framework 4, Output type as Console (for Console.WriteLine)

**Comment by xposure** [comment]
I have tracked this down as far as I could, the problem lies in GraphicsDevice.DirectX.cs at

    _swapChain.Present(syncInterval, PresentFlags.None);

this method will go up to at least 33ms if you start playing a youtube video in chrome and quite frequently up to 50+ms to return from.

**Comment by xposure** [comment]
I tested this with OpenGL and the issue wasn't as predominant but was still noticeable. The only thing that was strange is that with OpenGL SwapBuffers method returned a pretty constant 16ms (assuming this comes from waiting almost a full cycle for the vsync.

**Comment by prollin** [comment]
`_swapChain.Present(syncInterval, PresentFlags.None);`

This is where the rendering *actually* happens (the GPU finish processing all the rendering commands in order to present the result to the display) so it is normal for this to take some time. Your browser most likely uses hardware decoding when playing videos, which uses the GPU, and since GPUs don't have infinite resources, it is reasonable to assume it will impact your game.

**Comment by xposure** [comment]
I understand that, if you look at the example I put together in the gist, no rendering is actually taking place. Simply using a blank project for MonoGame with minimal setup can reproduce this. I have used YouTube like this for a lot of games and have never experienced it impacting the draw rate what-so-ever. 

Also if you look at my dxdiag, I'm not exact running a computer from 1998;) While its no longer top of the line, its still better than most. GPU resources should absolutely not be an issue here. With all that said, there is something going on with how SharpDX is interfacing with the GPU as well as Chrome/YouTube, there is no reason YouTube and a blank MonoGame project should hit 50ms draw calls on SwapChain on any sort of decent hardware.

*  Things to note, 50ms is 20FPS.
*  This 50ms does not happen when using OpenGL version on MonoGame

**Comment by prollin** [comment]
@xposure do you have VSync enabled by any chances?

**Comment by cphillips83** [comment]
Yes, the default settings for MonoGame/XNA is vsync on with fixed time step. This should still be 60hz or whatever the monitor is unless chrome/html5 player is somehow messing with the vsync.

I'm about to do this test on my home machine.

**Comment by cphillips83** [comment]
Chrome has updated to 115m and the problem seems far less of an issue now. I can still get it to happen with playing with the tabs and its still not "smooth" but its not hitting 50ms like it was. Updating video drivers now and will report back.

**Comment by cphillips83** [comment]
Latest nvidia drivers have completely fixed this problem 100%. I'm getting exactly 16ms no matter what chrome is doing and the vsync looks completely smooth now rather than "jittery" (not sure how else to explain it). 

This issue can be closed.
