### ISSUE TITLE
kungfubanana MonoDeps

### ISSUE THREAD

**Issue by cphillips83** [mono/MonoGame#3555]
git submodule update --init --recursive

Is failing with the following error making it impossible to build the latest MonoGame.

    Cloning into 'ThirdParty/Libs'...
    remote: Repository not found.
    fatal: repository 'https://github.com/kungfubanana/MonoGame-Dependencies.git/' not found
    Clone of 'https://github.com/kungfubanana/MonoGame-Dependencies.git' into submodule path 'ThirdParty/Libs' failed

**Comment by tomspilman** [comment]
That is on the master branch.  See... https://github.com/mono/MonoGame/issues/3464
