### ISSUE TITLE
Performance issue with MonoGame 3.3.*

### ISSUE THREAD

**Issue by FantasyVI** [mono/MonoGame#3559]
Well recently I moved from MonoGame 3.2 to 3.3. Right now I have the latest build, which is #3.3.0.2177 (22 Feb 15 04:10).

Now I know that 3.3 is not the final release and it's not a stable build but I thought I would just point out the performance issues I'm having.

When I create a MonoGame Windows Project (which runs on DX11) and set Vsync to false and IsFixedTimeStep to false to get the maximum fps, I only use ~76% of my GPU. In MonoGame 3.2 I always got 100% usage out of my GPU. I want to note that the project I created is new, which means there is nothing drawn on the screen. The only thing I added to this project were these few lines in the Initialize function.

this.IsFixedTimeStep = false;
graphics.PreferredBackBufferWidth = 1280;
graphics.PreferredBackBufferHeight = 720;
 graphics.SynchronizeWithVerticalRetrace = false;
graphics.ApplyChanges();

Here is a screenshot from MSI Afterburner v4.1.
http://i.imgur.com/hBMOXeL.png

As you can see the GPU usage is around 77%

**Comment by Nezz** [comment]
76% of GPU usage sounds better to me than 100% :)

**Comment by KonajuGames** [comment]
I'm not seeing what the problem is.  Lower GPU usage for the same result is a good thing.

**Comment by FantasyVI** [comment]
Lower GPU usage means less FPS. 

In MonoGame 3.2 my game was rendering at around 700-600 FPS. in MonoGame 3.3 I'm getting 400-300FPS. An empty Project in MonoGame 3.2 would give me 9999FPS but in MonoGame 3.3 I get max FPS of 5000-4500FPS. There is something bottlenecking the GPU. There is ~23% of the GPU power that I can not use in MonoGame 3.3. 

Any game project that does not draw anything on the screen should use 100% of the GPU. If you use XNA or DirectX or OpenGL or SFML or SDL and let the application run as fast as possible the GPU usage should always be 100%

**Comment by tomspilman** [comment]
> In MonoGame 3.2 my game was rendering at around 700-600 FPS.  in MonoGame 3.3 I'm getting 400-300FPS.

This difference could be caused by just about anything.

Without actually running a profiler on the GPU and CPU usage in your particular game and comparing results between 3.3 and 3.2 there is nothing more to do here.
