### ISSUE TITLE
On the topic of adding GLSL support to MonoGame's content pipeline

### ISSUE THREAD

**Issue by ala53** [mono/MonoGame#3566]
As an improvement to MonoGame, perhaps you could allow shaders to be written in both GLSL and HLSL. A compiler such as - https://github.com/Thekla/hlslparser - could be used and is probably easy to do a line-by-line port to C# (which I could do if there were no other significant roadblocks for adding it to the content pipeline) for so it can be used cross platform. 

**What other issues would GLSL support in MonoGame face?**

**Comment by KonajuGames** [comment]
We already use MojoShader in the content pipeline to convert HLSL to GLSL for the OpenGL platforms.  What it gives us that raw GLSL shaders does not is easy access to the effect parameters and techniques in the shader.  There is a plan to support shaders written in GLSL, but it is not implemented yet.  And what do we do then for platforms that require HLSL instead of GLSL?  There are far more projects available to convert from HLSL to GLSL than the other way.

**Comment by tomspilman** [comment]
> There is a plan to support shaders written in GLSL, but it is not implemented yet.

Exactly...  this is being worked on.  No firm date on it yet, but I expect it this year.

**Comment by ala53** [comment]
My apologies - I linked the wrong thing. I meant to link a GLSL to HLSL converter but accidentally linked one that does the other way around. 

Perhaps we could use some of the code from ANGLE (https://code.google.com/p/angleproject/) to convert the shaders from GLSL to HLSL. Unfortunately it would only work with GLES shaders but it would be a start.

**Comment by ala53** [comment]
The code for the shader translation is here
https://chromium.googlesource.com/angle/angle/+/master/src/compiler

**Comment by tomspilman** [comment]
I see GLSL->HLSL or HLSL->GLSL as utility features for us.  You would translate your shader once then maintain it separately.

Note when you get into console development you'll usually need other shader formats.  So maintaining multiple shader files or `#if`ing them into compatibility is common.

**Comment by ala53** [comment]
I always thought that the translation should be mostly under the hood - MonoGame's motto is "Write once. Play everywhere." and seems like having to maintain 2 or 3 different shader pipelines goes against that. `#if`s I understand - right now you have to support SM3 and SM4 (with an easy `#if`) but maintaining the shaders separately seems like an unnecessary pain.

**Comment by tomspilman** [comment]
> MonoGame's motto is "Write once. Play everywhere."

I've always felt that motto is sort of bogus...  i'd love to stop using it.

Anyone that has shipped games to PC, mobile, and console knows that no matter the technology used there is always extra stuff to do per-platform.

> having to maintain 2 or 3 different shader pipelines 

You wouldn't have to... we do want to provide a utility to translate and you are free to use it.

What we don't want is to force you to use HLSL on GLSL platforms or vice versa.

**Comment by ala53** [comment]
Fair enough on the motto section but integrating the translators into the pipeline rather than leaving them as external utilities should still be done in my opinion. Then you can write in HLSL or GLSL without having to having to re-run the translator every time you change a line in the shader - it's done behind the scenes.

**Comment by tomspilman** [comment]
> integrating the translators into the pipeline rather than leaving them as external utilities should still be done in my opinion.

The complexity will be that the GLSL support will probably come first...  automatic translation will come some time after.  So there will be a gap of time without any kind of automatic translation.

**Comment by ala53** [comment]
I see. I had just misunderstood what you were saying. I understand that it takes time to implement features - I just thought you were saying not to implement it at all.

**Comment by tomspilman** [comment]
See #2167 for info on this.
