### ISSUE TITLE
Pipeline tools missing

### ISSUE THREAD

**Issue by NobbZ** [mono/MonoGame#3569]
I installed monodevelop using the installer, but I can't find the content/pipeline-tools, but I'd like to stay away from 10 GiB MSVS minimal installation also and stay with xamarin. So I thought I could use the pipeline tools standalone, but there are none.

**Comment by tomspilman** [comment]
The pipeline tool is installed as part of the Windows installer for Visual Studio at the moment.  I *think* if you run the Windows installer and don't have VS installed it will still work...  I will just skip installing the VS templates.

**Comment by NobbZ** [comment]
But how can I find it? Several search tools are telling me, that none of the executables.

Also I tried installing MSVS 2013 Community and then creating a ContentProject as Subproject in a monogame project that only used the naked template, and this is what happened:

![Errormessage when creating ContentProject in MSVS 2013 Community](http://i.imgur.com/M9KHq2H.png)

**Comment by tomspilman** [comment]
> But how can I find it?

First off the Pipeline tool only exists in the development builds of MonoGame.  It isn't in the year old 3.2 release.

Once installed shortcuts are added and you can launch it from the start screen/menu.
