### ISSUE TITLE
DirectX can’t enable Anti Aliasing

### ISSUE THREAD

**Issue by shiro900** [mono/MonoGame#3571]
I make a new project in Monogame with DirectX, run this example code and AntiAliasing does not enable. If I make an OpenGL project it enables correctly. Why is this happening ? How can i fix this ?

    using System;
    using Microsoft.Xna.Framework;
    using Microsoft.Xna.Framework.Graphics;

    namespace GameName1 {
        public class Game1 : Game {
            GraphicsDeviceManager graphics;
            SpriteBatch spriteBatch;
            Texture2D texture;

            public Game1() : base() {
                graphics = new GraphicsDeviceManager(this);
                graphics.PreferredBackBufferWidth = 450;
                graphics.PreferredBackBufferHeight = 800;
                graphics.PreferMultiSampling = true;
                Content.RootDirectory = "Content";
            }
            protected override void LoadContent() {
                spriteBatch = new SpriteBatch(GraphicsDevice);
                texture = new Texture2D(spriteBatch.GraphicsDevice, 1, 1);
                texture.SetData<Color>(new Color[] { Color.White });
            }
            protected override void Draw(GameTime gameTime) {
                GraphicsDevice.Clear(Color.Black);

                Matrix skew = Matrix.Identity;
                skew.M12 = (float)Math.Tan((double)Math.PI / 16);

                spriteBatch.Begin(SpriteSortMode.Texture, null, null, null, null, null,
                    skew * Matrix.CreateTranslation(200, 200, 0));
                spriteBatch.Draw(texture, new Vector2(200, -200), 
                    new Rectangle(200, 200, 20, 500),  Color.White, 
                    (float)Math.PI / 8, Vector2.Zero, 4f, SpriteEffects.None, 0);
                spriteBatch.End();
            }
        }
    }

DirectX (AntiAliasing doesn't work):

![1][1]

OpenGL (AntiAliasing works):

![2][2]

Why is Anti aliasing not enabling correctly in DirectX but it does on OpenGL ? You can copy and paste this code and see for yourself, the texture is made programmatically, there is no images.

Edit: I also can't get it to work on android either

  [1]: http://i.stack.imgur.com/4sFTL.png
  [2]: http://i.stack.imgur.com/oq1Ix.png

**Comment by tomspilman** [comment]
The old https://github.com/mono/MonoGame/issues/358 issue covers this.

There are platforms where we cannot do it, but DirectX desktop is one where we can and should.  Just needs someone to jump in there and do the work.

**Comment by shiro900** [comment]
Do you know about android ? which is my main concern ?

**Comment by tomspilman** [comment]
For Android it probably would work on some percentage of phones/tablets.  

It seems like there is support in GLES platforms:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/GraphicsDevice.OpenGL.cs#L476

... but I can't say I know for certain if it works.
