### ISSUE TITLE
Xamarin.iOS / MonoTouch support for 3.3

### ISSUE THREAD

**Issue by DDReaper** [mono/MonoGame#3573]
Quick query / poll

Was testing / updating the sample Lib and tried to use the new Dev version of the NuGets for iOS.

The NuGet only targets Xamarin.iOS at present, the sample still uses the MonoTouch template and hence the NuGet cannot be installed.

So **for 3.3**, with the new NuGet's do we still want to support the older MonoTouch target?
Or is it a clean break to only support the newer Xamarin.iOS and Metal?

**Comment by danzel** [comment]
Xamarin.iOS definitely.

MonoGame doesn't support the old MonoTouch version any more, so we'd need to grab an old revision of the code before that was merged if we wanted to do that.

**Comment by DDReaper** [comment]
Right, that will need highlighting **significantly** if that is the case.  It will create an issue for anyone upgrading a 3.2 project to 3.3.
They will have to create a new iOS project with 3.3 and port their code (unless there is another migration strategy).  I think @dellis1972 new MD templates support iOS but I cannot see them on Windows.

**Comment by danzel** [comment]
I updated my app a few days ago. I just followed the official Xamarin guide:
http://developer.xamarin.com/guides/cross-platform/macios/updating_ios_apps/

**Comment by tomspilman** [comment]
@dellis1972 - I think this is moot now that Xamarin.iOS is free?

**Comment by danzel** [comment]
Yeah this can definitely be closed

**Comment by tomspilman** [comment]
Thanks @danzel !
