### ISSUE TITLE
MSI installer is missing the SharpDX.WP8.winmd file for x86 & ARM

### ISSUE THREAD

**Issue by DDReaper** [mono/MonoGame#3574]
In debugging the issue with the Windows Phone template, the issue simply appears to be a missing file in the MonoGame installer folder

> SharpDX.WP8.winmd

This is not copied from the installer in to the  folders for 
* MonoGame\Assemblies\WindowsPhone\x86
* MonoGame\Assemblies\WindowsPhone\ARM

I've checked the file exists in the ThirdParty SharpDX folder for Windows Phone 8.0 for both platforms.

So the MSI installer creator just needs BOTH files adding for x86 and ARM for the WindowsPhone platform to correct the issue.

I don't think this config is held in the source but on TeamCity. Correct me if I'm wrong and I'll update the necessary config
Ping @tomspilman @dellis1972 

I've tested locally by simply copying the correct SharpDX.WP8.winmd file for each platform in to the installed assemblies folder and ran a project.

So it's not a template issue, just a missing file in the installer.

**Comment by dellis1972** [comment]
we probably just need to add a filter .winmd to the right places in the sis
script and that will fix that up nicely.

File '..\..\MonoGame.Framework\bin\WindowsPhone\ARM\Release\*.winmd'
at
https://github.com/mono/MonoGame/blob/develop/Installers/Windows/MonoGame.nsi#L164

and the one just below

File '..\..\MonoGame.Framework\bin\WindowsPhone\x86\Release\*.winmd'
https://github.com/mono/MonoGame/blob/develop/Installers/Windows/MonoGame.nsi#L169

**Comment by dellis1972** [comment]
Assuming the wind files are in the Release directory on build

**Comment by tomspilman** [comment]
> I've checked the file exists in the ThirdParty SharpDX folder for Windows Phone 8.0 for both platforms.

We just copy the content of the MonoGame.Framework output folders into the installer.   So maybe for some reasons that file isn't being copied into the MonoGame.Framework output folders on a build?

Could be the cleaning on the TeamCity server removed an old version of that file that was in the output folder and was being copied over because of that.

Is this WP8 or WP8.1 projects?  Or both?

**Comment by DDReaper** [comment]
Just the WP8 build.
Tested the WP8.1 projects and they are fine

**Comment by DDReaper** [comment]
Shall I submt a pr with those changes @dellis1972 and test?
/cc @tomspilman

**Comment by DDReaper** [comment]
Submitted PR #3575 , will test once it's complete to verify it's working.

Yes @tomspilman I checked the WP8 build folder and the .winmd file is there.

It's these pesky WINRT components, they are a real pain (and were supposed to fix a lot of problems), guess the SharpDX team decided it wasn't worth making one for WP8.1 and Win8/8.1
