### ISSUE TITLE
[Poll] New MonoGame project start page

### ISSUE THREAD

**Issue by DDReaper** [mono/MonoGame#3584]
The original MonoGame projects all start at the good old CornFlowerBlue start screen.

With the WinPhone and 8.1 projects a new "spinning cube" was added for the start page.

Which does everyone think looks better?

* A blank screen
* An Animated 3D spinning cube (abstracted it its own class to make taking it out easier)
* Something else?

**Comment by rboelen** [comment]
definitely a blank screen

**Comment by cra0zy** [comment]
An animated 3d monogame logo would be nice

**Comment by cclements1384** [comment]
My personal opinion is that beginning with code to display a 3D shape may
distract from those that are just starting out.

**Comment by mgarstenauer** [comment]
A blank screen.

**Comment by theZMan** [comment]
Cornflower blue for me - everything else should be added later by the
programmer. This is just stuff I will have to delete every time.

**Comment by tomspilman** [comment]
What if we go from cornflower blue to "MonoGame Orange"?

  http://www.color-hex.com/color/e73c00

**Comment by DDReaper** [comment]
I would agree @theZMan the startup experience should be fitting to both beginners and experienced devs starting out.  Although I liked the spinning cube that was added to the WP8.1 project, it was too embedded to be useful as a starting point.

I love where you are going with that idea @tomspilman , I'd also love to have the MG logo front and centre (which is deployed with each and every template anyway).  If we did that then it would have to be easy to strip out (as per Andy's comment above).

Adds a certain MG distinction.

Another possibility Andy, is to create a "Game Class" item template, so you can just delete the existing one and start fresh that way maybe?

**Comment by Shqrdx** [comment]
> What if we go from cornflower blue to "MonoGame Orange"?
I like it, it brings a bit of individuality to MonoGame and mark the difference from XNA.

**Comment by DDReaper** [comment]
My only issue with the orrange is that it is a very strong colour, but that could work in MG's favour.  I completely agree with highlighting more that MG (although based on) is a different framework to it's predecessor, XNA.

**Comment by KakCAT** [comment]
Would adding two templates (one blank and another with a more complex code) would be too costly?  After all, you can choose from several templates for most project types...

**Comment by DDReaper** [comment]
I don't think two templates would make sense. We have the new samples lib and many good tutorials for people to get started.
Most who use the templates in anger want to start clean anyway.

Also taking a leaf out of the XNA book, their templates always started with that minimalistic look 😎

**Comment by cra0zy** [comment]
When creating an android application you choose the starting template, something similar in monogame may look nice.

**Comment by theZMan** [comment]
I humbly suggest the Xna style template with this one modifcation

```
            var interp = MathHelper.Clamp((float)gameTime.TotalGameTime.TotalSeconds/2f, 0f, 1f);
            GraphicsDevice.Clear(new Color(
                (byte)MathHelper.Lerp(Color.CornflowerBlue.R, 231f, interp),
                (byte)MathHelper.Lerp(Color.CornflowerBlue.G, 60f, interp),
                (byte)MathHelper.Lerp(Color.CornflowerBlue.B, 0f, interp)
                ));
```

**Comment by cra0zy** [comment]
@theZMan thats genius!!!

**Comment by DDReaper** [comment]
I think we have a winner!!!

I'll get a PR sorted for all the templates with that!!!

@theZMan wins the MonoGame mug with marshmallows in it :D

**Comment by KonajuGames** [comment]
Give it a try and see if it looks good first. :)​

**Comment by DDReaper** [comment]
I tried it and watched my eyes popped out.
Putting it together now

**Comment by ala53** [comment]
Related to PR #3587, I think this could be compacted down a bit (especially with @Shqrdx's pull request):

```
GraphicsDevice.Clear(Color.Lerp(Color.CornflowerBlue, Color.MonoGameOrange, MathHelper.Clamp((float)gameTime.TotalGameTime.TotalSeconds / 2, 0, 1));
```

It's quite a bit shorter and still has the same meaning (we don't need a Vector3 conversion here and using a specific named color makes it clearer).

**Comment by tomspilman** [comment]
Closing this in favor of https://github.com/mono/MonoGame/issues/4288.
