### ISSUE TITLE
Texture2D.GetData<byte> seems to be buggy

### ISSUE THREAD

**Issue by shameleo** [mono/MonoGame#3590]
I use latest release MonoGame 3.2 on windows (windows DirectX project).
I have this texture:
![origin](https://cloud.githubusercontent.com/assets/11148445/6482217/e0ab3468-c274-11e4-9e63-81a234e4541d.png)
When i write code like this:
```
byte[] pixelData = new byte[width * height * 4];
testTexture.GetData<byte>(pixelData);
testTexture.SetData<byte>(pixelData);      // now texture is corrupted
```
texture is getting spoiled.
 ![spoiled](https://cloud.githubusercontent.com/assets/11148445/6482219/e52e6f96-c274-11e4-8628-11fc2359cf15.png)
But if i use int[] to get data, everything is ok:
```
int[] pixelData = new int[width * height];
testTexture.GetData<int>(pixelData);
testTexture.SetData<int>(pixelData);     // it still the same (OK)
```
This approach works fine too:
```
int[] pixelData = new int[width * height];
testTexture.GetData<int>(pixelData);
testTexture.SetData<byte>(IntArrayToByteArray(pixelData));       // still OK
```
Here is my convert method:
```
static byte[] IntArrayToByteArray(int[] intArray)
{
      byte[] result = new byte[intArray.Length * sizeof(int)];
      Buffer.BlockCopy(intArray, 0, result, 0, result.Length);
      return result;
 }
```
So i guess Texture2D.GetData<byte> returns incorrect result.

**Comment by tomspilman** [comment]
A bunch of fixes and unit tests have been added to validate Texture2D.GetData.  So we suspect these issues are fixed in the upcoming 3.3 release.

Please report back if you test this with 3.3 or the latest development release and still have issues.
