### ISSUE TITLE
Protobuild.exe virus?

### ISSUE THREAD

**Issue by EdvinM** [mono/MonoGame#3591]
Hi.

I have tried to update the latest, hoping to get rid of the touch input bug (which freezes the entire game) and when i unarhived the datas, I got a notification from my avira antivirus that protobuild.exe contains an virus.

Here is a screen I made to show you:
http://imgur.com/rUsTZO1

**Comment by tomspilman** [comment]
> I got a notification from my avira antivirus that protobuild.exe contains an virus.

Protobuild.exe doesn't contain any virus... your antivirus is simply giving you a false positive.

@hach-que - Anything we can do to mitigate this?  Maybe this:  https://analysis.avira.com/en/submit

**Comment by EdvinM** [comment]
Ok, so I will remove it from the chest.

What about the bug that freezes my game? As I understood it is coming from the touch functions... is it somewhere fixed, or has a partial improvement?

**Comment by KakCAT** [comment]
if you're refering to this http://community.monogame.net/t/wp8-1-game-freezes-sporadically/1865/13 I'm waiting for feedback confirmation in order to open an issue. Could you please check if any of the possible solutions shown in the latest post fix the freeze for you?

**Comment by hach-que** [comment]
@tomspilman I've sent a false positive request through for the latest version of Protobuild.

**Comment by EdvinM** [comment]
@KakCAT The latest post is yours showing your video... I have tried to put a try and catch to throw an error after the game freezes but it didn't throw anything and the game frozen ... I have also installed the latest "unstable" monogame installer, and nothing ...

---------------------------------
Now trying to build the solution extracted from protobuild it is giving me this error:
http://i.imgur.com/rCNoIv0.png

**Comment by hach-que** [comment]
Just heard back from Avira and they've recognized it's a false positive.  The next definition update they push out should cause the virus warnings to go away.

@EdvinM You're trying to run a library project there (MonoGame.Framework.Net).  You need to set the startup project to be your game and then run it.

**Comment by EdvinM** [comment]
Yeah ... I noticed that actually the dlls were created even if I received that error box :D...
