### ISSUE TITLE
WP8.1 crash/freeze when IsfixedTimestep=true

### ISSUE THREAD

**Issue by KakCAT** [mono/MonoGame#3592]
Hi!

WP8.1 crashes in the Tick function of Game.cs, exactly in the line 
```
Task.Delay(sleepTime).Wait();
```

more info here : http://community.monogame.net/t/wp8-1-game-freezes-sporadically/1865/13

stack trace + exception info here : http://s28.postimg.org/ra702djzh/crash.png

Surrounding the Wait call with try/catch fixes the problem but I don't think it's the right solution

Thanks!

**Comment by nkast** [comment]
You can just ignore those types of exceptions. I am sure if you remove ArgumentException from the list of unhandled/thrown in the Debug-> Exceptions your program will run without problem.

**Comment by KakCAT** [comment]
Hi nkast,

you're right, sorry for the noise. I was confused by the fact that initially the crash was produced when testing the touchscreen bug. Closing.
