### ISSUE TITLE
GamePadState.IsButtonDown Ignores joystick deadzones.

### ISSUE THREAD

**Issue by BlackMajic** [mono/MonoGame#3593]
Not sure how to do a pull request since there's 2 months worth of commits inbetween, maybe cherry pick it?
https://github.com/mono/MonoGame/commit/63e2bf2c1e93f0f5b64e3ad57579790c96e9d934

Basically the bits for LeftThumbstickLeft, etc. are already set when the GamePadState is created in
https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Input/GamePad.SDL.cs#L305

I haven't checked the other platform GamePads, but at the least, the virtual thumbstick buttons should take joystick deadzones into account.

**Comment by cra0zy** [comment]
@tomspilman This can be closed, it has been fixed with #3632
