### ISSUE TITLE
Protobuild doesn't build the Monogame.Framework.Net project file for PSM

### ISSUE THREAD

**Issue by greyp** [mono/MonoGame#3594]
And as a result I can't get my game running on PSM because it requires GamerServices... 

Please refer to this thread:
http://community.monogame.net/t/is-gamerservices-supported-on-psm/2052/4

**Comment by DDReaper** [comment]
There was a reason when I did the .Net split for PSM as to why it didn't get a version.
This was simply because of the lack of a Lidgren version for PSM.

If this is required, I can look to bring back what PSM can support.

**Comment by KonajuGames** [comment]
What do you need from GamerServices for your game?

**Comment by greyp** [comment]
Oh now you mentioned that... I didn't realize GamerServices is pretty much for WP only... I separated those using statements, and the GamerServices-related errors are gone. Really sorry about the fuss... @_@
