### ISSUE TITLE
no "MonoGame.Framework.Content.Pipeline.Windows.csproj" file

### ISSUE THREAD

**Issue by hede** [mono/MonoGame#3595]
Just downloaded the latest source.

Double clicked the Win.sln.
VS couldn't open the project MonoGame.Framework.Conrent.Pipeline.Windows.

According to the sln file, the .csproj should be in projRoot\MonoGame.Framework.Content.Pipeline\ but there is no csproj there.

I think the WindowsGL proj is in the same boat too.

**Comment by KonajuGames** [comment]
You need to run Protobuild.exe in the root of the repo to generate the sln
and csproj files.​

**Comment by hede** [comment]
Correct you are, sir!
I remember reading this as well... It must have slipped my mind.
