### ISSUE TITLE
[Solution]Monogame PSM not rendering texture

### ISSUE THREAD

**Issue by mitko9000** [mono/MonoGame#3597]
I decided to give a try to the PSM part and when I tryed to draw simple texture I ended up with null pointer exception it turns out that inside SpriteBatcher method DrawVertexArray I had to add the following code in order to work : 

if(effect == null) {
  var vertexCount = end - start;
            _device._graphics.DrawArrays(DrawMode.Triangles, start / 2 * 3, vertexCount / 2 * 3);
} else {

 var passes = effect.CurrentTechnique.Passes;
            foreach (var pass in passes)
            {
                pass.Apply();
                _device._graphics.DrawArrays(DrawMode.Triangles, start / 2 * 3, vertexCount / 2 * 3);
            }
}

I hope that can help someone :)

**Comment by tgjones** [comment]
@tomspilman I guess this issue can be closed, given #3607, and the fact that `SpriteBatcher.DrawVertexArray` doesn't seem to exist anymore anyway.

**Comment by KonajuGames** [comment]
Closing.
