### ISSUE TITLE
Implement the Rg32

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#3605]
Implement the `Rg32` packed vector struct.

See the docs for the type here:

 https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.graphics.packedvector.rg32.aspx

You can probably base the work off the existing [`HalfVector2`](https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/PackedVector/HalfVector2.cs) type as it is also a two 16bit component type.

We should add new unit tests for the type as well:

 https://github.com/mono/MonoGame/blob/develop/Test/Framework/PackedVectorTest.cs

**Comment by cra0zy** [comment]
I'll try to do it, I've never tried to recreate a class using the documentation of it but seems easy enough.

**Comment by cra0zy** [comment]
I probably won't be able to do it, I really have to read a lot about the way packaging to uint should be done. Anyway whoever does try to do it here: https://mega.co.nz/#!HJpQmaiL!Pzal5O8M35_-lh9r81LmxGL6LJcQBpJTuqex3syLkFU everything but PackHelper and ToVector2 implemented.

**Comment by tomspilman** [comment]
Thanks @cra0zy.  Can someone else take this over and get a PR up?

**Comment by flibitijibibo** [comment]
I just scribbled the rest of the PackedVector types:

https://github.com/flibitijibibo/FNA/commit/ee4db8d7aafd29f343a3666b2cf38c141adf40ea
https://github.com/flibitijibibo/FNA/tree/master/src/Graphics/PackedVector

All of these are entirely untested, but it's a start!

**Comment by tomspilman** [comment]
As long as we can merge this under the MonoGame copyright i'm good with it.  If not then probably best that someone implement these from scratch themselves.  I just don't need yet one more license to manage here.

**Comment by flibitijibibo** [comment]
Yeah, go ahead and change the license as needed.

**Comment by cra0zy** [comment]
@tomspilman Do you want me to setup PR that adds Packed Vector types from FNA repository?

**Comment by tomspilman** [comment]
@cra0zy 

Just the ones from this commit:

 https://github.com/flibitijibibo/FNA/commit/ee4db8d7aafd29f343a3666b2cf38c141adf40ea

The rest are just copies of our existing ones.

We can put the MonoGame copyright on these as mentioned above.

I noticed some of the docs are incorrect, we will need to fix that.

Also we need to add in unit tests for them as well.  If you don't have time to write unit tests then let someone else do the work to submit it.  I can't accept them without the tests.

**Comment by cra0zy** [comment]
I'll have time a bit latter today to write those tests.

**Comment by cra0zy** [comment]
@tomspilman this can be closed
