### ISSUE TITLE
Future of the PSM / Vita support

### ISSUE THREAD

**Issue by mrhelmut** [mono/MonoGame#3607]
Hello,

Sony has just announced that the Playstation Mobile program and the associated PS Vita market will be discontinued and shut down on september 10th (as well as the previously announced Android market shut down on july 15th).

Question is: what about MonoGame PS Vita support?

The announcement does not specify if the PSM SDK will be discontinued too, and since I am not (yet) a registered PS dev, I don't know if it is possible to use the PSM SDK to build PS Vita games through this program. But if it is, it may be interesting to keep PSM support and further develop it, which would make it a great addition to the PS4 support.

Official statement, japanese only: http://www.jp.playstation.com/info/support/sp_20150311_psm_info.html

**Comment by KonajuGames** [comment]
The PSM Dev Portal is also closing as well, meaning the PSM SDK will no longer be available.  The [discontinuation notice](https://en-support.psm.playstation.net/app/answers/detail/a_id/343) on the PSM Dev Portal states that you can develop on a PS Vita or PS-Certified device until 15th July.

I would expect to see PSM support in MonoGame be removed at that time as well.

**Comment by tomspilman** [comment]
> what about MonoGame PS Vita support?

We are working on a solution to that, but can't announce anything just yet.
