### ISSUE TITLE
Pipeline: Content file icons should change based on file type

### ISSUE THREAD

**Issue by dneelyep** [mono/MonoGame#3609]
It would be somewhat useful to display different icons in the content tree based on file type. For example, an FBX file could have a different icon than a PNG file, to make it easy to distinguish the two.

I haven't yet found a decent free set of icons for the purpose.

**Comment by tomspilman** [comment]
> different icons in the content tree based on file type

On Windows you can request the file icon from the OS.  We might want to try that.

@cra0zy - Can that be done under GTK on Mac/Linux?

**Comment by dneelyep** [comment]
Notes if I don't get around to doing this:
* To get the Windows icon for a specific file, this method can be used: https://msdn.microsoft.com/en-us/library/system.drawing.icon.extractassociatedicon
    * One problem is that the above method requires a `File`, and `IProjectItem` uses relative paths to refer to file locations.The original path will need to be figured out somehow. Maybe add a `FullOriginalPath` field to `IProjectItem`? Or use a hard-coded list mapping extensions to icons, but that's kind of hacky.
* The icon for tree items is set in Pipeline.Windows/Windows/MainView.AddTreeItem, on the line:
`node.ImageIndex = item.Exists ? ContentItemIcon : ContentMissingIcon;`

**Comment by cra0zy** [comment]
It can be done under Gtk, but I wouldn't use system icons, I would rather we included our own for the following reasons:
1) If the file format isn't associated with anything, the icon would be the system blank icon, I don't like that (fbx would always have it on mac and linux because blender does not open fbx, it imports it)
2) Setting up missing icon indicator would be more difficult.

I don't mind adding this with my next 2 PRs, I'll look for the icons I think look good and post them here.

**Comment by tomspilman** [comment]
> If the file format isn't associated with anything, the icon would be the system blank icon

What is wrong with that?  Currently our default icon looks like this:

![capture](https://cloud.githubusercontent.com/assets/103522/6620863/2ac04340-c8a1-11e4-8dd1-05d97dd04c28.PNG)

Other than the color it is not very different from the Windows default icon:

![capture](https://cloud.githubusercontent.com/assets/103522/6620895/6455ae74-c8a1-11e4-9fb9-bac512d5097e.PNG)

> fbx would always have it on linux because blender does not open fbx, it imports it

Sure... that would be the same on Windows in the case of editors.  However if you have an FBX viewer associated it would show that icon.

> Setting up missing icon indicator would be more difficult.

I guess it would if we are trying to overlay a missing over the system defined icon.  I would say for missing we just have a special missing icon that we use instead.

**Comment by cra0zy** [comment]
> I guess it would if we are trying to overlay a missing over the system defined icon. I would say for missing we just have a special missing icon that we use instead.

I was not just referring to overlaying, I was also referring to the getting the default icon for the file(because the file wouldn't exist....), but I'm fine with having a special icon for missing stuff.

**Comment by tomspilman** [comment]
Well maybe the bigger question is more important?

 1. Having the correct icon associated to the opening application?
 2. Having consistent icons between the Pipeline tool across different platforms?

**Comment by cra0zy** [comment]
Icon.ExtractAssociatedIcon isn't working under mono linux, it always returns the same value.

**Comment by tomspilman** [comment]
> Icon.ExtractAssociatedIcon isn't working under mono Linux

Lame...  can we hack something by calling some Linux specific lib?

**Comment by cra0zy** [comment]
Can't find anything useful.. there is also a problem with Mac, it will probably need a separate way of acquiring icons.

**Comment by KonajuGames** [comment]
I don't think there is any standard for file icons in Linux.  Different
window managers may or may not support file icons in any number of
different ways.  GTK appears to do something, but you need the file's mime
type, but it also changes depending on icon theme is installed.​

**Comment by tomspilman** [comment]
Lame...  I worried this might be a mess on Linux, but hoped it wasn't.

The real issue here is to get something better than all the icons being the same for different file types.

Using the associated icon was ideal because we would then possibly display a reasonable icon for unknown file types (like in custom importers/processors).

But if that isn't possible on Linux then maybe it has to return a default icon the Pipeline tool provides.

So question... is it ok for Windows and Mac to do something different here than Linux?

**Comment by KonajuGames** [comment]
On Mac, you use `NSWorkspace.sharedWorkspace` and it's `iconForFileType` method.  Do we have access to this with MonoMac or would we need to use Xamarin.Mac for that?

I don't see it being a problem with different icon support on different platforms.

**Comment by cra0zy** [comment]
There is a standard for icons on linux that all the file managers use, themes can override any icon in the system(which is very nice IMO).

One more thing for mac is that the icon will need to be converted to Gdk.Pixbuf in order for it to be displayed in the treeview, and I haven't found a very efficient way to do that (http://stackoverflow.com/questions/20514115/converting-bitmap-to-gdk-pixbuff)

**Comment by cra0zy** [comment]
Something useful for linux, finally: http://stackoverflow.com/questions/1629172/how-do-you-get-the-icon-mime-type-and-application-associated-with-a-file-in-th

**Comment by cra0zy** [comment]
So, how about we use associated icons for WinForms Pipeline and custom icons for Gtk Pipeline?

**Comment by KonajuGames** [comment]
> So, how about we use associated icons for WinForms Pipeline and custom icons for Gtk Pipeline?

I'm fine with that.
