### ISSUE TITLE
Dead link to Monogame Starterkits in README.md

### ISSUE THREAD

**Issue by jeremy-edward-bauerle** [mono/MonoGame#3611]
The link to [Monogame Starterkits](https://github.com/kungfubanana/MonoGame-StarterKits) is dead.

Dead URL: https://github.com/kungfubanana/MonoGame-StarterKits

Possible replacement URL: https://github.com/KonajuGames/MonoGame-StarterKits

The possible replacement repo hasn't been updated in 3 years, so I don't know how suitable a substitute it is.

**Comment by tomspilman** [comment]
Yes that is a known... they haven't been maintained in a long while now.  In theory the new samples repo is the replacement for these:

https://github.com/Mono-Game/MonoGame.Samples

... but I suspect it is getting stale as well.
