### ISSUE TITLE
Buttons.LeftThumbstickUp incorrectly returns true when left stick pushed down

### ISSUE THREAD

**Issue by CrashLotus** [mono/MonoGame#3614]
On Windows 7 with latest development build.  Xbox360-compatible joystick in USB port.  Buttons.LeftThunbstickUp returns true when the left stick is pushed DOWN(back) instead of when it is pushed up(forward).

**Comment by tomspilman** [comment]
Isn't `Buttons.LeftThunbstickUp` an enum value?  How is it returning true?  Can you show us what API you are calling?

**Comment by cra0zy** [comment]
Are you using OpenGL or DirectX version?

**Comment by CrashLotus** [comment]
It is DirectX, although I don't see why that would matter.
That was rather imprecise of me.  I am referring to GamePadState.IsButtonDown().
As I test it further, I realize that both LeftThumbstickUp and LeftThumbstickDown are returning true when the left stick is pushed either up or down.  Here's a code snippet to illustrate the issue:

			System.Diagnostics.Debug.WriteLine(".");
			GamePadState padState = GamePad.GetState(PlayerIndex.One);
			if (padState.IsButtonDown(Buttons.LeftThumbstickUp))
				System.Diagnostics.Debug.WriteLine("Up");
			if (padState.IsButtonDown(Buttons.LeftThumbstickDown))
				System.Diagnostics.Debug.WriteLine("Down");
			if (padState.IsButtonDown(Buttons.LeftThumbstickLeft))
				System.Diagnostics.Debug.WriteLine("Left");
			if (padState.IsButtonDown(Buttons.LeftThumbstickRight))
				System.Diagnostics.Debug.WriteLine("Right");

Left and Right seem to work properly (although I think a larger dead zone would be appropriate).

**Comment by cra0zy** [comment]
DirectX uses Xinput, while  OpenGL uses Sdl1.2, it matters...

**Comment by tomspilman** [comment]
I've heard more reports of this issue occurring.

**Comment by KakCAT** [comment]
Hi,

I think the problem is at AddThumbstickButtons in GamePad.XInput.cs . 
Switching to

            if (thumbY < -deadZone)
                result |= thumbStickDown;
            else if (thumbY > deadZone)
                result |= thumbStickUp;

seems to fix the problem. Could somebody confirm that negative Ys are down and positive Ys are up?

**Comment by mrhelmut** [comment]
Hi,

I can confirm that XInput Y's are down and that @KakCAT code snipet fixes this issue.

**Comment by tomspilman** [comment]
Great...  lets get a PR going and some testing.

**Comment by KakCAT** [comment]
Hi,

is it possible somebody smarter than me could do the PR? :)

Everytime I have to make a PR I end using an obscene amount of time only to get nowhere :( I usually end up wiping my main repository and cloning it again to my pc (which with a 512KBps shared connection sometimes takes more than 4 hours). I've been fiddling with this PR for an hour now which will make 5 minutes to find the bug and 5 hours to push the code xD

p.s. sorry for the offtopic rant.

**Comment by cra0zy** [comment]
Sure, I can do it, give me 2 mins.

**Comment by KakCAT** [comment]
2 minutes? I "hate" you ;)

**Comment by cra0zy** [comment]
lol
