### ISSUE TITLE
[Content Pipeline] error: Importer 'H264Importer'

### ISSUE THREAD

**Issue by dm67x** [mono/MonoGame#3620]
Hello I have an error when i compile my mp4 file on monogame pipeline.

[ERROR]
Build started 17/03/2015 21:02:50

D:/Projets/Game1/Game1/Content/myfile.mp4
D:/Projets/Game1/Game1/Content/myfile.mp4: error: Importer 'H264Importer' had unexpected failure!
System.FormatException: Le format de la chaŒne d'entr‚e est incorrect.
   … System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   … Microsoft.Xna.Framework.Content.Pipeline.VideoContent..ctor(String filename)
   … Microsoft.Xna.Framework.Content.Pipeline.H264Importer.Import(String filename, ContentImporterContext context)
   … Microsoft.Xna.Framework.Content.Pipeline.ContentImporter`1.Microsoft.Xna.Framework.Content.Pipeline.IContentImporter.Import(String filename, ContentImporterContext context)
   … MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent(PipelineBuildEvent pipelineEvent)
Build 0 succeeded, 1 failed.
[ERROR]

Sorry for my english :)

**Comment by tomspilman** [comment]
Can you share the mp4 somewhere for us to test with?

**Comment by dm67x** [comment]
http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4 it's video file for test :)

**Comment by KonajuGames** [comment]
It would appear the output returned by ffmpeg may be always using
InvariantCulture, so the calls to float.Parse() will need to specify
CultureInfo.InvariantCulture.​

**Comment by KonajuGames** [comment]
Can you try the fix I posted in #3627?
