### ISSUE TITLE
Implement Joystick class/API

### ISSUE THREAD

**Issue by cra0zy** [mono/MonoGame#3634]
So the GamePad covers a way to access controllers that look like a xbox 360 controller. A Joystick class would allow access to any kind of controller, no matter the number of axis/buttons/hats, it would be on a lower level similar like the OpenTK joystick class operates.

**Comment by tomspilman** [comment]
This would work for complex flight sticks, racing wheels & pedals, weird VR controllers, etc.

What APIs would this abstract in the end?  I guess the OpenTK joystick class?  The DirectX XInput classes?

Does Joystick become the new abstraction and GamePad works on top of that?

**Comment by cra0zy** [comment]
> What APIs would this abstract in the end? I guess the OpenTK joystick class? The DirectX XInput classes?

I would use OpenTK, but we could also use OpenTK for GL and XInput for DX.

> Does Joystick become the new abstraction and GamePad works on top of that?

I would leave gamepad working on top of OpenTK GamePad because it can use sdl 2 gamepad database(which is quite filled).

**Comment by cra0zy** [comment]
Implemented with #3787
