### ISSUE TITLE
MonoGame compilation error

### ISSUE THREAD

**Issue by Shqrdx** [mono/MonoGame#3640]
![image](https://cloud.githubusercontent.com/assets/3036176/6746395/766cda1e-ced8-11e4-8e9c-dd2a6288acae.png)

Where these types is located ? (I updates dependencies)

**Comment by KonajuGames** [comment]
They've been added recently in Graphics\PackedVector.  Make sure you run
Protobuild to generate the project files again.​

**Comment by Shqrdx** [comment]
@KonajuGames Thank you !
