### ISSUE TITLE
Audio compilation broken :(

### ISSUE THREAD

**Issue by cra0zy** [mono/MonoGame#3644]
So I already know what caused this issue, it's this:
https://github.com/mono/MonoGame/commit/0632ec611217985c2c4738b2f8f1777a056f0583

And to be even more precise, it's this line of code:
> loopLength = data.Count / ((bitsPerSample / 8) * channelCount);

The error that occurs is this:
> Build started 3/20/2015 8:40:13 PM

> /home/harry/Documents/songtest/Game01.mp3
/home/harry/Documents/songtest/Game01.mp3: error: Processor 'SongProcessor' had unexpected failure!
System.NullReferenceException: Object reference not set to an instance of an object
  at Microsoft.Xna.Framework.Content.Pipeline.Audio.AudioContent.ConvertFormat (ConversionFormat formatType, ConversionQuality quality, System.String saveToFile) [0x00000] in <filename unknown>:0 
  at Microsoft.Xna.Framework.Content.Pipeline.Processors.SongProcessor.Process (Microsoft.Xna.Framework.Content.Pipeline.Audio.AudioContent input, Microsoft.Xna.Framework.Content.Pipeline.ContentProcessorContext context) [0x00000] in <filename unknown>:0 
  at Microsoft.Xna.Framework.Content.Pipeline.ContentProcessor`2[Microsoft.Xna.Framework.Content.Pipeline.Audio.AudioContent,Microsoft.Xna.Framework.Content.Pipeline.Processors.SongContent].Microsoft.Xna.Framework.Content.Pipeline.IContentProcessor.Process (System.Object input, Microsoft.Xna.Framework.Content.Pipeline.ContentProcessorContext context) [0x00000] in <filename unknown>:0 
  at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent (MonoGame.Framework.Content.Pipeline.Builder.PipelineBuildEvent pipelineEvent) [0x00000] in <filename unknown>:0 
Build 0 succeeded, 1 failed.

> Time elapsed 00:00:01.05.

**Comment by KonajuGames** [comment]
How is data null there? That contains the PCM data.

I'll check it out later today.

**Comment by cra0zy** [comment]
From the PR above:
//this line of code breaks audio compilation and therefor it has been commented
//2 things that this line of code does wrong are:
//1) data can be null, set by line 222
//2) bitsPerSample can be 0 ???
//loopLength = data.Count / ((bitsPerSample / 8) * channelCount);

**Comment by tomspilman** [comment]
Yeah... we should fix the source of the problem.  We should not comment out that code.  Let's see what @KonajuGames finds.

**Comment by cra0zy** [comment]
Well I commented it out so it can compile audio until the solution was found, it is meant to be there only temporary.

**Comment by cra0zy** [comment]
If it's any use, output of ffprobe of the mp3 file I was using:

> streams.stream.0.index=0
streams.stream.0.codec_name="mp3"
streams.stream.0.codec_long_name="MP3 (MPEG audio layer 3)"
streams.stream.0.profile="unknown"
streams.stream.0.codec_type="audio"
streams.stream.0.codec_time_base="1/44100"
streams.stream.0.codec_tag_string="[0][0][0][0]"
streams.stream.0.codec_tag="0x0000"
streams.stream.0.sample_fmt="s16p"
streams.stream.0.sample_rate="44100"
streams.stream.0.channels=2
streams.stream.0.channel_layout="stereo"
streams.stream.0.bits_per_sample=0
streams.stream.0.id="N/A"
streams.stream.0.r_frame_rate="0/0"
streams.stream.0.avg_frame_rate="0/0"
streams.stream.0.time_base="1/14112000"
streams.stream.0.start_pts=353600
streams.stream.0.start_time="0.025057"
streams.stream.0.duration_ts=444579840
streams.stream.0.duration="31.503673"
streams.stream.0.bit_rate="283598"
streams.stream.0.max_bit_rate="N/A"
streams.stream.0.nb_frames="N/A"
streams.stream.0.nb_read_frames="N/A"
streams.stream.0.nb_read_packets="N/A"
streams.stream.0.disposition.default=0
streams.stream.0.disposition.dub=0
streams.stream.0.disposition.original=0
streams.stream.0.disposition.comment=0
streams.stream.0.disposition.lyrics=0
streams.stream.0.disposition.karaoke=0
streams.stream.0.disposition.forced=0
streams.stream.0.disposition.hearing_impaired=0
streams.stream.0.disposition.visual_impaired=0
streams.stream.0.disposition.clean_effects=0
streams.stream.0.disposition.attached_pic=0
streams.stream.0.tags.encoder="LAME3.99r"

**Comment by KonajuGames** [comment]
Ok.  I'd just done some quick testing before bed on a Linux VM, and found it worked fine with a source wav file.  I came back here to ask how you were using it, and that post clears it up for me.  If you want to comment it out locally for now, I'll get it working properly with non-wav source files tomorrow.

**Comment by Eversor** [comment]
This is broken on all platform i think, I had to change all my content to WAV...

**Comment by KonajuGames** [comment]
I'm getting onto this now.​

**Comment by Eversor** [comment]
Thank you for your time.

**Comment by KonajuGames** [comment]
PR #3665 submitted.

**Comment by KonajuGames** [comment]
Closing via #3665
