### ISSUE TITLE
ModelMesh.Tag ignored in ContentManager.Load<Model>()

### ISSUE THREAD

**Issue by lllAlexlll** [mono/MonoGame#3649]
Hello,

***I have started porting my existing game engine from Xna to MonoGame recently. The process goes well and MonoGame looks very good but I have faced some issues. I will create 1 bug per issue.

MonoGame 3.3.0.2238
<b>Issue 1: ModelMesh.Tag ignored in ContentManager.Load<Model>()</b>
I have custom model processor which uses Model.Tag, ModelMesh.Tag and ModelMeshPart.Tag properties to store custom data. In ContentMagager.Load<Model>(), Model.Tag and ModelMeshPart.Tag are loaded just fine but ModelMesh.Tag is simply ignored. Currently I use simple workaround storing ModelMesh.Tag data in the ModelMeshPart.Tag but honestly I do not see any point to ignore MedelMesh.Tag property and I think that is a bug.

There are 
modelMeshPart.Tag = reader.ReadObject<object>();
and
model.Tag = reader.ReadObject<object>();
assignments in the
ModelReader : ContentTypeReader
class but there is no such assignment for the ModelMesh.Tag property.

Thank you!

**Comment by tomspilman** [comment]
Yep...  just need to fix this one line:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Content/ContentReaders/ModelReader.cs#L153

Thanks for reporting this @lllAlexlll !

**Comment by AndersonReyes** [comment]
This would be a super simple fix for me to start contributing. Has it been fixed?

**Comment by KonajuGames** [comment]
It hasn't yet.  Go for it.​

**Comment by lllAlexlll** [comment]
I confirm that the issue is fixed in the latest build.

**Comment by tomspilman** [comment]
Thanks for confirming @lllAlexlll !
