### ISSUE TITLE
iOS freeze & crash when attempting to resume following incoming call

### ISSUE THREAD

**Issue by Ben-P** [mono/MonoGame#3652]
When returning to a monogame game having received a call, the game screen displays, but updates do not resume. After about 10 seconds, the game crashes and returns to the home screen.

This occurs in the latest stable monogame build and development versions from just before this point until now.

Steps to reproduce:
1) Create a new iOS Universal app in Xamarin studio
2) Set up a standard "cornflower blue" game1 boilerplate class and update the AppDelegate and Main.cs files to run this.
3) Modify the game1 update and draw calls so that the ongoing updates can be seen (I put in a simple timer to display gameTime.TotalGameTime on the draw call)
4) Run the app (I was using an iPhone 5c running iOS 8.1)
5) Call the phone running the app
6) When the phone running the app switches to display the incoming call, hang up
7) The phone running the app will now return to the app, but the display will no longer update. After about 10 seconds, the app will crash.

**Comment by pauliharman** [comment]
This is a dealbreaker. Can't revert to 3.2 as Apple won't accept 32-bit apps, can't use 3.3 as apps will fail certification!

**Comment by danzel** [comment]
So this worked in 3.2?

Can you git bisect to track down when it happened?

**Comment by pauliharman** [comment]
Er... I suppose that's possible, for someone who [a] knows how to do a git bisect and [b] knows which of the tens of thousands of lines of code that probably changed between 3.2 and 3.3 affect the issue

**Comment by danzel** [comment]
There is a bit of docs on here about git bisect:
http://git-scm.com/docs/git-bisect

Basically git helps you do a binary search to figure out where the bad commit is. Which will make it much easier for someone to fix.

**Comment by Ben-P** [comment]
From what I've found, it looks like there's a problem in OpenALSoundController.cs: I swapped out the Monogame iOS DLL for the source and found that there was a crash occurring when trying to attach an event handler to AudioSession.Resumed when the game tries to resume after an incoming call (line 188 in the version I downloaded tonight).

If I put a breakpoint into Game.OnDeactivated (Game.cs, line 575) prior to the Raise(Deactivated, args) call and do not step past this until after hanging up the incoming call (i.e.: run the game, call the phone from another device, note that the breakpoint is hit, hang up on the other device then continue the run), the game resumes correctly.

I also found that the first v3.3 build of Monogame iOS (build date 25th Jan this year, downloaded from Teamcity) also exhibited this problem - I was unable to test further back than this as Monogame builds prior to this will not build when used with a Unified app.

**Comment by danzel** [comment]
^^ awesome stuff

**Comment by pauliharman** [comment]
Any ideas when this is going to be fixed? We have live projects on the App Store that we are unable to support because of this issue, as Apple will no longer accept non-64bit submissions (as per MonoGame 3.2)

**Comment by danzel** [comment]
This will be fixed when someone fixes it. Remember, this is an open source project maintained by volunteers.

The details from @Ben-P above should be enough for you to play around with the code to maybe workaround or fix the issue.
Possible commenting out the offending line will get it going.

**Comment by prollin** [comment]
We have encountered a few AudioSession crashes in our latest beta that seem similar to what is being described here. I also thought it could be cause by incoming calls but couldn't repro on my end. I quickly looked at the code and noticed that MonoGame was using a deprecated API (as of iOS 7.0) and decided to switch to the new API and see if we were still getting crashes from our users: It now has been a few beta builds without any crash.

The change is very simple: https://github.com/flyingdevelopmentstudio/MonoGame/commit/fc8934d4a1f9d951cce9ea2397ac415f26d46008

No guaranties this will fix the problem since it was hard to repro the issue on my end but hopefully someone with a good repro case will be able to confirm. Regardless, MonoGame should probably not be using the deprecated API.
