### ISSUE TITLE
Consider implementing / exposing texture arrays

### ISSUE THREAD

**Issue by tgjones** [mono/MonoGame#3653]
In Direct3D, there's an `ArraySize` property for textures, which I think would be really useful to expose:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/Texture2D.DirectX.cs#L363

```
desc.ArraySize = 1;
```

OpenGL has [array textures](https://www.opengl.org/wiki/Array_Texture), which look like the same thing (although not supported by OpenGL ES 2.0).

I think this could be a backwards-compatible change: if you want to `SetData` on one of these, you'd use the `level` parameter. You'd calculate the value for the `level` parameter using something similar to Direct3D's [D3D11CalcSubresource](https://msdn.microsoft.com/en-us/library/windows/desktop/ff476081%28v=vs.85%29.aspx), which we'd need to expose as a new API.

If this looks like something that would be of interest, then I'd be happy to work on a PR. I just wanted to first see if it matches MG's goals.

(My use-case: for cascaded shadow maps, it's nice to use a Texture2D array. The alternative is to use a single texture containing all the shadow maps, with offsets to sample from the correct cascade. It's certainly do-able without texture arrays, but more elegant with them.)

**Comment by tomspilman** [comment]
First thing...  how many of our target platforms support this?


> matches MG's goals.

As regards to graphics our goal is to provide a common API that works on a broad set of hardware and allow some common advanced features thru feature levels.

**Comment by tgjones** [comment]
> how many of our target platforms support this?

Texture arrays, and the related feature of being able to bind a particular element of a texture array as a render target, are supported by:

* Direct3D 11 (feature levels 10_0, 10_1, 11_0, 11_1 only. feature levels 9_1, 9_2, 9_3 don't support it)
* OpenGL 3.2 +
* OpenGL ES 3.0

In terms of MonoGame's platforms:

* Windows (OpenGL and DirectX) ✓
* Mac OS X ✓
* Linux ✓ (in theory)
* Windows Store ✓
* Windows Phone ✕ (AFAIK, supports Direct3D feature level 9_3, so doesn't support it)
* iOS ✕ (iOS now supports OpenGL ES 3.0, but MonoGame doesn't, and iOS doesn't support it as an ES 2.0 extension)
* Android. Some Android hardware supports the `EXT_texture_array` OpenGL ES 2.0 extension, so we can conditionally enable it, if the extension is present

> allow some common advanced features thru feature levels

Is there an example of feature level usage in MonoGame already? I guess this is something we have planned (in #1941) but isn't implemented yet? The only usage I can find of `GraphicsProfile` is for index sizes (16-bit, 32-bit).

**Comment by KonajuGames** [comment]
Some Android hardware also supports OpenGL ES 3.0 with Android 4.3 and higher.

The existing XNA `GraphicsProfile` values haven't really been used anywhere, except for the index size as you noted.  It's difficult to come up with new profiles because it casts such a wide net over features.

**Comment by tgjones** [comment]
> Some Android hardware also supports OpenGL ES 3.0 with Android 4.3 and higher.

@KonajuGames I'm still not clear about this.

* `EXT_texture_array` is the extension that covers this feature.
* [Some Android devices](http://stackoverflow.com/questions/3881197/opengl-es-2-0-extensions-on-android-devices) apparently support `EXT_texture_array` on ES 2.0
* OpenGL ES 3.0 supports texture arrays

My question is, does OpenGL ES 3.0 support texture arrays by

1. Supporting the `EXT_texture_array` extension, or
2. Simply by noting in the documentation that ES 3.0 supports texture arrays, so as long as you're using ES 3.0 you can expect it to be there?

I know that sometimes extensions are incorporated into the next version of the spec, but I can't find anything in the ES 3.0 docs about `EXT_texture_array`.

**Comment by KonajuGames** [comment]
This [article](http://www.informit.com/articles/article.aspx?p=2181697&seqNum=2) lists 2D texture arrays as a new feature in ES 3.0.

**Comment by KonajuGames** [comment]
As to how they're supported, I've never used ES 3.0 so I have no idea.  OpenGL still remains the mess that it typically has been.

**Comment by tgjones** [comment]
@KonajuGames Right, thanks :) I'm glad it's not only me...

Anyway, this discussion about OpenGL support is largely academic. To use texture arrays in HLSL, you need to declare your texture objects as `Texture2DArray`, and I'm fairly sure that MojoShader won't be able to convert those into OpenGL's equivalent (`sampler2DArray`).

So until MG either supports authoring shaders in GLSL, or uses a more up-to-date HLSL-to-GLSL converter, it won't be possible to fully implement or test texture arrays in OpenGL. (The same goes for [comparison samplers](https://github.com/mono/MonoGame/pull/3628), incidentally.)

**Comment by tomspilman** [comment]
>  It's difficult to come up with new profiles because it casts such a wide net over features.

Yet...  it is something we have to do.  We cannot head back down the path of cap bits.  I remember spending way too much time dealing with sites like:

**Comment by tgjones** [comment]
@tomspilman @KonajuGames so shall I create a PR? Obviously we can have more discussion about specifics, but do you think texture arrays are basically a good thing to have in MG?

**Comment by tomspilman** [comment]
> so shall I create a PR?

I would say yes if you also add it to `GraphicsCapabilities`.  This would give someone an immediate way to test for support.  Later we can map that to a feature level.

Can you also first more explicitly define the API you propose for this?

**Comment by tgjones** [comment]
> Can you also first more explicitly define the API you propose for this?

Yes. Here's what I propose:

``` csharp
new Texture2D(..., SurfaceFormat format, int arraySize); // New overload
new RenderTarget2D(..., bool shared, int arraySize); // New overload
GraphicsDevice.SetRenderTarget(RenderTarget2D renderTarget, int arraySlice);
new RenderTargetBinding(RenderTarget2D renderTarget, int arraySlice);
```

What I'm less sure about (and don't actually need, myself) is how to modify `GetData` and `SetData` to work with texture arrays. The more hand-holding approach is to add new overloads:

``` csharp
Texture2D.GetData(int level, int arraySlice, Rectangle? rect, T[] data, int startIndex, int elementCount);
Texture2D.SetData(int level, int arraySlice, Rectangle? rect, T[] data, int startIndex, int elementCount);
```

The downside is that the other overloads would still be there, but shouldn't be used for texture arrays.

The less hand-holding, more Direct3D-style, approach is to rename the existing `level` parameter to `subresource`, and add a public method to calculate the subresource index (this would be backwards compatible, since if `ArraySize == 1` then `subresource == level`):

``` csharp
Texture2D.GetData(int subresource, Rectangle? rect, T[] data, int startIndex, int elementCount);
Texture2D.SetData(int subresource, Rectangle? rect, T[] data, int startIndex, int elementCount);
int Texture2D.CalculateSubResourceIndex(int level, int arraySlice);
```

(I prefer this 2nd option, but I'm open to implementing either.)

*As an aside: I can foresee the various `RenderTarget2D` and `Texture2D` constructors getting out of hand. We might want to think about a Direct3D-style `Description` structure instead, for a future major version breaking change.*

**Comment by tgjones** [comment]
I guess I could also add a whole new class, `Texture2DArray : Texture` - I didn't think of that until just now. I was following Direct3D's lead on treating non-array and array textures as basically the same thing.  Then we'd also need a `RenderTarget2DArray`.

**Comment by tomspilman** [comment]
> The more hand-holding approach is to add new overloads

I think new overloads is the best approach.

> The downside is that the other overloads would still be there, but shouldn't be used for texture arrays.

I suspect the old methods would just work on the first array slice.  Same as if you call `SetData` without the mip level.

> more Direct3D-style, approach is to rename the existing  level  parameter to  subresource , and add a public method to calculate the subresource index

I think that is something to discuss and maybe implement as part of a refactor to new DX12/Metal/Vulkan style APIs.

> I can foresee the various `RenderTarget2D` and `Texture2D` constructors getting out of hand.

XNA-style is to define and initialize the resource as part of the constructor call.  They explicitly went that direction instead of adopting the DX9 style of structure descriptors.

I think the correct XNA-style and C#-style way of doing this is using named parameters.  For example we recently added this support to `SpriteBatch.Begin()`:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/SpriteBatch.cs#L66

We removed all other overloads of this function.  See how every parameter has a default value?  That allows you to do this:
```
spriteBatch.Begin();
spriteBatch.Begin(effect: MyEffect);
spriteBatch.Begin(depthStencilState: DepthStencilState.None);
spriteBatch.Begin(
   blendState: BlendState.Additive,
   effect: GetMyEffect(),
   transformMatrix: Matrix.CreateTranslation(10, 10, 10)
);
```
IMO this is almost superior to description structures and is a C# way to do things.

**Comment by tomspilman** [comment]
> I guess I could also add a whole new class,  Texture2DArray : Texture 

I am not sure that is worth the trouble.

**Comment by tgjones** [comment]
Thanks @tomspilman, that all sounds great. I've submitted the PR here: #3654.
