### ISSUE TITLE
Problem compiling MonoGame 3.3 in Monodevelop 5.7

### ISSUE THREAD

**Issue by mintwebdeveloper** [mono/MonoGame#3655]
Hi Hello I have a problem when I am trying to compile Monogame 3.3 on Monodevelop 5.7 on LinuxMint 17.1 it says "The type or namespace 'OpenTk' could not be found. Are you missing an assembly reference ?". Is there any instructions or step by step guide to compile and run Monogame 3.3 on Monodevelop 5.7 ?
![selection_001](https://cloud.githubusercontent.com/assets/7729521/6791840/2ec19f04-d1aa-11e4-857e-4b31a328d925.png)

**Comment by cra0zy** [comment]
You didn't download dependencies, https://github.com/Mono-Game/MonoGame.Dependencies, the correct way to get the code:
<ul>
<li>git clone https://github.com/mono/MonoGame.git</li>
<li>cd MonoGame</li>
<li>git submodule init</li>
<li>git submodule update</li>
<li>mono Protobuild.exe</li>
</ul>

**Comment by mintwebdeveloper** [comment]
Thanks so much cra0zy I have already compiled the code but how I can install on a folder ? or how I can add the compiled files on Monodevelop ? how i can add it as a plugin ?

**Comment by cra0zy** [comment]
You can't, the new addin is beeing worked on: #3361 .There is a download link near bottom if you want to try it out.

**Comment by mintwebdeveloper** [comment]
Ok np so how I can find the compiled libraries (I mean dlls) and develop libraries of monogames ?. How I can use them in my own projects in Monodevelop ?.

**Comment by thefiddler** [comment]
The dlls are placed under `MonoGame.Framework/bin/[Platform]/[CPU]/[Configuration]`. You can copy them to a folder in your project and add them to the project references.

**Comment by mintwebdeveloper** [comment]
Thanks for both you for your answers, now here is the problem. Let's says I have a folder which is located in /Programs/Monogame.Framework and I want to link with the project Platfomer2D (An example from monogame samples) also it seems I am missing some SDL libraries as you can see. How I can link this folder to this project in MonoDevelop ?. I so I can give you a better understanding:
![platformer2d](https://cloud.githubusercontent.com/assets/7729521/6877185/7c87985a-d4c6-11e4-95f7-764a22599365.png) I don't now how I can link this folder (Programs/Monogame.Framework) into this Platformer2D.

**Comment by cra0zy** [comment]
http://community.monogame.net/t/new-breed-of-samples-issue/2117/7

**Comment by cra0zy** [comment]
@tomspilman This can be closed, the new addin is out #3698, and I've already answered the original problem.
