### ISSUE TITLE
MonoGame must be on the same disk as project

### ISSUE THREAD

**Issue by zephyrthenoble** [mono/MonoGame#3656]
I'm working on a MonoGame WindowsGL project with others.  Unlike them, I have two drives: my C: drive , and SSD to hold the OS and other programs, and my M: drive for data and programs.  MonoGame was installed to the C: drive for whatever reason.  I kept getting the error

`Could not copy the file M:\program files (x86)\monogame\v3.0\assemblies\windowsgl\sdl.dll because it was not found`

I couldn't change the .csproj file as some people recommended, as it would screw up my teammates code.  I moved my repo to the C: drive and the problem disappeared.

I'm not sure if this is a MonoGame issue or not, but it seems silly to me that the build process inserts the current drive into the include string instead of the correct drive.

**Comment by KonajuGames** [comment]
That is definitely not intentional, nor should it happen.  `sdl.dll` is referenced via the `$(MSBuildProgramFiles32)` variable which should return the location of your 32-bit Program Files directory.  The installer also uses the NSIS variable `$PROGRAMFILES32` which returns the 32-bit Program Files directory.

Have you remapped Program Files to M: drive by any chance?

**Comment by KonajuGames** [comment]
Also, where did MSBuild get installed when you installed Visual Studio?  To C:\Program Files (x86)\MSBuild or M:\Program Files (x86)?

**Comment by zephyrthenoble** [comment]
MSBuild is installed in C:\Program Files (x86)\MSBuild.

As for viewing the above variables, I am not really a Windows guy, so I don't know how to view them.  I did however run `set PROGRAMFILES` and get back 

```
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C\Program Files (x86)
```

If you can point me in the right direction to view the exact value of the variables you mentioned, I will tell you what they are.

**Comment by KonajuGames** [comment]
I'm assuming that's a typo where the colon is missing in the path for `ProgramFiles(x86)`.

I don't know of an easy to debug MSBuild to see its variables.  I'm assuming that MonoGame installed its MSBuild files to `C:\Program Files (x86)\MSBuild\MonoGame`.  Trying to work out why it would be trying to read `sdl.dll` from `M:` instead of `C:`, and I don't have an easy answer at this stage.

**Comment by KonajuGames** [comment]
Here's something to try.  Go to Tools\Options -> Projects and Solutions\Build and Run.  Then enable diagnostic logging for the MSBuild output.  Then do a rebuild solution and check the output to determine the value of `MSBuildProgramFiles32`.

**Comment by tomspilman** [comment]
If you go to the Tools->Options under Projects and Solutions->Build and Run you can set the MSBuild project build output verbosity to Detailed or Diagnostic and get all the info on all the internal MSBuild vars and how they are set.

**Comment by zephyrthenoble** [comment]
I get
```
1>ProgramData = C:\ProgramData
1>ProgramFiles = C:\Program Files (x86)
1>ProgramFiles(x86) = C:\Program Files (x86)
1>ProgramW6432 = C:\Program Files
```

**Comment by KonajuGames** [comment]
Further down you will find the values for `MSBuildProgramFiles32`.

**Comment by zephyrthenoble** [comment]
Sorry, here it is

`MSBuildProgramFiles32 = C:\Program Files (x86)`

Additionally, here are the only two references to `M:\Program Files`

```
Target "_CopyOutOfDateSourceItemsToOutputDirectoryAlways: (TargetId:56)" in file "C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets" from project "M:\my\project.csproj" (target "_CopySourceItemsToOutputDirectory" depends on it):
Task "Copy" (TaskId:19)
  Task Parameter:
      SourceFiles=
          M:\Program Files (x86)\MonoGame\v3.0\Assemblies\WindowsGL\SDL.dll
                  CopyToOutputDirectory=Always
                  TargetPath=SDL.dll (TaskId:19)
  Task Parameter:
      DestinationFiles=
          bin\WindowsGL\Debug\SDL.dll
                  CopyToOutputDirectory=Always
                  TargetPath=SDL.dll (TaskId:19)
  Task Parameter:OverwriteReadOnlyFiles=False (TaskId:19)
C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(3951,5): error MSB3030: Could not copy the file "M:\Program Files (x86)\MonoGame\v3.0\Assemblies\WindowsGL\SDL.dll" because it was not found.
```

**Comment by cra0zy** [comment]
This can be closed since sdl was replaced with OpenTK/NVorbis
