### ISSUE TITLE
Possible OpenGL depth range / clipping bug

### ISSUE THREAD

**Issue by tgjones** [mono/MonoGame#3658]
It's very possible that I'm missing something obvious.

But it seems to me that MonoGame does not account for the difference in NDC space between Direct3D and OpenGL.

In Direct3D, the Z-coordinate in NDC ranges from 0 to 1, while in OpenGL it ranges from -1 to 1. So in Direct3D, anything in NDC space with `z < 0` will be clipped, while in OpenGL anything in NDC space with `z < -1` will be clipped.

The `Matrix.CreateOrthographic*` and `Matrix.CreatePerspective` methods use Direct3D conventions, so the NDC depth range created by these methods is from 0 to 1.

As far as I can see, that means that MonoGame's OpenGL renderer only ever uses half of the available depth range. Worse, near plane clipping doesn't work properly, because objects that *should* be behind the near clip plane, and therefore clipped, in fact aren't, because the near clip plane ends up (potentially) behind the camera. (That's how I noticed this bug - something that should have been clipped wasn't being clipped.)

The only mention I can find of this issue is over on FNA, here: flibitijibibo/FNA#282. @flibitijibibo mentioned a possible solution: `glClipControl`, and implemented it for FNA [here](https://github.com/flibitijibibo/FNA/commit/99019befdc4eb6d2de31706d0e89b7532affce3e), but it's only available in recent versions of OpenGL. You can also modify the `Matrix` methods that create projection matrices, but obviously that's not a general solution. @flibitijibibo has also added a note to the FNA docs about the issue, [here](https://github.com/flibitijibibo/FNA/wiki/2:-Building-with-FNA#depth-clipping-accuracy).

But I feel like I must be missing something, because surely this would have been noticed before now?

*(Note: MonoGame uses `posFixup` to account for the difference between Direct3D and OpenGL in the 0 location for the screen-space Y-coordinate. That's related to this, but it doesn't solve the NDC Z-coordinate problem.)*

**Comment by flibitijibibo** [comment]
An easy way to verify is to make that call to glClipControl and, if it's anything like my current port, it'll magically fix everything (and then you'll quietly sob when you realize you have to break content to _actually_ fix it for, say, OSX). Fixing depth inaccuracies can get really weird; adjusting with glClipControl fixed one game, but I still have to flip the SpriteBatch projection matrix depth value to get Rex Rocket rendering properly:

https://github.com/flibitijibibo/FNA/blob/master/src/Graphics/SpriteBatch.cs#L1078

Like pixel offsets you can find little ways to undo them without too much work, but unlike pixel offsets you can't make any one-size-fits-most solutions like posFixup (as far as I know). It's one of the reasons why it goes unnoticed most of the time, since the cases are very specific, yet blindingly obvious once you come across it. It took until the ~17th XNA port for me to notice that it was a thing at all!

**Comment by KonajuGames** [comment]
I've been making games professionally for 15 years and I had never heard of the term 'NDC' before (so many things I've still to learn), and I don't recall a depth clipping issue being raised here before.  This is one issue where I will have to leave it to people who know what they're talking about, because I'm not one of them.

**Comment by tgjones** [comment]
I was wondering whether the Z coordinate could be fixed up, like we do for the X and Y coordinates already. In fact, I just found this: MojoShader already has the code to do that, but it's commented out:
https://github.com/espes/mojoshader/blob/master/mojoshader.c#L2235

I wonder why it's commented out... It seems like it should work, but my maths is not strong enough to know if it will work in all cases.

**Comment by tgjones** [comment]
The MojoShader fixup code references Wine, which *does* use the Z coordinate fixup:
https://github.com/wine-mirror/wine/blob/master/dlls/wined3d/glsl_shader.c#L4645

Looking at the MojoShader history, it looks like the fixup code was added specifically for MonoGame, and when it was added, the Z coordinate fixup was already commented out.

**Comment by tgjones** [comment]
@espes I think you added that code to your fork of MojoShader - do you remember why the Z coordinate fixup is commented out?

**Comment by flibitijibibo** [comment]
Just tried that line in my MojoShader branch, seems to work fine without glClipControl. Boy am I glad you found this now... though the description doesn't explain it very well. I'm not well-versed in 3D math either, so I can't say why this might not work 100% of the time.

**Comment by flibitijibibo** [comment]
After working this one out in my head, and after going over all of my titles with this, it seems okay to use. I've had titles use weirdly high/low depth values and that might be affected by the `* 2` operation, but unless overflow is a thing to worry about this should keep things accurate without much fuss.

FNA commits:
https://github.com/flibitijibibo/MojoShader/commit/8e5037d1cafab148bac87b1b5d1dbdd4bc32f69e
https://github.com/flibitijibibo/FNA/commit/a4c92ac64e69cee2327da73f139de7154e6c196c
https://github.com/flibitijibibo/FNA/wiki/2:-Building-with-FNA/_compare/4bc5b76d67f439176722c13f7dd47c973e38df63...3d6afb7028cfa90941674b1482067987b50d1e87

**Comment by espes** [comment]
I like how it's past the 3-year anniversary of my original FX support in MonoGame and useful stuff is still turning up :P

I think it's only commented out because after couple hours of debugging a black screen when I was first hacking it together, I didn't trust anything...

**Comment by tgjones** [comment]
Good work @flibitijibibo! Hopefully we can make very similar changes to MonoGame, and then ideally have a lot of people test it before it gets released! :)

@tomspilman I think you updated the MojoShader DLL most recently - do you remember which source you used? Was it @espes' fork?

The maths in `glsl_shader.c` does make sense, but it's quite densely packed. Here's a less-packed version, just in case anyone's interested. Hopefully I got it right, as Tom Forsyth once [said](http://home.comcast.net/~tom_forsyth/blog.wiki.html#%5B%5BSpherical%20Harmonics%20in%20Actual%20Games%20notes%5D%5D), I'm more of a general concepts man myself :)

1. We want to map from Direct3D's `[0..1]` range to OpenGL's `[-1..1]` range in NDC space.
2. However, `gl_Position` is in clip space, not NDC space...
3. ... which means, according to the definition of clip space, that `gl_Position.z` is in the range `[0..w]`, and we need to map it to OpenGL's `[-w..w]`.
4. So we start with `z` in the range `[0..w]`, and take these steps:
  1. Divide `z` by `w`. Now `z` is in the range `[0..1]`.
  2. Multiply by 2. Now `z` is in the range `[0..2]`.
  3. Subtract 1. Now `z` is in the range `[-1..1]`.
  4. Multiply by `w`. Now `z` is in the range `[-w..w]`.
5. That gives us `z = ((z / w) * 2 - 1) * w`.
6. Some rearranging and cancelling gives you `z = (z * 2) - w`.
```

**Comment by tgjones** [comment]
> I think it's only commented out because after couple hours of debugging a black screen when I was first hacking it together, I didn't trust anything...

I've been there more times than I care to count :) It's good to know there wasn't a specific reason why it didn't work. And on the bright side, apparently nobody has really noticed any problem in practice.

**Comment by KonajuGames** [comment]
The maths is correct.

**Comment by tomspilman** [comment]
> @tomspilman I think you updated the MojoShader DLL most recently - do you remember which source you used? Was it @espes' fork?

Yes... we have a fork or his work here:

 https://github.com/Mono-Game/mojoshader

I added missing DLLEXPORT macros and updated the README with info on how to build MojoShader for MonoGame:

https://github.com/Mono-Game/mojoshader/blob/master/README.txt#L15


> Just tried that line in my MojoShader branch, seems to work fine without glClipControl.

Yeah the post transform fixup in MojoShader is the right path for now.

Once we move past MojoShader and start working with GLSL directly this will have to be something that a effect author will need to be aware of.  We can possibly provide some helper macro from MGFX like `MONOGAME_COORD_FIXUP` that internally does the same fixes but must be placed in the code.

**Comment by tgjones** [comment]
> Yeah the post transform fixup in MojoShader is the right path for now.

Great, I'll put a PR together.

> Once we move past MojoShader and start working with GLSL directly

That sounds like you're planning to remove automatic translation of HLSL to GLSL? I had thought that the translation would continue to exist, and that authoring in GLSL would be added as an additional option (and the only option, currently, on non-Windows platforms).

**Comment by tomspilman** [comment]
> That sounds like you're planning to remove automatic translation of HLSL to GLSL?

We're not going to keep MojoShader...  mostly because it is a dead path.  It won't support SM 4.x, 5.x, 6.x, or anything into the future from what I can tell.  

So we have to replace that translation with something else.  Most importantly something that works purely at the syntax level and doesn't require HLSL byte code to function.

Finding that solution shouldn't stop us from progressing on GLSL support.


> authoring in GLSL would be added as an additional option

I see it slightly differently...  authoring GLSL will be the primary path.  The translation from HLSL will be the optional feature that some may choose to use.

**Comment by tgjones** [comment]
> authoring GLSL will be the primary path. The translation from HLSL will be the optional feature that some may choose to use.

Cool. I totally agree on the priority - making GLSL a first-class authoring language is the most important thing.

But once that's in place, I'm really interested in pursuing a HLSL-source-to-GLSL-source transpiler, perhaps something like [hlslparser](https://github.com/Thekla/hlslparser), but updated to support HLSL SM 5.0+. Vulkan and SPIR-V muddy the waters here - but I think the basic idea of a single source language will still be a good problem to solve, regardless.

**Comment by tomspilman** [comment]
> making GLSL a first-class authoring language is the most important thing.

Yeah... that is what i'm thinking too.


> I think the basic idea of a single source language will still be a good problem to solve,

My hesitation comes from knowing that some closed console platforms have some different shading languages and specialized keywords for some features.  While HLSL<->GLSL is easy...  it may be very hard to support that path for all our possible targets.

This is why native language Effect files is our first priority and cross-compiling is just a nice feature to have for some cases when we can have it.

**Comment by tgjones** [comment]
> My hesitation comes from knowing that some closed console platforms have some different shading languages 

I don't have any access to closed console platforms, but from what I know about PSSL, for example, it seems like it would be quite "easy" to add it as another transpile target.

> This is why native language Effect files is our first priority and cross-compiling is just a nice feature to have for some cases when we can have it.

That totally makes sense. With the minor caveat that I think I'd give cross-compiling more value than "just a nice feature" - I think that a good cross-compiling solution would bring custom cross-platform effects within reach of a lot of people who wouldn't otherwise bother. Anyway, we can continue the discussion after GLSL compilation works :)
