### ISSUE TITLE
.Fbx models animation issue

### ISSUE THREAD

**Issue by lllAlexlll** [mono/MonoGame#3672]
Hello,

***I have started porting my existing game engine from Xna to MonoGame recently. The process goes well and MonoGame looks very good but I have faced some issues. I will create 1 bug per issue.

MonoGame 3.3.0.2238
<b>Issue 2: .Fbx models animation issue</b>
The problem is that my .Fbx animations are not played correctly in MonoMage as they did in Xna. I use custom Skinned Model Processor and Animation Player based on XNA skinning sample (GPU). 

Please take a look at the FBX model: https://www.dropbox.com/s/c5618bvugosu128/Gate001.FBX?dl=0. It is created using 3D Stuio Max and is rendered well in both 3D Studio Max and official FBX Review software but when loaded in MonoGame and rendered using SkinnedEffect, model meshes are shifted and distorted. In Xna this model was rendering correctly.

I'm not sure what I'm doing wrong, have you any ideas?

Thank you!

**Comment by mgarstenauer** [comment]
I took a quick look at your model in our engine. 

> model meshes are shifted and distorted

I can't confirm this... but I am using our own model format. These are my results:

Gate001.FBX contains a gate with two moving parts.
XNA, FBX Review, open3mod: The parts move up/down.
MonoGame: The parts move left/right.

A look at the skeleton shows that the skeleton in MonoGame is rotated 90° and probably also has an offset compared to XNA. --> Seems to be a bug in the OpenAssetImporter.

I can take a look at it, but I probably won't get to it until next week.

**Comment by tomspilman** [comment]
@mgarstenauer - That would be great if you could investigate it.

**Comment by lllAlexlll** [comment]
Thank you guys. 
Just to confirm: I use XNA content project combined with MonoGame
Content Importer: Autodesk FBX - XNA Framework
Content Processor: My custom Skinned Model processor

**Comment by mgarstenauer** [comment]
@lllAlexlll Ok, thanks for the clarification. I first assumed that you were using the MonoGame content pipeline.

I will report back with my findings next week.

**Comment by lllAlexlll** [comment]
Here is additional information for thought. A long time ago, when we started loading skinned models and animations in XNA, we faced some similar issues with the skeleton / bones positioning. The issue was that in 3D Studio Max animations were playing well but they had issues when loaded in XNA. We were trying to fix that and then we quickly figured out that the XNA model importer is not perfect and we have to follow some rules in 3D Studio Max when creating our models to not get them broken in XNA.
So now in the Monogame, it is possible that we have to fix our models in 3D Max somehow to make them working well in MonoGame but I'm trying to understand the difference.

**Comment by lllAlexlll** [comment]
<b>I have fixed the issue. That was my XNA to MonoGame conversion bug.</b>

> XNA, FBX Review, open3mod: The parts move up/down.
> MonoGame: The parts move left/right.

@mgarstenauer Since I use Xna Content project and FBX format I guess your case is not applicable to me. Possibly you have found another OpenAssetImporter bug =)

Thanks again!

**Comment by mgarstenauer** [comment]
@lllAlexlll Thanks for the follow-up.

> Possibly you have found another OpenAssetImporter bug =)

Yeah, looks like it. Anyway, I will investigate what's going on there.

**Comment by mgarstenauer** [comment]
Just a quick update: I finally found the time to investigate this OpenAssetImporter issue.

The OpenAssetImporter assumes that all transformation pivots are reset before exporting, which is the recommended practice. But in this case the transformation pivot of the root bone is not reset.

I have extended the OpenAssetImporter to handle these cases. I will provide a PR shortly.

**Comment by tomspilman** [comment]
Thanks @mgarstenauer !
