### ISSUE TITLE
AddResourceReference / RemoveResourceReference Performance Issues

### ISSUE THREAD

**Issue by lllAlexlll** [mono/MonoGame#3694]
Hello,

***I have started porting my existing game engine from Xna to MonoGame recently. The process goes well and MonoGame looks very good but I have faced some issues. I will create 1 bug per issue.

MonoGame 3.3.0.2238
<b>Issue 3: AddResourceReference / RemoveResourceReference Performance Issues</b>
I have noticed significant performance drop after porting my game from XNA to MonoGame (DX). Here is the Performance Analysis report from Visual Studio:

![1](https://cloud.githubusercontent.com/assets/11595800/6987977/8f91553c-da55-11e4-9403-be44e2b85d4e.jpg)

![2](https://cloud.githubusercontent.com/assets/11595800/6987980/93e01024-da55-11e4-8f6c-a358df803796.jpg)

![3](https://cloud.githubusercontent.com/assets/11595800/6987982/97989c9a-da55-11e4-933b-33a233a2a6dd.jpg)

Looks like <b>Microsoft.Xna.Framework.GraphicsDevice.AddResourceReference</b> and <b>Microsoft.Xna.Framework.GraphicsDevice.RemoveResourceReference</b> methods are the root cause of the performance issues. Not sure it I'm doing something wrong but in XNA there were no such issues.

Thank you!

**Comment by tomspilman** [comment]
`GraphicsDevice.AddResourceReference` is only called when a new resource is created.  Are you creating a ton of `DepthStencilState` objects every frame?  Why are you doing that?

**Comment by lllAlexlll** [comment]
Each object in the game world has it's own DepthStencilState, RasterizerState and BlendState settings and that is why I'm creating these objects for each objed drawn, is it wrong? 
<b>Anyway I have removed DepthStencilState object creation for each game entity and now performance is just fine (same as with XNA or even better)!</b> 
I guess I have to consider the architecture. 
Also DepthStencilState settings per entity are not so important for me and I can find some workaround for that. The only concern is that in XNA I was able to set DepthStencilState for each object without noticeable performance drop but current MonoGame behaviour is acceptable too. Thanks!

**Comment by tomspilman** [comment]
> I'm creating these objects for each objed drawn, is it wrong?

I would think most of your objects use a few common render states.  Create those once at start and reuse them.  Creating new render states for every object and every rendered frame is a bad idea.


>  in XNA I was able to set DepthStencilState for each entity without noticeable performance drop 

XNA uses DX9 and MonoGame uses DX11...  render states work very different between the two.


Still we could find ways to improve the performance of `GraphicsDevice.AddResourceReference`.  It doesn't need to be all that slow.

**Comment by lllAlexlll** [comment]
Yup.. Now I see that setting RasterizerState also causes performance issues (less noticeable in my case). When I remove both DepthStencilState and RasterizerState creations then I alsways have 60 FPS. So I have to work on improving design.
But still it would be awesome if there are ways to improve the performance of `GraphicsDevice.AddResourceReference`.

**Comment by lllAlexlll** [comment]
I'm closing the issue since I plan to reuse render states. Thanks for advice.
