### ISSUE TITLE
WinGL Links Against SDL?

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#3713]
I noticed that the WindowsGL template tries to include the SDL.dll:

https://github.com/mono/MonoGame/blob/develop/ProjectTemplates/VisualStudio2010/WindowsGL/MonoGameWindowsApplication.csproj#L59

Is this actually needed for WinGL?  This isn't packaged in the installer currently which is why I ask.

@thefiddler  @cra0zy ??

**Comment by christallire** [comment]
AFAIK, we only requires OpenTK.DLL to run WinGL application properly.

**Comment by cra0zy** [comment]
Tao.Sdl(and sdl) can be completely removed from WinGL, before they were used for joystick/gamepad, but now they don't have a purpose.

On Linux Tao.Sdl is still use for Audio(sdl_mixer), tho if we connect Linux to OpenAL we could also completely remove Sdl from there too.

**Comment by tomspilman** [comment]
> Tao.Sdl(and sdl) can be completely removed from WinGL

I'll gladly accept a PR that fixes the WindowsGL template that removes those.

**Comment by tomspilman** [comment]
Fixed in https://github.com/mono/MonoGame/pull/3716
