### ISSUE TITLE
Windows phone 8.1 adcontrol not visible

### ISSUE THREAD

**Issue by Rakesh-gene** [mono/MonoGame#3715]
Hi Team,
I am developing a game for windows phone 8.1 and i am using monogame 3.3 for doing the same.
In my gamePage.xaml file I have pubcenter ad-control which does not show up at all. I have given height, width, bg color etc, which are some of the solutions found on the internet but nothing worked.

On further investigation found that SwapChainBackGroundPanel is not supported for windows phone 8.1 and above. I am suspecting this might be the issue. If not I don't know how to proceed further.

Please let me know if you need a sample to replicate the issue.

**Comment by zno5** [comment]
I have the same trouble.
Did you solve this problem?
Please let me know how to show Ads in MonoGame for WP8.

**Comment by Rakesh-gene** [comment]
Hi Jinho,

The issue was with the sdk that was used. Please use the latest sdk.

Regards,
Rakesh
