### ISSUE TITLE
Choose Application bug on Windows / Missing References

### ISSUE THREAD

**Issue by NVentimiglia** [mono/MonoGame#3731]
Steps to replicate :
1) Install MonoGame 3
2) Download Samples from Git
3) Open .sln file

I am using Windows 8 and Visual Studio Pro 2013

I get a "Choose Application" dialog, please advise.

<img src="http://community.monogame.net/uploads/default/_optimized/84e/fce/8b0154b3aa_690x279.png" width="690" height="279">

I can manually open the project by dragging the sln file onto visual studio. Once I do that all of my references are missing (even System). No amount of nuget reinstall / restore fixes the issue.

**Comment by tomspilman** [comment]
> I get a "Choose Application" dialog

I've never seen that dialog before in my life.  What the heck is that from?

**Comment by NVentimiglia** [comment]
It is obviously from satan. The question is why.

I have my projects and tools installed on D: and my os on C: (ssd), could that be the cause ?

https://github.com/mono/MonoGame/issues/3656

**Comment by tomspilman** [comment]
Look and see what EXE that dialog is coming from.

**Comment by cra0zy** [comment]
I remember what that dialog is... it's a dialog that occurs when opening sln file and you have to select a version of visual studio that you want to use to open the file. Normally in the listbox it would offer options like:
VS 2010 C# Express
VS 2013 Community Edition
etc.

**Comment by cra0zy** [comment]
IMO this has nothing to do with MonoGame, it has to do with your visual studio installation

**Comment by tomspilman** [comment]
Ah...   that is right.  @NVentimiglia - Open your copy of VS then from the File menu open the MonoGame solution you are trying to open.

**Comment by NVentimiglia** [comment]
Ok, Im going to uninstall and reinstall VS.
