### ISSUE TITLE
Missing References Nuget non

### ISSUE THREAD

**Issue by NVentimiglia** [mono/MonoGame#3732]
Steps to replicate.

- Fresh install of Visual Studio 2013
- Fresh install of nuget from codeplex
- Fresh install of MonoGame 3.4
- Download Samples
- Run Platform2D Android

Visual studio loads and I get missing reference exceptions.

I have also tried the NuGet restore... removing the package and readding it.

````
Error	1	This project references NuGet package(s) that are missing on this computer.
 Enable NuGet Package Restore to download them. 
 For more information, see http://go.microsoft.com/fwlink/?LinkID=322105.
 The missing file is ..\..\..\packages\MonoGame.Binaries.3.2.3-alpha\build\MonoAndroid\MonoGame.Binaries.targets.	
D:\Users\Nicholas\Projects\MonoGame\Platformer2D\Platforms\Android\Platformer2D.csproj	143	5	Platformer2D
````

I checked my packages and confirmed that the package was missing. I also checked my MonoGame install folder (in Program Files) and cold not find anything. Please advise.

![monogame](https://cloud.githubusercontent.com/assets/125889/7147837/bb7e5978-e2b2-11e4-9679-178ed0809934.png)

**Comment by tomspilman** [comment]
Android requires purchase of Xamarin's Android runtime:

http://xamarin.com/platform

**Comment by NVentimiglia** [comment]
I have Xamarin Android. This error happens on all other platforms.

**Comment by tomspilman** [comment]
@DDReaper - Is this because the samples need new nuget packages?

**Comment by NVentimiglia** [comment]
Just reinstalled Xamarin, no help.

**Comment by cra0zy** [comment]
Can you create an android project with visual studio(not MonoGame)

**Comment by NVentimiglia** [comment]
As in a 'classical' java project? yes, I can.

**Comment by cra0zy** [comment]
No, I meant any xamarin android project that's not MonoGame Android project.... how do you even start a java android project with visual studio?

**Comment by NVentimiglia** [comment]
Yes, the C# android xamarin app works also.

**Comment by DDReaper** [comment]
Ok, seems to be a bit of a NuGet cleanup issue that didn't appear on my machine.

Just remove the lines containing:
``` xml
MonoGame.Binaries.3.2.3-alpha
```
And the sample project should compile cleanly.

Will try and free some time to clean that up.

**Comment by tomspilman** [comment]
@DDReaper - Can this issue be closed?  Or is there something we need to fix in our nuspec files?

**Comment by DDReaper** [comment]
I'll fix it in the next samples update.
