### ISSUE TITLE
Texture does not show (its all black)

### ISSUE THREAD

**Issue by mjsalman** [mono/MonoGame#3733]
I use Visual Studio 2012 and I have two projects one is an XNA Window game and the other one is MonoGame Window. They both use the same x file and my code in both projects is the same. Now in XNA my textures are rendered properly while in MonoGame they are not its all black. Am I doing something wrong

**Comment by mrhelmut** [comment]
Hello,

It may not be an issue. Could you please describe your problem and share your projects on [MonoGame's forum](http://community.monogame.net/) and close this issue until we are sure it is one?
Without further detail about how you handle your texture in both of your projects, it could anything.

Thanks!

**Comment by mjsalman** [comment]
I have attached the visual studio project. The x file was generated by blender. When I create an Xna project instead and use this file and the same c# code it works properly
Thanks Mike
