### ISSUE TITLE
MGFX - Set texture parameter ignored?

### ISSUE THREAD

**Issue by AquilaAbriel** [mono/MonoGame#3734]
Just a simple shader accepting a texture2d parameter to do some blending with the pixel shader texture:
```
sampler SamplerA : register(s0);

Texture2D FrameB;
sampler SamplerB = sampler_state
{
	Texture = <FrameB>;
    Filter = Linear;
    AddressU = Clamp;
    AddressV = Clamp;
};


uniform float BlendAmount;


float4 Interpol(float4 position : SV_Position, float4 color : COLOR0, float2 texCoord : TEXCOORD0) : COLOR0
{
	float4 pixA = tex2D(SamplerA, texCoord);
	float4 pixB = tex2D(SamplerB, texCoord);

	float pixAAlpha = pixA.w;
	float pixBAlpha = pixB.w;

	float4 test = {pixAAlpha, pixBAlpha, 0.0, 1.0};
	return test;
}


technique Interpolate
{
    pass Pass0
    {
        PixelShader = compile ps_4_0 Interpol();
    }
}
```

Project code:

```C#
spriteBatch.Begin(SpriteSortMode.Deferred, null, null, null, null, interpolator);
{
    interpolator.Parameters["FrameB"].SetValue(frameB);
    interpolator.Techniques[0].Passes[0].Apply();
    spriteBatch.Draw(frameA, new Vector2(0, 0), Color.White);
}
spriteBatch.End();
```
When running this shader it seems to work as expected, but on the next run (The next rendered frame) the parameter texture is ignored completely and only the pixel shader input texture is shown.
On the first run I can see a red and green picture resulting in some yellow parts when overlapping (as expected), but on the second run only the red channel is used. (Missing the green parts --> FrameB not used?)

Am I doing something wrong or is this a defect within the fx framework?
Thank you for reading.

**Comment by nkast** [comment]
I think you must change to this line `interpolator.CurrentTechnique.Passes[0].Apply();`

**Comment by AquilaAbriel** [comment]
Thank you nkast for your reply.
Unfortunately, the result stayed the same...
still the texture parameter seems to be ignored after the first frame.

**Comment by AquilaAbriel** [comment]
Okay, I think I have to add some more details about my code...
I figured out a way make this shader work as expected but I don't know why:

My draw method:
```C#
protected override void Draw(GameTime gameTime)
{
    GraphicsDevice.SetRenderTarget(gameRendertarget);
    GraphicsDevice.Clear(Color.Transparent);
    AEGraphics.RenderGraphics(gameRendertarget, spriteBatch);

    GraphicsDevice.SetRenderTarget(null);
    GraphicsDevice.Clear(Color.Black);

    //GaussBlur
    spriteBatch.Begin(SpriteSortMode.Deferred, null, null, null, null, gaussBlur);
    {
        gaussBlur.Parameters["TextureWidth"].SetValue(1280.0f);
        gaussBlur.Parameters["TextureHeight"].SetValue(720.0f);
        gaussBlur.CurrentTechnique.Passes[0].Apply();
        spriteBatch.Draw(gameRendertarget, new Vector2(0, 0), Color.White);
    }
    spriteBatch.End();

    //Interpolator Test
    spriteBatch.Begin(SpriteSortMode.Deferred, null, null, null, null, interpolator);
    {
        interpolator.Parameters["FrameB"].SetValue(frameB);
        interpolator.CurrentTechnique.Passes[0].Apply();
        spriteBatch.Draw(frameA, new Vector2(0, 0), Color.White);
    }
    spriteBatch.End();

    base.Draw(gameTime);
}
```
Once I deactivate the first three lines:

```C#
GraphicsDevice.SetRenderTarget(gameRendertarget);
GraphicsDevice.Clear(Color.Transparent);
AEGraphics.RenderGraphics(gameRendertarget, spriteBatch);
```

The shader works as expected.
Within this code I render the game screen:

```C#
public static void RenderGraphics(RenderTarget2D target, SpriteBatch spriteBatch)
{
    spriteBatch.Begin();
    foreach (KeyValuePair<int, Dictionary<string, AESprite>> layer in layers)
    {
        Dictionary<string, AESprite> sprites = layer.Value;
        foreach (KeyValuePair<string, AESprite> sprite in sprites)
        {
            //Just some math to calculate the rectangles
            spriteBatch.Draw(sprite.Value.sprite, targetRect, sourceRect, Color.White);
        }
    }
    spriteBatch.End();
}
```

I have no idea why this codes prevents the shader later applied to fail.
Maybe a timing issue? I remember from xna times that the renderer starts to skip frames if
running to slow.
Sorry for the long post and thank you for reading.

**Comment by AquilaAbriel** [comment]
I created and uploaded a small project demonstrating this issue.
https://mega.co.nz/#!qVs1nQzY!1k25owmaoi6dge4l6W1sBWofYMO4czhy5gHRuJcZJ0o

Maybe it is my own fault. Is the way I am using and switching the rendertargets correct?

**Comment by tgjones** [comment]
This looks very similar to an issue that was fixed last week. If you haven't already, try downloading the latest development build and see if that fixes the problem.

**Comment by AquilaAbriel** [comment]
Ah, thank you tgjones. I will try the development build than.
If the development build works correctly, I will close this issue.

**Comment by AquilaAbriel** [comment]
Thank you again tgjones. You were right. I tried development build 3.4.0.215 and well it works perfectly.
I hope this bug fix will be included into the stable release soon.
--Issue Closed--
