### ISSUE TITLE
Implement GenerateTangentFrames

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#3735]
We need someone to implement `ModelProcessor.GenerateTangentFrames`.

You just need to check if `GenerateTangentFrames` is true in `ModelProcessor.ProcessMesh()`:

https://github.com/mono/MonoGame/blob/2d43afcc304bbcc53d45c2f31471192c8b1daa32/MonoGame.Framework.Content.Pipeline/Processors/ModelProcessor.cs#L149

If so then you need to pass the `MeshContent` into the existing `MeshHelper.CalculateTangentFrames` to do the work...  this method is already implemented.

For bonus points implement `ModelProcessor.SwapWindingOrder`.  Just needs to pass the mesh to `MeshHelper.SwapWindingOrder`.

**Comment by Shqrdx** [comment]
Ummh, I tested, models really lacks tangent/binormal processing(model with these signatures is not drawable) for bump mapping.. sadly it is hard to testing unless you hack Pipeline.

**Comment by tomspilman** [comment]
> sadly it is hard to implementing unless deep hacking in Pipeline

That is not accurate.  As I stated above all the support for generating tangent frames is already implemented.  We just need to check the flag and run it.

**Comment by Vodacek** [comment]
Done in https://github.com/mono/MonoGame/pull/4034

**Comment by danzel** [comment]
@tomspilman this can be closed
