### ISSUE TITLE
Replace copy.sh with .build file

### ISSUE THREAD

**Issue by cra0zy** [mono/MonoGame#3739]
So with the last PR I separated generation part of the linux installer so that part of the installer can be done on the build server. 

The idea is as following, replace the file: https://github.com/mono/MonoGame/blob/develop/Installers/Linux/copy.sh with ".build" file.

Currently copy.sh file is used to copy all the needed files to the Installers/Linux/Installer/, and this folder could be just added to an archive and be given to the user.

**Comment by tomspilman** [comment]
> so that part of the installer can be done on the build server. 

Why part of and not all?  Where will the rest be done?  What files need to be moved around (we have to setup the build server to pass the right file around)?

**Comment by cra0zy** [comment]
> Why part of and not all?

Because this way you can use windows build server to create linux installer. After copy script is done you have a folder that contains:
Data (Folder)
Makeself (Folder)
generate.sh (File)
generate_deb.sh (File)

generate.sh can be run from linux or mac (or cygwin) and will generate linux .run package.
generate_deb has to be run from linux and will generate .deb package for Ubuntu and Debian.

**Comment by tomspilman** [comment]
> Because this way you can use windows build server to create linux installer.

But we can't really...  it only creates a part of the installer.  We still need a Linux box to do the rest.

IMO we should solve the core problem... we need to add a Linux box to the build system.


> generate_deb.sh has to be run from linux and will generate .deb 
> package for Ubuntu and Debian.

Cab `generate.sh` also be run from Ubuntu?  This means all we need is one Ubuntu box then correct?

**Comment by cra0zy** [comment]
> But we can't really... it only creates a part of the installer. We still need a Linux box to do the rest.
> 
> IMO we should solve the core problem... we need to add a Linux box to the build system.

The rest (running one of the generate scripts) takes less than 30 seconds, and when I separated the generation, I was thinking that this could be used for nightly builds, and for stable builds we could just run the generate scripts from any Linux manually.

Adding a Linux build server would also be a way of doing it. In which case copy.sh could be just connected to the .build file, and not have to be replaced.

> Cab generate.sh also be run from Ubuntu? This means all we need is one Ubuntu box then correct?

Ubuntu is Linux.▼▼

> generate.sh can be run from linux or mac (or cygwin) and will generate linux .run package.
