### ISSUE TITLE
Archive The Old Forums

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#3745]
We need to find a tool to archive the content (text, links, images) of the old forums:

 http://monogame.codeplex.com/discussions

We can then take them down to avoid confusing users as to where to ask questions.

The static archive can then be put on the new site in a read only state.

**Comment by cra0zy** [comment]
Call be crazy but I made a software thats able to parse discussion pages and save their content... 

Anyway just tell me the format you want everything saved as and I can save it. Currently it extract the following information from every post:
username
date
date edited
data(leaves html untouched)
It automatically goes over all the discussions > threads > posts.

**Comment by cra0zy** [comment]
If you want to modify it yourself for saving, feel free to do so:
https://mega.co.nz/#!DUAgnLIY!BR2Rj30jk-j1TCjtRVVPmlzA4naFd1ieQRU1fToMRgk

**Comment by cra0zy** [comment]
PS. You probably want to save stuff in Topic.cs line 50, so that it doesn't consume to much RAM.

**Comment by tomspilman** [comment]
> Anyway just tell me the format you want everything saved as and I can save it. 

I thinking of just a static mirror of the existing content.

It would be interesting to "import" the content into our instance of Discourse (http://www.discourse.org/), but I wouldn't know where to begin with that.  It would make it all searchable which would be nice.

**Comment by cra0zy** [comment]
> I thinking of just a static mirror of the existing content.

I can just set everything to be exported to any static way, I would only need a template to use for exporting(how the webpage should look, html, javascript and css files, or maybe mysql database and just import it from somewhere later?).

> It would be interesting to "import" the content into our instance of Discourse (http://www.discourse.org/), but I wouldn't know where to begin with that. It would make it all searchable which would be nice.

Not impossible, but it does sound like a lot of work. This looked interesting(for seeing how to write import scripts): https://github.com/dkobia/discourse-import-bbpress-plugin

**Comment by tomspilman** [comment]
> I would only need a template to use for exporting(how the webpage should look, html, javascript and css files, or maybe mysql database).

We could develop something based on our current website theme maybe.

I don't know what would be best here really.


> Not impossible, but it does sound like a lot of work.

Yep... it does.


> would you need to create fake users for it.

I guess something like that would need to happen.  Not sure of what the options are within Discourse for that sort of thing.

**Comment by nkast** [comment]
Years ago I used httrack, not sure if there is anything more advanced nowdays.
It's a classic for crawling and creating a static copy of a website.
http://www.httrack.com/

**Comment by tomspilman** [comment]
So follow up...   I tried to do this, but couldn't get httrack to spider the old site correctly without it moving out and grabing other project pages and non-MonoGame stuff.  I gave up and since then the new community site is getting pretty good...  so this isn't needed anymore.
