### ISSUE TITLE
Pipeline Tool Start Page

### ISSUE THREAD

**Issue by cra0zy** [mono/MonoGame#3748]
I was thinking that instead of opening the last opened project on startup we present the user with a page that offers all recent projects (and maybe MonoGame News?).

@tomspilman @nkast I would like to hear your opinion on this.

**Comment by tomspilman** [comment]
> we present the user with a page that offers all recent projects 

It is duplicate work... we already have a recent projects menu.  It isn't like opening projects is the bottleneck to productivity.

IMO we can't even consider this while https://github.com/mono/MonoGame/issues/3230 is still an issue.


> and maybe MonoGame News?

It would make sense if the pipeline tool was the central tool everyone opens to start a new MonoGame project....    but it isn't.

It would be like Notepad having "Windows news".

**Comment by cra0zy** [comment]
> It would make sense if the pipeline tool was the central tool everyone opens to start a new MonoGame project.... but it isn't.

Agreed.
