### ISSUE TITLE
Pipeline - System.Exception could not load .spritefont

### ISSUE THREAD

**Issue by Temeez** [mono/MonoGame#3754]
Windows 8.1, newest prebuild dev build.
Font [menufont.spritefont](https://github.com/CartBlanche/MonoGame-Samples/blob/master/GameStateManagement/Content/menufont.spritefont)
Picture of the problem: http://i.imgur.com/kFuy03w.png

Is the spritefont building completely busted, or does it not like certain .spritefont files? Or am I perhaps missing something?

Also the pipeline window got the black plague after 3.2 :(

**Comment by tomspilman** [comment]
> Or am I perhaps missing something?

I think the system you are on does not have the Segoe UI fonts installed.

**Comment by Temeez** [comment]
That is a huigh possibility, need to check when I get home.

Follow up question: Why does the system that builds the font need it to be installed? It feels a bit "handicapped".

**Comment by tomspilman** [comment]
> Why does the system that builds the font need it to be installed?

That is how it worked under XNA too.  Sprite fonts need the true type font being used to be installed.

That said we have a feature for Mac/Linux where it can use a ttf font that is in the same folder as the .spritefont.  This feature just isn't implemented under Windows yet.

**Comment by Temeez** [comment]
Glad to hear that feature is in the works.

Also, looks like I had Segoe UI font installed, but it was looking for Segoe UI Mono which wasn't and got butt hurt because of that, slightly edited the .spritefont file and now it builds without problems.

Thanks @tomspilman :)

**Comment by jmoral4** [comment]
For anyone that happens to have this issue in the future -- **Segoe UI Mono** was introduced with XNA 4.0 and included in various tutorials, etc, but unfortunately is nowhere to be found outside of that.

If you're downloaded code from the MSDN XNA site, are using an older tutorial, or are using your own older code from a Win7/8 box, you may run into the situation where the font cannot be found and it breaks your content pipeline.

The solution, as mentioned above, is to select another font. _Alternatively_, you can copy over the old font files from /Windows/Fonts on any machine that has them. 

In my case, my main developer box had been upgraded over time (Win 7/8/10) and retained the old XNA font files but these were causing build breaks for anyone building the project on a new Windows 10 desktop with Monogame installed.
