### ISSUE TITLE
So, Google 2.0 id api is gone, community.monogame.net needs updating

### ISSUE THREAD

**Issue by cra0zy** [mono/MonoGame#3755]
So if you try to sign in to community.monogame.net you will be presented with: https://support.google.com/accounts/answer/6206245?p=openid&rd=1
because yesterday(for my timezone) they removed the old api.

**Comment by tomspilman** [comment]
I'll fix it today.

**Comment by tomspilman** [comment]
@cra0zy - Try it now.

**Comment by cra0zy** [comment]
It's alive, Alive!!!!
