### ISSUE TITLE
2MGFX not building - missing VirtualFile

### ISSUE THREAD

**Issue by totallyeviljake** [mono/MonoGame#3759]
After update to latest MG and protobuild, the 2MGFX project (contained in MG.Windows) will not compile. It is missing the VirtualFileSystem and VirtualFile classes.

I don't see these files in the repo either.

**Comment by tgjones** [comment]
Maybe you need to run `git submodule update`? I've just checked and it compiles okay for me, after recreating the project file using Protobuild. `VirtualFile` and `VirtualFileSystem` are in the `CppNet` assembly, which is referenced by `2MGFX`. `CppNet.dll` is in the MonoGame-Dependencies submodule.

**Comment by totallyeviljake** [comment]
yeah, looks like it was an out of sync deps. thanks
