### ISSUE TITLE
Formatting in MathHelper

### ISSUE THREAD

**Issue by WardBenjamin** [mono/MonoGame#3774]
While working on the new Random class, I noticed that (since my IDE differentiates) the MathHelper class is poorly indented, with some functions for some reason using only one layer of indentation, and tabs at that. Can I have permission to change the formatting a bit @tomspilman ? I will try to keep it as minimal as possible.

**Comment by KonajuGames** [comment]
We prefer not as part of a feature addition or bug fix PR because it adds a
lot of noise to the changes in the PR, making it harder to review.

There will be a formatting pass done at some point. It's all down to
choosing a good time to do so.

**Comment by WardBenjamin** [comment]
Of course as not of the feature addition, but it is very hard on the eyes. I understand the reason not to do formatting since it breaks the line change history badly, but it's messing up the formatting with the new class. Should I just ignore it and continue?

**Comment by cra0zy** [comment]
I am a bit confused... this class: 
https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/MathHelper.cs
looks perfectly fine. What do you mean by "one layer of indentation"?

**Comment by WardBenjamin** [comment]
If you check, the last two functions have a bunch of tabs (mixed with spaces) which look fine in the Github text viewer but do not if you have you have your IDE set to 4 spaces == 1 tab.

**Comment by cra0zy** [comment]
oh yea, you are right.

**Comment by tomspilman** [comment]
No...  lets not make any formatting changes.  It always makes the PRs harder to approve.  And if I say yes now... then how can I say no to others later.

**Comment by WardBenjamin** [comment]
@tomspilman I was not suggesting that the pull request contain these edits, only that they be done to improve code readability and such. I have no problem with this decision however :+1:
