### ISSUE TITLE
OS X installer may need to create /usr/local/bin

### ISSUE THREAD

**Issue by KonajuGames** [mono/MonoGame#3791]
OS X does not appear to have /usr/local/bin by default, even though it is in the PATH.
http://community.monogame.net/t/os-x-3-4-installer-package-issue/2355
The installer should create the directory if it does not exist and give it the appropriate permissions.

@dellis1972 Are you able to look into this?

**Comment by dellis1972** [comment]
I'll take a look

-----Original Message-----
