### ISSUE TITLE
Any plan on add a UI system ?

### ISSUE THREAD

**Issue by Scellow** [mono/MonoGame#3792]
Hello,

Do you guys have plan on adding a UI system ? That's the only thing that is missing to monogame

Thanks <3

**Comment by tomspilman** [comment]
No

**Comment by tomspilman** [comment]
We don't have plans for that.  MonoGame is just not a "game engine".  MonoGame is more about abstracting hardware and low level features like XNA was.

If we ever consider that we would probably just write an engine on top of MonoGame as a separate thing.

**Comment by Scellow** [comment]
What a quick response, thanks :p 

Yeah i understand, well i guess it's time for me to try to make my own instead of depending on 3rd party libs :p

**Comment by KonajuGames** [comment]
Here's a discussion in the MonoGame Community about [UI frameworks](http://community.monogame.net/t/ui-frameworks/653).

**Comment by tomspilman** [comment]
>  i guess it's time for me to try to make my own instead of depending on 3rd party 

There are lots of good ones out there... I would find one you like and modify from there.

**Comment by theZMan** [comment]
Digital Rune stuff is rock solid extensive, built and tested on MonoGame (and I think the DR team contribute back) and generally great http://www.digitalrune.com/Products/GameEngine/GameUI.aspx but not free... in all seriousness though $199 for the indie license is cheaper than anything you could make yourself

If you want free this one works http://xnagui.codeplex.com/ - at least it did on XNA.

**Comment by Scellow** [comment]
After hours of googling i found this:

https://github.com/NeoforceControls/Neoforce-Mono

The monogame port of Neoforce XNA, it's looking really great : http://neoforce.codeplex.com/
