### ISSUE TITLE
Memory leak in VertexBuffer.GetData and IndexBuffer.GetData

### ISSUE THREAD

**Issue by mgarstenauer** [mono/MonoGame#3797]
The methods VertexBuffer/IndexBuffer.PlatformGetData<T> are pinning the data array using GCHandle.Alloc, but never release the handle. 

- https://github.com/mono/MonoGame/blob/81765ff2f4ce6bced932f87ee62496ffc253cc65/MonoGame.Framework/Graphics/Vertices/VertexBuffer.DirectX.cs#L88
- https://github.com/mono/MonoGame/blob/81765ff2f4ce6bced932f87ee62496ffc253cc65/MonoGame.Framework/Graphics/Vertices/IndexBuffer.DirectX.cs#L86

Other methods (Texture2D.GetData, etc.) seem to be implemented correctly.
I suggest adding a try-finally block to all methods where GCHandle.Alloc is used.

**Comment by tomspilman** [comment]
That is a pretty huge memory leak... I don't know when that got introduced.  But we need someone to submit a fix ASAP.

Second... how could we detect these mistakes in an automated way via a unit test?

**Comment by tgjones** [comment]
> Second... how could we detect these mistakes in an automated way via a unit test?

JetBrains' [dotMemory Unit](https://www.jetbrains.com/dotmemory/unit/) is pretty cool for that. It's free, but it does requires ReSharper or dotCover to be installed. There isn't yet a standalone runner, but they plan to add one, so that it can be integrated with TeamCity.

At its simplest, it lets you add an attribute like this to your tests:

``` csharp
[AssertTraffic(AllocatedMemoryAmount = 1000, Types = new[] { typeof(string) })]
[Test]
public void TestMethod1()
{
    // Some user code
}
```

But you can also do this:

``` csharp
var memoryCheckPoint1 = dotMemory.Check();  // 1

foo.Bar();

var memoryCheckPoint2 = dotMemory.Check(memory =>
{
    // 2
    Assert.That(memory.GetTrafficFrom(memoryCheckPoint1).Where(obj => obj.Interface.Is<IFoo>()).AllocatedMemory.SizeInBytes,
        Is.LessThan(1000));
});

bar.Foo();

dotMemory.Check(memory =>
{
    // 3
    Assert.That(memory.GetTrafficFrom(memoryCheckPoint2).Where(obj => obj.Type.Is<Bar>()).AllocatedMemory.ObjectsCount,
        Is.LessThan(10));
});
```

I don't know if the ReSharper requirement rules it out, but I know that a number of us do have ReSharper installed. And it will be even more useful once it can be run automatically on TeamCity.

**Comment by tomspilman** [comment]
> JetBrains' dotMemory Unit is pretty cool for that.

Wow... that is exactly what we're looking for I think.

We should keep an eye out for this and support it as soon as there is TeamCity support for it.

**Comment by Ed-Pavlov** [comment]
[There is release candidate of dotMemory Unit 2.0](https://confluence.jetbrains.com/display/ReSharper/ReSharper+9.2+EAP)

It contains standalone launcher which can be used with any standalone unit test runner. TeamCity plugin coming soon

Give it a try and send us a feedback  :)
