### ISSUE TITLE
Monogame on Mobile

### ISSUE THREAD

**Issue by WardBenjamin** [mono/MonoGame#3810]
So, I am seriously interested in making a non-Xamarin dependant version of MG for mobile, along with a few others that I have talked to. This would initially be for Android if it did actually happen. What are the actual limitations that everyone has gone through when trying to develop MG for mobile platforms? Graphics issues? Touch interpretations?

**Comment by tomspilman** [comment]
> I am seriously interested in making a non-Xamarin dependant version of MG for mobile

What C# runtime would you use to do this?

**Comment by cra0zy** [comment]
I've given a fair amount of thought on this subject, android only:
- First option would be to use: https://github.com/koush/androidmono to get mono working and then write some custom wrappers for basically everything
- Second option would be to use CS2J to convert c# to java, I actually tried this method just to see if it was feasible: http://community.monogame.net/t/monogame-on-android-without-xamarin-android/1931
- Third option would be to use JSIL to get the game converted to javascript, and then run it within Android WebView component, but the problem with this actually comes from the fact that for JSIL javascript code to run, it needs to be run from a server, can't remember why

**Comment by WardBenjamin** [comment]
Hm, that is clever. Some options look like AndroidMono, Dot42, and Java conversion (would probably require some annoying manual code changes after conversion. I was previously considering [Dot42](https://github.com/dot42/dot42) but AndroidMono seems like an option as well.

**Comment by WardBenjamin** [comment]
Another option for this could actually be the Core CLR. Since MS has released the linux version of the CLR, I think I can compile a version of it that will run on top of the Android kernel if I do some hackery with the Android NDK and some C++ standard libraries. Also, I think that this would require the use of some Java to actually start the console corerun executable, but I think it is possible. I am going to start to try and hack together a runtime that will be able to run on an emulator, starting with setting up a toolchain and building the Linux version of the CoreCLR, and then playing with the NDK to see if I can build the CLR against the Android Bionic headers.

**Comment by cra0zy** [comment]
@WardBenjamin any luck?

**Comment by WardBenjamin** [comment]
It's taking a long time to wrap my head around the way that Android handles system events and such, I may have to embed some callback events into the CLR so you can access them inside of MG.

Progress as of this point:
 - Linux version of the CLR building on Ubuntu 14.04
 - Android NDK installed
 - Android SDK installed (except for Android Studio)

I have a repository at https://github.com/WardBenjamin/coreclr that I will update periodically with my results, probably starting tonight.

**Comment by WardBenjamin** [comment]
I am working on this but this is not really something we should focus on for the forseeable future. Closing.

**Comment by cra0zy** [comment]
Well, I got mono up and running on android... but then I realized about mono license... and then I scratched that idea of the list...

Also scratch the JSIL idea as well, turns out it loads forever, and then it throws an error.

**Comment by WardBenjamin** [comment]
@cra0zy what were the steps to get Mono running?

**Comment by cra0zy** [comment]
https://github.com/JeroMiya/androidmono plus didn't use the default mono repo.

It's not worth doing it...

**Comment by zwcloud** [comment]
[Xamarin.iOS & Xamarin.Mac](https://github.com/xamarin/xamarin-macios) and [Xamarin.Android](https://github.com/xamarin/xamarin-android) is open-sourced. Maybe you are interested in how they work on Android.

**Comment by Jjagg** [comment]
I don't think there's much interest in this left because of Xamarin being free now for teams of less than 5 people.

**Comment by zwcloud** [comment]
@Jjagg MonoGame is meant for making game but Xamarin is meant for building regular apps. I think MonoGame should remove the dependency on Xamarin and take advantage of the mono runtime from Xamarin.Android and Xamarin.iOS since they have been opensourced. Just using the C# runtime and standard libraries is enough.

**Comment by cra0zy** [comment]
> take advantage of the mono runtime from Xamarin.Android

Name 1 advantage.

**Comment by KonajuGames** [comment]
Essentially that's what we do.  We use the Xamarin compiler, runtime and libraries.  Nothing else.  There is nothing else we could gain by taking bits of the open sourced code.

**Comment by Jjagg** [comment]
> MonoGame is used to make game but Xamarin is used to build regular apps

You may be confusing Xamarin with Xamarin.Forms...
