### ISSUE TITLE
MonoGame crashes on Windows Phone 8.1 (Emulator and level 9_3 devices)

### ISSUE THREAD

**Issue by mgarstenauer** [mono/MonoGame#3828]
MonoGame crashes in the Windows Phone 8.1 Emulator (Emulator 8.1 U1 WVGA 4 inch 512MB) and potentially all feature level 9_3 devices.

The app exits with:
SharpDX.SharpDXException: HRESULT: [0x887A0005], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_DEVICE_REMOVED/DeviceRemoved], Message: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.

I have tracked the problem down to the following line:
https://github.com/mono/MonoGame/blob/ca6e7edc007b0a73dc36810b4ef4b4e851ec44f1/MonoGame.Framework/Graphics/TextureCollection.DirectX.cs#L82
MonoGame is trying to clear the vertex texture slot. However, feature level 9_3 (or lower) does not support vertex textures. This call results in: "D3D11: Removing Device."

Suggested solution:
Disable vertex textures if feature level <= 9_3 (Reach profile).
Enable vertex textures only if feature level >= 10_0 (HiDef profile).

**Comment by tomspilman** [comment]
@tgjones - Got time for this fix?

**Comment by tgjones** [comment]
@tomspilman I'm away this weekend, but I can look at it when I get back on Sunday evening.

**Comment by tomspilman** [comment]
Thanks!
