### ISSUE TITLE
Improve The README.md

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#3846]
We need to review and improve our existing README.md file:

https://github.com/mono/MonoGame/blob/develop/README.md

Some things I've noticed so far:

  - The supported platforms is out of date.
  - We shouldn't repeat download info from the website... just link them to it.
  - Remove link to the old Starter Kits.
  - Does anyone ever really use our IRC channel anymore?
  - Update the "Current Roadmap" or remove it?

Also maybe we can come up with some improvements to ours by looking at other good READMEs:

  https://github.com/Microsoft/msbuild/blob/master/README.md
  https://github.com/dotnet/coreclr/blob/master/README.md
  https://github.com/dotnet/corefx/blob/master/README.md

Any other ideas are welcome!

**Comment by tomspilman** [comment]
Idea... maybe add a link to the [Help Wanted](https://github.com/mono/MonoGame/labels/Help%20Wanted) label under contributing as a suggestion as to where to start.

**Comment by cra0zy** [comment]
Should PlayStation Mobile stay under supported platforms?

**Comment by tomspilman** [comment]
> Should PlayStation Mobile stay under supported platforms?

The store for PSM games will be shut down July 15, 2015 and the service will be shut down September 10, 2015.  So for certain we will remove support for PSM later this year.

Still we should probably stop advertising support for it as someone starting with it now would be screwed.

**Comment by cra0zy** [comment]
What do you think about this: https://github.com/cra0zy/MonoGame/tree/readme

**Comment by cra0zy** [comment]
Also I really don't know what should Windows UAP be combined with Windows Phone and Windows Store Apps

**Comment by dsaf** [comment]
Roadmap kind of gives a feeling that the project is in active development rather than maintenance mode. Also it is nice to know what to expect from the upcoming release, e.g. whether [PCL] (https://github.com/mono/MonoGame/issues/3405) will be a part of it :).

**Comment by tomspilman** [comment]
> Roadmap kind of gives a feeling that the project is alive and in active development 

For me... I always look at the monthly pulse page on any project:

 https://github.com/mono/MonoGame/pulse/monthly

When you see merges on a daily basis and lots of opened and closed issues... I feel confident that the project is active.

**Comment by dsaf** [comment]
> When you see merges on a daily basis and lots of opened and closed issues...

That is true, it's the first thing to check on any repo :).

> What might be better for a roadmap...

C# team is doing this: milestones, labels and a planning issue per release/feature - for discussions.

**Comment by tgjones** [comment]
@tomspilman Can this be closed now that #4465 is merged?

**Comment by tomspilman** [comment]
I still want to make some more improvements, so lets leave this open a bit longer.

**Comment by tomspilman** [comment]
Fixed in https://github.com/mono/MonoGame/pull/4625.
