### ISSUE TITLE
Monogame Linux Installer "broken"

### ISSUE THREAD

**Issue by WardBenjamin** [mono/MonoGame#3850]
Hey all,

When using Monogame on Linux, the nuget package works perfectly, but I noticed that when I downloaded the 3.4 Linux download (Monogame.Linux.zip) from monogame.net, a few things were wrong. First, generate_deb.sh, makeself-header.sh, and makeself.sh are not marked as executable when unzipped. Second, the pipeline tool .deb generates with the version of 3.3-1, instead of 3.4. Is this intentional, or should it be changed?

**Comment by WardBenjamin** [comment]
Oh, just found a third issue. The deb that is generated through makeself also does not change the monogame-pipeline executable in /bin to be exectuable, so I had to run `sudo chmod +x /bin/monogame-pipeline` on that as well.

**Comment by cra0zy** [comment]
This has been fixed in #3786

**Comment by WardBenjamin** [comment]
@cra0zy thanks for letting me know. Will this be a part of 3.4 or will it only be a part of the upcoming 3.5 release?

**Comment by cra0zy** [comment]
3.5

**Comment by WardBenjamin** [comment]
Thanks. Closing.
