### ISSUE TITLE
Structures should be serializable

### ISSUE THREAD

**Issue by ivanvulovic** [mono/MonoGame#3851]
A number of structures (Vector2/3/4 for example) are marked [Serializable] in Microsoft's XNA and are not in MonoGame. This should be changed for compatibility and just because it's helpful to have. I haven't looked more systematically at what does/doesn't match; Vector3 was what I ran into.

**Comment by tomspilman** [comment]
We switched to `[DataContract]` serialization a couple of years ago:

 https://github.com/mono/MonoGame/issues/3072
