### ISSUE TITLE
MonoGame.Framework.iOS reference for ModelReader optimized away.

### ISSUE THREAD

**Issue by Izikio** [mono/MonoGame#3859]
When creating a Xamarin iOS app, if you set the assembly linker to link all assemblies, The ModelReader gets optimized away. 

I've noticed that to prevent this, you have created instances like so
<code>
var hStringReader = new StringReader();
</code>

ModelReader is missing a reference, so it gets optimized away. 

Additionally, is there any reason that you are not using the Preserve attribute instead (For all readers that are invoked dynamically).
[Xamarin.iOS.Foundation.Preserve]

Could you add the fact that the library has to be set to link sdks only to the nuget readme?

Regards

**Comment by tomspilman** [comment]
Yes... ModelReader` needs to be added to this block of code:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Content/ContentTypeReaderManager.cs#L117

Should be a simple PR for someone.

**Comment by KonajuGames** [comment]
> Additionally, is there any reason that you are not using the Preserve attribute instead (For all readers that are invoked dynamically).
> [Xamarin.iOS.Foundation.Preserve]

The `Preserve` only exists in iOS and Android, and it's in different namespaces on those platforms.  And it appears with the addition of `Xamarin.iOS.Foundation` it still won't be consistent across platforms.

If we were to try to use the `Preserve` attribute, it would a mess of #if conditionals and then we would need the alternative for the other platforms anyway.  So we have remained with the one approach that works across all platforms.

**Comment by danzel** [comment]
This can be closed (Side note, we need to add Int32Reader in there too for Song loading on iOS. Will submit....)
