### ISSUE TITLE
Problem with compiling 3d models

### ISSUE THREAD

**Issue by cra0zy** [mono/MonoGame#3862]
http://community.monogame.net/t/wont-load-non-content-fbx-in-monogame-3-4-0-455-on-linux/2455

I've looked into that and it turns out models compiled from Linux can't be loaded, while those compiled from Windows can.

No errors occur during the build of the model.

**Comment by tomspilman** [comment]
First thing to do is convert the same FBX on Linux and Windows and do a binary comparison of the XNB files.   Those files should be basically identical.

**Comment by cra0zy** [comment]
squarew is windows produced and squarel is linux produced, https://mega.co.nz/#!2QZjwSKK!KXtV7ytgVbD3tuDt3RQ6_7fx5vdw96O4HgHA9ZnJ5sk

I forgot to check the version of Pipeline on Win(which I will do right now), on Linux it's newest Pipeline.

**Comment by cra0zy** [comment]
I have found something interesting, setting compiling platform to Windows created xnb that can be loaded.. I know where to look now.

**Comment by cra0zy** [comment]
I am more confused than I was... it now produces correct xnb files... and I have no idea why it produced those unreadable xnb for that short time.

**Comment by tomspilman** [comment]
Could it be the Linux/Windows/DesktopGL change in the `TargetPlatform` enum?

**Comment by cra0zy** [comment]
found what was causing the problem, submitting a PR in 2 mins..
1 thing I don't understand is why did it load the Linux files at all...

**Comment by cra0zy** [comment]
#3863 fixes it
