### ISSUE TITLE
Content.mgcb build fail when code is from a GIT repository.

### ISSUE THREAD

**Issue by SirMartin** [mono/MonoGame#3870]
Hi to all,

I started a little project, and I started in one computer, and I made a GIT repository and I commited all the project in the GIT, when I downloaded the repository (in other/same computer) I can't build it, and monogame gives me this fail.

###### The command ""C:\Program Files (x86)\MSBuild\MonoGame\v3.0\Tools\MGCB.exe" /@:"C:\Users\Eduardo.Izquierdo\Documents\Piribisoft%20Airlines%20Game\com.piribisoft.airlines.windows\Content\Content.mgcb" /platform:Windows /outputDir:"C:\Users\Eduardo.Izquierdo\Documents\Piribisoft%20Airlines%20Game\com.piribisoft.airlines.windows\Content\bin\Windows" /intermediateDir:"C:\Users\Eduardo.Izquierdo\Documents\Piribisoft%20Airlines%20Game\com.piribisoft.airlines.windows\Content\obj\Windows" /quiet" exited with code -532462766.

I found another issue with the same problem, but I tried all the solutions, with the same result. I checked and reinstalled the same version of MonoGame (3.4) in both computers, but the problems also happens in the same computer. Also I checked the MonoGameContentReference, but is OK in all the cases.

The fun is at if I copy the "original" solution, in other folder it's works, and if I copy the solution into a pendrive and I move to the other computer is also works. Any idea? I can't understand this. I uploaded to my git repository without any .gitignore, so all the files are uploaded, but it continues failing.

It's crazy.

Can you help me people?

Thank you so much.

**Comment by KonajuGames** [comment]
My thinking is that it could be one of two things:
- the spaces in the paths are appearing as %20 in the error message.  Is that only in the error report or are those repalcements for the spaces happening earlier somewhere?
- line endings in the mgsb file.  Git does line ending conversion depending on settings in your gitconfig, which can be global or local.

**Comment by SirMartin** [comment]
Yes thank you, this was the fail number 1 you quoted. 

The problem was at in the Git Origin was created the name with white spaces, so when I cloned the repository in my machine, git set up the path with "%20" instead of white spaces, so the mono game failed. I renamed my local path in my computer, changing the "%20" for white spaces, and build perfect.

Thank you so much for your help.
