### ISSUE TITLE
Content pipeline implementation isn't exposed

### ISSUE THREAD

**Issue by ollipekka** [mono/MonoGame#3872]
As a user who is trying to implement Content Pipeline Extension that deals with graphics, I'm unable to reproduce things like Texture2DReader, because ContentReader.GraphicsDevice is internal.

In my use case, I'm trying to implement TextureAtlas content pipeline extension. It reads TextureAtlas which contains dictionary of regions and an image. I'm not able to initiate new Texture2D, because I can't get handle to a GraphicsDevice.

To reproduce this, copy contents of https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Content/ContentReaders/Texture2DReader.cs to a custom extension. It doesn't compile.

**Comment by mgarstenauer** [comment]
To get the GraphicsDevice call

```
var graphicsDeviceService = (IGraphicsDeviceService)input.ContentManager.ServiceProvider.GetService(typeof(IGraphicsDeviceService));
var graphicsDevice = graphicsDeviceService.GraphicsDevice;
```

in your ContentTypeReader.

**Comment by tomspilman** [comment]
@mgarstenauer @KonajuGames @dellis1972 

Is there are good reason we shouldn't just make `ContentReader.GraphicsDevice` public?  Other than backwards compatibility with XNA?

**Comment by KonajuGames** [comment]
It's the same two non-obvious lines of code that have to repeated in any ContentTypeReader, so I don't see why not expose it.

**Comment by mgarstenauer** [comment]
We could expose `ContentReader.GraphicsDevice` in MonoGame for convenience. ... Or, why not remove the internal `ContentReader.GraphicsDevice`!

Here is my reasoning: I personally prefer XNA's architecture, which has a clean separation: The `ContentManager` stuff is in Microsoft.Xna.Framework.dll which does not have a dependency on Microsoft.Xna.Framework.Graphics.dll. So, in theory, the content pipeline should be usable and testable independent of the graphics stuff.

**Comment by ollipekka** [comment]
Similarly GraphicsDevice.GraphicsCapabilities seem to be hidden. Even if i'm able to extract GraphicsDevice, I'm not able to implement IOS support for textures ala Texture2DReader because third party pipeline extension assemblies are second-class citizens.
(talking about this class) https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/GraphicsCapabilities.cs

Another option would be to expose Texture2DReader so that I could utilize it inside my TextureAtlasReader.

While I like XNA's architecture, I feel that sticking to it and treating it as the holy canon is going to gimp MonoGame in the long run. Ideally I'd like to see being able to reproduce core behavior in any third party pipeline extensions.

I don't suggest that these APIs should be visible when using MonoGame normally, but only having access to these APIs during ContentReader (and maybe other pipeline functions as well)

**Comment by dellis1972** [comment]
@ollipekka I've been looking at my own "Atlas" processor. And in keeping with the way the Model processor works you should be able to create your own "atlas" xnb but have it reference the textures via external references. That way the built in Texture Processor can do its job an optimise of the target platforms (and it does allot of stuff you don't want to replicate yourself PVRTC/DXT texture compression etc). I do something like 

```
OpaqueDataDictionary data = new OpaqueDataDictionary();  
data.Add("PremultiplyAlpha", PremultiplyAlpha); 
data.Add ("TextureFormat", TextureFormat);
var e = new ExternalReference<TextureContent>(textureName);
var texture = context.BuildAsset<TextureContent,TextureContent>(e, "TextureProcessor", data,"TextureImporter",Path.GetFileNameWithoutExtension(textureName)+"_Texture"); 
```
Store the "texture" value in the return object of your Processor.
then in the Writer you can use
```
output.WriteExternalReference (texture);
```

and in the Reader use

```
input.ReadExternalReference<Texture2D> ();
```
in the right place.


here the TextureFormat and PremultipleAlpha properties are properties of my new Processor, and the TextureName comes from the Atlas input file.

With this you end up with your atlas.xnb file and a texture.xnb file (just like you do with models. There is no need to reference the GraphicsDevice at all, you can do this all within the current API. That said, it was/is not MonoGame's intention to stick with the XNA api only, but to extend it where it makes sense. So this might be something that happens :)
