### ISSUE TITLE
Crash in Mac OSX - GamePad

### ISSUE THREAD

**Issue by kjpou1** [mono/MonoGame#3875]
Current Development branch as of May 25 When overriding the update method in the Game:

        protected override void Update(GameTime gameTime)
        {
            base.Update(gameTime);

            // Allows the game to exit
            #if (WINDOWS && !NETFX_CORE) || WINDOWSGL || WINDOWSDX || MACOS
            if (GamePad.GetState(PlayerIndex.One).Buttons.Back == ButtonState.Pressed)
            Exit();
            #endif
        }

Calling the GamePad.GetState here causes the following crash:

2015-05-25 08:53:10.820 CocosSharpTests[53100:1772618] _createMenuRef called with existing principal MenuRef already associated with menu
2015-05-25 08:53:10.821 CocosSharpTests[53100:1772618] (
	0   CoreFoundation                      0x90fe2c63 __raiseError + 195
	1   libobjc.A.dylib                     0x9aa73a2a objc_exception_throw + 276
	2   CoreFoundation                      0x90fe2b7d +[NSException raise:format:] + 141
	3   AppKit                              0x95fe2193 -[NSCarbonMenuImpl _createMenuRef] + 70
	4   AppKit                              0x95fe1924 -[NSCarbonMenuImpl _instantiateCarbonMenu] + 155
	5   AppKit                              0x95fe187e -[NSCarbonMenuImpl setupCarbonMenuBar] + 40
	6   AppKit                              0x95fdfddd -[NSApplication finishLaunching] + 1398
	7   ???                                 0x104b3204 0x0 + 273363460
	8   ???                                 0x104b2094 0x0 + 273358996
	9   ???                                 0x027ddc40 0x0 + 41802816
	10  libUnable to determine number of joysticks.
Object reference not set to an instance of an object
mono-2.0.dylib                   0x0040ec8f mono_jit_runtime_invoke + 751
	11  libmono-2.0.dylib                   0x005d0baf mono_runtime_invoke + 127
	12  libmono-2.0.dylib                   0x005d10da mono_runtime_class_init_full + 778
	13  libmono-2.0.dylib                   0x0040bc17 mono_jit_compile_method_with_opt + 4119
	14  libmono-2.0.dylib                   0x0040aba9 mono_jit_compile_method + 57
	15  libmono-2.0.dylib                   0x004c0d91 common_call_trampoline + 961
	16  libmono-2.0.dylib                   0x004c09bc mono_magic_trampoline + 60
	17  ???                                 0x007ef088 0x0 + 8319112

The calling line is https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Input/GamePad.OpenTK.cs#L84

**Comment by cra0zy** [comment]
This is a duplicate of #3790

**Comment by kjpou1** [comment]
Thanks @cra0zy will close as duplicate
