### ISSUE TITLE
Memory leak in Windows store universal app

### ISSUE THREAD

**Issue by dekroll** [mono/MonoGame#3876]
I have a problem with unmanaged memory leak in Windows Store Universal App. 
Here are steps to reproduce the problem:
1) Create Universal project from MonoGame template
2) Add blank page for Windows 8.1 project and button to it
``` xaml
		<Button Content="Go forward" Click="ButtonBase_OnClick"/>
```
``` csharp
		private void ButtonBase_OnClick(object sender, RoutedEventArgs e)
		{
			var gamePage = new GamePage(string.Empty);
			Window.Current.Content = gamePage;
		}
```
3) Modify app.xaml.cs
``` csharp
        protected override void OnLaunched(LaunchActivatedEventArgs args)
        {
			var blankPage = new BlankPage();
			Window.Current.Content = blankPage;
			Window.Current.Activate();
        }
```
4) Add a button to game page 
``` xaml
<SwapChainBackgroundPanel
    x:Class="MonoTest.GamePage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:MonoTest"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <Grid >
		<Button Click="GoBackBtnClicked" Content="Start game"/>
    </Grid>
</SwapChainBackgroundPanel>
```
``` csharp
	    private void GoBackBtnClicked(object sender, RoutedEventArgs e)
	    {
			var blankPage = new BlankPage();
			Window.Current.Content = blankPage;
	    }
```
Here what I can see in profiler: 
![image](https://cloud.githubusercontent.com/assets/4506967/7794076/42bd76da-02cf-11e5-9f62-8d3ad27fbc82.png)
Unmanaged memory allocations are done on navigation to game page. 

I tried to call Dispose for game 

```csharp
        public GamePage(string launchArguments)
        {
            this.InitializeComponent();
            // Create the game.

            _game = XamlGame<Game1>.Create(launchArguments, Window.Current.CoreWindow, this);
			Unloaded += OnUnloaded;
        }

	    private void OnUnloaded(object sender, RoutedEventArgs routedEventArgs)
	    {
		    _game.Dispose();
	    }
```

But this code throws ObjectDisposedException
```
    System.ObjectDisposedException: The Game1 object was used after being Disposed.
    Object name: 'Game1'.
       at Microsoft.Xna.Framework.Game.AssertNotDisposed()
       at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
       at Microsoft.Xna.Framework.Game.Tick()
       at Microsoft.Xna.Framework.MetroGameWindow.Tick()
       at Microsoft.Xna.Framework.MetroGamePlatform.<StartRunLoop>b__0(Object o, Object a)
```
Can please anyone help me with this problem?

PS I'm using MonoGame 3.4

**Comment by faisalr** [comment]
I think you should use SwapChainPanel instead of SwapChainBackgroundPanel

**Comment by dekroll** [comment]
Thanks for the answer. Do you have a working example?  
XamlGame Create method requires SwapChainBackgroundPanel (third argument). 

```csharp
        static public T Create(string launchParameters, CoreWindow window, SwapChainBackgroundPanel swapChainBackgroundPanel)
```

**Comment by faisalr** [comment]
I am using Windows 10 universal project with MonoGame 3.5

    public static T Create(string launchParameters, CoreWindow window, SwapChainPanel swapChainPanel);

Try this

        XamlGame<Game1>.Create(string.Empty, Window.Current.CoreWindow, this);

**Comment by dekroll** [comment]
> I am using Windows 10 universal project with MonoGame 3.5


I have no plans to upgrade to Win10 at the moment (I'm using 8.1). 

> I noticed AssertNotDisposed which means you should never dispose the game.


But there should be a way to release resources. 

> Use  _game.Exit();


Exit is marked as obsolete in windows store apps.

**Comment by faisalr** [comment]
Why do you need to release resources?

With your way of using Window.Current.Content you don't need to dispose anything.

**Comment by dekroll** [comment]
> Why do you need to release resources?
> With your way of using Window.Current.Content you don't need to dispose anything.

Please check the [image](https://cloud.githubusercontent.com/assets/4506967/7794076/42bd76da-02cf-11e5-9f62-8d3ad27fbc82.png) from issue description. This is profiler screenshot . If I do not release resources of the Game instance amount of allocated memory will continue increasing.

**Comment by faisalr** [comment]
I am bad at memory management I am C# only... :smile:

**Comment by tomspilman** [comment]
@dekroll 

It seems like you are trying to create a `Game` when a page loads, free it when you leave the page, then create it again later.

This pattern is not one we've designed MonoGame for... so likely the leaks you are seeing are caused by that issue.

We have been working on removing a lot of the 'static` globals we use in places which should help, but not much else has been done to make this a "feature" for MonoGame.  If you want to see that happen then we are always looking for people to contribute... but it will take some effort and there are design issues to consider as well.

**Comment by dekroll** [comment]
> Instead create it once and just hide the page and reshow it.

Hi! Thanks for the response, this is what I finally decided to do, but I thought that there is a better way :). 

Again, thanks for the answer.
