### ISSUE TITLE
[Content Pipeline] Opening a content pipeline file opens previously opened file

### ISSUE THREAD

**Issue by zephyrthenoble** [mono/MonoGame#3882]
When I double click on a content pipeline file, the content pipeline tool opens up with the previous file.  I then have to manually go to file -> open and select the file for the new content pipeline file to be loaded.

I believe this is not deliberate, but I could be wrong.

OS: Windows 8.1
Pipeline: 3.4.0.211

**Comment by cra0zy** [comment]
Duplicate of #3230

**Comment by zephyrthenoble** [comment]
Thanks, didn't see that one when I searched.
