### ISSUE TITLE
Content loading capitalization policy different on Windows and Linux

### ISSUE THREAD

**Issue by WardBenjamin** [mono/MonoGame#3889]
I don't know about OSX, but I know that the capitalization policy is different on Windows and Linux as far as content loading goes. On Windows, `Content.Load<Texture2D>(@"Tiles/Null")` will load `Tiles/null.xnb` even though capitalization is different, however this is not true for Linux. On Linux, it will throw a "Cannot load as non-content file" error unless the image is renamed to `Null.xnb` or the line that loads it is changed to use lowercase.

What is the correct policy? I am inclined to agree with the more strict one that is implemented on Linux.

As a note, this may impact the Linux/WinGL merge.

**Comment by KonajuGames** [comment]
It depends on the file system of the OS.  Windows is case-insensitive, but almost every other platform is case-sensitive.  We cannot change how the file system of the host platform works.

It is best practice to use the correct case when loading your content.  This will allow the same code and data to be used on all platforms.  We just cannot enforce it on Windows.

**Comment by cra0zy** [comment]
As @KonajuGames said, different file systems, different rules.

On FAT and NTFS creating file called "Abc.txt" is same as creating a file called "abc.txt" or "ABC.txt", it's not case sensitive.

On EXT it is case sensitive, so you can have all 3 files in the same folder.
