### ISSUE TITLE
Spritefont Editor

### ISSUE THREAD

**Issue by cra0zy** [mono/MonoGame#3902]
I have the tool I wrote few years back that I am still using for editing spritefonts. Would it be of any use to add it here?

**Comment by tomspilman** [comment]
What specifically does it do?

**Comment by KonajuGames** [comment]
I had occasionally entertained the thought of an editor, perhaps just a
property grid, to edit .spritefont files rather than hand editing the XML.

**Comment by tomspilman** [comment]
When we originally planned the Pipeline tool we had the idea that eventually we could add some sort of plug-in API for viewers/editors.  Starting with built in editors/viewers for stock types seems like a reasonable place to begin to develop such an API.

**Comment by cra0zy** [comment]
> plug-in API for viewers/editors

I've written such a thing before, but last time I did it, the main application was only Gtk which made me allowed to use Gtk Widgets as editors. This time since there are 2 backends I'm either gonna have to make plugin integrate with propertygrid or require for the addin to provoide both backends.

**Comment by tomspilman** [comment]
> since there are 2 backends, I'm either gonna have to make plugin
> integrate with propertygrid or require for the addin to provoide both
> backends.

Well first off note that if we are going to do this... it will eventually be more than just the property grid we will expose to the plugin.  I would like to see a "view" area be exposed as well... probably to be tabbable with the output window or something.

To make plugins easy to write we have to abstract the property grid or any "widget" with our own API.  Vastly simplified of course and aimed specifically at the types of things plugin would need to do.  Just like we have `IView.AddTreeItem` or `IView.OutputAppend`.  Could be that `IView` needs to be broken up into `IView`, `ITreeView`, `IPropertyView` to begin with.

Plugins would have to also be able to create its own undo/redo actions if they plan to make changes to the content in any way.

There is a lot of work here to do this right.

**Comment by cra0zy** [comment]
> Well first off note that if we are going to do this... it will eventually be more than just the property grid we will expose to the plugin. I would like to see a "view" area be exposed as well... probably to be tabbable with the output window or something.

Yea, had the same idea :), actually I've already done some starting work on this.

> To make plugins easy to write we have to abstract the property grid or any "widget" with our own API. Vastly simplified of course and aimed specifically at the types of things plugin would need to do. Just like we have IView.AddTreeItem or IView.OutputAppend. Could be that IView needs to be broken up into IView, ITreeView, IPropertyView to begin with.

I don't think that's a good idea, what purpose would it serve if we allowed modifying treeview/propertyview? 

For tabbed widgets/controls, it would be much better if we allowed them to use Gtk/WinForms than writing our own API for GUI backend for few reason:
1) People wouldn't need to learn a new GUI api in order to write an extension
2) They would be able to use any widget/control they wanted

> Plugins would have to also be able to create its own undo/redo actions if they plan to make changes to the content in any way.

☑ Checked

**Comment by tomspilman** [comment]
> People wouldn't need to learn a new GUI api in order to write an extension

Actually they would have to learn two, or one, or none if they are lucky and know both GTK and WinForms.  It also requires testing on both, bug fixing on both, etc.

Every plugin system for cross platform tools that I've seen abstracts the GUI.  We need to as well.

**Comment by cra0zy** [comment]
> Every plugin system for cross platform tools that I've seen abstracts the GUI. We need to as well.

Can you give me an example, preferably something that is open source so I can see how it works.

**Comment by cra0zy** [comment]
Side note, the way I am thinking of is Monodevelop Addin api, it allows using Gtk widgets in a lot of places.

**Comment by tomspilman** [comment]
> Can you give me an example, preferably something that is open source so I can see how it works.

For open source I would say Blender... can't think of another right now.  But I would point at the tools that I have extended in the past: 3dsmax, Maya, Softimage.

**Comment by cra0zy** [comment]
All of them have their own gui systems... We have 2 gui systems and that's what I find so problematic.

**Comment by cra0zy** [comment]
I thought about this a bit and came to the conclusion, do we really even need API for the pipeline tool at all? What would that API offer that people couldn't get by building an application in WinForms?

Also I should have posted an image of the spritefont editor:
![sfe](https://cloud.githubusercontent.com/assets/6773302/8021354/62f47b34-0c9c-11e5-8a6c-fa522983d8c1.png)

**Comment by KonajuGames** [comment]
`Kerring` -> `Kerning`  :)

The only issue I see with this is that the SpriteFont XML can be extended.  The XNA localization sample does this by changing the typename at the top of the spritefont file to make it use a different font processor.

**Comment by cra0zy** [comment]
> Kerring -> Kerning :)

You know... I made this app few years ago, and I haven't noticed that...

> The only issue I see with this is that the SpriteFont XML can be extended. The XNA localization sample does this by changing the typename at the top of the spritefont file to make it use a different font processor.

That's easy to implement.

Btw I was gonna change the layout and add xml view as well.

**Comment by tomspilman** [comment]
> What would that API offer that people couldn't get by building an application in WinForms?

What you suggest then is the Pipeline tool simply having a way to associate an "editor" and "viewer" for file types and launching the right executable in different situations.

I would say depending on the tool there is a lot of boiler plate stuff we could unify.  There are the basics like file loading/saving, undo/redo, UI standards, etc.  If we support viewers for content we would provide a common rendering framework for doing so... via MonoGame of course.

To do this all yourself would be more challenging, but still not impossible.  We could help by providing some common tool/viewer framework project.  We would implement some standard tools and let people write some of their own.

Regardless of the path we take we do really need to support launching external editors/viewer better than we currently do.  Right now on Windows we just go with the file association for "Open"...  but I think we might need something more complex than that.

**Comment by cra0zy** [comment]
> If we support viewers for content we would provide a common rendering framework for doing so... via MonoGame of course.

That actually sounds like a very good. A lot of people who currently write games with MonoGame could easily create Pipeline Tool extensions. One thing we would need to provide is a UI Framework(for Buttons, TextBoxes, etc.).

**Comment by tomspilman** [comment]
>  A lot of people who currently write games with MonoGame could easily create Pipeline Tool extensions.

That was my whole point to begin with.  Make extensions for viewing and editing content easy to write and maintain across Windows/Mac/Linux.


> One thing we should provide is a UI Framework(for Buttons, TextBoxes, etc.).

This is again where I think wrapping GTK/WinForms is what we need here.  We would not be developing a MonoGame UI system.

**Comment by cra0zy** [comment]
> This is again where I think wrapping GTK/WinForms is what we need here. We would not be developing a MonoGame UI system.

I don't like the idea of wrapping Gtk and WinForms, it would be much easier to just port the entire tool to Xwt...and I wouldn't like to port it to Xwt because of all the cool native stuff I've done for the Gtk version...

We don't need to develop a MonoGame UI system, we could use an existing one.

**Comment by tomspilman** [comment]
>  I wouldn't like to port it to Xwt because of all the cool native stuff I've done for the Gtk version

Exactly....   the whole reason we're not searching for a unified toolkit is because we want the Pipeline tool to feel like a native app on its platform.  Fundamentally any unified toolkit requires compromise on one platform or another to make it work the same.  

This is what I've learned in over 20 years of GUI development.

> We don't need to develop a MonoGame UI system, we could use an existing one.

Tools should use native UIs... not game UIs.

**Comment by cra0zy** [comment]
> This is what I've learned in over 20 years of GUI development.

You know, when you say it like that I can't complain... I have yet to live 20 years in total 

> Tools should use native UIs... not game UIs.

The problem with that comes from few things:
1) We won't be able to write wrappers for everything (ie. fontchooser button)
2) Gtk 2, Gtk 3 and WinForms all act differently 
3) You won't be able to use all properties of widgets/controls, ie. textbox(winforms) won't have multiline because entry(gtk) doesn't have that option but instead there is a whole another widget called textview
4) There would need to be some kind of bridge between the native UI and MonoGame rendered container which would be very awkward(Threads!!!!)
5) We are forcing the user to learn a new UI which is only useful for the Pipeline Tool

Side Note: I just remembered one very weird thing... Xwt can be embedded in Gtk O o...

**Comment by tomspilman** [comment]
> You know, when you say it like that I can't complain

 I just spent way too many years looking for this ideal toolkit...  it just doesn't exist and likely never will.
 
 This is specifically why we went with a MVC style abstraction.


> The problem with that comes from few things:

Let me be more clear when I say wrapping the GUI.  I don't mean expose every feature of every widget on each platform.

I mean provide a simplified wrapper aimed specifically at the types of things Pipeline plugins would need.  We would provide the basics (button, textbox, dropdowns, etc), expose our existing property grid, and expand and evolve things as reasonable requests come up.

**Comment by cra0zy** [comment]
We can actually use Xwt.

For Gtk it already has both Gtk2 and Gtk3 backends, and can be embedded into a Gtk app.

For WinForms we would need to provide a backend, but it's gonna be faster to do this,  than to write whole UI system from scratch.

**Comment by KonajuGames** [comment]
I found Xwt to be not a very nice alternative.  It appeared good at the
start (wraps native controls, yeah!), but in actual use it fell short in
many ways (doesn't implement this, or that, manages to not look native, and
oh it crashed).​

**Comment by cra0zy** [comment]
> I found Xwt to be not a very nice alternative

I'm not talking about replacing Gtk/Win Forms with Xwt.
What I'm talking about is using Xwt withing Gtk/Winforms for extensions as Widget/Control.

**Comment by cra0zy** [comment]
So at the end of the discussion the extension system should:
 - Have MonoGame render inside the main area (position where the output is currently, will be tabbed)
 - Have ability to use native Widgets/Controls inside the main area
 - Have ability to extend stuff like: Context Menu, Open Application...

Now for native extension widgets I would use Xwt because I could do stuff like:
```c#
var xwt_button = new Xwt.Button("Hello");
Xwt.GtkBackend.GtkEngine ge = new Xwt.GtkBackend.GtkEngine();
var gtk_button = (Gtk.Widget)ge.GetNativeWidget(xwt_button);
```
and get the native Gtk Widget.

I looked into possibilities for WinForms(since Xwt doesn't have that backend), and one possibility is to just use WPF controls inside WinForms.

The above is just for extensions, so that they would have a common GUI api.

@tomspilman @KonajuGames agreeing / disagreeing / objections?

**Comment by tomspilman** [comment]
> Now for native extension widgets I would use Xwt
> one possibility is to just use WPF controls inside WinForms.

Both @KonajuGames and i have repeatedly said this is a bad idea.

We do not need Xwt for any reason.

**Comment by cra0zy** [comment]
> Both @KonajuGames and i have repeatedly said this is a bad idea.
> 
> We do not need Xwt for any reason.

What should be used for GUI system?

**Comment by cra0zy** [comment]
@tomspilman @KonajuGames Pick something:
1) Use Gtk and WinForms separately for GUI
2) Use existing MonoGame GUI system(ie. Empty Keys)
3) Create MonoGame GUI system
4) Use existing multi platform GUI system(ie. Xwt)
5) Create multi platform GUI system
6) Something else

The only one that I am not doing is number 5, reason, that would mean that I would be creating Xwt that is worse than existing Xwt, and that can't be used anywhere but inside MG Pipeline.

**Comment by cra0zy** [comment]
Well, I redesigned the old layout, thought I should post it here:

![redesign](https://cloud.githubusercontent.com/assets/6773302/8118934/57af718a-1092-11e5-9dc2-7f6faf1083e3.png)

**Comment by WardBenjamin** [comment]
:+1: I approve. If it's cross-platform, that'll do well. 

I think Xwt is the correct choice here. It's not a good idea to write a new version of that, it's just another part of Monogame that we'd have to maintain, which means a huge amount of work.

> @tomspilman @KonajuGames Pick something:
1) Use Gtk and WinForms separately for GUI
2) Use existing MonoGame GUI system(ie. Empty Keys)
3) Create MonoGame GUI system
4) Use existing multi platform GUI system(ie. Xwt)
5) Create multi platform GUI system
6) Something else

I think 3 would be really cool, since it could be used in games as well as in our applications. Otherwise, option 4 seems like our only real maintainable choice.

**Comment by cra0zy** [comment]
Most of the stuff have been implemented: https://youtu.be/ThdzkckrJkU

**Comment by cra0zy** [comment]
I've played a bit with integrating SF Editor inside Pipeline Tool... looks nice: http://youtu.be/qDozLRSUnuk

**Comment by cra0zy** [comment]
I uploaded the Spritefont Editor to: https://github.com/cra0zy/SFEditor

If you ever do want it in MonoGame repo, I don't mind moving it.
