### ISSUE TITLE
[MacOS]: GraphicsDevice.Metrics are not being reset.

### ISSUE THREAD

**Issue by kjpou1** [mono/MonoGame#3904]
It looks like the Metrics values are not being reset between rendering presentation.  The only place I see the metrics being reset is here: https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/GraphicsDevice.cs#L490 which MacOSX is not calling.

All other platforms seem to be ok so far.

**Comment by tomspilman** [comment]
@Shqrdx - Got time to fix this.  Seems like MacOS should be fixed to call `Present()` even if it does nothing on that platform.  Like if you look at the Windows8 implementation:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Windows8/MetroGamePlatform.cs#L185

Looks like `MacGamePlatform` doesn't override this and call the graphics device present.  Looking at the implementation:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/GraphicsDevice.OpenGL.cs

... it doesn't look like it would do much on Mac anyway, but it does seem like we are missing some dispose actions in there.

**Comment by Shqrdx** [comment]
I maded simple PR to fix this. I am not sure its good or not(I dont have Mac).

**Comment by kjpou1** [comment]
Verified change works in commit https://github.com/mono/MonoGame/issues/3905

Thanks guys.  Ready to be merged

**Comment by danzel** [comment]
This issue can be closed.
