### ISSUE TITLE
README.md Roadmap implies Monogame is not at version 3 yet

### ISSUE THREAD

**Issue by ryanisaacg** [mono/MonoGame#3915]
"MonoGame 3.0 will mark the start of full support for the entire XNA API."

MonoGame is currently at 3.4, so shouldn't that read: "MonoGame 3.0 **marked** the start of full support for the entire XNA API"?

**Comment by tomspilman** [comment]
That is correct, but i'm going to close this one in favor of the existing issue we have on improving the readme file.  See https://github.com/mono/MonoGame/issues/3846.
