### ISSUE TITLE
graphics change

### ISSUE THREAD

**Issue by DindleBug** [mono/MonoGame#3937]
RESOLVED

When i try to change the resolution in the constructor any changes i made change back to default...  
i tried this in a blank project and had the same issues, i have put the code that i wrote bellow, not that i think it will help...

        public Game1()
            : base()
        {
            graphics = new GraphicsDeviceManager(this);
            Content.RootDirectory = "Content";

            graphics.IsFullScreen = true;
        }

Am i just doing it wrong, sorry if so...

Made a few print screens of it changing as well,

![monoreport](https://cloud.githubusercontent.com/assets/11158981/8164571/c7b1db66-1381-11e5-84b9-5859270de3b6.jpg)

sorry if this is my fault and not a bug

**Comment by cra0zy** [comment]
What project templates are you using?

If you were using WindowsGL, the fullscreen has been fixed in develop branch with #3845(GraphicsDeviceManager.cs always put fullscreen to false for WinGL)

If you are using WindowsDX than it's a bug.

**Comment by DindleBug** [comment]
Thanks for responding.
I was just using "MonoGame Windows Project" so yeah the one using directx.
so just i just use open gl projects for now, will i have to do anything different when making it?

**Comment by DindleBug** [comment]
Ah just downloaded a newer version of monogame and no longer have the issue. I guess i just haven't used it in a while...

**Comment by danzel** [comment]
This can be closed then please :)
