### ISSUE TITLE
iOS SpriteFont Load - End of Stream Exception

### ISSUE THREAD

**Issue by m20tgd** [mono/MonoGame#3940]
I am trying to display text on the screen using Monogame for an iOS project with Xamarin Studio using SpriteFonts. I have converted the .spritefont file to .xnb using the Monogame Pipeline tool.

When I load the font using Content.Load<SpriteFont>("file"), an exception is thrown that reads "Failed to read past end of stream".

I've found lots online of people having issues with loading spritefonts on Monogame, but not this issue in particular.

Can anyone help?

**Comment by KonajuGames** [comment]
I haven't come across an EndOfStreamException when loading a SpriteFont before.  Did you set iOS as the target platform when building the content?

**Comment by m20tgd** [comment]
Yes, I had.

But just tried it all again from scratch and it is now working! Not sure what I was doing wrong before.

Thanks for the help though.

**Comment by danzel** [comment]
This can be closed then please :)
