### ISSUE TITLE
SpriteFont.MeasureString incorrect height

### ISSUE THREAD

**Issue by nkast** [mono/MonoGame#3941]
For a  bitmap Font (Texture) imported both by XNA importer  and MG/MGCB  and the following test code:
```
SpriteFont font;
string ch = " ";
font = content.Load<SpriteFont>("Pages\\Menus\\DialogFont");
System.Diagnostics.Debug.WriteLine(".LineSpacing = " + font.LineSpacing);
System.Diagnostics.Debug.WriteLine(".MeasureString("+ch+") = " + font.MeasureString(ch));
font.LineSpacing += 10;
System.Diagnostics.Debug.WriteLine(".LineSpacing += 10;");
System.Diagnostics.Debug.WriteLine(".LineSpacing = " + font.LineSpacing);
System.Diagnostics.Debug.WriteLine(".MeasureString("+ch+") = " + font.MeasureString(ch));
```

![mgspritefont](https://cloud.githubusercontent.com/assets/3018589/8189345/62f7acd0-1464-11e5-9b29-07d5c1ca8b26.png)

I get the following results:

XNA (XNA xnb)
.LineSpacing = 14
.MeasureString(" ") = {X:13 **Y:18**}
.LineSpacing += 10;
.LineSpacing = 24
.MeasureString(" ") = {X:13 Y:24}
 
MonoGame (XNA xnb)
.LineSpacing = 14
.MeasureString(" ") = {X:13 **Y:18**}
.LineSpacing += 10;
.LineSpacing = 24
.MeasureString(" ") = {X:13 Y:24}

MonoGame ( MGCB xnb)
.LineSpacing = 14
.MeasureString(" ") = {X:13 **Y:14**}
.LineSpacing += 10;
.LineSpacing = 24
.MeasureString(" ") = {X:13 Y:24}

`char ="A";`
MonoGame (XNA xnb)
.LineSpacing = 14
.MeasureString("A") = {X:15 **Y:18**}
.LineSpacing += 10;
.LineSpacing = 24
.MeasureString("A") = {X:15 Y:24}

MonoGame (MGCB xnb)
.LineSpacing = 14
.MeasureString("A") = {X:15 **Y:14**}
.LineSpacing += 10;
.LineSpacing = 24
.MeasureString("A") = {X:15 Y:24}

.
The results under XNA and MG match (Y:18) when using the same .XNB but the height is wrong (Y:14) when using the .XNB imported by MGCB.
Clearly the problem here is in the Font importer.

**Comment by nkast** [comment]
For a .spriteFont (Arial/12) imported both by XNA importer and MG/MGCB, I get the following results:

XNA (XNA xnb)
.LineSpacing = 19
.MeasureString(" ") = {X:4 **Y:20**}
.LineSpacing += 10;
.LineSpacing = 29
.MeasureString(" ") = {X:4 Y:29}

MonoGame (XNA xnb)
.LineSpacing = 19
.MeasureString() = {X:4 **Y:20**}
.LineSpacing += 10;
.LineSpacing = 29
.MeasureString() = {X:4 Y:29}

MonoGame ( MGCB xnb)
.LineSpacing = 18
.MeasureString( ) = {X:4 **Y:18**}
.LineSpacing += 10;
.LineSpacing = 28
.MeasureString( ) = {X:4 Y:28}

**Comment by KonajuGames** [comment]
The spritefont importer will never get the exact same figures because XNA
used the Windows GDI to rasterize the TrueType font and we use FreeType.
There will always be a slight difference.

For the font texture importer, we should be able to get the same result.

**Comment by nkast** [comment]
True, the spritefont renders the fonts to a bitmap so we will never get exactly what XNA do.
I have another larger spritefont and has the same error, that is MeasureString Y return the same value as LineSpacing. 

I found what I think is a misinterpretation of SpriteFont data when it was originally reverse engineered.
I look at what MG Glyph contain when reading old xnb from XNA and xnb from MGCB.
bitmap font from XNA pipeline
Glyph | MeasureString() | .BoundInTexture | .Cropping
-------| ----------------------|-----------------------|--------------
" "     |X:13 Y:18           |125 97 1 1           |12 17 13 18
"A"   |X:15 Y:18           |97 17 14 14           |0 0 15 18
":"    |X:5 X:18           |87 113 4 10           |0 4 5 18
"j"    |X:15 X:18           |1 81 14 14           |0 0 15 18

bitmap font from MGCB
Glyph | MeasureString() | .BoundInTexture | .Cropping
-------| ----------------------|-----------------------|--------------
" "     |X:13 Y:14           |253 49 1 1           |12 17 1 1
"A"   |X:15 Y:14           |210 1 14 14         |0 0 14 14
":"    |X:5 X:14           |199 62 4 10           |0 4 4 10
"j"    |X:15 X:14           |129 33 14 14       |0 0 14 14

The .Copping field has to be two different things.
a top left offset and a size.

The following table makes more sense
Glyph | MeasureString() | .BoundInTexture | .TextureOffset | .glyphSize
-------| ----------------------|-----------------------|----------|---
" "     |X:13 Y:18           |125 97 1 1           |12 17 |13 18
"A"   |X:15 Y:18           |97 17 14 14           |0 0 |15 18
":"    |X:5 X:18           |87 113 4 10           |0 4 |5 18
"j"    |X:15 X:18           |1 81 14 14           |0 0 |15 18

**Comment by KonajuGames** [comment]
Those tables are unreadable.  Need to wrap them in the tags to get fixed width type.

**Comment by KonajuGames** [comment]
Also, you need to make it clear which font import method you are using for these tests: .spritefont file (FontDescription) or font texture.  They are both imported in very different ways.

**Comment by nkast** [comment]
fixed. Git markup need a clear line before the headers.
