### ISSUE TITLE
Request for regular "MonoGame Windows (XAML) Project" template (i.e. not for Windows Store)

### ISSUE THREAD

**Issue by BrainSlugs83** [mono/MonoGame#3950]
This is a feature request and a request for guidance:

-----------------------------------------------------------------------------------------------------------------

In VS2013 there is a "MonoGame Windows Store (XAML) Project" template, which is kind of neat, but it's only there for Windows Store apps.

Allowing XAML in this way is very cool (especially for games or tooling that might make heavy use XAML UI elements, etc.).

However, developing in "app mode" all the time is super annoying, since (at least in Windows 8.1) it forces you to always run full screen, with a slight delay on opening the app, and no easy way to close the apps (alt+f4 is about as good as it gets, everything else involves mouse, and it's really nice while developing to just be able to press ESC and exit the damn thing, but you can't do it -- App.Current.Exit() doesn't even work anymore, it just minimizes the thing).

-----------------------------------------------------------------------------------------------------------------

1.) Can you please make it easy (i.e. include a project template) for developing a regular Windows desktop application with XAML / Monogame? (i.e. "MonoGame Windows (XAML) Project") -- [or otherwise, if you can provide guidance, and I'm able to figure it out, I could submit a pull request...]

2.) It seems this project template is missing all together in VS2015 (other project templates are there, but this one is just plain missing -- might be it's own issue / request, but I thought I'd check here first).

3.) Is it possible to support XAML on other platforms as well (i.e. Linux, Android, etc.)?

4.) Also, somewhat off-topic (I can log another issue, etc. if you like, but hopefully you can just point me  at some quick guidance here?), but the MonoGame slogan "Write once, play everywhere" seems to not be the default state if you're just using the out-of-the-box templates -- in the sense that, I have to create a new solution for each platform I want to support. -- Is there guidance on how to build a single solution with multiple projects in them that all share the same codebase? -- I thought about putting all my engine code into a portable library, but, it would have to reference the mono game DLLs, so it can't be a portable library... right? -- I suppose I could just add the same source files via "Add as a Link" in all the projects -- even then though, what should I do about the content projects? -- **bottom line: Is there official guidance here?**

Thank you! :-)

**Comment by tomspilman** [comment]
>  developing a regular Windows desktop application with XAML / Monogame?

I don't think such a thing exists in Windows 8.x.  The closest thing I guess would be a desktop WPF app... but XAML in WPF isn't the same as XAML on a WinStore app.

> It seems this project template is missing all together in VS2015

VS2015 work isn't done yet.  That said we don't plan to support Win8 development on VS2015... the focus there will be Win10 apps.

> Is it possible to support XAML on other platforms as well (i.e. Linux, Android, etc.)?

No....  XAML is specific to Windows.


> the MonoGame slogan "Write once, play everywhere" seems 

We're working on replacing that slogan... we agree it isn't realistic.  Still haven't decided on a new one yet.


> I suppose I could just add the same source files via "Add as a Link" in all the projects 

Generally that is what I do.  Simple and works on all platforms.

**Comment by BrainSlugs83** [comment]
Thanks for the quick reply.

>The closest thing I guess would be a desktop WPF app... but XAML in WPF isn't the same as XAML on a WinStore app.

Oh dang, I didn't realize it wasn't WPF.  That's what I really want, is to be able to integrate WPF in a desktop app with MonoGame.

I stumbled across this while searching around, and might try it out (in a forum post, somewhere, the author mentioned one of the controls integrates with MonoGame): [https://github.com/tgjones/gemini](https://github.com/tgjones/gemini)

>That said we don't plan to support Win8 development on VS2015... the focus there will be Win10 apps.

I suppose that makes sense. -- On a side note: it sounded like -- from the Build 2015 keynote -- that any Windows Application (even native Win32 applications) will be able to be packaged up as Universal apps -- and that would lead me to think that one could build a WPF/MonoGame hybrid app (like what I'm interested in) and still deploy it as an app on the Windows Store. -- take that with a grain of salt though, as I haven't done any Windows 10 Universal App development yet.

>No.... XAML is specific to Windows.

What about if it was WPF?

>We're working on replacing that slogan... we agree it isn't realistic. Still haven't decided on a new one yet.

Oh, I mean... I actually liked it, and I was just hoping to see the tools / templates mature more in that direction...

>Generally that is what I do. Simple and works on all platforms.

How do you deal with the content projects?  Do you just put relative paths in all of them or something?

**Comment by dsaf** [comment]
> > the MonoGame slogan "Write once, play everywhere" seems

> We're working on replacing that slogan... we agree it isn't realistic. Still haven't decided on a new one yet.

It's not 100% realistic, but it's definitely 95% realistic.

I am not good with marketing, but maybe something along the lines of:

*"let's you focus on what's important"*
*"maximize the code reuse"*
*"universal game code"*
*"the game assembly"*

This is what MonoGame should be aiming for:

http://blog.xamarin.com/porting-existing-.net-apps-to-four-mobile-platforms-with-pcl/

While something like vibration might not be present in every platform, things like Vector2 are universal.

Why can't I have:

*MyGame.Core:*
```csharp

public class Monster
{
    public Vector2 Positon { get; set; }
}
```

*MyGame.Android:*
```csharp

public class AndroidSpecificMonster : Monster
{
/* Android-specific code */
}
```

**Comment by LoveDuckie** [comment]
@dsaf I was about to point to the PCL issue thread myself. :) :+1:

**Comment by dsaf** [comment]
@LoveDuckie that's my biggest wish for the 3.5 release :). I want to increment the number of projects in my solution when adding a new platform support - not multiply them.

**Comment by LoveDuckie** [comment]
@dsaf Yeah, I completely agree. I would also prefer to avoid using compilation statements all over the place with shared projects as well. Makes for much cleaner and less fragile code.

**Comment by dsaf** [comment]
@LoveDuckie my second biggest wish is the introduction of the ```MonoGame.Core.dll``` discussed in  #3405 which would be a PCL library containing never changing highly-portable types such as ```Vector2``` which is one of very few dependencies for useful libraries such as Farseer and https://github.com/Robmaister/SharpNav by @Robmaister.

**Comment by LoveDuckie** [comment]
@dsaf I did read about that and it does make sense. One step at a time, I suppose. 

First we need to demonstrate that the current method of generating PCLs for the Windows library of the Framework is reliable and useable as part of the TeamCity build system.

**Comment by Robmaister** [comment]
@dsaf Yeah that would definitely be good for SharpNav in keeping the NuGet dependencies small. SharpDX is still a much bulkier NuGet package, at ~330MB, though.

**Comment by tomspilman** [comment]
Closing this as Windows has moved on to Windows 10 and UWP projects which work on desktop windows and as fullscreen "metro" style store apps.
