### ISSUE TITLE
Controller support on OS X

### ISSUE THREAD

**Issue by eswick** [mono/MonoGame#3959]
I am having trouble getting controllers working on OS X (10.11).

I have tried both an Xbox One controller using the Xone-OSX driver, and a USB PS4 controller using native support. In both cases, `GamePad.GetCapabilities(PlayerIndex.One).IsConnected` returns `false`. I'm not sure how to go about debugging this issue. Any guidance would be appreciated.

**Comment by KonajuGames** [comment]
As far as I know, no-one else has tried those two controllers on a Mac before with MonoGame.

MonoGame uses the OpenTK on Mac, so we get whatever support OpenTK has for controllers.  From what I know of getting Xbox 360 controllers to work on the Mac, it wasn't a simple task.

**Comment by eswick** [comment]
I've filed an issue with OpenTK. Thank you.
