### ISSUE TITLE
PipelineTool build canceled abruptly with no message

### ISSUE THREAD

**Issue by jamesford42** [mono/MonoGame#3960]
I have on occasion had a build be abruptly canceled with no feedback to me that it occurred, or any error messages. In fact it looks as if it is still building, perhaps hanging within an individual processor. However that is not what is actually happening. Actually it isn't even building anymore, since the 'build' menu item is enabled and 'cancel' is disabled. I do not know how to reliably reproduce this issue but it happens to me from time to time, and building again will skip past what is already built and start on the next item, and continue onward as expected this time.

**Comment by KonajuGames** [comment]
I've seen that while testing my texture content pipeline.  The message won't be passed through, or a failure message won't be listed.

**Comment by cra0zy** [comment]
We could add a message when the MGCB process is ended, and in case there was no success/failed message we could add one.

**Comment by jamesford42** [comment]
Yea. There must be an exception happening somewhere that is terminating mgcb.exe without the reason being routed to output.

**Comment by ChewyMoon** [comment]
Any news on this? I experience this when I add all of my assets (around 40mb) to the project. I also get this error message when I build the solution in VS.

`
The command ""C:\Program Files (x86)\MSBuild\MonoGame\v3.0\Tools\MGCB.exe" /@:"E:\Coding\Projects\C#\Other\Zeroed\Zeroed\Content\Content.mgcb" /platform:Windows /outputDir:"E:\Coding\Projects\C#\Other\Zeroed\Zeroed\Content\bin\Windows" /intermediateDir:"E:\Coding\Projects\C#\Other\Zeroed\Zeroed\Content\obj\Windows" /quiet" exited with code -532462766.	Zeroed		
`

**Comment by cra0zy** [comment]
I'll set up a PR for this in few hours

**Comment by ChewyMoon** [comment]
I have found the issue after running MGCB manually in a command prompt, this is because something in the content project does not have an importer.

```
Unhandled Exception: System.Exception: Couldn't find a default importer for 'E:/
Coding/Projects/C#/Games/Zeroed/Zeroed/Content/Title/KenVector Future Thin.ttf'!

   at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ResolveImporte
rAndProcessor(String sourceFilepath, String& importerName, String& processorName
)
   at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.BuildContent(S
tring sourceFilepath, String outputFilepath, String importerName, String process
orName, OpaqueDataDictionary processorParameters)
   at MGCB.BuildContent.Build(Int32& successCount, Int32& errorCount)
   at MGCB.Program.Main(String[] args)
```

**Comment by jamesford42** [comment]
IMO the pipeline tool needs to capture and output any exception which occurs within mgcb causing it to close. That is the proper fix for this issue, not fixing an mgcb individual crash.

**Comment by tomspilman** [comment]
> IMO the pipeline tool needs to capture and output any exception which occurs within mgcb causing it to close.

You cannot capture an exception in a child process from the calling process.  For this reason #3998 helps as it handles another possible exception and reports the error for us which is the best possible conclusion to issues like this.

Still as @cra0zy mentioned in https://github.com/mono/MonoGame/pull/3986 there are exceptions that cannot be captured or handled... even by the app itself.  The application will just fail out with an error code.  This is where the Pipeline tool needs to correctly capture the MGCB process exit code and report a fatal failure when it occurs.
