### ISSUE TITLE
PixelBitmapContent.TryCopyTo between Vector4/Color/etc pixel types

### ISSUE THREAD

**Issue by jamesford42** [mono/MonoGame#3964]
The current implementation of PixelBitmapContent.TryCopy to only works if the source and destination are both `PixelBitmapContent<T>` where T is the same type.

This is not a bug, its just an incomplete implementation of the original XNA feature-set. It shouldn't be all that difficult to add transformation from one pixel type to another (thought there are quite a few type conversions to be handled).

Eg, for source `PixelBitmapContent<SrcT>` and destination `PixelBitmapContent<DstT>` ... convert srcPixel from SrcT to DstT, then set as dstPixel.

**Comment by KonajuGames** [comment]
I have this implemented in a feature branch. Currently finalising things so
it works correctly on all desktop platforms.

**Comment by KonajuGames** [comment]
This all works as expected now.
