### ISSUE TITLE
Android: Support ImmersiveSticky

### ISSUE THREAD

**Issue by danzel** [mono/MonoGame#3974]
```SYSTEM_UI_FLAG_IMMERSIVE_STICKY``` was added in Android 4.4, it allows apps to take over the whole screen and hide the soft keys.
ref https://developer.android.com/training/system-ui/immersive.html

You can enable this in your Android app using this:
```c#
var view = (Android.Views.View)g.Services.GetService(typeof(Android.Views.View));
view.SystemUiVisibility = (StatusBarVisibility)(SystemUiFlags.LayoutStable | SystemUiFlags.LayoutHideNavigation | SystemUiFlags.LayoutFullscreen | SystemUiFlags.HideNavigation | SystemUiFlags.Fullscreen | SystemUiFlags.ImmersiveSticky);
```

But if you do it with monogame you end up with your game still rendering at the non full screen size, with gaps above and below (filled with the Clear'd color).

I've done a bit of searching, it looks like we need to probably use the sizes that get passed in to onSurfaceChanged rather than the ones we fetch in AndroidGameWindow.Initialize
http://stackoverflow.com/questions/20555083/android-gl-screen-size-in-immersive-mode
https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Android/AndroidGameWindow.cs#L47

I'm not sure exactly how we should touch the rest of the system to make it work best.
I'm thinking if the user sets ```GraphicsDeviceManager.IsFullScreen = true;```, then we should try set ImmersiveSticky.
Then we can update GraphicsDeviceManager.ResetClientBounds to update PreferredBackBufferWidth/Height based on what we receive in OnSurfaceChanged.
https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/GraphicsDeviceManager.cs#L593

Thoughts?
Has anyone else tackled this yet?

**Comment by danzel** [comment]
I have a commit up over here that seems to make this work:
https://github.com/danzel/MonoGame/commit/72efdae0d6b947a88def6268d4167aa69029e3e7

If the user adds the SystemUiVisibility setting to their Activity1.OnCreate method then we'll set the view up correctly full screen.

We probably want to move setting this in to monogame, I'm not sure where though.

Will do more testing, feedback appreciated.

**Comment by Nezz** [comment]
I have fixed this some time ago:
https://github.com/mono/MonoGame/pull/3560/files

Did someone break it in the meantime?

**Comment by tomspilman** [comment]
@Nezz - Your changes from that PR are still intact...  maybe some other code changed or something in Xamarin.Android that broke it.

**Comment by danzel** [comment]
I am working on a slightly old fork, looks like I branched 5 days before this was merged.
I'll close this and update to master when I have time. I expect it works as you say. Thanks!

**Comment by Nezz** [comment]
I hope everything will work. You are welcome :)
