### ISSUE TITLE
Consider adding the effect compilation API to the framework

### ISSUE THREAD

**Issue by rds1983** [mono/MonoGame#3979]
Hi,
As far I understand, right now, if you want to use an FX in your game, then it has to go through the Content Pipeline, which will preprocess all macroses according to the Processor's Defines settings.
Such behavior is problematic if you have many defines in your FX code(which is often true for 3d engines), as you have to make an effect for every possible defines' set.
Therefore I propose to add the Effect compilation API to the framework.
Roughly speaking, I mean the addition of the function that takes FX code as input and produces the Effect bytecode as result.
Like following:
```c#
byte[] simpleEffectByteCode = EffectUtils.Compile(Resources.MyShader, string.Empty);
Effect simpleEffect = new Effect(device, simpleEffectByteCode);
byte[] lightningEffectByteCode = EffectUtils.Compile(Resources.MyShader, "LIGHT=1");
Effect lightningEffect = new Effect(device, lightningEffectByteCode);
```

**Comment by Nezz** [comment]
AFAIK shader compilation requires Windows desktop, so it simply wouldn't work on any other platform.

**Comment by rds1983** [comment]
Yeah, that is the problem.
Well, then another approach is to use multi compile approach(as in Unity).
It means adding special instruction to FX(such as #pragma multi_compile LIGHTS_ON LIGHTS_OFF). And making 2MGFX/Content Pipeline compile FX into special MultiCompileEffect with all possible variant compiled. MultiCompileEffect, in it's turn, will be a factory for ordinary Effects.
In code it'll look like this:
FX:
```hlsl
#include "Macros.fxh"

#pragma multi_compile LIGHTS_ON LIGHTS_OFF

BEGIN_CONSTANTS

#ifdef LIGHTS_ON
float3 dirLight0Direction;
float4 dirLight0DiffuseColor;
#endif

MATRIX_CONSTANTS

float4x4 worldViewProj;
float3x3 worldInverseTranspose;
float4 diffuseColor;

END_CONSTANTS

struct VSInput
{
    float4 Position : SV_Position;
#ifdef LIGHTS_ON
    float3 Normal   : NORMAL;
#endif
};

struct VSOutput
{
    float4 PositionPS : SV_Position;
    float4 Color: COLOR;
};

VSOutput VertexShaderFunction(VSInput input)
{
    VSOutput output;

    output.PositionPS = mul(input.Position, worldViewProj);

#ifdef LIGHTS_ON
    float3 normal = mul(input.Normal, worldInverseTranspose);
    float lightIntensity = dot(-normal, dirLight0Direction);
    output.Color = float4(saturate(dirLight0DiffuseColor * lightIntensity));
#endif

    return output;
}

float4 PixelShaderFunction(VSOutput input) : SV_Target0
{
#ifdef LIGHTS_ON
	return diffuseColor * input.Color;
#else
    return diffuseColor;
#endif
}

TECHNIQUE(Default, VertexShaderFunction, PixelShaderFunction);
```

C#:
```c#
MultiCompileEffect mcEffect = Content.Load<MultiCompileEffect>("MyEffect");
Effect simpleEffect = mcEffect.Create(new [] {"LIGHTS_OFF");
Effect lightningEffect = mcEffect.Create(new [] {"LIGHTS_ON"});
```

**Comment by tomspilman** [comment]
> Well, then another approach is to use multi compile approach(as in Unity).

Right... offline pre-compile of all needed variants is the best approach.

This should be fairly easy to do with a custom processor which internally calls the default `EffectProcessor`.

**Comment by rds1983** [comment]
Thanks for the help. I'll make such processor.
First testing revealed that there may be a compilation performance issue in the distant future.
Compiling above FX code 1000 times took about 3 mins on my box(core i5 2400).
I had looked over the EffectProcessor code and would like to propose small optimization.
Tools/2MGFX/ShaderInfo.cs has following line:
            var tree = new Parser(new Scanner()).Parse(newFile, fullPath);
which is performance hit, as it creates new parser and scanner each time. I've made Parser static created only once and the above test time downed to 30 seconds(6x improvement).

**Comment by tomspilman** [comment]
Note that shader compiling will never be extremely fast as the MS HLSL compiler under the hood is itself pretty slow.  This is one big reason you don't compile shaders on demand at runtime.

**Comment by rds1983** [comment]
Yeah. On the other hand, if you have thousands of shader variants, precompiling it may be problematic in terms of time and size.
It was quite interesting to read how Unity developers face that problem: http://blogs.unity3d.com/ru/2014/05/06/shader-compilation-in-unity-4-5/

Anyway multi variant shaders processor should be enough for my task(simple 3D Engine based on Monogame).

**Comment by ala53** [comment]
Regarding a multi-platform FX compiler, MojoShader (which MonoGame uses and which is cross platform) said:
```
Work is in progress to allow MojoShader to work as a replacement stack for the D3DX shader tools. The library already provides a preprocessor and an assembler to generate bytecode from low-level source, and construction of a full HLSL compiler is in progress.
```
Perhaps that functionality can be integrated? It would definitely be a "beta"-esque feature, and probably better suited for MonoGame 4.0, but seems possible: compile the shader to bytecode using MojoShader and if on windows, just load the bytecode shader. If on any other platform, have MojoShader recompile it to GLSL and then pass that to the driver.

**Comment by tomspilman** [comment]
@ala53 - [That message is from 2009](https://web.archive.org/web/20090208212357/http://icculus.org/mojoshader/)... not sure how accurate it is anymore.

**Comment by ala53** [comment]
Well then, somebody needs to update their website.

How about something a bit more modern? https://github.com/unknownworlds/hlslparser
It can parse HLSL at the source code level and convert it to GLSL. The best possibility I can think of is this: have two platform backends. One uses the SharpDX shader compiler on Windows and it will work as expected while the other uses the HLSL parser project to convert the code and then upload it to the driver. Unfortunately, said project would only support the desktop versions of MonoGame because HLSLParser doesn't support GLSL ES and additionally, it would only support DX9 on OpenGL platforms.

**Comment by tomspilman** [comment]
> It can parse HLSL at the source code level and convert it to GLSL.

That is the eventual plan.

**Comment by rds1983** [comment]
Meanwhile, I've made draft version of the Monogame's multi compile effect library:
https://github.com/rds1983/MonoGame.MultiCompileEffects
Hopefully, it'll be useful for someone other than me.

**Comment by tomspilman** [comment]
Thanks for linking that @rds1983 .  I'm going to close this issue now and recommend your solution if this comes back up.
