### ISSUE TITLE
MGCB - TextureImporter fails since upgrade to 3.5.0.344

### ISSUE THREAD

**Issue by AquilaAbriel** [mono/MonoGame#4000]
I recently upgraded the Monogame sdk to version 3.5.0.344 but now the content pipeline tool won't build nor rebuild my games content anymore.

MBCB settings:
/outputDir:bin
/intermediateDir:obj
/platform:Windows
/config:
/profile:HiDef
/compress:False

Content:
#begin Shader/blurGauss.fx
/importer:EffectImporter
/processor:EffectProcessor
/processorParam:DebugMode=Auto
/build:Shader/blurGauss.fx

#begin Textures/Animation/anms_sea_level_1.png
/importer:TextureImporter
/processor:TextureProcessor
/processorParam:ColorKeyColor=255,0,255,255
/processorParam:ColorKeyEnabled=True
/processorParam:GenerateMipmaps=False
/processorParam:PremultiplyAlpha=True
/processorParam:ResizeToPowerOfTwo=False
/processorParam:MakeSquare=False
/processorParam:TextureFormat=Color
/build:Textures/Animation/anms_sea_level_1.png
...

Shader compilation seems to work fine. (Are finished without any errors)
But texture compiling results in the following error:

>Importer 'TextureImporter' had unexpected failure!
>System.NullReferenceException

>Microsoft.Xna.Framework.Content.Pipeline.TextureImporter.Import(String filename, ContentImporterContext context)

>Microsoft.Xna.Framework.Content.Pipeline.ContentImporter`1.Microsoft.Xna.Framework.Content.Pipeline.IContentImporter.Import(String filename, ContentImporterContext context)

>MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent(PipelineBuildEvent pipelineEvent)

This error messages repeats for every texture content within my content project...

What I tried:
-Uninstall and reinstall Monogame sdk
-Delete and recreate mgcb project

I would appreciate any help or advice from your side...
I know it's a unstable version of the sdk. I switched to a newer version to track down
another problem I encountered while working on my project and wanted to know
if this problem might be already fixed.

Let me know if you need any further information...

**Comment by Vodacek** [comment]
I have the same issue! Some PNG files have only 8 bits per pixel. Exception is thrown from here: https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework.Content.Pipeline/TextureImporter.cs#L246
as the face is null. Workaround is simple. Open image in MS Paint and save it (even without any change). Image is saved with 32 bits per pixel and it is loaded correctly :-)

**Comment by KonajuGames** [comment]
Thanks for the explanation, @Vodacek .  That will help greatly in implementing the fix.

**Comment by AquilaAbriel** [comment]
Thank you Vodacek,
I tried different color codings, but texture importer still fails to compile them...
Greyscale saved from photoshp -> failed
8bit per channel saved from photoshop -> failed
16bit per channel saved from photoshop -> failed
png saved from ms paint -> failed

Rescaled to power of 2 -> failed
Rescaled to square and power of 2 -> failed

I could not find any setting that would result in a successful compilation...

**Comment by KonajuGames** [comment]
I can replicate this. Works on Mac.  Fails on Windows.  I have been trying to debug it, but it will have to wait until tomorrow night to finish it.

**Comment by AquilaAbriel** [comment]
Ok, thanks for your reply.
Up to version 3.5.0.341 texture compiling worked as expected.
From my point of view something broke in version 344.
Thank you for your support. Looking forward to next release.

**Comment by KonajuGames** [comment]
It appears to be something with the latest version of FreeImage on Windows
that was included as part of that update.

**Comment by KonajuGames** [comment]
This should be fixed now in latest.
