### ISSUE TITLE
Input - GetVirtualButtons() incorrectly reports LeftThumbstickDown all the time

### ISSUE THREAD

**Issue by kvenkateshan** [mono/MonoGame#4001]
private Buttons GetVirtualButtons () {
            var result = Buttons.buttons;
            var sticks = ThumbSticks;
            
            if (sticks.Left.X < 0)
                result |= Microsoft.Xna.Framework.Input.Buttons.LeftThumbstickLeft;
            else if (sticks.Left.X > 0)
                result |= Microsoft.Xna.Framework.Input.Buttons.LeftThumbstickRight;
            
            if (sticks.Left.Y < 0)
                result |= Microsoft.Xna.Framework.Input.Buttons.LeftThumbstickDown;
            else if (sticks.Left.Y > 0)
                result |= Microsoft.Xna.Framework.Input.Buttons.LeftThumbstickUp;
            
            if (sticks.Right.X < 0)
                result |= Microsoft.Xna.Framework.Input.Buttons.RightThumbstickLeft;
            else if (sticks.Right.X > 0)
                result |= Microsoft.Xna.Framework.Input.Buttons.RightThumbstickRight;
            
            if (sticks.Right.Y < 0)
                result |= Microsoft.Xna.Framework.Input.Buttons.RightThumbstickDown;
            else if (sticks.Right.Y > 0)
                result |= Microsoft.Xna.Framework.Input.Buttons.RightThumbstickUp;
            
            return result;
        }

**Comment by tomspilman** [comment]
Is this maybe related to https://github.com/mono/MonoGame/issues/3614 ?

**Comment by kvenkateshan** [comment]
Exactly the same!

**Comment by tomspilman** [comment]
That is fixed in the develop branch and seems to be in the 3.4 release.  Maybe you just need to update your fork of MonoGame?

**Comment by kvenkateshan** [comment]
I do see the changes locally..

// TODO: this needs adjustment. Very naive implementation. Doesn't match XNA yet
            var result = (Buttons)0;
            if (thumbX < -deadZone)
                result |= thumbstickLeft;
            if (thumbX > deadZone)
                result |= thumbStickRight;
            if (thumbY < -deadZone)
                result |= thumbStickUp;
            else if (thumbY > deadZone)
                result |= thumbStickDown;
            return result;

**Comment by tomspilman** [comment]
Leave a comment
