### ISSUE TITLE
XNA test project is not working after last texturing commit

### ISSUE THREAD

**Issue by Shqrdx** [mono/MonoGame#4009]
I mean MonoGame.Tests.XNA is not compilable after https://github.com/mono/MonoGame/pull/3991. There is a bunch of errors. Even after muting it a bit the func called CompressDefault is not correctly working

![image](https://cloud.githubusercontent.com/assets/3036176/8753528/28ffb6de-2cc5-11e5-956e-ee426000b04b.png)

(TextureProcessorOutputFormat.Compressed is not exist in XNA)

**Comment by tomspilman** [comment]
@KonajuGames - ?

**Comment by KonajuGames** [comment]
That looks like a good change.  XNA doesn't have `TextureProcessorOutputFormat.Compressed`, so the XNA-specific change to use `DxtCompressed` instead should be ok.

**Comment by Shqrdx** [comment]
If you see the screenshot above the test is failed, after this change.
It is the issue.. not PR,

**Comment by Shqrdx** [comment]
@KonajuGames What you or Tom suggest to do ?

**Comment by KonajuGames** [comment]
I didn't understand what that second screenshot was trying to show.  I don't have XNA installed any more, so I can't run the XNA version of the tests.

**Comment by Shqrdx** [comment]
The NUnit test failed at CompressDefaultWindowsCutOut

**Comment by Shqrdx** [comment]
Should we just exclude it from xna test ?

**Comment by Shqrdx** [comment]
Ok, I created a fix, if Tom accept it this issue will be closed.

**Comment by KonajuGames** [comment]
Which condition is failing in the Dxt3 test?  Is that the one causing problems?  The iOS and Android compression tests also need to be excluded, which you have done in that PR.  I'd like the DXT tests to pass on XNA.

**Comment by Shqrdx** [comment]
Assert.IsAssignableFrom<T>(output.Faces[0][0]); at CompressDefault in CompressDefaultWindowsCutOut

**Comment by Shqrdx** [comment]
@KonajuGames So, how you suggest to fix it ?

**Comment by tomspilman** [comment]
@KonajuGames - Did I merge #4012 too soon?

**Comment by KonajuGames** [comment]
It's not major, but I'd like to work out why that assert is failing.  Though without XNA installed that might be interesting...

**Comment by Shqrdx** [comment]
If these test was changed in past, as it show in the error screenshot above, than overall behavior could differs from XNA, even if 2 test in "#if !XNA" block worked correctly it doesn mean they are real correct.
