### ISSUE TITLE
How to properly cap FPS in Monogame?

### ISSUE THREAD

**Issue by uzyfeo** [mono/MonoGame#4013]
I wanted to cap FPS of my game at 30fps conditionally if being built for Windows Phone, as I don't need it to be running at 60fps on it and I heard from too many it is better to have it capped on mobile device because of battery draining.

I used same snippet of code used by XNA for Windows Phone 7:

```
//FrameRate is 30fps by default for WindowsPhone.
TargetElapsedTime = TimeSpan.FromTicks(333333);
```

But... As it is doing its job capping FPS, it is affecting everything else too, causing stuttering and sound issues. Because of this, I suppose I'm doing something wrong.

Anything which would help me would be great, as I was not able to find anything on the internet regarding this "issue" (most people wanted quite the opposite :D )

BTW... Sorry if I sound stupid but this is first time I'm working with Monogame/XNA on some project :)

**Comment by tomspilman** [comment]
What platform are you having this problem on?

**Comment by uzyfeo** [comment]
Windows Phone 8.1

**Comment by uzyfeo** [comment]
Isn't it like I'm handling the code wrong? 

Cause I'm starting to think that I understood the above command wrongly. 

I thought it should slow down the tick rate by which Drawing is performed, but now I'm starting to think it is affecting Game's tick rate, rather than Drawing rate... In this case, my Update method is wrong, as it is kind of counting on 60 ticks... 

I'm using elapsed GameTime for updating every variable, but this will be like 2x bigger now, which could cause the "stutter" and audio not playing correctly, as audio playing/stopping/pausing is being updated with objects, so some are "skipping" or doing other things incorrectly... And objects are being drawn twice the distance...

So... What could I do to somehow trick this? Cause I need it to at least look smooth and I'm not that skilled with MonoGame right now... Could use some help...

(Probably Help Wanted label is appropriate for this "issue"...)

**Comment by nkast** [comment]
try something like this: 

```
void Game()
{
//..
            TargetElapsedTime = TimeSpan.FromTicks(333333);
            GraphicsDeviceManager.PreparingDeviceSettings += new EventHandler<PreparingDeviceSettingsEventArgs>(graphics_PreparingDeviceSettings);
}

        void graphics_PreparingDeviceSettings(object sender, PreparingDeviceSettingsEventArgs e)
        {
            e.GraphicsDeviceInformation.PresentationParameters.PresentationInterval = PresentInterval.Two;
        }
```

**Comment by uzyfeo** [comment]
It seems like it is doing no difference unfortunately :(

**Comment by theZMan** [comment]
Your API call is correct.

The tick affects the tick of the entire game - so update AND draw are called at 30fps. So yes animation will not be quite as smooth. Physics may behave slightly differently but as long as you used Elapsed time then it will move things the same speed. And yes in general its a good idea to target a lower FPS to save battery.

Other than starting/stopping sound the actual 'playing' of the sound should be done by the OS or a background thread on whatever platform so the frame rate shouldn't cause sound problem.

So this might be a platform issue. Can you try to make a repro - something simple e.g. Bounce a single sprite around the screen while playing some sounds. Make it so that a screen touch switches from 60fps to 30fps

**Comment by nkast** [comment]
Well, try to set `TargetElapsedTime = TimeSpan.FromTicks(166666); //60fps` to get updates at 60fps and  `PresentationInterval = PresentInterval.Two` to sync draw at 30fps.

**Comment by uzyfeo** [comment]
@theZMan Sound is playing fine, I was reffering to my Update function not playing/stopping/pausing like it should with lower tick rate so there is no needs for tests - playback is fine!
@nkast Now it is working how fine, thanks :+1:
