### ISSUE TITLE
Setting `GraphicsDevice.Viewport` behaves differently in DX to GL

### ISSUE THREAD

**Issue by craftworkgames** [mono/MonoGame#4018]
I found a bug that could be related to #3572 #3386 and #1683 but none of those seem to describe the issue the way I'm seeing it. I've managed to reproduce a minimum sample to prove it.

Here's the code:

    public class Game1 : Game
    {
        private GraphicsDeviceManager _graphics;
        private SpriteBatch _spriteBatch;
        private Texture2D _texture;

        public Game1()
        {
            _graphics = new GraphicsDeviceManager(this);
            Content.RootDirectory = "Content";
            Window.AllowUserResizing = true;
        }

        protected override void LoadContent()
        {
            _spriteBatch = new SpriteBatch(GraphicsDevice);
            _texture = Content.Load<Texture2D>("hills.png");
        }

        protected override void UnloadContent()
        {
        }

        protected override void Update(GameTime gameTime)
        {
            if (GamePad.GetState(PlayerIndex.One).Buttons.Back == ButtonState.Pressed || Keyboard.GetState().IsKeyDown(Keys.Escape))
                Exit();

            base.Update(gameTime);
        }

        protected override void Draw(GameTime gameTime)
        {
            GraphicsDevice.Viewport = new Viewport(50, 50, 400, 300);
            GraphicsDevice.Clear(Color.CornflowerBlue);

            _spriteBatch.Begin();
            _spriteBatch.Draw(_texture, new Vector2(-200, -200));
            _spriteBatch.End();

            base.Draw(gameTime);
        }
    }

Nothing particularly special going on here. I'm drawing a single large sprite and setting the `Viewport` property as shown in the [MSDN example](https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.graphics.graphicsdevice.viewport.aspx)

The problem is, when referencing the `MonoGame.Framework.WindowsGL` NuGet package I get different behaviour to referencing the `MonoGame.Framework.WindowsDX` NuGet package.

## WindowsGL

Before window resize:
![image](https://cloud.githubusercontent.com/assets/3201643/8776145/432bf9cc-2f32-11e5-9234-8dbcdd27f792.png)

After window resize:
![image](https://cloud.githubusercontent.com/assets/3201643/8776154/4d83a8b6-2f32-11e5-9871-fee69c386c08.png)

## WindowsDX

Before window resize:
![image](https://cloud.githubusercontent.com/assets/3201643/8776145/432bf9cc-2f32-11e5-9234-8dbcdd27f792.png)

After window resize:
![image](https://cloud.githubusercontent.com/assets/3201643/8776180/74c12610-2f32-11e5-9dba-1b024a0c4414.png)

**Comment by tomspilman** [comment]
Thanks for the great test case @craftworkgames !

We need to test this on plain desktop XNA as well and make sure we're doing the correct fix.

**Comment by KonajuGames** [comment]
@cra0zy has a PR #4007 to correct this, with some discussion in there.

**Comment by cra0zy** [comment]
> has a PR #4007 to correct this, with some discussion in there.

No... it's not to correct this... WindowsDX is the one with the bug here, and I am correcting some stuff in WindowsGL.

At start I thought WindowsGL was the one with the bug sine I haven't used Xna in a long time, but @dellis1972  warned me in time.

**Comment by tomspilman** [comment]
> WindowsDX is the one with the bug here

We need to be 100% certain of this.  Not what @dellis1972 or anyone else said.

This means running the same test under XNA on a Windows machine.  There is no substitute for that.

**Comment by cra0zy** [comment]
> We need to be 100% certain of this. Not what @dellis1972 or anyone else said.

I installed the Xna once @dellis1972 warned me to test it out, Xna does what WindowsGL does, WindowsDX has a bug.

**Comment by tomspilman** [comment]
Tried @craftworkgames test on XNA and got this:

![cap](https://cloud.githubusercontent.com/assets/103522/8796222/afbace9e-2f58-11e5-82e0-8306e03bc8a7.JPG)

@craftworkgames - Can you share your `hills.png` so I can be sure this isn't an image size issue.

**Comment by cra0zy** [comment]
Xna window resize: http://youtu.be/mJZSBSayoKs

**Comment by craftworkgames** [comment]
> @craftworkgames - Can you share your hills.png so I can be sure this isn't an image size issue.

Yes of course. Here's the full image in the original size (2048x1536). I better give it attribution. It's one of the free assets on [GameDevMarket.net](https://www.gamedevmarket.net/asset/simple-hills-background-1030/?ally=yJRl98tX)

![hills](https://cloud.githubusercontent.com/assets/3201643/8797823/5033be98-2fe1-11e5-8435-dc9fb035849d.png)

**Comment by craftworkgames** [comment]
To give a little context about how I found this bug I'll tell you the story.

I'm currently working on the [MonoGame.Extended](https://github.com/craftworkgames/MonoGame.Extended) library and I tried [introducing unit tests](http://dylanwilson.net/writing-unit-tests-with-monogame-is-difficult) into the project but had issues unit testing against the GL version so I switched to the DX version. 

In the process, some of the code broke when setting the `GraphicsDevice.Viewport` property. That's when I created this bug report. I couldn't actually figure out a way to to get the DX version to work at all. 

The behavior of the bug makes it very difficult to achieve [Letterboxing / pillarboxing resolution independence](http://dylanwilson.net/resolution-independence-in-monogame-with-viewport-adapters) so as far as I can tell the DX version is definitely broken.

While I'm working on MonoGame.Extended I'll be do some cross platform testing the DX and GL versions. Maybe it'll turn up more bugs. I should probably install XNA too but I haven't done that for a long time (is it even possible on Windows 8?)

**Comment by uzyfeo** [comment]
Yes, it is! I didn't tried to install it directly from Microsoft, but from here.. https://mxa.codeplex.com/

There it is available for multiple Visual Studios versions, not only 2010 release.

**Comment by theZMan** [comment]
Yes XNA works on Windows 8 (and 10) - you need to install VS2010 and possibly use this workaround http://blogs.msdn.com/b/astebner/archive/2012/02/29/10274694.aspx

I can't reccomend https://mxa.codeplex.com/ since its a 3rd party repackaging the Microsoft installer and who knows what else you get along with it. But it is the only way to make it work without VS2010. Do it at your own risk!

**Comment by uzyfeo** [comment]
I must agree with you with that 3rd party statement, but I had to write about it here, as it minimally helped me to install it on my Win8.1 computer without any problems + I didn't had to install another VS just for XNA :)

**Comment by craftworkgames** [comment]
I've run into this again recently and it's pretty annoying.

@tomspilman You tried this on XNA back in July and it was clearing different. Did you ever figure out what XNA does?

**Comment by cra0zy** [comment]
Xna does the same thing as WindowsGL... I literally posted a video above...

**Comment by craftworkgames** [comment]
Thanks @cra0zy. It's confirmed then. So it needs to be fixed in the DX version?

I heard a rumor that the DX version was going to be dropped in favor of doing everything in GL?

**Comment by tomspilman** [comment]
> I heard a rumor that the DX version was going to be dropped in favor of doing everything in GL?

That isn't possible.  There are platforms we support that are DX only.

There is work on a unified Desktop OpenGL platform targeting Windows/Mac/Linux on one set of binaries.  But the Windows with DirectX path will still be there.

**Comment by craftworkgames** [comment]
Okay good to know. I'll take a closer look at fixing this bug later in the week then.

**Comment by craftworkgames** [comment]
I finally got around to taking a closer look at this and I've made some progress.

It turns out that [line 654](https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Game.cs#L654) of Game.cs is overwriting the Viewport property of the GraphicsDevice *after* the viewport has been set by the user.

I found this by creating 2 identical Game projects with one of them referencing the MonoGame DX source and the other referencing MonoGame GL. The GL one behaves as expected and the DX one is broken.

I set the Viewport property in the ClientSizeChanged event of the Window in my Game1.cs constructor.

    Window.ClientSizeChanged += (sender, args) =>
    {
        GraphicsDevice.Viewport = new Viewport(100, 100, 300, 300);
    };

If I comment out the Viewport assignment in the MonoGame Game.cs class the problem goes away.

     var viewport = new Viewport(0, 0,
         GraphicsDevice.PresentationParameters.BackBufferWidth, 
         GraphicsDevice.PresentationParameters.BackBufferHeight);

     //GraphicsDevice.Viewport = viewport;
     Platform.EndScreenDeviceChange(string.Empty, viewport.Width, viewport.Height);

Unfortunately, this code is shared between all platforms so doing this runs the risk of breaking something else. I don't understand why this code was put here in the first place.

Another part to the problem that I haven't yet investigated could be that the ClientSizeChanged event is firing too early, or in the wrong order. That could explain why GL and DX behaves differently.

**Comment by cra0zy** [comment]
Isn't https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Windows/WinFormsGameWindow.cs#L391 causing the issue?

**Comment by craftworkgames** [comment]
@cra0zy That look promising. I can't see any reason why that `#if` should exist.

**Comment by craftworkgames** [comment]
Looks like we have a [workaround](https://github.com/craftworkgames/MonoGame.Extended/pull/96) in MonoGame.Extended for this issue at least. Hopefully it'll be fixed in the MonoGame 3.5 release.

**Comment by JoshuaLamusga** [comment]
BoxingViewportAdapter has a constructor that references this issue like it's an open problem. That should be fixed.

**Comment by Jjagg** [comment]
@JoshuaLamusga Please open an issue or pull request in MonoGame.Extended. MonoGame.Extended is not maintained by the MonoGame Team.

**Comment by JoshuaLamusga** [comment]
Whoops, forgot this was a MG not MGE thread.
