### ISSUE TITLE
what is ThumbStickDefinition ?

### ISSUE THREAD

**Issue by Shqrdx** [mono/MonoGame#4028]
Could I remove https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Input/ThumbStickDefinition.cs in next PR ?

**Comment by tomspilman** [comment]
Yuck... yeah I think so.  I suspect it was part of a virtual thumbstick implementation for iOS which we had in the early days.  None of that code is left except for this it seems.

**Comment by Shqrdx** [comment]
this should fix it - https://github.com/mono/MonoGame/pull/4029
