### ISSUE TITLE
DirectX and OcclusionQuery

### ISSUE THREAD

**Issue by Skeatwin** [mono/MonoGame#4033]
I try to do the lens flare effect in my game (see http://xbox.create.msdn.com/en-US/education/catalog/sample/lens_flare), and that use the OcclusionQuery class.
And after long tests, I found OcclusionQuery dosn't work on DirectX platform, the result of PixelCount is always 0 and the IsComplete property is always set to False.

I hope that you can help me, thanks :smile: 

Here is a part of the code:

if (this.occlusionQueryActive == true)
            {
                // If the previous query has not yet completed, wait until it does.
                if (!this.occlusionQuery.IsComplete)
                    return;

                this.occlusionAlpha = Math.Min(occlusionQuery.PixelCount / OCCLUSION_QUERY_AREA, 1f);
            }

            // Set renderstates for drawing the occlusion query geometry. We want depth
            // tests enabled, but depth writes disabled, and we disable color writes
            // to prevent this query polygon actually showing up on the screen.
            this.GraphicsDevice.BlendState = BlendStateExtended.ColorWriteNone;
            this.GraphicsDevice.DepthStencilState = DepthStencilState.DepthRead;

            // Set up our BasicEffect to center on the current 2D light position.
            this.basicEffect.World = Matrix.CreateTranslation(lightPosition.X, lightPosition.Y, 0);
            this.basicEffect.Projection = Matrix.CreateOrthographicOffCenter(0, viewport.Width, viewport.Height, 0, 0, 1);

            this.basicEffect.CurrentTechnique.Passes[0].Apply();
            this.occlusionQuery.Begin();
            this.GraphicsDevice.DrawUserPrimitives(PrimitiveType.TriangleStrip, occlusionQueryVertices, 0, 2);
            this.occlusionQuery.End();
            this.occlusionQueryActive = true;

**Comment by Vodacek** [comment]
yes, this is because OcclusionQuery is implemented only at OpenGL platforms

**Comment by Skeatwin** [comment]
Thank for your reply I will waiting the implementation :)

**Comment by ShyroFR** [comment]
Awesome, thanks!

**Comment by Skeatwin** [comment]
Great work ! thanks Monogame ! :)
