### ISSUE TITLE
Draw timing issue when Nvidia 3D Vision is activated - workaround included

### ISSUE THREAD

**Issue by wulf21** [mono/MonoGame#4035]
## Introduction

First of all I want to point out that this issue may be more important than you may think at first because it may happen in every monogame, even if it's pure 2D. Even worse, a usual player that owns 3D Vision may not even have the idea that the graphic glitches he is seeing may be related to 3D Vision, he forgot to deactivate.

## Symptoms

So now for the issue itself. After experiencing random graphic glitches I wrote a sample code as simple as possible (see below). In order to run it you will need

1. a new plain Windows Desktop monogame project
2. a resource file named "pixel.xnb" which is a 2D-Texture that simply contains a single black pixel.

What it does is to draw a horizontal black line with a height of 5 pixels on a white background and move it vertical in steps of 5 pixels every frame. Works perfectly with 3D Vision deactivated but if 3D Vision kicks in the following happens:

![timingglitch](https://cloud.githubusercontent.com/assets/13534999/8926879/966c40c4-3513-11e5-91e5-6c76f57c98c8.jpg)

It turned out that it was impossible to get a regular screenshot from the glitch, so I needed to take a photograph of my screen. So please ignore the unsharp grey stripes - they are a side-effect of taking a photograph of the screen and not really there. What is the real glitch are the 3 thin horizontal lines, there only should be one, which is the lowest of them.

If you could see the movement: The glitch lines appear to be flickering (I think about 20 times/second, see my theory below). But taking a video of the glitch is even more impossible (120 Hz video camera, anyone? :D ). Then the glitch lines change their position at random points of time.

Looking through my 3D glasses it appeared that the glitch lines are only in the half-picture intended for the right eye, the left eye looks normal.

## Theory

 After some research about the internal workings of DirectX graphics and how Monogame uses it I came up with the following theory how this happens:

1. Monogame creates a swapchain in the video memory which consists of a screen buffer and 2 back buffers
2. since 3D Vision needs 2 half-pictures it creates secondary buffers for the right eye. It doesnt tell the application anything about that (wouldn't be possible with older 3D games that are automatically converted into stereo 3D)
3. When a Frame should be drawn, Monogame sends draw instructions to the graphics card and waits until they are executed, then presents the next buffer in the swapchain.
4. Monogame (or SharpDX?) uses some unusual way to determine when the draw operations are finished. At least I assume it must be unusual since I never noticed the same problem in other 3D games. The call returns when the first buffer has been drawn, the secondary buffer has not yet been drawn.
5. Under normal circumstances the next Frame is drawn now. If that happens the preceding draw operations are cancelled. The secondary buffer remains unchanged.
6. only at random times (for example when the operating system gives cpu time to another thread or process) the graphics card is given enough time to execute the drawing operations for the seondary buffer. Then the secondary buffer is changed.
7. The screen is presented with the contents of the primary and secondary buffers. Since the secondary buffer contains an old version of the drawing from some random point of time in the past, a flickering ghost will appear. Since there are 3 secondary buffers it flickers at a rate of
   
   120 Hz / 2 (half pictures/second) / 3 (buffers/half-picture) = 20 Hz
   
   There are up to 3 ghosts, because we have 3 secondary buffers.

## Workaround

To test my theory I just gave the graphics card more time to finish by adding a Thread.Sleep() to the draw cycle. To test remove the slashes from the line `Thread.Sleep( (int)gameTime.ElapsedGameTime.TotalMilliseconds/8);` in my code sample. I found the appropriate amount of time with trial and error, it may be system dependent.

On my system this removes all the graphic glitches.

## Suggestions for Solution

The second best solution would be to deactivate 3D Vision in Monogame completely. There is an API (nvapi.dll) that allows game developers to control 3D vision, so Monogame would need to check wether it is present and make the appropriate calls.

The best solution would be of course to fix the source of the problem since this would allow to write 3D-vision compatible games with Monogame.

## Code

```csharp
using System;
using System.Threading;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;

namespace Game1
{
    public class Game1 : Game
    {
        GraphicsDeviceManager graphics;
        SpriteBatch spriteBatch;
        private Texture2D pixel;

        private int linepos = 0;

        private Rectangle screen;

        public Game1()
        {
            graphics = new GraphicsDeviceManager(this);
            graphics.IsFullScreen = true;
            graphics.PreferredBackBufferWidth = 1920;
            graphics.PreferredBackBufferHeight = 1080;
            Content.RootDirectory = "Content";
        }
        protected override void Initialize()
        {
            graphics.IsFullScreen = true;

            this.IsFixedTimeStep = true;
            this.TargetElapsedTime = new System.TimeSpan(166666L);
            screen = GraphicsDevice.Adapter.CurrentDisplayMode.TitleSafeArea;

            base.Initialize();
        }
        protected override void LoadContent()
        {
            spriteBatch = new SpriteBatch(GraphicsDevice);
            pixel = Content.Load<Texture2D>("pixel");
        }
        protected override void UnloadContent()
        {
        }

        protected override void Update(GameTime gameTime)
        {
            if (GamePad.GetState(PlayerIndex.One).Buttons.Back == ButtonState.Pressed || Keyboard.GetState().IsKeyDown(Keys.Escape))
                Exit();

            linepos = (linepos + 5) % screen.Height;

            base.Update(gameTime);
        }

        protected override void Draw(GameTime gameTime)
        {
            GraphicsDevice.Clear(Color.White);
            spriteBatch.Begin(samplerState: SamplerState.LinearWrap);
            spriteBatch.Draw(pixel, new Rectangle(0, linepos, screen.Width, 5), new Rectangle(0, 0, screen.Width, 5), Color.White);
            spriteBatch.End();
            //Thread.Sleep( (int)gameTime.ElapsedGameTime.TotalMilliseconds/8);

            base.Draw(gameTime);
        }
    }
}
```

**Comment by KonajuGames** [comment]
What do you mean by "the preceding draw operations are cancelled"? Is this an internal Nvidia thing with the extra rendering it does for the other view?

There is nothing special or unusual that MonoGame or SharpDX does to wait for drawing to complete. Have you tried playing with the value of `PresentationParameters.PresentationInterval`?  It defaults to One, which means it tells DirectX to wait for the vertical refresh.  This can also be set to Two or Immediate, which maps directly to the equivalent functionality in DirectX.

**Comment by wulf21** [comment]
I have tried setting PresentationParameters.PresentationInterval to Two already (indeed that was my first guess), however this made no difference. Only including an additional sleep time fixed it so far.

I do not know wether the way Monogame waits for completion is special in any way, it is just an assumption (as explained in the next sentence). Indeed I am not 100% sure about anything I wrote under the headline "Theory", probably I was not clear enough about that.

It just seemed logical because
1. it fits the symptoms and
2. my workaround does fix it

Wether this "cancellation" is an Nvida-internal thing I cannot say. I only can tell that the result is that the right-eye-picture is only drawn at random points of time and that the screen will cycle through 3 different pictures (which correspond to the 3 buffers).

**Comment by wulf21** [comment]
So, I did some more experimenting around. It turned out that the `sleep()` must be placed exactly there, i.e. between submitting the last draw instructions to the graphics card (which is done within `spriteBatch.End()`, which eventually calls `ID3D11DeviceContext::DrawIndexed()` ) and the presentation of the next frame (which the gameloop does after `Game1.draw()` completed). Any other place and it would have no effect.

So appearantIy my conclusion that the next draw call is responsible turned out to be wrong. I now assume that somehow a too early call to `present()` leads to the described effect, i.e. the draw instructions for the right eye do not get executed.

In order to test this I modified the source code of the Monogame framework so the DirectX GraphicsDevice exposes its `_d3dContext` as a public readonly property on which then manual calls can be made.

When `Flush()` is called on the context after `spriteBatch.End()` this has the same effect that the graphics bug disappears. So it really seams that some instructions left in the instruction buffer for some strange reason do not get executed unless they are manually sent to the GPU with flush().

Since Microsoft writes in the documentation of ID3D11DeviceContext::Flush() that "each call to Flush incurs a significant amount of overhead." I tried to measure it with a System.Diagnostics.Stopwatch. The measurements returned that `Flush()` takes about 1% of the time of the game loop, which is much better then the 1/8th loop time that was required to sleep; measurements done in Debug configuration. I am aware that these circumstances are nowhere near a realistic game situation but I expect that it would not be much more than this, because the instruction buffer, according to the Microsoft doc, will regularly get flushed anyways.

So, the question remains, why is that flush needed despite Microsoft telling that "most applications don't need to call this method" ? I searched a bit, but the behaviour that some instructions in the buffer under some circumstances are not executed seems to be documented nowhere.

**Comment by KonajuGames** [comment]
To me it would seem like a NVIDIA driver issue.

**Comment by wulf21** [comment]
By that, do you mean my system is misconfigured or a general problem with the NVIDIA driver?

To rule out the first possibility, I did a clean uninstallation and reinstallation of the NVIDIA drivers, but the problem persists. Of course I can't be 100 % sure that nothing is wrong with my system, so I did a request in the Nvidia 3D vision forums to download my test application to see if others can reproduce the issue.

**Comment by Nezz** [comment]
3D Vision is a really hacky attempt from Nvidia. This seems like a general problem to me with their workaround for games not supporting 3D Vision out of the box.

While I own two displays myself supporting it, I think that requesting to disable it is the best approach as 3D Vision is/will be discontinued.

**Comment by wulf21** [comment]
Yes it is hacky, but in general it works, except for problems that are to be expected (like some effects e.g. lens flare and post processing being drawn at screen depth or menu items being drawn at another depth than the mouse pointer.)

This is the first time I saw this kind of issue, i.e. a previous frame left behind as a flickering ghost. So my first thought was that it is probably related to Monogame.

The other possibility is that this glitch appears purely due to the simplicity of my example and goes away if something more complicated is drawn, which in general will take more time to complete. To confirm this, I would need another simple test application that is not written in Monogame (ideally directly in C++/DirectX).

I think the core technology behind 3D vision will, for now, continue to survive since NVIDIA announced that they want to do something similar with Ocolus Rift, i.e. diaplay content that was not intended for VR.

Since you do have 3D Vision, can you please check, wether you can reproduce the bug on your system? I put an archive together which contains both the binaries and the source code that can be downloaded here:

http://www.mediafire.com/download/pt1e4sb2l7era36/3dvision_bugtest.zip - 5.6 MB

The 3dvision_bugtest_fix1.exe contains the `Thread.Sleep()` workaround, while the 3dvision_bugtest_fix2.exe contains the `Flush()` workaround.

My request in the 3D vision forum has been answered by 2 people for now. It appears that the issue is independend of the driver version and the GPU. All who have tested (including myself) are running Windows 7 64 bit.

**Comment by Nezz** [comment]
I'm currently on holiday (as much as I can be on holiday around the Windows 10 release), but I will check it once I'm back in about a week.

**Comment by bo3b** [comment]
Thanks very much for the detailed analysis and experimentation.  This is a really interesting result, and based on your conclusion that it works properly on 350.12 and fails on further drivers seems to be clearly a driver bug.

In general the core technology "3D Vision Automatic" actually works pretty well.  There is no disagreement that it is a bit of a hack, but with 5 years of experience I think we say it's pretty good.  The combination with HelixMod fixes allows us to make flawless 3D games. There are presently no plans from NVidia to discontinue 3D Vision, although people do seem hell-bent on coming to that conclusion.  Their support is weak, but people have been predicting the demise of 3D Vision ever since I started getting involved more than 3 years ago.


This bug seems directly related to one-eye problems we've seen in some recent games.  GTA5 has a glitch unless you switch to Max Payne 3 profile.  FarCry4 has this glitch on drivers past 350.12.

I would also have thought that DX11 would defer a Present() if the pipeline was still busy, but something seems to have changed in recent drivers. 

Given that you can fix the problem with a Flush() call that suggests an interesting possible workaround for these glitches.  I'll see if I can add an optional feature to 3Dmigoto that allows us to call Flush() before Present() as a way to fix some of these problems.  

Thanks again for the detailed look.

**Comment by Nezz** [comment]
> There are presently no plans from NVidia to discontinue 3D Vision, although people do seem hell-bent on coming to that conclusion.

Maybe it will live on with VR glasses, but I haven't seen any new displays in two years.

**Comment by bo3b** [comment]
>> There are presently no plans from NVidia to discontinue 3D Vision, although people do seem hell-bent on coming to that conclusion.

> Maybe it will live on with VR glasses, but I haven't seen any new displays in two years.

Sorry, not really the place for this discussion, but you don't count the ROG Swift?  Released in the last year.

**Comment by Nezz** [comment]
You are right. It isn't listed on Nvidia's site. Although it supports 3D vision with the kit sold separately, all the marketing materials focus on 144Hz and G-Sync. Essentially it only supports 3D vision because it has the refresh rate.

Things look similarly bad on the game side. AFAIK Arkham Origins was the last 3D ready game released in 2013. The Arkham series had a great track record, but look at Arkham Knight...

Anyway, we are totally our of topic, se we can agree not to agree :)

**Comment by wulf21** [comment]
So, as bo3b already has told, I can now definitely confirm that this is a driver issue, not and issue with MonoGame. The version numbers the 3 people within the 3D vision forums reported hinted that the bug didn't happen in older versions, so I installed different versions of the NVIDIA driver and could confirm this on my system.

Other than that, I quickly puzzled together another Test application based on C++/DirectX starting from Microsofts official DirectX11 tutorial sample. It is showing the same behaviour.

So, I have now more than enough material to report the issue directly to NVIDIA. I hope it will be taken serious. Any experience with that?

**Comment by wulf21** [comment]
So, It looks like Nvidia actually has fixed the bug in the newest driver version. So it's case closed.
