### ISSUE TITLE
Remove GetExecutingAssembly() Call

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#4047]
We should remove the call to `GetExecutingAssembly()` here:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Content/ContentTypeReaderManager.cs#L55

And replace it with the `WINRT` version which should work on all platforms and is much less expensive to execute.

**Comment by mattiascibien** [comment]
Hi, is there any problem if I try to work on this? I guess that a call to 
```
typeof(Class).GetTypeInfo().Assembly
```
Can be good?
