### ISSUE TITLE
error x5426 - compiler says too many operations for ps_2_0 when using ps_4_0...

### ISSUE THREAD

**Issue by AlienScribble** [mono/MonoGame#4048]
When building the effect below I receive this error: 
error x5426: shader uses texture addressing operations in a dependency chain that is too complex for the target shader model (ps_2_0) to handle. 
The model is vs_4_0_level_9_1 and ps_4_0_level_9_1
(In xna I was able to use model 3_0) 
So I'm suspecting it is checking if my operations exceed shader 2 maximum amount instead of 4. 
I do notice that it works like a charm if I use ps_5_0

Here is the code in case it is useful: 

#define TECHNIQUE(name, vsname, psname ) technique name { pass { VertexShader = compile vs_4_0_level_9_1 vsname (); PixelShader = compile ps_4_0_level_9_1 psname(); } }
//#define TECHNIQUE(name, vsname, psname ) technique name { pass { VertexShader = compile vs_5_0 vsname (); PixelShader = compile ps_5_0 psname(); } }
#define DECLARE_TEXTURE(Name, index) Texture2D<float4> Name : register(t##index); sampler Name##Sampler : register(s##index) 
#define SAMPLE_TEXTURE(Name, texCoord)  Name.Sample(Name##Sampler, texCoord) 
#define NUM_SAMPLES 32

DECLARE_TEXTURE(Texture, 0);
float4x4 MatrixTransform;
float2 lightScreenPosition;
float Density;
float Decay;
float Weight;
float Exposure;

struct VSOutput
{
	float4 position		: SV_Position;
	float4 color		: COLOR0;
	float2 texCoord		: TEXCOORD0;
};

VSOutput SpriteVertexShader(float4 position	: SV_Position, float4 color : COLOR0, float2 texCoord : TEXCOORD0)
{
	VSOutput output;
	output.position = mul(position, MatrixTransform);
	output.color = color;
	output.texCoord = texCoord;
	return output;
}

float4 SpritePixelShader(VSOutput input) : SV_Target0
{	
	float2 TexCoord = input.texCoord;
	float2 DeltaTexCoord = (TexCoord - lightScreenPosition);                       //vector between pixel and light-pos
	DeltaTexCoord = DeltaTexCoord * (1.0f / NUM_SAMPLES * Density);  //divide it up into units (however many samples along that dist_vect)

	float3 col = SAMPLE_TEXTURE(Texture, TexCoord); //sample a color at the current pixel	
	float IlluminationDecay = 1.0;
	float3 Samp;
	
	for (int i = 0; i < NUM_SAMPLES; ++i)              //move along the vector between the light and pixel
	{
		TexCoord -= DeltaTexCoord;                                       //go to the next sample-pixel
		Samp = SAMPLE_TEXTURE(Texture, TexCoord);  //get the pixel color 
		Samp *= IlluminationDecay * Weight;                         //multiply it by the decay amount 
		col += Samp;			                //add up to get the average intensity along this vector afterwards
		IlluminationDecay *= Decay;                                       //adjust decay (in a curving way)
	}
	return float4(col*Exposure, 1);		
}

TECHNIQUE(SpriteBatch, SpriteVertexShader, SpritePixelShader);

**Comment by mgarstenauer** [comment]
> So I'm suspecting it is checking if my operations exceed shader 2 maximum amount instead of 4. 

That is correct. If you specify `ps_4_0_level_9_1`, the compiler is targeting Direct3D 9 hardware with similar limits to `ps_2_0`. See  [Direct3D 9.1, 9.2, and 9.3 feature levels](https://msdn.microsoft.com/en-us/library/windows/desktop/jj215820(v=vs.85).aspx#direct3d_9.1__9.2__and_9.3_feature_levels)

You can either reduce the complexity of the pixel shader, or you need to specify another feature level, such as `ps_4_0_level_9_3`, `ps_4_0`, or `ps_5_0`.

**Comment by AlienScribble** [comment]
Oh I see, since it worked ok in xna with 3 I thought maybe this was a glitch in the compiler count limit - didn't realize 9_1 was setting limit for 2. I'll just use 5_0 then. Thanks :)
