### ISSUE TITLE
Unexpected token error on in Effect file

### ISSUE THREAD

**Issue by FaceHunter** [mono/MonoGame#4053]
Hello everyone,

I'm porting some old XNA code over to MonoGame and I'm getting the following errors:

```
C:\Users\Michael\Git\gbh2dev-face-mg\gbh2dev\Content\Shadow.fx(250,51) : Unexpected token '2' found. Expected CloseParenthesis
C:\Users\Michael\Git\gbh2dev-face-mg\gbh2dev\Content\Shadow.fx(250,51) : Unexpected token '2' found. Expected CloseBracket
C:\Users\Michael\Git\gbh2dev-face-mg\gbh2dev\Content\Shadow.fx(250,51) : Unexpected token '2' found. Expected CloseBracket
C:\Users\Michael\Git\gbh2dev-face-mg\gbh2dev\Content\Shadow.fx(264,51) : Unexpected token '3' found. Expected CloseParenthesis
C:\Users\Michael\Git\gbh2dev-face-mg\gbh2dev\Content\Shadow.fx(264,51) : Unexpected token '3' found. Expected CloseBracket
C:\Users\Michael\Git\gbh2dev-face-mg\gbh2dev\Content\Shadow.fx(264,51) : Unexpected token '3' found. Expected CloseBracket
C:\Users\Michael\Git\gbh2dev-face-mg\gbh2dev\Content\Shadow.fx(278,45) : Unexpected token '5' found. Expected CloseParenthesis
C:\Users\Michael\Git\gbh2dev-face-mg\gbh2dev\Content\Shadow.fx(278,45) : Unexpected token '5' found. Expected CloseBracket
C:\Users\Michael\Git\gbh2dev-face-mg\gbh2dev\Content\Shadow.fx(278,45) : Unexpected token '5' found. Expected CloseBracket
C:\Users\Michael\Git\gbh2dev-face-mg\gbh2dev\Content\Shadow.fx(293,45) : Unexpected token '7' found. Expected CloseParenthesis
C:\Users\Michael\Git\gbh2dev-face-mg\gbh2dev\Content\Shadow.fx(293,45) : Unexpected token '7' found. Expected CloseBracket
C:\Users\Michael\Git\gbh2dev-face-mg\gbh2dev\Content\Shadow.fx(293,45) : Unexpected token '7' found. Expected CloseBracket
```

The corresponding lines look like this:
```C
PixelShader = compile ps_5_0 ShadowTermPS(2);
PixelShader = compile ps_5_0 ShadowTermPS(3);
PixelShader = compile ps_5_0 ShadowTermPS(5);
PixelShader = compile ps_5_0 ShadowTermPS(7);
```

The full file is available [Here](https://gist.github.com/FaceHunter/be81d8e8a8c468dd96f0)

I have no idea what's causing this and it looks like correct syntax to me.

Thanks in advance,
FaceHunter

EDIT: the same error occurs in another file, also with `PixelShader = compile ps_5_0 SomeFunction(true);` only with true and false

**Comment by mgarstenauer** [comment]
In MonoGame you can't set pass an argument in `PixelShader = compile ps_5_0 SomeFunction(argument);`
This works in XNA, but not it is not supported MonoGame.

Instead you can add the following functions:

    float4 ShadowTermPS2(in float2 in_vTexCoord	: TEXCOORD0, in float3 in_vFrustumCornerVS : TEXCOORD1)	: COLOR0
    {
        return ShadowTermPS(in_vTexCoord, in_vFrustumCornerVS, 2);
    }
    float4 ShadowTermPS3(in float2 in_vTexCoord	: TEXCOORD0, in float3 in_vFrustumCornerVS : TEXCOORD1)	: COLOR0
    {
        return ShadowTermPS(in_vTexCoord, in_vFrustumCornerVS, 3);
    }
    ...

And then use:

    PixelShader = compile ps_5_0 ShadowTermPS2();
    PixelShader = compile ps_5_0 ShadowTermPS3();
    PixelShader = compile ps_5_0 ShadowTermPS5();
    PixelShader = compile ps_5_0 ShadowTermPS7();

**Comment by FaceHunter** [comment]
@mgarstenauer That worked, thanks!
