### ISSUE TITLE
MonoGame PCL for v3.4 or develop

### ISSUE THREAD

**Issue by WardBenjamin** [mono/MonoGame#4056]
Hey MonoGame team,

I'm working on [MonoGame.Extended](https://github.com/craftworkgames/MonoGame.Extended), which provides/will provide extensions such as cameras, GUI, etc, and ran into an interesting issue. We are compiling our core library as a PCL against the MonoGame PCL available on Nuget, and this limits us to old versions of MonoGame (the most recent being v3.2.99.1-Beta, two major versions behind). Many changes have been made since then, and even being able to use v3.4 would be a ton better. Can I get some directions on how to build MonoGame as a PCL, and/or an update to the Nuget package?

**Comment by cra0zy** [comment]
Duplicate of #3944

**Comment by WardBenjamin** [comment]
Is there a way to build it myself? This is something that I need if I am going to develop on Linux, since a ton of bugs are present in old versions that have since been fixed.

**Comment by WardBenjamin** [comment]
@DDReaper Hunting around github and the MonoGame forums, I found a link to your PCL branch, then found the (slightly newer if I remember correctly) PCL generator using Piranha. Would this still work for the current branches?

**Comment by WardBenjamin** [comment]
So, using @DDReaper's old PCL generation branch, I have created a new version that can be both built on Linux (and most likely Mac as well, I don't have one to test) as well as using the v3.4 release. 

Could we update the Nuget package with this binary? You can check out my branch at https://github.com/WardBenjamin/MonoGame/tree/PCL_v3.4.

**Comment by DDReaper** [comment]
@WardBenjamin do you want to close this issue if it's superseded by the others, so as not to confuse things.

Great work picking up the mantle, I got dragged several ways to sunday with work and other projects.  if you need to bounce ideas, just ping me :dart:

**Comment by WardBenjamin** [comment]
> if you need to bounce ideas, just ping me

Thanks!

I'm going to spend some time tonight working on this.... I'm having a very odd issue with my build.... possibly because the DLL that Piranha generates isn't versioned? Hm... that could be because the WinGL one is not either... I'll check it out.

Anyway, closing. Also referencing https://github.com/mono/MonoGame/issues/3944 for the record.
