### ISSUE TITLE
TextureCube support in MonoGame pipeline

### ISSUE THREAD

**Issue by stampergames** [mono/MonoGame#4062]
TextureCube objects do not appear to be supported by the MonoGame pipeline.  When passing a multiple face dds file into the pipeline, the result, at load time, is a Texture2D object instead of a TextureCube.  

This issue appears to have been previously discovered at http://community.monogame.net/t/loading-cubemaps-generated-with-monogame-pipeline/1025 but an issue was never recorded

**Comment by nkast** [comment]
A very basic DDS importer https://github.com/tainicom/ProtonType 
DLL: https://github.com/tainicom/ProtonType/tree/master/bin/Release/AnyCPU/Content.Pipeline

I use it to import cubemaps from the ATI CubeMapGen tool and what I wanted was to preserve any MipMap and DXT1 info. It can also convert DXT1 to Color.

**Comment by tomspilman** [comment]
I'm pretty sure the lib we use for texture importing, FreeImage, already supports DDS enough to fix this.

@KonajuGames ?

**Comment by nkast** [comment]
FreeImage dont support multiple faces or mipmaps and probably uncompress everything. I need to preserve the compression and filtering done by CubeMapGen.

**Comment by KonajuGames** [comment]
Can you provide a sample multi-face DDS to test this with?

**Comment by nkast** [comment]
Here:
https://onedrive.live.com/redir?resid=21955F536F871E02!24731&authkey=!AFIEibXpOwOOvuE&ithint=file%2cdds
Basic cubeMap generated by http://developer.amd.com/tools-and-sdks/archive/legacy-cpu-gpu-tools/cubemapgen/
64x64 + Mips , DTX1

FreeImage will read the first Face and drop the mipmap chain. XNA will save a Texture2D.

**Comment by KonajuGames** [comment]
Investigating FreeImage further, it completely lacks support for anything beyond a single face in a DDS file.  I started implementing DDS import, which the standard TextureImporter will use instead of FreeImage when presented with a DDS file.  It is similar to @nkast 's importer, but will support more DDS features.  I'm not keen on expanding DXT to Color though.  For importing cubemaps for use on non-desktop platforms, we would need to find another way of importing.

**Comment by nkast** [comment]
@KonajuGames 
For replacing the current DDS importer in MonoGame we have to at least support what FreeImage already does, that is Single face image (Texture2D) but didn't had a DDS of that kind to test it with.
DDS is used to import odd formats, a practical importer only need to convert DDS to XNB with no-change format and convert to Color format for those platforms that don't support DXT1 and/or compressed 3D/cube textures. For example, although Android supports DXT, GLES doesn't support DXT in cubemaps. 
Decompressing DXT1 was trivial, took a couple of hours to read the msdn documentation and implement it. Let me know if I can contribute in any way.

DDS support is needed to port XNA projects but I see DDS as one more step, it's a low level format similar to XNB. Besides DDS I would like to see a CubeMap importer that takes a set of images or a Cross image and convert it directly to XNB/CubeTexture. This requires some advanced filtering when generating mips, sampling pixels from adjusted faces on the edges.

**Comment by KonajuGames** [comment]
@tomspilman and I have been discussing other cubemap import techniques for after we get DDS cubemap done (cross, linear, lat-long, sequence, etc).  The DDS reader will support single face import, as well as any mipmaps present, as well as cubemap.

**Comment by KonajuGames** [comment]
Pull request #4136 submitted to add the cubemap and mipmapped texture support from DDS.
