### ISSUE TITLE
Android screen auto rotation problem

### ISSUE THREAD

**Issue by icewind** [mono/MonoGame#4064]
Hi. I have an android app with multiple activities and one of them(not main) is AndroidGameActivity with monogame game. 
All works fine but it does not seems to react on device or emulator gets rotated. Native android views rotates without any problems. 
My Activity setup

    [Activity (
        Label = "GameActivity", 
        ScreenOrientation = ScreenOrientation.Portrait | ScreenOrientation.Landscape, 
        LaunchMode = LaunchMode.SingleTask,
        AlwaysRetainTaskState = true,
        ConfigurationChanges = ConfigChanges.Orientation | ConfigChanges.Keyboard | ConfigChanges.KeyboardHidden)]			
    public class GameActivity : Microsoft.Xna.Framework.AndroidGameActivity

And in the game constructor i've set theese properties for the graphics

    graphics = new GraphicsDeviceManager (this);
    Content.RootDirectory = "Content";	            
    graphics.IsFullScreen = false;	
    graphics.SupportedOrientations = DisplayOrientation.Portrait | 
        DisplayOrientation.LandscapeLeft |
        DisplayOrientation.LandscapeRight | 
        DisplayOrientation.PortraitDown;

If I set only Landscape it works fine, but it just can't switch between Portrait and landscape. Did I missed some thing?
Thanks.

**Comment by icewind** [comment]
If I replace monogame with a simple View it is rotating as I expected.
This works in AndroidGameActivity

    SetContentView(Resource.Layout.GameLayout); //Simple layout with a text and a button

And this is not

    MyGame game = new MyGame ();
    SetContentView((View)game.Services.GetService(typeof(View)));

Is there any workaround or maybe my activity setup is wrong?

**Comment by Nezz** [comment]
This should work:

```
    [Activity(ScreenOrientation = ScreenOrientation.Sensor,
        ConfigurationChanges = ConfigChanges.Orientation | ConfigChanges.Keyboard | ConfigChanges.KeyboardHidden | ConfigChanges.ScreenSize)]
```

**Comment by icewind** [comment]
Sadly it's does not. Also tried FullSensor without any luck. Other activities rotates well even with 
`ScreenOrientation = ScreenOrientation.Unspecified`

**Comment by icewind** [comment]
Still can't figure how to make it work. I've created a sample project to illustrate this issue. Please take a look. 
https://yadi.sk/d/UeCs5fAIibJx8
Also i've recorded a short video with demonstration from this project. 
https://yadi.sk/i/ucBp_WP2ibJjo (if you will download it it will be a better quality)

**Comment by icewind** [comment]
I'm not spent too much time on this since i have different issues in this project, but today i've tested it on real device(Samsung Galaxy S5) and it's working as expected. Seems like it is an issue with the Xamarin Android Player.
Also i've created a test project with OpenGL view(Without monogame), and it also can't rotate.

I've created a thread on Xamarin Forums http://forums.xamarin.com/discussion/48948/change-orientation-problem?new=1
