### ISSUE TITLE
MediaPlayer.Volume adjustement only works on 1st played Song

### ISSUE THREAD

**Issue by mrhelmut** [mono/MonoGame#4072]
Hi there,

I am having problems adjusting the volume of songs while playing. I noticed that it works fine with the first Song played after app launch, but any subsequent song played can't have their volume changed (with the exception of ```MediaPlayer.Volume = 0.0f``` which correctly totally mutes the song).

Platform: WinDX.

Possible related issues: #3884

EDIT: it seems to be a problem with the ```MediaSession``` and ```MediaFactory.GetService(session, MediaServiceKeys.StreamVolume, AudioStreamVolumeGuid, out volumeObj);```. If I force the recreation of a new ```MediaSession``` at each play, it works. So it looks like there is a problem with retrieving the correct ```AudioStreamVolume``` for the given song stream. Most probably related to the fact that topology updates are async (and therefore still bound to the previous stream somehow when trying to retriever the stream volume controller).

Most XAudio2 media session impletations seem to re-create a session at every play because media session updates are async. So if you guys are OK with that, I can submit a PR that Shutdown media sessions upon stop and start a fresh one upon start.

It is also because of those async initialisations that getting the audio stream volume controller may fail (and needs to wait). I can clean that up and init it once the topology is correctly set (you can know that with the MediaEvent callback).

Let me know if that sound coherent.

**Comment by tomspilman** [comment]
@mrhelmut - I suspect this PR might solve this issue:

 https://github.com/mono/MonoGame/pull/4044/files

Do you have some time to give it a test?

**Comment by mrhelmut** [comment]
Oh, I missed that PR.

It works! Looks clean and safe to me. It should fix quite a bunch of bugs.
