### ISSUE TITLE
API for drawing basic shapes

### ISSUE THREAD

**Issue by cra0zy** [mono/MonoGame#4082]
One thing that always bugged me about XNA is that it doesn't have a way of drawing basic shapes very easily. We may want to implement some extra methods to SpriteBatch like DrawCircle, DrawRectangle, etc.

@tomspilman @KonajuGames Thoughts?

**Comment by danzel** [comment]
Na, keep it out as an extension.

**Comment by Shqrdx** [comment]
I would like if separated(but official) assembly been made. Which contains all shapes,geometry figures and other extensions..

**Comment by theZMan** [comment]
I would recommend starting with the primitives sample from XNA - I
personally use it in a lot of games for debug output so it would be a good
start point.

http://xbox.create.msdn.com/en-us/education/catalog/sample/primitives

**Comment by cra0zy** [comment]
I still think that having some way of drawing basic shapes would be beneficial, I almost always have to add my code for drawing stuff.

libgdx for example has ShapeRenderer for that: https://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/graphics/glutils/ShapeRenderer.html

**Comment by KonajuGames** [comment]
I don't think they belong in the framework itself, but an extension library such as [MonoGame.Extended](https://github.com/craftworkgames/MonoGame.Extended) by @craftworkgames would be a good home.
