### ISSUE TITLE
SpriteBatch Sort Garbage

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#4086]
I'm fairly certain that the sorting code in SpriteBatch is generating garbage.  Take a look at this code:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/SpriteBatcher.cs#L215

The `List<T>.Sort(...)` there takes a delegate as it shows in the doc:

https://msdn.microsoft.com/en-us/library/w56d4y5z(v=vs.110).aspx

This means on each batch sort we are allocating a delegate to pass to the sort then throwing it away.

Not sure if this can be fixed by allocating the delegate and storing it or if we should use one of the other overloads for `Sort` which doesn't generate garbage.

**Comment by mrhelmut** [comment]
I didn't noticed garbage related to sprite sorting, but I don't have code using it anymore to give it an extensive test. It can't harm to do a preemptive fix though.

Switching to ```List<T>.Sort(IComparer<T>)``` sounds safe (and have static comparers instances within ```SpriteBatcher```?)
If that makes sense to you, I'll try to submit a PR.

**Comment by mgarstenauer** [comment]
Note that the compiler automatically caches certain delegates and lambdas (except closures). `CompareTexture` is a static method, so it is likely that the delegate is cached. But this may depend on the platform and should to be tested using a memory profiler.

**Comment by tomspilman** [comment]
> But this may depend on the platform and should to be tested using a memory profiler.

That is the thing...  it is compiler/runtime dependent.  By using a method we know is optimal on all platforms I think we're safer.

**Comment by MichaelDePiazzi** [comment]
@tomspilman Would this have been resolved by PR #4172?

**Comment by tomspilman** [comment]
Yep... it totally did.  Thanks for the reminder!
