### ISSUE TITLE
UAP issue (Update Required)

### ISSUE THREAD

**Issue by HeshamMeneisi** [mono/MonoGame#4091]
Altough the SDK is installed and I can create and run a UAP normally, the MonoGame UAP project just cannot recognize the SDK and the solution doesn't load showing a message (Update required).

![uap](https://cloud.githubusercontent.com/assets/10683997/9340990/79697050-45f3-11e5-926f-a307f6d8c06a.PNG)

EDIT: I have acquired VS 2015 Enterprise from Dreamspark and it's fully featured, all features are installed except for the Win10 emulator. Updated to KB3073097

**Comment by mattiascibien** [comment]
@HeshamMeneisi are you using the stable installer? If you develop for Windows 10 RTM you should get the latest development version which works.

**Comment by HeshamMeneisi** [comment]
I think I was confused by the download page into thinking that 3.4 is the latest version. Now that I downloaded and installed 3.5, everything is fine. Thanks for your help :+1:

**Comment by mattiascibien** [comment]
@HeshamMeneisi no problem.

**Comment by danzel** [comment]
@HeshamMeneisi Please close your issue :)

**Comment by HeshamMeneisi** [comment]
Ok, issue closed :)
