### ISSUE TITLE
XAudio crashes if a SoundEffectInstance is playing while disposing the SoundEffect

### ISSUE THREAD

**Issue by mrhelmut** [mono/MonoGame#4093]
I noticed that XAudio (and possible other implementations) would crash if a ```SoundEffectInstance``` is playing while its parent ```SoundEffect``` is being disposed or unloaded via ```ContentManager.Unload()```.

I have a temp fix (see https://github.com/mrhelmut/MonoGame/tree/SoundEffectDisposeFix) that stops any playing/paused pooled ```SoundEffectInstance``` before the disposal of their ```SoundEffect```, and returns them to the pool. But that doesn't concern non-pooled instances.

What do you guys think about this? ( @tomspilman @KonajuGames ?) Should all pooled and non-pooled instances of a given ```SoundEffect``` be stopped? Or do one consider that non-pooled instances (via ```SoundEffect.CreateInstance```) life-cycle is up to the developer?

Let me know what you think and if I should push that fix or rework it.

**Comment by MichaelDePiazzi** [comment]
@mrhelmut Is this issue resolved now that your PR has been merged?

**Comment by mrhelmut** [comment]
Yes! Closing!
