### ISSUE TITLE
Monogame for Windows using DX's MediaPlayer mute only one song.

### ISSUE THREAD

**Issue by iMalinois** [mono/MonoGame#4096]
While using Mediaplayer to play songs in my game, developed in monogame for windows using DX I have encountered a bug where only one song will mute/unmute when changing the MediaPlayer.IsMuted property but as soon as I play another song using the MediaPlayer, the mute will no longer work, and the music will keep playing. the same thing happens when using the Volume Property, mute will sieze to work as song as a new song is played.

its something like that:
MediaPlayer.Play(Song1);
MediaPlayer.IsMuted = true; //Mute just fine
MediaPlayer.Stop();
MediaPlayer.Play(Song2); //Game will unmute the song, playing the song in full volume.
MediaPlayer.IsMuted = true; //This line will not work, the song wont mute.

any ideas on how to solve it?

Edit:
The origion of the problem is a bug in the MediaPlayer class in MonoGame 3.4 Build.
To solve the problem download a newer build (3.5 Unstable or higher).

**Comment by mrhelmut** [comment]
Are you working with the latest dev build or directly with the develop branch? This has been fixed recently (see #4044).

**Comment by iMalinois** [comment]
@mrhelmut I am currently using the official 3.4 Build of monogame, I would like to give the fix a shot and test it on my project, but I cant get the github build to run, not sure if I am doing it right actually.

**Comment by mrhelmut** [comment]
Cool!
Could you please close this issue? @iMalinois

**Comment by iMalinois** [comment]
@mrhelmut Yep.
