### ISSUE TITLE
Content Manager Not Working 

### ISSUE THREAD

**Issue by heroics** [mono/MonoGame#4106]
Perhaps I'm using it wrong, but my content manager doesn't seems to work. If load up my assets in the MonoGame Content Manager my code can't access them, but if I Load my assets in the Contents folder they can. Again perhaps I'm doing it wrong but I don't think I am. Any help  would most appreciated, or perhaps this is a problem for others so I wanted to bring it up.

-Have a great day!

**Comment by danzel** [comment]
I think you are misunderstanding the Content Manager.
(I haven't used it yet so blind leading the blind here).
It is a tool for converting your content from the input format (.png .wav etc) in to something better for loading (.xnb).

Have you hit the build button in the Content Manager? It should spit out .xnb files in to your Content dir afaik.

**Comment by heroics** [comment]
I'm not quite sure I understand, perhaps I'm simply using it wrong. I will read the documentation a bit more.

**Comment by vchelaru** [comment]
Please review docs here:

http://developer.xamarin.com/guides/cross-platform/game_development/monogame/introduction/
