### ISSUE TITLE
Move Mouse fastly can cause graphics device crash

### ISSUE THREAD

**Issue by YangFan789** [mono/MonoGame#4107]
![monogame](https://cloud.githubusercontent.com/assets/14011681/9540966/6ad80b46-4d96-11e5-80e4-cc76f0bd863b.gif)
In a project which is newly created by monogame template, **just move** mouse like this. And memory usage increase quickly, and then graphics device crash. On my machine, it is no an accident. If you moving mouse like this, crash happened certainly.

Env: Windows 10 64bit, Visual Studio 2015, MonoGame 3.4, Intel HD Graphics 5500, AMD Radeon R9 M275

**Comment by tomspilman** [comment]
@YangFan789 - Did you using the Windows or WindowsGL template for this?

**Comment by YangFan789** [comment]
@tomspilman  Is *MonoGame Windows Project*

**Comment by tomspilman** [comment]
So this is a DirectX build which uses WinForms under the hood for the window.  I have no clue why this would be happening really.

**Comment by KakCAT** [comment]
I haven't been able to reproduce it with latest build, Win10 64bits, VS2015, Intel HD Graphics 4000.

Being a memory issue, posting memory diagnostics info (running with Alt+F2, then choosing memory) may give clues.

**Comment by YangFan789** [comment]
@KakCAT 
https://onedrive.live.com/redir?resid=133F72FD3E600053!19629&authkey=!AG7mEUB7qJHX528&ithint=file%2cdiagsession
The first snapshot is startup. Then shake mouse and memory usage increase. It is the second snapshot.The third snapshot after graphics device crash

**Comment by YangFan789** [comment]
I have a small personal engine base on SharpDX. I shake mouse like this to test my engine. My engine became slow too. it should be SharpDX

**Comment by KakCAT** [comment]
I've had a look at the logs and it seems not to be a MonoGame problem, as you said the problem is also present with your SharpDX project this is probably the culprit. Anyways SharpDX has been extensively tested and something as easy as 'moving the mouse over the window' would have been detected imho, so I wouldn't discard it's a problem with the drivers instead of SharpDX.

**Comment by YangFan789** [comment]
I test DuckGame which is base on XNA(if I don't install xna it would not run normally, so it is not base on MonoGame), it also have the same problem.
If it is a driver problem, then why the other game like gta5, lol, bf3 and etc wouldn't crash ?
As you said , SharpDX is "extensively tested", then drivers? they are not extensively tested?

**Comment by KakCAT** [comment]
Honestly, no idea.

**Comment by tomspilman** [comment]
> I test DuckGame which is base on XNA ... it also have the same problem.

If the same graphics device crash occurs with MonoGame and XNA then there isn't much we can do to fix it.

I suggest a few more things to test.  Run your test on another machine...  I suspect it won't crash.  Also be sure you have the latest drivers for your graphics device.

**Comment by YangFan789** [comment]
I've notice that HD5500 Driver is a Computer Manufacturer Graphics Driver. And the other game like gta5, lol, bf3 is not run on HD5500 but on AMD R9. So I run MonoGame on R9, and it didn't crash like before expect memory usage increase fast. I also test on another old machine, nothing happened.
So we can know that culprit is the driver. The driver had been modified but didn't test extensively.
Thanks to the help of tomspilman and KakCAT , I think I can continue working on my framework which had the same problem.

**Comment by tomspilman** [comment]
Glad to see you figured it out.
