### ISSUE TITLE
Consider adding profiling API

### ISSUE THREAD

**Issue by rds1983** [mono/MonoGame#4111]
Hi,
Right now, it's not easy to get various drawing profiling info(shader switches, draw calls, texture bindings, etc). It could be done following way:
a) Add class ProfilingInfo:
  ```csharp
  public sealed class ProfilingInfo
  {
    public int TextureBindings { get; set; }
    public int DrawCalls { get; set; }
    public int ShaderSwitches { get; set; }
    public int VertexCount { get; set; }
  }
  ```

b) Add readonly property ProfilingInfo to the GraphicsDevice class and make it updated during the rendering.

c) Then in the runtime it could used following way:
  ```csharp
  protected override void Draw(GameTime gameTime)
  {
    GraphicsDevice.ProfilingInfo.Reset();
    ...
    // Render
    ...
    // GraphicsDevice.ProfilingInfo holds the required info for the rendered frame
  }
  ```

**Comment by tomspilman** [comment]
@rds1983  - Actually we've already added a feature like this:

http://www.monogame.net/documentation/?page=P_Microsoft_Xna_Framework_Graphics_GraphicsDevice_Metrics

So you an basically do this:

```
override void Draw(GameTime gameTime)
{
     // Do some drawing!

    // Get the metrics for what you just drew.
     var metrics = this.GraphicsDevice.Metrics;

    // Draw some more stuff.

    // Get the metrics since the last metrics call.
    var metrics2 = this.GraphicsDevice.Metrics - metrics;

    // Base will call present and reset the metrics for the next frame.
    base.Draw(gameTime);
}

```

**Comment by rds1983** [comment]
Thanks for the explanation. However GraphicsMetrics seems to lack amount of shader switches and texture bindings.

**Comment by rds1983** [comment]
So my original proposal transforms to extending GraphicsMetrics with properties: PixelShaderSwitchesCount, VertexShaderSwitchesCount and TextureBindingsCount. I could implement this, actually. Will such pull request be accepted?

**Comment by tomspilman** [comment]
We kept it simple to begin with, but we figured eventually we would extend it.   You can see some of our previous discussion here:

https://github.com/mono/MonoGame/issues/3624

> PixelShaderSwitchesCount, VertexShaderSwitchesCount and TextureBindingsCount.

 I would say adding:

   - `PixelShaderCount` - Number of times the pixel shader was changed on the GPU.
   - `VertexShaderCount` - Number of times the vertex shader was changed on the GPU.
   - `TextureCount` - Number of times a texture was changed on the GPU.
   - `ClearCount` - Number of times Clear was called.
   - `TargetCount` - Number of times a target was changed on the GPU.

... would be the logical next step.  Things like the pixel and vertex shader switches will need to be hooked up at a low level in the platform specific `PlatformApplyState` and `PlatformSetTextures` calls.  Tracking clear and targets can go into the common code in `GraphicsDevice`.

@KonajuGames  @Shqrdx  @dellis1972  ?

**Comment by Shqrdx** [comment]
Ok, why not, I have free time so I will try add these members soon.

**Comment by tomspilman** [comment]
@Shqrdx - Lets wait and see what @KonajuGames thinks at least.

Also @rds1983 offered to do the work first.... if he does it we have yet one more person contributing which is always good.

**Comment by Shqrdx** [comment]
@tomspilman Ok )

**Comment by Shqrdx** [comment]
Hmm.. look like he is ignore it.. I will take this problem myself

**Comment by KonajuGames** [comment]
Sorry.  This came in during a time when I got a lot of email and this got lost in the pile.

Those extra metrics sound like a good and easy enough place to start extending GraphicsMetrics.

@rds1983 Are you wanting to add these or happy to let @Shqrdx take it on?

**Comment by Shqrdx** [comment]
Sorry. He is offline from september 3. I offered my PR too soon ? :)

**Comment by KonajuGames** [comment]
> Sorry. I offered my PR too soon ? :)

Nah. That's ok if he's been offline for a while.  It's more my bad for leaving this one hanging for too long.

**Comment by rds1983** [comment]
Sorry, the pull request has been created. It lacks the TargetCount, but other fields have been added.

**Comment by tomspilman** [comment]
@rds1983 and @Shqrdx you guys decide which PR we're going to focus on.

**Comment by rds1983** [comment]
Sorry, didnt saw the PR is already there. I suggest use Shqrdx's as it has the target count.

**Comment by Shqrdx** [comment]
me too :)

**Comment by KonajuGames** [comment]
The PR has now been merged.  Thanks @Shqrdx and @rds1983.
