### ISSUE TITLE
Feature proposal: content encryption

### ISSUE THREAD

**Issue by mrhelmut** [mono/MonoGame#4115]
Hello there,

For our coming title, we are using licensed assets and their license obliges us to "not make the assets easily readable from the game files". Which means that we are contractually bound to obfuscate in some sort a few files. While XNB packaging/compression is fine for most asset types, it isn't for Song, because this type of assets is not embedded in XNB.

Since it's something out of the scope of the original XNA, I would like to have your opinion if that would make a good feature to add to MonoGame. It isn't a trivial task so if not, we'll most likely don't bother integrating that feature deeply into MonoGame and just do some custom encryption of song files on platforms where they can be browsed.

**Comment by KonajuGames** [comment]
Song is difficult because most of the MediaPlayer implementations use system playback which assumes direct access to the media file on disk.

**Comment by tomspilman** [comment]
I would assume that XNBs are already not easily readable enough in this case.

For Song in particular things would be tricky.  Like looking at Windows and the various media player APIs...  i'm sure there is some way to let you provide a stream to it.  I just don't know how that works.

Making this feature work correctly on all platforms could be very tricky.

**Comment by KonajuGames** [comment]
Are there particular platforms you are targeting?  With Ogg Vorbis song playback you should be able to integrate on-the-fly stream decryption as it is the most flexible.  I believe you can provide your own data feed to Windows Media APIs, but it gets complex.  Other platforms such as iOS and Android are just plain difficult.

**Comment by mrhelmut** [comment]
You are right, there's a bunch of issues to embed media files, the most tricky one will most probably be XAudio, feeding it streams is not trivial.

Compression is fairly enough, the encryption part was to initiate the discussion and have your thoughts about it.

I assume that this would be relevant only to platforms that allow to freely browse game files: Windows & Linux.
OS X may not be a problem, assuming that commercial games are packaged by Xamarin.Mac into a non-browsable archive.

The proposal ends up being: an option to embed Song into XNB's on desktop platforms (and ignoring the option on non-desktop ones?) and allowing MediaPlayer to read from data streams.

**Comment by Nezz** [comment]
If you are legally required to hide your content, I would recommend you to write your own content processor and importer. The processor would do the encryption and the importer would decrypt the asset in-memory. It would act as a simple wrapper around the standard processors/importers.

This works well for all assets, except songs. For those, you need to do a bit of extra work: Before calling MediaPlayer.Play, you would have to save them in a decrypted form to the user's storage and feed that file to the MediaPlayer.

**Comment by mrhelmut** [comment]
Good point, it would be way better to handle that through custom processors.

Regarding MediaPlayer, I took a look at how would that be possible with MediaFoundation, and it sounds a bit bad. Like you said, one have to decode the song into a wma file somewhere (that's what we are doing right now in our project, with password zipped wma's using DotNetZip). The drawback is that if you don't clean the decoded file (or if the game crashes before that), users can grab the wma.
The only solution with song and MediaFoundation, is to transcode the wma to wav in memory and give that raw stream to XAudio... Sounds as dirty as to zip wma to me.

Looks like the case of Song files is a dead end.

Hence, I'm closing this "issue", assuming you would agree.
