### ISSUE TITLE
Please update the Current Roadmap

### ISSUE THREAD

**Issue by dsaf** [mono/MonoGame#4116]
It seems like at least these three are done:

> * The MonoGame 2.x series is now in maintenance mode.
> * MonoGame 3.0 will mark the start of full support for the entire XNA API.
> * The Content Pipeline is currently under development. This will allow compiling of assets to optimized formats for the MonoGame supported platforms in Visual Studio or MonoDevelop without requiring XNA Game Studio 4.0 installed.

It would be great to mention the status of the official PCL package which is in pre-release and a couple of releases behind: https://www.nuget.org/packages/MonoGame.Framework.Portable. It is not immediately obvious what is the plan even based on the discussion #3405 (which is lengthy).

**Comment by cra0zy** [comment]
The reademe file is outdated, see: #3846

**Comment by dsaf** [comment]
@cra0zy I see, thank you.
