### ISSUE TITLE
GamePad not working on Windows 7 / DirectX

### ISSUE THREAD

**Issue by mrhelmut** [mono/MonoGame#4120]
Hey there,

We are testing our game against several configurations and it appears that gamepads are no more working on Windows 7 and Vista (DirectX target).

They are correctly installed but are not detected in MonoGame. There is no crash related to any XInput version mismatch. The game works correctly but gamepad can not be pooled.

Installing a previous DirectX redist (XInput 1.3) doesn't change this.

My wild guess is that SharpDX loads XInput 9.1.0 (compatibility mode) if it can't find XInput 1.4 (Win8) and that the 9.1.0 is lacking some features useful to MonoGame.

Or am I missing a dependency?

EDIT: may be related to #3240 (and just noticed that I already pop'd that discussion over there...).

**Comment by MichaelDePiazzi** [comment]
@mrhelmut I just tried this myself and can confirm that gamepads no longer work.

I've found the problem though - The recent update of the SharpDX libraries (PR #4010) which broke sound effects on Win7 (issue #4045), has also broken gamepads.

The good news is that I can confirm that PR #4057 which fixes the sound effects on Win7 also fixes gamepads (for me at least).

**Comment by mrhelmut** [comment]
Good to know! I was suspecting that PR too. Thx!

**Comment by MichaelDePiazzi** [comment]
This can be closed now. PR #4057 which fixes it has now been merged.
