### ISSUE TITLE
What is happening with Windows Phone 8.1 ?

### ISSUE THREAD

**Issue by KakCAT** [mono/MonoGame#4129]
Hello,

I'd like to reopen this issue with some proof that CompositionTarget.Rendering is totally broken on WP8.1 (and WP10 at some extent)

* Using VS2013, crete new Visual C# -> Store Apps -> Universal Apps project. Blank App
* Add function to MainPage.xaml.cs

		void renderingFunc (object sender,object args)
		{
			renderingCount++;
		}

* Add CompositionTarget.Rendering+=renderingFunc; to the MainPage constructor.
* Add a button to the XAML and a textblock in order to print stuff. Associate this function to the button

		private void Button_Click(object sender, RoutedEventArgs e)
		{
			textBlock.Text=String.Format ("Rendering calls: {0}",renderingCount);
		}

* Run on WP8.1 device (mine is Nokia 920 , latest firmware update).Tapping the button will print the number of times Rendering has been called
* Now mash the screen with all fingers, tapping and dragging. Admitely it takes some more time than MonoGame to crash, but I can make it crash in 10-15 seconds

* Now tap the button. Tap no longer works.

OK, now the weird part. I was writing this message to show the evilness of CompositionTarget.Rendering, affecting touch, adding a huge delay to screen rotation, increasing global warming and in WP10 I think it's the culprit that sometimes randomly the touch locations are 'portrait' when should be 'landscape'.  When I thought... this is weird, I can't see why subscribing to CompositionTarget can affect this.

So, at the previous message I removed everything related to CompositionTarget, and incremented the counter each time the button was pushed. Guess what? WP8.1 still stops receiving touches.

So, creating a simple XAML app, adding a button, and mashing, makes the button (and all touch) stop working in my Nokia 920.

So, my question is... is it just an issue with my Nokia 920 or is somebody else able to reproduce this problem? Because it seems that everything with XAML in it is freezing when mashing the screen in WP8.1 mode (not a problem in WP8.0) 

EDIT: I've seen several WP8.1 only games freezing under those conditions, and apparently not using MonoGame at all, which would confirm that everything-XAML based on my Nokia 920 is affected by this problem.

**Comment by danzel** [comment]
wow :(

**Comment by jakepoz** [comment]
Ouch,

 Which games did you see freezing on WP8.1?

**Comment by KakCAT** [comment]
I tested several games several months ago before deciding not using new versions until WP10 hoping problems would disappear there. It was very easy to find problematic games because the last store told you if games were WP7.5, WP8.0 or WP8.1 games. For WP8.1 only games, there was a decent amount of chances you could find a freezing one (1 to 5 I'd say). WP8.0 and previous never had this problem.

However there's one game I remember which hung the WP8.1 and just tested it and still freezes:  Beach Buggy Racing

**Comment by KakCAT** [comment]
Candy Crush and Extreme Road Trip 2 also have this problem. I'm starting to think that there may be a problem with my Nokia 920, because I refuse to believe such games have this problem too. Could somebody please try with another WP8.1 device?

**Comment by jakepoz** [comment]
Hmm just tried Beach Buggy and Candy Crush and I didn't get the issue on my Lumia 920. 

I will test it next on my Lumia 520, where is was much easier to reproduce at least in a Monogame setting.

**Comment by KakCAT** [comment]
I decided to update my 520 to 8.1 in order to check this issue. 520 indeed does not freeze when mashing the screen with Candy Crush neither Beach Buggy, neither with my posted application.

This is probably an issue with my 920. It's a developer device which was probably one of the first WP8 devices released so there may be some kind of hardware bug which makes 920 act erratically when pushing the touch panel. Weird thing is that there's several people at #3316 (and jakepoz here) telling that this problem also appears in 520.

Maybe @nkast which tested extensively this problem some months ago may say which devices he tested this problem with.

**Comment by jakepoz** [comment]
Candy Crush does appear to work on the 520. However, we do see the issue with Monogame based games on the 520 very reliably.

**Comment by nkast** [comment]
@jakepoz, I believe older MG games targeting  wp8.0 are ok, correct?
We had a few reports for small touch lags which we were not able to reproduction, probably related to this issue, but nothing like freeze, rotation delays, etc.

**Comment by nkast** [comment]
@kakCAT 
I tested it on L620, I will be able to run your XAML tests in a few days. My phone does run weird lately, sceen goes blank immediately on phone calls, Skype isn't responsive and I have to smash buttons repeatedly to the thing react, some other apps too from time to time. Maybe something is broken or need to replace my screen protector.
Insider update is stuck at 10166 (or something) keeps rebooting after update back to WP8.1.
I would prefer to skip 8.1 entirely and wait  w10 for the next project.

**Comment by KakCAT** [comment]
Thanks,  if my XAML test doesn't block @nkast 's 620 or @jakepoz 's 520 I'll close this issue, as this is more a bug of my device than a monogame problem

I also wanted to completely skip 8.1 and port directly to w10, but w10 also have its own set of problems which I think are related to CompositionTarget.Rendering , that why I started investigating this problem again.

**Comment by nkast** [comment]
Tried to repeat it on Candy Crush Saga and  Beach Buggy Racing by  smashing my fingers on the screen. I saw no noticeable frame drops.

**Comment by KakCAT** [comment]
Thanks, I'll close the issue because it seems obvious it's a problem with my device model
