### ISSUE TITLE
Mouse.GetState() always returns 0, 0?

### ISSUE THREAD

**Issue by energyuser** [mono/MonoGame#4130]
Hello! I would like to get the attention of the devs about an issue that currently makes `MouseState` unusable. I'm using the latest dev build of MonoGame, `3.5.0.574`, I believe? So here's an example code:

```c#
protected Texture2D cursorTex;
protected Rectangle cursorRect;
protected MouseState mouseState;

public virtual void LoadContent(ContentManager Content)
{
    content = new ContentManager(Content.ServiceProvider, "Content");
    cursorTex = content.Load<Texture2D>(@"Graphics/Cursors/cursor_0");
}

public virtual void Update(GameTime gameTime)
{
    mouseState = Mouse.GetState();
    cursorRect = new Rectangle(mouseState.X, mouseState.Y, cursorTex.Width, cursorTex.Height);
}

public virtual void Draw(SpriteBatch spriteBatch)
{
    spriteBatch.Draw(cursorTex, cursorRect, Color.White);
}
```
Above, I am trying to create a custom cursor for my game. But when I debug, the cursor image stays at the `0, 0` coordinates of the screen and won't move. Could the image be the problem? It is a BMP file 32x32 pixels with magenta background for transparency.

Why do `Mouse.GetState().X` and `Mouse.GetState().Y` always return `0, 0`? I tested this exact same code in XNA and it worked (although my cursor texture had offset compared to the default windows mouse pointer). In my override methods I call `base.LoadContent(Content);`, `base.Update(gameTime);` and `base.Draw(spriteBatch);` and everything else works except the cursor. Did it work before? What was the default behavior? Can a developer test the issue as well?

**Comment by energyuser** [comment]
Upon further investigation, on a new project I tested it and the code worked. It could be my own project, but that's the only place in the project I use `MouseState`? Furthermore, this does not explain how I copied all my Monogame project files to my XNA test project and it worked there (except the cursor offset issue)... Must be some kind of behavior difference between Monogame and XNA?

**Comment by mrhelmut** [comment]
Do you remember what of project you created in the first place? (e.g. Windows, Windows GL...) And what is the type of the working one? It may be an issue related to a specific type of projects. "Windows" projects are working fine regarding this matter.
If you can reproduce it and upload a project, I'll try to take a look at it.

The offset may be normal depending on your cursorTex, but feel free to share that as well.

**Comment by energyuser** [comment]
Hello, my Monogame project was Windows project under DirectX. The test project (XNA) is of Windows Game type. Here's a link to the cursorTex: http://i.stack.imgur.com/zAHCi.png
I will upload my current project and link it to you in a moment (don't worry, it's small I haven't even gotten past the menu yet).

**Comment by mrhelmut** [comment]
If you happen to be able to share the whole solution, that'd be great. There seems to be a few dependencies and missing assets I would need to fully test that over the latest MonoGame.

**Comment by energyuser** [comment]
Whoops, I will upload them in an archive and send you a link.

**Comment by energyuser** [comment]
There it is:
http://download1072.mediafire.com/3nafnpn9uybg/v91ik5231colwu5/Content.zip
Just extract the archive and put it in `Content.RootDirectory`.

**Comment by energyuser** [comment]
You will also need to change the spritefont if you don't have the font `Andy` and `Andy italic` installed on your machine. You can use Arial.

**Comment by energyuser** [comment]
The solution (built under Visual Studio 2015):
```

Microsoft Visual Studio Solution File, Format Version 12.00
# Visual Studio 14
VisualStudioVersion = 14.0.23107.0
MinimumVisualStudioVersion = 10.0.40219.1
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "WindowsGame1", "WindowsGame1\WindowsGame1.csproj", "{9A58B18A-4692-4F1E-9278-BEC471828F11}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|x86 = Debug|x86
		Release|x86 = Release|x86
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{9A58B18A-4692-4F1E-9278-BEC471828F11}.Debug|x86.ActiveCfg = Debug|x86
		{9A58B18A-4692-4F1E-9278-BEC471828F11}.Debug|x86.Build.0 = Debug|x86
		{9A58B18A-4692-4F1E-9278-BEC471828F11}.Release|x86.ActiveCfg = Release|x86
		{9A58B18A-4692-4F1E-9278-BEC471828F11}.Release|x86.Build.0 = Release|x86
	EndGlobalSection
	GlobalSection(SolutionProperties) = preSolution
		HideSolutionNode = FALSE
	EndGlobalSection
EndGlobal
```

**Comment by energyuser** [comment]
@mrhelmut What do you think is it a MonoGame issue or it is something in my code?
