### ISSUE TITLE
SoundEffect instance has distortion after effect is played.

### ISSUE THREAD

**Issue by sforbes42** [mono/MonoGame#4144]
When trying top play a sound on Windows with the SoundEffect instance, I get distortion and/or white noise after the effect has finished playing, for about the same duration as the sound effect.
In my particular case, I am loading a sound effect via the SoundEffect.FromStream method.

The following thread has more detail regarding the issue and a possible fix.

http://community.monogame.net/t/created-soundeffect-plays-corruption-at-end/1644/7

**Comment by MichaelDePiazzi** [comment]
I recently fixed a problem like this in the Windows DirectX build (PR #4049). What version of MonoGame are you using?

**Comment by sforbes42** [comment]
I am using the latest official 3.4 build.

**Comment by sforbes42** [comment]
Michael it does look like PR #4049 is the same issue. I will go ahead and close this issue. I'll look forward to an official MonoGame release in the not too distant future. Thanks!

**Comment by DarkKoga17** [comment]
I am using MonoGame 3.4 on Ubuntu 15.04 with Monodevelop 5.9 =)

2015-09-20 0:47 GMT-03:00 Michael De Piazzi <notifications@github.com>:
