### ISSUE TITLE
SpriteBatch not rendering

### ISSUE THREAD

**Issue by dhdguysg** [mono/MonoGame#4160]
## Main issue
I've been working on a 2D game where you can build, but I am having issues working with cursors, I'm attempting to use a SpriteBatch cursor, but it isn't drawing at all, The blocks draw fine, but the cursor still refuses to draw. 
## Code
I have everything defined, Here is the block that has issues though
```c#
spriteBatch.Draw(cursor, cursorPos, Color.Transparent);
```
Nothing is rendering here,
## Edits
I changed the code from the old one in Code, to
```c#
spriteBatch.Draw(cursor, cursorPos, Color.WhiteSmoke);
```
It draws in the topleft corner, but still isn't drawing where I want it to.

**Comment by danzel** [comment]
You probably don't want to specify the cursor color at all, or use Color.White if you do.

What are your ```.Begin``` and ```.End``` calls on the SpriteBatch?
Check you are updating the ```cursorPos``` variable?

**Comment by vchelaru** [comment]
This feels like a support question and not a bug .

@dhdguysg Please review docs on how to use SpriteBatch. Lots of XNA resources exist, and you can see proper Monogame docs here:

http://developer.xamarin.com/guides/cross-platform/game_development/monogame/introduction/
