### ISSUE TITLE
Thumbstick inputs being clipped when using circular deadzone

### ISSUE THREAD

**Issue by MichaelDePiazzi** [mono/MonoGame#4170]
I've been working on improving and fine-tuning controller input for my game recently, and I've noticed when using the circular deadzone setting that the thumbsticks feel a bit too touchy.

After doing some investigation, I found that the method being used in MonoGame seems to be incorrect. Here is a graph showing what it's currently doing. The colours represent the resulting thumbstick vector length: Blue = 0 (i.e. the deadzone), Green = Normal range, Yellow = 1 (i.e. full movement)
![circular_deadzone_with_circular_gate](https://cloud.githubusercontent.com/assets/5249498/10328138/1e79c7c8-6ce3-11e5-980a-e3cbdbe7ccd6.png)
So you can see from the big thick yellow area that the values are being clipped. This results in a halfway movement of the thumbstick being equivalent to a full movement. This is not what I'd expect. And looking at Shawn Hargreaves blog article on this subject (http://blogs.msdn.com/b/shawnhar/archive/2007/03/28/gamepads-suck.aspx), the graphs he provided don't seem to show any clipping being done like this. So I'm assuming this behaviour is actually incorrect.

This is my expectation of what the graph should actually look like (which is in line with Shawn Hargreaves graph):
![new_method_with_circular_gate](https://cloud.githubusercontent.com/assets/5249498/10328141/24f2b6c8-6ce3-11e5-8b45-1e5d9ba278af.png)

Unless anyone has reason to believe I'm wrong about this, I'm planning to submit a PR soon which corrects this.

Also on a related note - While looking into this, I came across the GamePadThumbSticks.Gate property. I can't seem to find this in XNA, so I assume it's been added to MonoGame for some reason? I'm not sure exactly why this setting is needed, but the default for it is GateType.Round (which normalises the thumbstick vector if it's length is greater than 1). So if I set it to GateType.None, then the above graph now looks like this:
![circular_deadzone_with_no_gate](https://cloud.githubusercontent.com/assets/5249498/10328143/2b1bbc48-6ce3-11e5-983a-b8c8b9039419.png)
Red means that the vector length exceeds the expected maximum of 1. So basically GateType.Round was hiding these out of range values coming from the circular deadzone function.

Does anyone know why this Gate property was added to MonoGame? It seems unnecessary as the deadzone setting could be controlling this (ie. GamePadDeadZone.IndependentAxes => GateType.Square,  GamePadDeadZone.Circular => GateType.Round, GamePadDeadZone.None => GateType.None). I have a funny feeling that it might have been added to correct these out of range values, so it might be unnecessary if this was the reason.

**Comment by tomspilman** [comment]
This sounds reasonable, but I haven't looked into it myself very much.  @mrhelmut was the last person to look at the deadzone code, so maybe he has something to add here.

Also keep in mind that we want to use the same deadzoning technique on all the platforms with small tweaks for hardware differences.  So lets make sure the final code is in one place to be shared by all the platforms.

**Comment by MichaelDePiazzi** [comment]
@tomspilman No problem. The fixes I'm planning are only going to be done in the GamePadThumbSticks class, so this will be shared by all platforms.

**Comment by MichaelDePiazzi** [comment]
FYI - I just found that the GamePadThumbSticks.Gate property was introduced in PR #94, but unfortunately there wasn't any explanation given as to why it was necessary for MonoGame when XNA doesn't have it.

**Comment by tomspilman** [comment]
I would say it isn't needed... sounds like an enhancement that was added back then.  Seems like it would be better for people to use `GetState` with `GamePadDeadZone.None` and do their own custom filtering in those cases.

**Comment by MichaelDePiazzi** [comment]
Ok cool, I will remove it then. But I might submit that as a separate PR to the circular dead zone fix so that it doesn't potentially hold it up.

**Comment by tomspilman** [comment]
That would be fine.

**Comment by mrhelmut** [comment]
My bad, thanks for fixing that. :)

**Comment by MichaelDePiazzi** [comment]
@mrhelmut No worries :)
