### ISSUE TITLE
Latest commit has missing implementation for GamePad.UWP.PlatformGetMaxIndex()

### ISSUE THREAD

**Issue by LoveDuckie** [mono/MonoGame#4174]
The most recently made commit by @tomspilman introduces an issue whereby the implementation for PlatformGetMaxIndex() is missing from the UWP partial class implementation of GamePad. Leads to compilation errors.

**Comment by LoveDuckie** [comment]
FYI: https://github.com/mono/MonoGame/commit/a10b8094b0e44a8401639b843ae77cd8fff5e7a5

**Comment by danzel** [comment]
This can be closed now @tomspilman
