### ISSUE TITLE
GameHasControl always returns true on iOS regardless of background music.

### ISSUE THREAD

**Issue by vchelaru** [mono/MonoGame#4185]
To reproduce:

1. Create a MonoGame iOS project
1. Open Spotify
1. Begin playing music on spotify
1. Run the game
1. Check ```Microsoft.Xna.Framework.Media.MediaPlayer.GameHasControl```

Expected: ```Microsoft.Xna.Framework.Media.MediaPlayer.GameHasControl``` should return false if background music is playing
Actual results: ```Microsoft.Xna.Framework.Media.MediaPlayer.GameHasControl``` returns true regardless of whether background music is playing.

**Comment by vchelaru** [comment]
On further research it seems like launching the monogame game stops background music from playing - so the property may actually be correct, but there's something else going on here. I'll update as I find more...

**Comment by vchelaru** [comment]
There seems to be something else going on with audio automatically stopping.

**Comment by danzel** [comment]
Dupe of #735 ?

**Comment by vchelaru** [comment]
Thanks @danzel , that is indeed it, and seems to have died at the beginning of 2013.
