### ISSUE TITLE
"Copy Task does not support copying directories" UWP build issue

### ISSUE THREAD

**Issue by DDReaper** [mono/MonoGame#4192]
Trying to port a project over to a new UWP project and getting some real troubles with the latest 3.5 builds (3.4 does not work anymore at all)

When trying to build the project, I am getting the following error:
"Severity	Code	Description	Project	File	Line
Error		The source file "C:\Development\Sandbox\MonoGameUWP1\MonoGameUWP1\Content\bin\WindowsStoreApp\" is actually a directory.  The "Copy" task does not support copying directories.	MonoGameUWP1"

Which seems to indicate a fault in the MGCB build process for copying the content folder.  Note, my content folder is actually blank (new project).

Also a related issue, is that the MG project is not usable when you create it fresh, as you have to close and reopen it else loads of references do not show up.

**Comment by tomspilman** [comment]
Can you link the content of the project file that is failing here?

**Comment by DDReaper** [comment]
I've receated a brand new project from scratch. 
1: Adding MG references and starting the project works fine
2: As soon as I add the imports for MGCB and add a content project (set as MonoGameContentBuilder), the issue surfaces.

So something in the MSBuild task is failing.  Some Gogle searches point to this as a new cause for concern in MSBuild projects.  Take this post on the MSBuild team blog - http://blogs.msdn.com/b/msbuild/archive/2005/11/07/490068.aspx

**Comment by DDReaper** [comment]
Note @tomspilman it's not the content project (I don't beleve) as I'm testing the "New UAP MG Project template" so the ContentProject it'self is blank.  It seems to be the post build MSBuild copy process.
I've also tested with a clean project to ensure it's not a template issue.

**Comment by DDReaper** [comment]
As another side note, the UAP template sets the Project type (in .csproj) as WindowsStoreApp.

Is this correct?

**Comment by DDReaper** [comment]
I also tried deleting the Content Project and the following error appears:
Severity	Code	Description	Project	File	Line
Error		The command ""C:\Program Files (x86)\MSBuild\MonoGame\v3.0\Tools\MGCB.exe" /@:"" /platform:WindowsStoreApp /outputDir:"C:\Development\Sandbox\UWPApp1\UWPApp1\Content\bin\WindowsStoreApp" /intermediateDir:"C:\Development\Sandbox\UWPApp1\UWPApp1\Content\obj\WindowsStoreApp" /quiet" exited with code -532462766.	UWPApp1		
Which seems bad practice, MG shouldn't assume a Content project is mandatory surely?

**Comment by tomspilman** [comment]
> MG shouldn't assume a Content project is mandatory surely?

I wouldn't be surprised that we don't gracefully support deletion of the content project created with the template.  It just isn't a usage scenario I tested when I created it.

That said we should fix that.

**Comment by DDReaper** [comment]
OK, usage aside .

Any thoughts to the MSBuild / MGCB issue?  Seems to stop the ability to have MGCB's in the project at all presently.
Attached the project for reference, however it is just a New project using the UAP template
https://www.dropbox.com/s/6jjzb9c77u7uptm/MonoGameUWP1.zip?dl=0

**Comment by tomspilman** [comment]
I assume here the project that is failing is `MonoGameUWP1.csproj`...

https://gist.github.com/tomspilman/9e76e944d9cacd70d4ce

... correct?

**Comment by DDReaper** [comment]
Yes, that looks about right.  THat is what the UAP template is creating at the moment.

**Comment by tomspilman** [comment]
Well I see no copy task in that project.  The only other suspect here is the MGCB build targets file which also doesn't include a copy task, but maybe it is generated internally from the `<Content>` tag:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework.Content.Pipeline/MonoGame.Content.Builder.targets#L90

First be sure the targets file located at `$(MSBuildExtensionsPath)\MonoGame\v3.0\MonoGame.Content.Builder.targets` is up to date on your machine.

**Comment by DDReaper** [comment]
I've recreated the issue manually.
By creating a brand new project and adding the MGCB import definitons in to the .csproj.

I've installed the latest successful 3.5 installer from Jenkins, it seems to all look fine.  So it's something kicked off in the MCGB build.  Most likely the post MGCB copy task (my guess)
How does MGCB copy the build content files to the build project currently?

**Comment by tomspilman** [comment]
> How does MGCB copy the build content files to the build project currently?

The link I posed above...

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework.Content.Pipeline/MonoGame.Content.Builder.targets#L90

... is exactly how it happens.  MGCB builds into its own obj/bin files then the standard C# `<Content>` task to do the copy for us.

I suspect the issue is either...
```
Include="$(ParentOutputDir)\%(ExtraContent.RecursiveDir)%(ExtraContent.Filename)%(ExtraContent.Extension)" 
```
... or ....
```
<Link>$(ContentRootDirectory)\%(ExtraContent.RecursiveDir)%(ExtraContent.Filename)%(ExtraContent.Extension)</Link>
```
... within the `<Content>` task.  Those might be expanding to an empty folder and when the `<Content>` task is processed in the bowels of MSBuild and becomes a `<Copy>` task that it ends up failing.

**Comment by DDReaper** [comment]
Right, you got me thinking and I found the root cause of the issue and It's becase it IS a BLANK project.
Bascially, the MGCB didn't have anything to build, so the Content folder was empty, so all MSBUILD was trying to do was copy an Empty folder.

Granted, this is not a great experience, but not a showstopper.
Possibly we could have a "dummy" file in the Content Folder so this doesn't occur, far simplier than trying awkward fixes to the build process / config?

**Comment by cra0zy** [comment]
This issue also occurs with WindowsDX/GL templates, and probably with the other templates as well.

Targets file(MonoGame.Content.Builder.targets) has been changed 6 days ago so it's probably something that has been changed there that's causing the issue: https://github.com/mono/MonoGame/pull/4152/files

**Comment by DDReaper** [comment]
Interesting, so we have two separate issues related to New or Empty projects and It's not just UWP.

As that file is also the MD plugin, can I assume this is affecting MD deployments as well @cra0zy ?

**Comment by tomspilman** [comment]
> Targets file(MonoGame.Content.Builder.targets) has been changed 6 days ago 

Ah... that now makes sense.

@dellis1972 - Can you take a look at your changes and see what needs to be fixed here for both Windows and XBuild support?

**Comment by dellis1972** [comment]
@tomspilman I'll see if I can replicate on my Windows 10 VM and see what we can do.

**Comment by dellis1972** [comment]
@tomspilman @DDReaper PR is up https://github.com/mono/MonoGame/pull/4196 :)

**Comment by DDReaper** [comment]
Ok, grabbing the setup and testing

**Comment by DDReaper** [comment]
Confirmed, fix is good. Empty MGCB file builds and runs correctly now
