### ISSUE TITLE
Windows DirectX: WinFormsGameWindow.UpdateWindows generating garbage

### ISSUE THREAD

**Issue by MichaelDePiazzi** [mono/MonoGame#4199]
I've recently been profiling my game a bit (using CLRProfiler) to try and find code generating excess garbage, and I came across the following from MonoGame (this is from the heap allocation graph):
![profile1](https://cloud.githubusercontent.com/assets/5249498/10633916/b1f0a33a-7820-11e5-8eff-3c8e69372028.png)
I took a closer look at the method in question and found that there was some LINQ being used which seemed to be the culprit:
```C#
foreach (var window in _allWindows.Where(w => w.Game == Game))
    window.UpdateMouseState();
```
So I changed it to the following and that seemed to clean it up:
```C#
foreach (var window in _allWindows)
    if (window.Game == Game)
        window.UpdateMouseState();
```
![profile2](https://cloud.githubusercontent.com/assets/5249498/10634004/4c46f218-7821-11e5-9358-4133ba7a68ee.png)
I looked at UpdateMouseState also, but these allocations seemed to be coming from the .NET Framework itself so I assume there's not much that can be done about that.

If I'm correct about this, I'm more than happy to submit a PR. I just thought I'd raise an issue first to see what others thought as I'm fairly new to reducing garbage generation (my C# experience so far was mainly in business software dev).

**Comment by KonajuGames** [comment]
Absolutely submit a PR.  LINQ is well known for garbage generation.

**Comment by MichaelDePiazzi** [comment]
Cool, thanks @KonajuGames. Just submitted PR #4200 for this.

**Comment by MichaelDePiazzi** [comment]
PR has been merged, so I'll close this now.

**Comment by KonajuGames** [comment]
If you put "Fixes #4199" in the PR message, it will automatically close the issue when the PR is merged.

**Comment by MichaelDePiazzi** [comment]
Cool, I didn't know that. I'll be sure to do that in future. Thanks for the tip!

**Comment by theZMan** [comment]
I"m pretty sure the emtpy XNA template also suffers from garbage in the underlying Mouse code too so there's a pretty good chance you can't get rid of it.

However at least on PC level 0 garbage collections have never been an issue and the mouse code never ran on the xbox. I have no clue what happens with Xamarin and on the other platforms though.
