### ISSUE TITLE
SpriteBatch rendering is not smooth

### ISSUE THREAD

**Issue by bousquetm** [mono/MonoGame#4202]
Hi all,

I've noticed an issue with SpriteBatch rendering on WindowsGL platform (does not occur on Windows DX nor XNA 4.0). When drawing a sprite that moves at constant speed, the animation "stutters" and is not smooth, even though the program runs at 60fps. It seems that sometimes the draw is delaye or something.

Here's a very simple example to reproduce the bug (the texture red is just a 64x64 red texture):

```C#
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;

namespace MonogameTest
{
	public class Game1 : Game
	{
		public Game1()
		{
			_graphics = new GraphicsDeviceManager(this);
			Content.RootDirectory = "Content";
			IsFixedTimeStep = true;
		}

		////////////////////////////////////////////////////////////////////////// Override Methods

		protected override void LoadContent()
		{
			_spriteBatch = new SpriteBatch(GraphicsDevice);
			_texture = Content.Load<Texture2D>("red");
			_pos = Point.Zero;
		}

		protected override void Update(GameTime gameTime)
		{
			if (Keyboard.GetState().IsKeyDown(Keys.Space))
			{
				_pos.X = 0;
			}
			_pos.X += 6;

			base.Update(gameTime);
		}

		protected override void Draw(GameTime gameTime)
		{
			GraphicsDevice.Clear(Color.CornflowerBlue);

			_spriteBatch.Begin();
			_spriteBatch.Draw(_texture, _pos.ToVector2(), Color.White);
			_spriteBatch.End();

			base.Draw(gameTime);
		}

		////////////////////////////////////////////////////////////////////////// Private Members

		private GraphicsDeviceManager _graphics;
		private SpriteBatch _spriteBatch;
		private Texture2D _texture;
		private Point _pos;

	}
}
```

I've reproduced it Monogame 3.4 and also with the last unstable version (currently 3.5.0.703). I also tried on 2 different computers, same problem with both.

Thanks in advance!

Martin

**Comment by KonajuGames** [comment]
Log out the value of gameTime and see if it has any fluctuations.

**Comment by bousquetm** [comment]
I logged the gameTime value in Update and Draw: no fluctuations, I'm always at 16.667ms. Just to be sure, I also removed IsFixedTimeStep = true in the constructor.

**Comment by MichaelDePiazzi** [comment]
@bousquetm I assume you're using fixed timed step? i.e. `Game.IsFixedTimeStep = true` (which is the default setting). In this case, the gameTime values aren't the actual elapsed times - it's the target elapsed time (which will always be 16.667ms). So instead, try measuring the time between draw calls yourself (e.g. using a stopwatch) and see if that shows any fluctuations.

But just looking at the MonoGame code for fixed time step, it may be possible that there could be noticeable fluctuations. MonoGame is currently using the "Sleep" function to delay until it's time to update, but the accuracy of the sleep function is dependant on the timer resolution (which can vary greatly). If the resolution is 15 ms (which is typical), then sleeping for 1ms may actually sleep for up to 15ms.

I've had problems with the accuracy of Sleep before in my own code, so I may be able to help in this area. I have quite a solid solution for Windows which measures the current resolution of the timer (using the Windows API) and takes that into consideration. I'm not sure how to go about this on other platforms though.

**Comment by nkast** [comment]
@MichaelDePiazzi 
I agree, We can't depend on the OS to give back the core exactly after `sleepTime` milliseconds.
We can allow a small threshold, sleep only for (sleepTime-sleepThreshold) and Spinlock for the rest.

Plus, On windows store projects the sleep function generates garbage by creating a new Task object.
https://github.com/mono/MonoGame/blob/0b25f56e861fb602db884c40267b99ea947bae15/MonoGame.Framework/Game.cs#L438

**Comment by bousquetm** [comment]
I added Game.IsFixedTimeStep = false in the constructor of my class and measured the time between draw calls with a Stopwatch. As predicted, even if it is generally accurate, the time shows some peaks that can go up to 37ms!

What bothers me is that this happen only with WindowsGL, not with DirectX (maybe that's because another Sleep() method is used in SharpDX?).

**Comment by tomspilman** [comment]
> We can allow a small threshold, sleep only for (sleepTime-sleepThreshold) and Spinlock for the rest.

That is probably the best we can do.  However an experiment with `Monitor.Wait` could be interesting.

The sleep is there to allow desktop windowed games to free up unused CPU cycles.  If not a match 3 puzzle game would consume 100% of a core mostly spin locked waiting for the timer to do the next tick.  We also here used it internally when spawning several test clients of a game on the same PC for automated stress testing.  Having all instanced consuming 100% of a core with unnecessary timer spinlock work limited our testing time.

On mobile and consoles... the sleep is possibly never needed.

**Comment by MichaelDePiazzi** [comment]
> I added Game.IsFixedTimeStep = false in the constructor of my class

Ok, that's weird then... if you're still seeing fluctuations with IsFixedTimeStep disabled, then it must be something else as MonoGame doesn't use Sleep in this case.

I tried setting up a simple WindowsGL test project similar to yours, but I get quite a smooth frame rate with no noticeable fluctuations regardless of what settings I use...

What version of MonoGame are you using? Are you using the latest version from GitHub?

**Comment by MichaelDePiazzi** [comment]
@nkast @tomspilman

> I agree, We can't depend on the OS to give back the core exactly after sleepTime milliseconds.
> We can allow a small threshold, sleep only for (sleepTime-sleepThreshold) and Spinlock for the rest.

If the fluctuations from Sleep do prove to be enough of an issue, then this is probably a good cross-platform compromise. I'd also suggest to maybe only use a `Sleep(1)` each time to reduce the chance of overshooting. e.g.
```c#
if (IsFixedTimeStep && _accumulatedElapsedTime < TargetElapsedTime)
{
    var sleepTime = (int)(TargetElapsedTime - _accumulatedElapsedTime).TotalMilliseconds;
    if (sleepTime > sleepThreshold)
        Thread.Sleep(1);
    goto RetryTick;
}
```

The solution for Windows I'm using, while quite accurate, uses an undocumented Windows API method (NtQueryTimerResolution). So obviously not a solution that will work for any other platforms. And because it's undocumented, probably not something that can be relied on in future even for Windows... :stuck_out_tongue:
Here's the code anyway for those that are interested:
```c#
[DllImport("ntdll.dll", SetLastError = true)]
private static extern int NtQueryTimerResolution(out int MinimumResolution, out int MaximumResolution, out int CurrentResolution);

/// <summary>
/// Returns the current timer resolution in 100ns units
/// </summary>
public static int GetCurrentResolution()
{
    int min, max, current;
    NtQueryTimerResolution(out min, out max, out current);
    return current;
}

/// <summary>
/// Sleeps as long as possible without exceeding the specified period
/// </summary>
public static void SleepForNoMoreThan(double milliseconds)
{
    var timerResolution = GetCurrentResolution();
    int adjustedTime = (int)(milliseconds * 10000);
    if (timerResolution > adjustedTime)
        return;
    var tickCount = adjustedTime / timerResolution;
    int adjustedSleepTime = (((tickCount - 1) * timerResolution) / 10000) + 1;
    Thread.Sleep(adjustedSleepTime);
}
```

> Plus, On windows store projects the sleep function generates garbage by creating a new Task object.

Good spot!

> The sleep is there to allow desktop windowed games to free up unused CPU cycles. If not a match 3 puzzle game would consume 100% of a core mostly spin locked waiting for the timer to do the next tick.

I completely understand and agree this is important. I've personally noticed on laptops in particular that if you're not using Sleep when you can, then they have a tendency to overheat quickly due to the high CPU usage.

However, XNA does seem to be spinning the CPU. Doing a comparison between MonoGame and XNA using fixed time step and no v-sync, XNA utilises 100% of a core (and for some reason runs at 61 fps?!? Maybe an XNA bug?) while MonoGame uses very little (obviously due to Sleep being used). So perhaps another solution for people who need precise timing and don't care about the CPU usage (i.e. XNA behaviour) would be to add a MonoGame specific property to enable/disable spin waiting? (e.g. `Game.UseSpinWaiting` with a default of false)

Although, in saying all of this, it doesn't sound like this is the problem with bousquetm's issue...

**Comment by StunGunStudios** [comment]
The strange choppy movement is something I've observed with both a basic WindowsGL 2D and 3D project. Not a big deal to me, since I use DirectX, though. I'm using a recent installation from the build server.

**Comment by MichaelDePiazzi** [comment]
@StunGunStudios @bousquetm
Hmmm... I have another thought... Do you have v-sync enabled? i.e. `GraphicsDeviceManager.SynchronizeWithVerticalRetrace = true` (which is the default setting). And if so, what is the refresh rate of your monitor?

**Comment by StunGunStudios** [comment]
Yeah, I hadn't changed the defaults, and setting it to true in the initialize method didn't change anything.

**Comment by MichaelDePiazzi** [comment]
@StunGunStudios Ok. But what is the refresh rate set to for your monitor? Is it 60Hz, or something different?

**Comment by StunGunStudios** [comment]
Yeah, it's set to 60p Hz, according to Intel HD Graphics Manager.

**Comment by MichaelDePiazzi** [comment]
@StunGunStudios Ok, well there goes that theory :) I thought it might've had something to do with updates running at 60Hz, but then the monitor running at a different frequency (e.g. 50Hz). Guess not though.

**Comment by StunGunStudios** [comment]
It's really weird that—unless I'm imagining it—the stuttering seems to occur more when there's a debugger attached and it's run in debug mode, and less when run in release mode with no debugger. That would seem to indicate CPU usage problems, which makes no sense when the program is using so little CPU and it's just a little square moving around a cornflower blue screen.

**Comment by StunGunStudios** [comment]
Also, I logged the gameTime in the draw method, and with IsFixedTimeStep set to false, I get values anywhere from 0157931 to 0206435, though mouse of them are around 016. With IsFixedTimeStep set to true, they're all 0166667 except for at the start.

**Comment by MichaelDePiazzi** [comment]
> Also, I logged the gameTime in the draw method, and with IsFixedTimeStep set to false, I get values anywhere from 0157931 to 0206435, though mouse of them are around 016. With IsFixedTimeStep set to true, they're all 0166667 except for at the start.

Makes sense. When using fixed time step, game time returns the target time step (which is 16.7ms by default). With it disabled, game time returns the actual elapsed time and shows up the fluctuations you're experiencing. So to find the actual elapsed time when using fixed time step, you have to measure it yourself (e.g. with a stopwatch).

Maybe try setting `Game.IsFixedTimeStep = true`, and `GraphicsDeviceManager.SynchronizeWithVerticalRetrace = false` (be sure to either set this in your `Game` class constructor, or call `GraphicsDeviceManager.ApplyChanges` after setting it). MonoGame should then limit updates to 60Hz without being influenced by v-sync. Measure the time between updates using a stopwatch and see if you get a more stable result then. If you do get a stable result, then the issue may be related to the WindowsGL v-sync implementation.

**Comment by nkast** [comment]
>which makes no sense when the program is using so little CPU 
The other day I was doing some profiling and getting very erratic results from frame to frame. It turns out it was the Power balance. Because the program was doing so little, sleeping most of the time, the CPU frequency was falling from 100% to 40% and back to 100% every few frames. Maybe in your case this cause frame drops/inconsistent frame rate. Go to "Power Options" and check if your profile is set to `Balanced` and change it to `High Performance`.

**Comment by bousquetm** [comment]
@MichaelDePiazzi I tried a few different version: the 3.4 version, the latest unstable version (3.5.0.703), and I compiled the version from source from the git repo, the problem happens on all versions.

I did some profiling and it seems that the issue lies in PlatformPresent() of GraphicsDeviceOpenGL.cs. I logged the use of Context.SwapBuffer() using:

```C#
Stopwatch watch = Stopwatch.StartNew();
Context.SwapBuffers();
watch.Stop();
double time = watch.Elapsed.TotalMilliseconds;
Debugger.Log(0, "", "" + time + "\n");
```

And the result is very erratic... Here the result of the ouput console (in ms):

14.9283
14.6689
15.1128
15.1272
14.7734
28.1945
0.0769
0.0734
4.3861
15.3425
14.8273
9.9379
14.97
14.8636
14.6239
14.9514
14.98
31.7239
0.0712
13.0714
15.1503
15.0567
14.7853
14.972
14.0267
14.7683
14.9601

This seems to be a resolved issue in OpenTK (https://github.com/opentk/opentk/issues/43) but maybe it hasn't been merged in Mobnogame (I don't know what version of OpenTK is used).

**Comment by MichaelDePiazzi** [comment]
@bousquetm Hmmm... well as best as I can tell the fix for that OpenTK issue should be in MonoGame already. The fix was done in January, and the version of OpenTK in MonoGame is from July. I may be wrong though. Can anyone else confirm this?

Did you try disabling v-sync to see if that stabilises things? (see my previous comment)

**Comment by StunGunStudios** [comment]
> Maybe try setting  Game.IsFixedTimeStep = true...

I'll try this out later today.

> Go to "Power Options" and check if your profile is set to  Balanced  and change it to  High Performance .

I've got power options set to a custom level, where the minimum CPU state is always set to 100 percent. Basically just a custom High Performance plan. But just to be certain, I changed it to High Performance and the issue didn't go away.

**Comment by StunGunStudios** [comment]
@MichaelDePiazzi Setting IsFixedTimeStep to true and SynchronizeWithVerticalRetrace to false seems to significantly improve the stutters, but it does not eliminate them. The log gives values that are, for the most part, 16 and 15, with fairly consistent jumps to 30 or 32 every fifteen or so Update calls, and occasional drops to 1. There's a pattern involved with the drops to one, though— it's almost always 32 - 1 - 30, then back to 16 and 15 until the next spike.

**Comment by MichaelDePiazzi** [comment]
@StunGunStudios
Ok, so v-sync is playing a part here. But if you're still getting stutters when it's off, then this must be coming from the inaccuracy of the Sleep function.

When you see it spike up to 30+ms, it's "overslept" so to speak. And then it makes sense that it would drop to 1-2ms after that because MonoGame would then try to play catch up to get the average update frequency back to 60Hz.

Try measuring your timer resolution while running your test using this code:
```c#
[DllImport("ntdll.dll", SetLastError = true)]
private static extern int NtQueryTimerResolution(out int MinimumResolution, out int MaximumResolution, out int CurrentResolution);

/// <summary>
/// Returns the current timer resolution in 100ns units
/// </summary>
public static int GetCurrentResolution()
{
    int min, max, current;
    NtQueryTimerResolution(out min, out max, out current);
    return current;
}
```
The `GetCurrentResolution` method will give you back the current timer resolution in 100ns units, so 1ms = 10000.

For me, the timer resolution is getting switched to 1ms whenever I run either a OpenGL or DirectX MonoGame project. But if I'm right, you'll get back 15.6ms (which is the normal value for modern Windows).

So let me know what you find, and we'll go from there...

**Comment by StunGunStudios** [comment]
Okay, these tests were conducted in Release mode.

With 

>IsFixedTimeStep = true;
>graphics.SynchronizeWithVerticalRetrace = false;

in the Game1 constructor, the stuttering problems have now seemed to all but vanish. GetCurrentResolution returns 10007, except when it very occasionally returns 5003. With those lines not present in the constructor, the stuttering problems return, but GetCurrentResolution seems to return 5003 much less frequently.

And this is weird, because, unless I'm horribly mistaken, earlier I had those two lines in the constructor and the stuttering was still there, albeit reduced.

**Comment by StunGunStudios** [comment]
Switching back to the original output, with the previously mentioned lines in the constructor, the output for how many milliseconds pass before each Update is called stays around 16,  and 17 now, with the occasional 15 or 18.

**Comment by MichaelDePiazzi** [comment]
@StunGunStudios 
So your timer resolution is currently between 0.5-1ms. Basically anything can change the timer resolution, so I'm guessing that another process has lowered it. Common culprits are multimedia applications, games, web browsers, etc. I've even see Visual Studio change it.

So first of all, get your hands on a tool which will measure the timer resolution. Sysinternals has a command line one here: https://technet.microsoft.com/en-us/sysinternals/bb897568. I also found a C# GUI version here: https://github.com/tebjan/TimerTool (I didn't try this one though)

Then I'd close all your currently open apps. If you then run your measurement tool, you should hopefully find that the timer resolution has reverted to the normal value of 15.6ms. Then just run the compiled binary of your test program and you should find the stuttering is back (and if I'm right, the timer resolution will remain at 15.6ms).

**Comment by StunGunStudios** [comment]
@MichaelDePiazzi Sorry, I accidentally did the tests wrong. So the results of the tests are this:

With 

>IsFixedTimeStep = true;
>graphics.SynchronizeWithVerticalRetrace = false;

in the constructor, the elapsed milliseconds before each Update call is 16 or 17, with 15 or 18 appearing occasionally. GetCurrentResolution more or less always returns 10007. The stuttering is gone. Without the two lines, the stuttering reappears, but the results of the test or more or less the same, with a single drop to 9 ms that I can find.

**Comment by StunGunStudios** [comment]
@MichaelDePiazzi You're right on. Before I closed all the applications, ClockRes gave me a reading of 1 ms. When I closed everything, it switched to 15.6-ish. Then, when I just ran the binary for the test project, the stuttering was back and really bad.

**Comment by MichaelDePiazzi** [comment]
@StunGunStudios Aha... and did the timer resolution remain at 15.6ms while running the test project? And what happens when you run the project using DirectX instead?

**Comment by StunGunStudios** [comment]
Yep. Running the OpenGL test app, the resolution stayed at 15.625. When I ran a DirectX project, though, the resolution switched to 1.001.

**Comment by StunGunStudios** [comment]
@MichaelDePiazzi Wait, hold on, it only switched to 1 when I ran the game I've been working on for a while. For some reason, when I run the DirectX equivalents to the simple square/cube moving projects, the resolution still stays at 15.625... but with no choppiness.

**Comment by StunGunStudios** [comment]
Okay, so the culprit for the DirectX versions becoming choppy was graphics.SynchronizeWithVerticalRetrace = false;

When I removed that line, the choppiness went away, but the resolution stayed at 15.625. However, as I said before, when I run the game I'm currently working on, the resolution goes to 1.001. Maybe that's because my game has a lot more going on than the test projects?

**Comment by MichaelDePiazzi** [comment]
@StunGunStudios
Very interesting...

Well, the 15ms timer resolution is definitely related to the stuttering. If the stuttering goes away for DirectX when you enable v-sync (i.e. removing `SynchronizeWithVerticalRetrace = false`), that just tells me that SharpDX/DirectX is better at handling the lower timer resolution than OpenTK/OpenGL is.

I'm not sure what causes it to drop to 1ms though. I can't see MonoGame, OpenTK, or SharpDX changing the timer resolution. So I can only assume that this is something that the video drivers are changing under certain conditions to get more accurate timing.

Anyway, let's now try and prove if the Sleep in MonoGame is the culprit.

1. Grab the latest MonoGame source and open the WindowsGL project.
2. Open the `Game.cs` class and find the `Tick` method.
3. Comment out this line: `System.Threading.Thread.Sleep(sleepTime);`
4. Run your test project using this modified version of MonoGame (make sure you leave in the `SynchronizeWithVerticalRetrace = false` though)

This will basically cause the CPU to "spin" until it's time to update (which will result in 100% CPU usage), but should mean accurate timing. If the Sleep function is the culprit, then the stuttering should be gone. Let me know what you find.

**Comment by StunGunStudios** [comment]
@MichaelDePiazzi  Uh, that might be a little difficult. I've tried building Monogame from source once or twice, and I guess I just don't have the know-how, because I've never succeeded. Visual Studio always tells me there's about 33378 compile-time errors, which happens when I run Protobuild and then open the Monogame.Windows solution and try to build it.

**Comment by MichaelDePiazzi** [comment]
@StunGunStudios No probs, I can make the change and provide you with the binaries. Gimme a few mins...

**Comment by MichaelDePiazzi** [comment]
@StunGunStudios Here you go: http://plus7software.com/downloads/MonoGame.WindowsGL.CpuSpinTest.zip

**Comment by StunGunStudios** [comment]
Thanks. As expected, the new dlls run the CPU usage up to 25 percent, but the stuttering is gone.

**Comment by MichaelDePiazzi** [comment]
@StunGunStudios
Great, this proves `Sleep` is to blame! Now try this version:
http://plus7software.com/downloads/MonoGame.WindowsGL.SleepTest.zip

This version uses Sleep more conservatively to try and get timing more accurate. So give this a run and see what results you get, it should hopefully be more stable.

I've also added a property named `SleepThreshold` to the `Game` class so you can tweak things. The default is `1.0`. Increasing it will increase timing accuracy at the cost of increased CPU usage. A value of `16.7` will be maximum accuracy (and maximum CPU usage). So really we're looking for the smallest value we can get without noticeable stuttering.

Let me know what you find.

**Comment by StunGunStudios** [comment]
@MichaelDePiazzi I can get SleepThreshold down to about 9.5 before the stuttering starts to become noticeable. This is just with a simple cube moving around an empty screen, though. I can try porting my current game to OpenGL, but it will probably take some time since I have a lot of classes and I don't know of any way to turn a DirectX project into an OpenGL one other than starting a new project and copying and pasting all the code.

@bousquetm Can you run some tests with your code and find the lowest SleepThreshold you can get before stuttering appears?

**Comment by StunGunStudios** [comment]
@MichaelDePiazzi Okay... Strange findings to report. I ported my game over to WindowsGL, and even at 16.7 stuttering still occurs, probably because my game has too much going on. But the weird thing is, the stuttering is not constant. CPU usage seems to oscillate back and forth between 25% and 10 or lower, and the stuttering does not occur when the CPU is at 25% (one logical processor's worth), but when the CPU usage falls, the stuttering happens.

**Comment by MichaelDePiazzi** [comment]
@StunGunStudios
Cool. But I guess this would make the CPU usage of 1 core roughly 50%, which is definitely not ideal.

Don't worry about porting your game, that's probably a bit too much messing around just for testing this. We'll wait and see what results @bousquetm gets.

I've got one more test for you though. Give this version a try:
http://plus7software.com/downloads/MonoGame.WindowsGL.AccurateSleepTest.zip

This version uses my more accurate sleep code (which I mentioned earlier in this thread). You should find that it gives you stable results as well as keeping the CPU usage down. The only problem though is that this code will only work on Windows. Let me know if it works for you.

**Comment by MichaelDePiazzi** [comment]
> but when the CPU usage falls, the stuttering happens

@StunGunStudios I think you might find that the timer resolution is also changing. i.e. when the CPU usage is high the resolution is high (e.g. 1ms), and when the CPU usage is low the resolution is low (e.g. 15ms).

Also, I've noticed this kind of behaviour when using a "power saver" profile (i.e. like what @nkast was talking about).

What kind of machine are you using? i.e. Desktop or laptop? And what are the specs?

**Comment by StunGunStudios** [comment]
@MichaelDePiazzi I'm using a laptop. Fourth generation i3 Intel processor at 1.9GHz, 4GB RAM, 64 bit. As for the power profile, mine is currently not set to a power saving mode, but I'll see what's going on with the timer resolution.

The new DLLs work great with the simple test project, but my ported game still has some choppiness issues when too many calculations are happening per update.

**Comment by MichaelDePiazzi** [comment]
@StunGunStudios
Yeah, laptops tend to be a lot more aggressive with power saving for obvious reasons (even when not using a power saving mode). Let me know what you find with the timer resolution.

And that's great to hear that the my sleep code works well! If you're still getting choppiness in your game though, then I'd say that's just to do with too many calculations being done per update as you've mentioned and not to do with this particular issue.

I think I might submit a PR which at least uses my sleep code for Windows platforms, and uses the normal code for other platforms (but with some minor tweaks to make it a little more accurate at least).

**Comment by StunGunStudios** [comment]
@MichaelDePiazzi So, the timer resolution is definitely the problem. In seeming defiance of all logic, the OpenGL version runs well, just about as good as the DirectX version, when I have the DirectX version open at the same time, because the DirectX executable automatically sets the clock resolution to 1.001. As soon as I close the DirectX version and the resolution returns to 15.625, the OpenGL version stops running well and starts stuttering.

Is there any way to ensure that the timer resolution is set to 1.001 when the OpenGL project exe is run? Because the problem goes away entirely with the DLLs you built and the resolution at 1.

**Comment by KonajuGames** [comment]
See the remarks in the MSDN page for [Sleep()](https://msdn.microsoft.com/en-us/library/windows/desktop/ms686298(v=vs.85).aspx) on how to set the time resolution.

**Comment by KonajuGames** [comment]
But, that is not a solution because any other process can [change the global time resolution](https://randomascii.wordpress.com/2013/07/08/windows-timer-resolution-megawatts-wasted/).

**Comment by MichaelDePiazzi** [comment]
@StunGunStudios Hmmm... I'd say this is possibly an issue with your video drivers. DirectX is setting the timer resolution to 1ms to get the accurate timing, whereas OpenGL is not for some reason. Are your video drivers updated to the latest version?

And yes, you can set the timer resolution in Windows using the timeBeginPeriod function (https://msdn.microsoft.com/en-us/library/windows/desktop/dd757624%28v=vs.85%29.aspx). It's generally not recommended to mess with it though unless absolutely necessary.

**Comment by MichaelDePiazzi** [comment]
> because any other process can change the global time resolution

Yes, but Windows will use the lowest currently requested resolution. So if one process requests 10ms, and another requests 1ms, it will use 1ms.

**Comment by StunGunStudios** [comment]
>I'd say this is possibly an issue with your video drivers.

Could be possible. I had to disable audio when porting to OpenGL because it said no audio drivers were found... But if it's really due to driver issues, that could mean this entire thread has been spent chasing a ghost.

**Comment by KonajuGames** [comment]
There is nothing wrong with setting the time resolution, and it is indeed a recommended solution for games or other applications that need the higher resolution.  Just be aware that it comes with some caveats and responsibilities (like returning it to normal through timeEndPeriod when the game is minimized).

**Comment by KonajuGames** [comment]
> I had to disable audio when porting to OpenGL because it said no audio drivers were found

MonoGame OpenGL uses OpenAL for audio, so you likely did not have OpenAL installed.

**Comment by MichaelDePiazzi** [comment]
> Could be possible.

Ok, try updating your drivers then and see if that helps.

> But if it's really due to driver issues, that could mean this entire thread has been spent chasing a ghost.

Well, we still don't really know for sure if it's driver issues, nor have we confirmed yet if @bousquetm gets the same results as you.

Regardless, I don't think it's been a waste of time though. The issues with use of the Sleep function are still valid. They are just less noticeable with a high resolution timer (e.g. 1ms). I think the small improvements I've made are beneficial to MonoGame anyway and I still plan to submit a PR.

**Comment by StunGunStudios** [comment]
So I updated the drivers and the OpenGL version now runs fine even with the resolution still at 15.625. But, just to be sure, I tried referencing the original MonoGame DLLs and slight choppiness reappeared, so definitely submit a PR.

>MonoGame OpenGL uses OpenAL for audio, so you likely did not have OpenAL installed.

Yeah I don't think I do. I probably won't bother, though, since I plan to keep using DirectX anyway.

**Comment by MichaelDePiazzi** [comment]
@StunGunStudios Glad to hear that the driver update helped. Hopefully @bousquetm's issues are similar.

And I'll try get a PR with my improvements submitted in the next day or two.

**Comment by MichaelDePiazzi** [comment]
Just submitted PR #4207. I can't say that it will resolve this issue, but it should at least improve things a bit. @StunGunStudios has already confirmed that these changes helped somewhat. Hopefully @bousquetm will also find the same thing.

**Comment by bousquetm** [comment]
Ok, so I ran a few test (sorry for the delay, I'm having a crunch time at my day job), and I have the same behaviour as @StunGunStudios:

- When I run the opengl project with VSync=on, there is a lot of stutter, and ClockRes returns "Current timer interval: 1.000 ms"
- When I run the same project with VSync=off, there is still some stuttering but less than before. (ClockRes still shows 1.000ms)
- When I run the directX project with VSync=on, there is no stuttering at all, and ClockRes resturns a timer interval of 15.600ms
- When I run the directX project with VSync=off, there is a lot of stuttering! And ClockRes still show a timer of 15.600ms
(by the way I tested it on 2 different desktop PC)

I'm doing the tests now with your build AccurateSleepTest,  getting you updated!

**Comment by StunGunStudios** [comment]
@bousquetm Have you tried updating your video drivers? For me, that got rid of the problem.

**Comment by bousquetm** [comment]
I confirm that with AccurateSleepTest, there is some big improvement!

I upgraded my drivers, but it doesn't change anything. On the other hand, I'm testing on a Radeon HD 4850 and I think it's broken somehow :p I'll have to test on my PC at work just to be sure (which has a NVidia graphic card). Even with the SleepTest build with SleepThreshold at 16.7 I still have barely noticeable stutters, so there may be another problem that has nothing to do with timers (GC collection .maybe?)

**Comment by StunGunStudios** [comment]
When I ported my game to OpenGL, I still had stutters even at 16.7 until I updated my driver, whereas with a simple test project there were no stutters even before I updated my driver. It seems as if many different factors can affect it. It's good that you saw improvement with the changes that @MichaelDePiazzi made, though.

**Comment by MichaelDePiazzi** [comment]
@bousquetm
I'm glad that the accurate sleep test gave you a big improvement! This means my PR should resolve your issue at least.

Although I find it interesting that you get the opposite to @StunGunStudios in regards to timer resolutions. i.e. for you, OpenGL enables a high resolution timer, but DirectX does not. And on 2 different desktop PCs as well... out of curiosity, what are the specs of the PCs?

**Comment by KonajuGames** [comment]
The game should set the timer resolution it wants, rather than hoping
something else will set it to a suitable value.​

**Comment by MichaelDePiazzi** [comment]
> The game should set the timer resolution it wants, rather than hoping something else will set it to a suitable value.​

Agree. I just find it interesting that the video drivers seem to be using different timer resolutions for OpenGL and DirectX. And I guess there's not really a friendly cross-platform way of controlling timer resolutions. Meaning that spinning the CPU is the only reliable way to get accurate timing across all platforms.

**Comment by bousquetm** [comment]
@MichaelDePiazzi the part with ClockRes happens only on my home PC (core i5, 4GB ram, radeon HD 4850). 

On my PC at work, the clock always stays at 1.000ms (Intel Xeon E5 1650 (12 cores), 32GB of RAM, NVIDIA GeForce GTX 670). AccurateSleepTest gives better result in this PC too!

Tell me if you need me to do more tests.

**Comment by StunGunStudios** [comment]
>(Intel Xeon E5 1650 (12 cores), 32GB of RAM, NVIDIA GeForce GTX 670)

o_O Do you work for the CIA?

**Comment by bousquetm** [comment]
Nope, I just work on a AAA game ^^
