### ISSUE TITLE
[Suggestion] Set Window size in the constructor of GraphicsDeviceManager.cs

### ISSUE THREAD

**Issue by Scellow** [mono/MonoGame#4215]
Hello

It would be cool to get the desired window size at runtime, this way there will be no more that little annoying resize effect

```cs
m_graphics = new GraphicsDeviceManager(this, WIDTH, HEIGHT);
```

**Comment by StunGunStudios** [comment]
I've only observed the resize effect when starting an OpenGL application—it doesn't seem to happen when using DirectX. I suspect it might be some kind of artifact of OpenGL's programming.

**Comment by cra0zy** [comment]
> It would be cool to get the desired window size at runtime, this way there will be no more that little annoying resize effect

I was kind of immune to it, but now that you pointed it out I can't unsee it... 

> I suspect it might be some kind of artifact of OpenGL's programming.

Not even close... had nothing to do with OpenGL

**Comment by cra0zy** [comment]
@Scellow Side note, your title is a bit misleading, you could have just said "Annoying window resize effect at game startup" or something like that...

**Comment by Scellow** [comment]
@cra0zy You are right about title, tried to change it, but has no effect

Also thanks for your PR, ill test it tonight :)
