### ISSUE TITLE
[Website] Add a Link on the MG Downloads page to the latest MG Installers

### ISSUE THREAD

**Issue by DDReaper** [mono/MonoGame#4237]
Had a few comments from devs who are having issue accessing the latest Beta installers for MonoGame.

Most don't want to download the source, they just want to install the latest version

Could we add a link to the downloads page that points to the installer artefacts for the latest successful Committed builds?

**Comment by tomspilman** [comment]
What are we missing...

![capture](https://cloud.githubusercontent.com/assets/103522/11061590/ce6faad6-876d-11e5-8995-de30b8da9c46.PNG)

 The "MonoGame for Visual Studio" link is to the installer from the latest develop branch build.  Same with "MonoGame for Mac", "MonoGame for Ubuntu" and  "MonoGame for other Linux distros".

Seems like we have exactly what you are asking for here.

**Comment by DDReaper** [comment]
#FacePalm, thanks @tomspilman ,  I just read that wrong.

**Comment by tomspilman** [comment]
> I just read that wrong.

Maybe we can improve it...  if you can make the mistake I expect others could too.

**Comment by DDReaper** [comment]
I'll have a good look and see if I can offer any suggestion.
