### ISSUE TITLE
Different render result XNA/MonoGame

### ISSUE THREAD

**Issue by KakCAT** [mono/MonoGame#4242]
The following code:

    Texture2D tex;
    SpriteBatch batch;

....

	if (tex==null)
	{
		tex=new Texture2D (g.GraphicsDevice,1,1);
		Color []col=new Color [1]; col[0]=Color.White;
		tex.SetData<Color> (col);
		batch=new SpriteBatch (g.GraphicsDevice);
	}
	
	batch.Begin (SpriteSortMode.Deferred,BlendState.NonPremultiplied,SamplerState.LinearWrap,DepthStencilState.Default,RasterizerState.CullNone);

	batch.Draw (tex,new Rectangle (100,100,50,50),Color.White);
	batch.Draw (tex,new Rectangle (120,120,50,50),null,Color.Red,0,Vector2.Zero,SpriteEffects.None,1);

	batch.End();

in XNA renders the white rectangle in front of the red rectangle, however in MonoGame renders the white rectangle behind the red rectangle.

**Comment by mrhelmut** [comment]
Maybe related to #4184 ?

**Comment by KakCAT** [comment]
you're right, I wasn't using the latest build available. Updating fixes the problem.

Sorry for the noise.
