### ISSUE TITLE
Rectangle XmlSerialization

### ISSUE THREAD

**Issue by cra0zy** [mono/MonoGame#4264]
Serializing a rectangle gives:
```xml
<Rectangle>
    <X>0</X>
    <Y>0</Y>
    <Width>0</Width>
    <Height>0</Height>
    <Location>
      <X>0</X>
      <Y>0</Y>
    </Location>
    <Size>
      <X>0</X>
      <Y>0</Y>
    </Size>
  </Rectangle>
```

so... did Xna also write out Size and Location? They seem kind of pointless especially considering they are calculated.

**Comment by tomspilman** [comment]
Hum...  probably not.  Some unit tests here would help.

**Comment by tgjones** [comment]
@cra0zy How are you serializing the rectangle to produce the XML above?

Because there is a test - https://github.com/mono/MonoGame/blob/develop/Test/Assets/Xml/12_MathTypes.xml - that shows MonoGame should already do the right thing, at least in `IntermediateSerializer`.

**Comment by cra0zy** [comment]
https://github.com/mono/MonoGame/blob/develop/Tools/Pipeline/Common/PipelineSettings.cs#L62

**Comment by tgjones** [comment]
That's because you're using the standard .NET `XmlSerializer` - you need to use `IntermediateSerializer` if you want to take advantage of MonoGame's more optimal serialisation.

**Comment by cra0zy** [comment]
> That's because you're using the standard .NET XmlSerializer - you need to use IntermediateSerializer if you want to take advantage of MonoGame's more optimal serialisation.

I didn't know about it :O Well closing considering no point in supporting XmlSerializer with IntermediateSerializer around, thanks for the info @tgjones !!!
