### ISSUE TITLE
Investigating an "app can't start" issue

### ISSUE THREAD

**Issue by mrhelmut** [mono/MonoGame#4267]
Hello there,

We are getting reports of several players that our game doesn't work anymore. The process starts, but is stuck at 72KB memory usage and 0% CPU. It doesn't crash and stays like that. No window, nor icon appear, which make me think that the program fails before the Main().

The only relevant change we made before getting those reports was to update MonoGame to the latest source code. Before that, we were on commit 4d5a7fd, from the 29th September (https://github.com/mono/MonoGame/tree/4d5a7fd8c0971f2fec4e52f40b06f2289874a42c). I've reviewed merged commits since then and couldn't identify a potential cause.

Given that the process gets stuck at 72KB, it most probably is a problem with the .NET bootstrap (and would appear to not even call the Main()), so it may not be related to MonoGame. But builds prior to the update are still working.

Players' environments seem fine, the game was working previously, hence they meet software requirements.

I couldn't reproduce the issue on any of our machines.

Does anybody already ran into this kind of problem with a .Net app? My best guess would be that .Net is unable to load some assemblies, but it would result in a crash, isn't it?

P.S.: it's a Windows DX project. Also, I've verified all assemblies for corruption, everything is fine. I'm also signing everything, so I don't think it's a problem with GAC and local assemblies.

**Comment by tomspilman** [comment]
I have run into weird issues if the machine doesn't have a sound card or even if there are no speakers or headphones plugged into the sound card.

That is all I can think of right now.

**Comment by mrhelmut** [comment]
It appears to be related to a recent Avast anti-virus update... Avast has introduced a bug which prevent most .Net applications to start correctly... I'm trying to reach them to fix that.

**Comment by tomspilman** [comment]
> Avast has introduced a bug which prevent most .Net applications to start correctly

Wow.... really?  That is pretty bad.
