### ISSUE TITLE
[MGCB] Inconsistent output when two files in a row have errors

### ISSUE THREAD

**Issue by nkast** [mono/MonoGame#4271]
![mgcberror](https://cloud.githubusercontent.com/assets/3018589/11445114/491418a4-9532-11e5-9f0c-caa09723a423.png)

The .mgcb file have 3 files, GeometryA , GeometryB , GeometryC. Files B & C are corrupted.
Notice that between the error messages for B and C, a line is missing with the filename of C.
"P:/TestPipeline/GeometryC.fbx"

As a result, tools like  https://github.com/mono/MonoGame/pull/4168 might group all error lines under the file 'GeometryB.fbx'. 

Actually the GTK tool might be immune to it as it checks for lines starting with '/', haven't tested it since I haven't got a Linux box. But on windows where paths start with a letter I am trying different tricks, like File.Exists(line) as a hint to restart.

**Comment by cra0zy** [comment]
This does cause trouble for Gtk Pipeline as well.

**Comment by nkast** [comment]
Actually MGCB outputs the filename.
The exception message has no newline and the the filename is appended at the end of the prev line.

**Comment by tomspilman** [comment]
Thanks @nkast !
