### ISSUE TITLE
[Mac] Upgrade to the newer Xamarin.Mac API

### ISSUE THREAD

**Issue by hach-que** [mono/MonoGame#4275]
The newer Xamarin Mac API changes the namespace for all of the Mac APIs (they are no longer prefixed with `MonoMac`).  This is the unified API that is shared with iOS and tvOS.  Xamarin have since deprecated the legacy API, so I think it's safe to say that the legacy API might not work on newer versions of OS X (especially through the App Store).

The newest version of Protobuild targets this unified API by default, but MonoGame still targets the old API.

This page has more details on the Unified API for Mac: https://developer.xamarin.com/guides/cross-platform/macios/updating_mac_apps/

**Comment by mrhelmut** [comment]
Would that imply to have a Xamarin subscription to build / package for OS X?
I haven't built for OS X yet, but I was assuming that a Xamarin subscription is optional and that I can package / publish a MonoGame project with MonoKickstart (like I would be doing on Linux) if I didn't wanted to use the Xamarin packaging.

**Comment by KonajuGames** [comment]
The free MonoMac only builds 32-bit.  As of February this year, the Mac App Store has required 64-bit support in new app submissions.  64-bit supported is provided as part of the new Unified API available in Xamarin.Mac, which will not be back-ported to MonoMac.  I don't know how much longer MonoMac will be supported.  So it would seem that we should switch to Xamarin.Mac and deprecate MonoMac.

**Comment by hach-que** [comment]
Yeah I think MonoMac is quickly approaching it's end-of-life. I mean,
Xamarin deprecated it years ago, but with Apple's requirement changes and
the lack of backporting I don't think MonoMac is actually viable for
developers any more.

Technically Protobuild still does support it; if Xamarin.Mac is not
installed, it will use MonoMac, and it'll add the PLATFORM_MAC_LEGACY
define to the build so you can #ifdef it. But whether MonoGame wants to
#ifdef all those call sites and namespaces is another story.

**Comment by KonajuGames** [comment]
Unfortunately it is not something that we can test as I don't think we don't have a license of Xamarin.Mac for the build server, I don't have one and I don't think Tom does either.

**Comment by hach-que** [comment]
The build server does appear to have Xamarin.Mac, or Protobuild wouldn't be using it for the Mac builds (and it is right now, but the Protobuild you have is using the legacy Xamarin.Mac, not the new unified API).  Basically I think it's just a case of upgrading Xamarin on the build server?

If you don't personally have a Xamarin.Mac license, you will definitely qualify under the open source Xamarin program (that's how I have my Xamarin.Mac license): https://resources.xamarin.com/open-source-contributor.html

**Comment by mrhelmut** [comment]
> The free MonoMac only builds 32-bit. As of February this year, the Mac App Store has required 64-bit support in new app submissions. 64-bit supported is provided as part of the new Unified API available in Xamarin.Mac, which will not be back-ported to MonoMac. I don't know how much longer MonoMac will be supported. So it would seem that we should switch to Xamarin.Mac and deprecate MonoMac.

I wasn't aware of the 64-bit part, thanks for clarifying!

**Comment by hach-que** [comment]
So I am working on this, but I'm running into a pretty annoying issue. According to the Xamarin Mac documentation:

```
Note: The Xamarin.Mac implementation of OpenTK does not include the Input API, so you will need to use the Apple provided APIs to add keyboard and Mouse support. Optionally you can create a custom instance of the MonoMacGameView and override the KeyDown and KeyUp methods.
```

I'm assuming the old legacy API did provide OpenTK's Input namespace?  As I don't have MonoMac installed I can't do this myself, but can someone confirm that's the case?

**Comment by hach-que** [comment]
So the branch I'm working on I've just not implemented GamePad / Joystick platform backends for MacOS (when using the new Xamarin APIs, MonoMac will continue to work).  I'm going to try and implement them at some point; I'm guessing I'll need to make use of the new game pad stuff that tvOS is using?

**Comment by jjxtra** [comment]
Is there a nuget package or dll available that will work with the new Xamarin.Mac and the Mac App Store?

**Comment by hach-que** [comment]
No, I think the NuGet package for MonoGame targets MonoMac?

If you want to target the Xamarin.Mac API, you'll need to build MonoGame from source.

**Comment by jjxtra** [comment]
I see. I didn't see any .sln or .csproj files. Are there instructions anywhere to build from source?

**Comment by hach-que** [comment]
Yeah, just run Protobuild.  If you're on a Mac, from a terminal, and once
you're in the directory where you've cloned MonoGame, just run it from the
command line like:

> mono Protobuild.exe

and it'll generate the project and solution files for you.

**Comment by patridge** [comment]
FWIW, from a Mac, I ran `mono Protobuild.exe` on the latest develop and it generated a bunch of projects, but Xamarin.Mac did not appear to be in the resulting VisualStudio20XX directories (nor any other Mac-looking projects).
