### ISSUE TITLE
[MGCB] Audio Quality ignored

### ISSUE THREAD

**Issue by nkast** [mono/MonoGame#4283]
SoundEffect always output 44100Hz audio, Quality setting is ignored.
Windows platform.

**Comment by tomspilman** [comment]
We used to try to generate ADPCM for Windows in low/medium quality settings, but that wasn't working for us at one point...

https://github.com/mono/MonoGame/blob/0b25f56e861fb602db884c40267b99ea947bae15/MonoGame.Framework.Content.Pipeline/Processors/SoundEffectProcessor.cs#L54

So now it should be handled here...

https://github.com/mono/MonoGame/blob/0b25f56e861fb602db884c40267b99ea947bae15/MonoGame.Framework.Content.Pipeline/Audio/AudioContent.cs#L194

So either we're not specifying the bitrate correctly to ffmpeg or it is ignoring it for some reason.

**Comment by nkast** [comment]
I did some test with latest ffmeg and you have to set sample rate (-r:a or -at), otherwise it defaults to 44100. 
But I could move that to MonoGame, somehow the two values -bitrate&samplerate- have to match .
And I have no idea what that change will do to the other output formats/platforms.

**Comment by nkast** [comment]
XNA Audio importer for reference 
(tested by building an XNA content proj and loading with Monogame)

 | SampleRate | Chennels  | Compression 
input | 48000Hz | 2Ch | .WAV
XNA/Best | 48000Hz | 2Ch | PCM
XNA/Medium | 44114Hz | 1Ch | MSADPCM
XNA/Low | 23891Hz | 2Ch | MSADPCM 

 | SampleRate | Chennels  | Compression 
input | 44100Hz | 1Ch
XNA/Best | 44100 | 1Ch | PCM
XNA/Medium | 44121Hz | 1Ch | MSADPCM
XNA/Low | 22060Hz | 1Ch | MSADPCM

 | SampleRate | Chennels  | Compression 
input | 22050Hz | 1Ch
XNA/Best | 22050Hz, 1Ch | PCM
XNA/Medium | 22111Hz, 1Ch | MSADPCM
XNA/Low | 11055Hz | 1Ch | MSADPCM

we can extract the following rules:

 | SampleRate | Channels  | Compression 
Best |  no change | no change | PCM
Medium | max(44100Hz) | one channel | MSADPCM
Low | half | no change | MSADPCM

I'm not saying Monogame has to copy XNA behavior, I'd rather see more options to control audio output.

**Comment by KonajuGames** [comment]
Those are very odd results.  The number of channels should never change.  Standard sample rates are 48000, 44100, 22050, and 11025Hz.  It looks like it might be dropping the sample rate to the next lower level when dropping the Quality property.

**Comment by tomspilman** [comment]
> The number of channels should never change

Yeah... from our tests from a few years ago it seemed all XNA did was drop the sample rate and change the format.

**Comment by tomspilman** [comment]
FYI...  i'm adding a ton of unit tests for `AudioContent` right now which should solve these issues.  We should be very accurate to XNA after this.

**Comment by tomspilman** [comment]
@nkast - FYI...  https://github.com/mono/MonoGame/pull/5001.
