### ISSUE TITLE
Bounty: Update audio system not to drain CPU on Android

### ISSUE THREAD

**Issue by jakepoz** [mono/MonoGame#4284]
The audio system stays active on Android devices and continues to drain battery when Monogame apps are in inactive in the background. This has been documented here:

http://community.monogame.net/t/mg-android-game-keeps-draining-battery-life-in-background/2664

and here:

Monogame Issue https://github.com/mono/MonoGame/issues/3899

We wanted to post a $1,000 USD bounty for the successful resolution of this issue and it's acceptance into the Monogame develop branch. It looks like there are two viable solutions, one is to compile a new openal-soft library and use the new functions to pause suspend/pause the device when necessary. Another would be a fully managed mixer. Either way, this is a big blocker for anyone pushing games to production on Android, and we hope for a final solution soon :)

**Comment by jakepoz** [comment]
Here is the bounty information: https://www.bountysource.com/issues/28801418-bounty-update-audio-system-not-to-drain-cpu-on-android

**Comment by totallyeviljake** [comment]
Someone reported this problem to use a long time ago (about 18 months ago). I found that it was only present in certain android devices and limited OS versions. Did you find the same @jakepoz ?? I ignored it as being a nuance of bad OS driver implementations. Seems to have gotten worse..

**Comment by jakepoz** [comment]
We are seeing it on all sorts of devices now, definitely repros on the Nexus 5x, and basically every other device we have tried. We also get a TON of emails from users complaining.

**Comment by KonajuGames** [comment]
The managed mixer, while working for the main part, isn't ready yet. So
I'll get back to the rebuilding of openal-soft with the latest source which
I had underway.

**Comment by jakepoz** [comment]
Sweet, please let us know if you want us to test any builds.

**Comment by KonajuGames** [comment]
I built new binaries, dropped them in and it plays the occasional sound
instead of every sound. Still trying to work out why.

**Comment by jakepoz** [comment]
Hey Konaju,

 Any ideas? We have a bunch of users saying that they see the battery drain issue. Is there anything you could use from us to help?

**Comment by KonajuGames** [comment]
I was working on it again last night. It works fine in the emulator, but on
hardware it misses playback on  many sounds. I don't have a solution yet,
but will be back on it tonight.

**Comment by KonajuGames** [comment]
If you can, check out the PR I just submitted (#4303).  Supports suspending the audio mixer thread and adds 64-bit support.

**Comment by jakepoz** [comment]
Sweet, testing it out now.

**Comment by jakepoz** [comment]
Nice, it is working and the battery issue appears fixed. @danzel Can you give it a try just to verify please?

**Comment by danzel** [comment]
Yep works for me, CPU in background seems fixed.

**Comment by jakepoz** [comment]
Hi Konaju, please be sure to claim the bounty on bountysource: https://www.bountysource.com/issues/28801418-bounty-update-audio-system-not-to-drain-cpu-on-android

Looks like some other community members also added on to this one :)

**Comment by KonajuGames** [comment]
Many thanks for that.  A very pleasant surprise.
