### ISSUE TITLE
Can no longer enter $(Platform) in Output Directory in GTK# Pipeline GUI

### ISSUE THREAD

**Issue by dellis1972** [mono/MonoGame#4289]
Since the change over to use a Directory browser to set the Output and Intermediate Directories in the Pipeline tool I can no longer manually type in 

bin\$(Platform)
obj\$(Platform)

via the UI, the file has to edited manually.. This is useful when separating out build output per platform

I suspect this is a conflicting requirement..
What might be possible is a "browse" button e.g [...] in the edit box so users can either type or browse for a directory.

**Comment by cra0zy** [comment]
Linux also doesn't have it, I kind of forgot about it, will setup a PR to either implement it or make a dialog that's able to select it

**Comment by cra0zy** [comment]
Is there somewhere a list of things that can go like "$(Platform)"? I want to add a help message to the dialog.
