### ISSUE TITLE
Blurry Fonts from the pipeline, works right with the XNA pipeline

### ISSUE THREAD

**Issue by Tzenchor** [mono/MonoGame#4305]
Hi, I have a project i did for school with XNA and now i have converted it to Monogame.
But the weird thing is that if I run the game with what the Monogame pipeline generates i get blurry texts, both with 3.4 and 3.5, but if I just copy the Content folder from the XNA version it shows right.
XNA:
![xna](https://cloud.githubusercontent.com/assets/11319966/11668345/f6917c3e-9df6-11e5-89d3-94a60786dfbe.PNG)
MonoGame 3.4
![mono3 4](https://cloud.githubusercontent.com/assets/11319966/11668383/3515ee2c-9df7-11e5-811e-ec75f1d2fecd.PNG)
MonoGame 3.5 (current)
![mono 3 5 dev](https://cloud.githubusercontent.com/assets/11319966/11668394/41fb10b8-9df7-11e5-904a-fda93730cee5.PNG)

The font is a simple calibri of size 10 with kerning enabled

**Comment by KonajuGames** [comment]
Try expanding the Font Processor properties and setting the Texture Format
to Color. Font textures are compressed by default, which loses some quality.

**Comment by Tzenchor** [comment]
Made the change but no difference

**Comment by tomspilman** [comment]
That looks to be more than just blurry...  that looks to be completely messed up text.

Can you share the font XNB here for people to test?

**Comment by Tzenchor** [comment]
Here they are in this zip. It's contents are the xnb from monogame, the one from xna and the spritefont file used for its generation
https://onedrive.live.com/redir?resid=7C0DE47C61522229!5889&authkey=!APDQX-r56qxONho&ithint=file%2czip
By the way, if I try to attach the file directly it fails, but says that zip files are supported

**Comment by KonajuGames** [comment]
That's fine. Thanks for those. I can take a look tonight my time if no one
else grabs it before then.

**Comment by tomspilman** [comment]
@KonajuGames  great!

**Comment by KonajuGames** [comment]
It's strange.  At sizes of 12 or 14, it produces garbled results.  Anything at 15 or larger and it renders the glyphs correctly.  At first guess, it appears to be something with FreeType, but I'm still investigating.

**Comment by KonajuGames** [comment]
It is indeed a bug in FreeType.
https://github.com/Robmaister/SharpFont/issues/18
What they suggest in that port (making the dpi much larger) makes the glyphs bigger, and reducing the font size correspondingly doesn't always fix it, and the output size is not quite correct either.

**Comment by Tzenchor** [comment]
I don't think that is the problem.
I have downloaded the SharpFont project and modified the test project to show size 12 text and added the calibri font, and this is the result:
![shrapfontexample](https://cloud.githubusercontent.com/assets/11319966/11723958/60709cd6-9f71-11e5-8f21-916511bf8c1f.PNG)
Having a fast look at monogame code, it feels wrong or outdated. For example, when creating the fontface in monogame it takes the wanted size and shifts it 6 times to the left, while in Sharpfont they use the target size directly

**Comment by Tzenchor** [comment]
I have been comparing both procedures and i have found that the SharpFont dll is outdated, the one in monogame is version 2.5.3.0 while the current one is 3.0.1.200.
So they are not equivalent, and i think the change will require the rewriting of  [SharpFontImporter.cs](https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework.Content.Pipeline/Graphics/Font/SharpFontImporter.cs) to make it work

**Comment by KonajuGames** [comment]
The reason for the left shift of the values when passing them to SharpFont
is that FreeType expects the values in twips, of which there are 64 twips
to a point.  The left shift by 6 is multiplying the value by 64.
​
It's difficult to keep up to date with the several dependencies we have,
especially for the content pipeline.  If they changed it so the multiply by
64 is no longer required, it will change some things.  We can certainly
look at moving to the new version.

**Comment by Tzenchor** [comment]
Definitely there is something wrong with freetype. Updating Sharpfont and by extension freetype does not solve anything, and the "solution" of increasing the dpi works but generates oversized bitmaps.
The problem is that the bitmaps created have 1 bpp instead of 8 bpp

**Comment by Tzenchor** [comment]
Eureka!!, i have found the problem.
For font sizes below 15 pixels the glyphs get rendered in 1bpp bitmaps instead of 8bpp ones as stated in sharpfont documentation.
I have a fix ready that gives this result
![update](https://cloud.githubusercontent.com/assets/11319966/11967682/1ee50700-a905-11e5-9101-fdb128dafa73.PNG)
I know that there are still wrong, but it is an easy fix

**Comment by Tzenchor** [comment]
Fixed, after commenting the code tomorrow i'll do the pull request. As proof:
![update2](https://cloud.githubusercontent.com/assets/11319966/11968736/bec4c04e-a90f-11e5-9e6c-24a2bdde66dd.PNG)

**Comment by KonajuGames** [comment]
Interesting. I'm keen to see the fix.
