### ISSUE TITLE
Remove Storage Classes

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#4311]
I am proposing the full removal of the existing storage classes:

 - [StorageContainer.cs](
https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Storage/StorageContainer.cs)
 - [StorageDevice.cs](https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Storage/StorageDevice.cs)
 - [StorageDeviceHelper.cs](
https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Storage/StorageDeviceHelper.cs)

Back in https://github.com/mono/MonoGame/issues/2389 I was suggesting redesign, but really after seeing more console SDKs and how each one uses a different method for storage (as well as different TRC requirements)...  it seems better to just drop support for this old API entirely.

Then at a later date if we can work out something that works in all cases we can talk about adding a new API.

So is anyone using this functionality?  Would it be missed at all?

**Comment by mrhelmut** [comment]
I would agree.

I never used them because console SDKs / TRCs are so different and some of them don't even have a folder based storage paradigm, not to mention the difference between async and blocking calls to each SDK (hence, implementing these classes may be quite touchy on some platforms).

**Comment by KonajuGames** [comment]
The Storage namespace is very much targeted towards the Xbox 360, memory cards and the Guide.  And the whole Begin..End async model needs to be updated to async/await.

I have always used IsolatedStorage for PC and phones.

**Comment by mgarstenauer** [comment]
I agree - the storage classes are not needed anymore.

**Comment by lolznoob** [comment]
I use them!
