### ISSUE TITLE
Mac OS Permissions for ffmpeg and ffprobe

### ISSUE THREAD

**Issue by jeroldhaas** [mono/MonoGame#4312]
By default, the installed Pipeline.app has permissions set as follows:
```
-rw-r--r-x   1 root  wheel  22810832 Nov  2 08:38 ffmpeg
-rw-r--r-x   1 root  wheel  22762608 Nov  2 08:38 ffprobe
```
In order for sound effects to process properly, permissions need to be set by default with installer to:
```
-rwxr--r-x   1 root  wheel  22810832 Nov  2 08:38 ffmpeg
-rwxr--r-x   1 root  wheel  22762608 Nov  2 08:38 ffprobe
```

**Comment by tomspilman** [comment]
@dellis1972 @cra0zy 

Haven't we been dealing with this lately?

**Comment by dellis1972** [comment]
looks like its fixed in develop 

https://github.com/mono/MonoGame/blob/develop/Installers/default.build#L117

@jeroldhaas are you using the latest unstable release?

**Comment by jeroldhaas** [comment]
No. Stable. If develop is fixed, then the issue is already resolved. Thanks. :)

**Comment by dellis1972** [comment]
@jeroldhaas try the latest unstable mac installer, it should hopefully fix the issue :)

**Comment by jeroldhaas** [comment]
I'd manually corrected on my end, but I appreciate all your time. :+1:
