### ISSUE TITLE
EffectParameter.Setvalue(int[]) not implemented

### ISSUE THREAD

**Issue by JustinKerbice** [mono/MonoGame#4315]
The [method] (https://msdn.microsoft.com/en-us/library/bb198903%28v=xnagamestudio.40%29.aspx) from XNA 4.0 is not yet implemented in MonoGame.
(instead there  is thecommented block:
`/*
		public void SetValue (int[] value)
		{
			throw new NotImplementedException();
		}
        */` )

**Comment by KonajuGames** [comment]
PR #4268 is already present to implement that missing method.
