### ISSUE TITLE
Pipeline - Deleting last item in folder deletes folder

### ISSUE THREAD

**Issue by halcyon1234** [mono/MonoGame#4318]
MonoGame 3.4
Visual Studio 2010
Windows 7

Go to pipeline
Add new folder
Add item to folder (any kind-- model, texture, whatever)
Later, delete the only item in that folder

Expectation:  Item deleted, with empty folder remaining

Actual:  Item is deleted, folder is deleted too.

(So now I have to recreate the folder to add another item to the folder)

**Comment by tomspilman** [comment]
@halcyon1234 - Do you mean the folder in the Pipeline tool tree view?  Or are you talking about a folder on disk?

@cra0zy - Thoughts?

**Comment by cra0zy** [comment]
> @halcyon1234 - Do you mean the folder in the Pipeline tool tree view? Or are you talking about a folder on disk?

He is talking about treeview. Pipeline Tool doesn't have any actual deletion code.

I'll look into it a bit later today.

**Comment by halcyon1234** [comment]
Yes, the Pipeline treeview.  In the screenshot, if I delete "robots.fbx", it will delete "Models" (or remove them from the treeview).



http://i.imgur.com/Wi8n7Sz.png

FYI: I just tested, and it is just from the treeview.  It doesn't remove it from the disk's file structure itself.
