### ISSUE TITLE
Game.Window.ClientBounds returns incorrect location

### ISSUE THREAD

**Issue by MichaelDePiazzi** [mono/MonoGame#4344]
When using XNA, `Game.Window.ClientBounds` returns the desktop location of the upper-left corner of the client area (i.e. the internal area of a window which doesn't include window borders, title bar, etc).

But in the Windows and WindowsGL builds, MonoGame is currently always returning (0, 0). There are likely more builds also affected (very likely Linux, maybe others).

I have a fix for the Windows (DirectX) build and I will submit a PR for this shortly.

However, I am not sure of the fix for WindowsGL / DesktopGL builds. I took a quick look into it, but could not see how to obtain the same position via the OpenTK INativeWindow interface. It only seems to give the desktop location of the entire window (including borders, etc). I could not find a way getting the desktop location of the internal client area.

**Comment by tomspilman** [comment]
> When using XNA,  Game.Window.ClientBounds  returns the desktop location of the upper-left corner of the client area 

Are we 100% certain of this?  Was it tested under fullscreen and windowed modes?

**Comment by MichaelDePiazzi** [comment]
> Are we 100% certain of this? Was it tested under fullscreen and windowed modes?

Yes, I confirmed this behaviour in XNA for both fullscreen and windowed modes. It's only really windowed mode that is the problem in MonoGame. In fullscreen mode, the desktop location of the client area is typically (0, 0) anyway.

**Comment by tomspilman** [comment]
> In fullscreen mode, the desktop location of the client area is typically (0, 0) anyway.

Not always...  multi-monitor systems are different in that regard which is why I asked.

**Comment by MichaelDePiazzi** [comment]
> Not always... multi-monitor systems are different in that regard which is why I asked.

Yes, true. So typically in fullscreen mode the desktop location is (0, 0) for the primary monitor is what I meant. In a multi-monitor setup, XNA returns the appropriate desktop location depending on the monitor it's on. e.g. (-1920, 0) for the monitor left of the primary. My PR for Windows DirectX replicates this same behaviour.

**Comment by MichaelDePiazzi** [comment]
@cra0zy Did you have any luck figuring out how to do this in WinGL/Linux?

**Comment by cra0zy** [comment]
> @cra0zy Did you have any luck figuring out how to do this in WinGL/Linux?

I have it set up for window mode locally, I'll setup fullscreen tomorrow(it's 2 in the morning right now in my timezone).

**Comment by cra0zy** [comment]
I had a PR that needed rebasing and was fixing some other stuff on OpenTK side so I added a commit there.

**Comment by MichaelDePiazzi** [comment]
Thanks @cra0zy! I'm not sure how I missed that the INativeWindow interface also had a PointToScreen method... d'oh! :) I'll try give your change a test later.

**Comment by MichaelDePiazzi** [comment]
FYI - This issue is resolved by PRs #4345 and #4216, and can be closed once they are both merged.
