### ISSUE TITLE
Microsoft.Xna.Framework.Content.Pipeline not working under Windows 10 UWP

### ISSUE THREAD

**Issue by GrafSeismo** [mono/MonoGame#4353]
Just tried to install current (dev) package into a new universal windows 10 Update 1 project to get a custom content processor to work but do not find a pipeline dll ready for UWP. May the current Update 1 of Visual Studio did also scrumbled current UWP nuget package. When i create a new project i get a message that i have to update the project by creating a new project and copy source / assets  / etc. to the new project to get it ready for current update 1 release. But i can open older existing projects.

My current configuration:
Microsoft Visual Studio Community 2015 Version 14.0.24720.00 Update 1
Microsoft .NET Framework Version 4.6.01038
Microsoft Visual C# 2015 00322-20000-00000-AA031
NuGet Package Manager 3.3.0
Visual Studio Tools for Universal Windows Apps 14.0.24720.00

**Comment by nkast** [comment]
did you install the 10240 SDK? 
VS2015.1 comes with 10586 SDK , 10240 is optional.

**Comment by GrafSeismo** [comment]
it is Windows SDK 10.0.10586.15 installed

**Comment by nkast** [comment]
What is the exact message? and what did you mean by you can't find a dll ready for UWP?
My guess is that the MG templates create a 10240 project and you have to either run VS2015.1 installer again to install 10240, or change the project to 10586.

**Comment by GrafSeismo** [comment]
10586 comes with Update 1, i do not downgrade a legal update. I tried to upgrade sources but dependend files are mostly do not support .NETcore which seems to be the standard for UWP apps now. So i tried the newest "Development" build and could install the pipeline now.
