### ISSUE TITLE
iOS issue with texture parameters in pixel shader

### ISSUE THREAD

**Issue by mcastrillo** [mono/MonoGame#4355]
hello,

I'm trying to get working a pixel shader that works perfectly in windows phone, windows (directx), windows 8 and android, but on iOS seems to be some kind of mistake when I pass a texture as parameter on ios, does not throw any error at runtime, simply it don't get the texture. I also tried with the last sources of monogame from github.

my pixel shader:

```HLSL
sampler TextureSampler : register(s0);

texture MaskTexture;
sampler mask = sampler_state
{
	Texture = <MaskTexture>;
};

float4 PixelShaderFunction(float4 pos : SV_POSITION, float4 color1 : COLOR0, float2 coords : TEXCOORD0) : SV_TARGET0
{
	float4 color = tex2D(TextureSampler, coords);
	return color * tex2D(mask, coords);
}

technique Technique1
{
	pass Pass1
	{
#if SM4
	PixelShader = compile ps_4_0_level_9_1 PixelShaderFunction();
#elif SM3
	PixelShader = compile ps_3_0 PixelShaderFunction();
#else
	PixelShader = compile ps_2_0 PixelShaderFunction();
#endif
	}
}
```

on my Draw method...

````C#
            spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend);
            Efecto.Parameters["MaskTexture"].SetValue(Mascara); // This parameter does not work on ios, it gives a black box
            Efecto.CurrentTechnique.Passes[0].Apply();
            spriteBatch.Draw(Avatar, Vector2.Zero, Color.White);
            spriteBatch.End();
````

The result should be:

![image](https://cloud.githubusercontent.com/assets/5202166/11962898/878bc284-a8e3-11e5-9093-78906d64bb1c.png)

but I only get a black box... I also tried to directly return the texture color on the shader without parameter to be sure that the shader is applied and it works, the problem seems to be the texture as parameter.

As I said, it works on Android, Windows Phone and Windows using DX monogame, but does not on IOS (tried on emulator, iPhone 5 and iPhone 6)

Thanks

**Comment by mcastrillo** [comment]
ups!... finally I found the problem, sorry for the inconvenience: seems that textures on iOS have to be power of two to work as parameters on shaders. Hope it may help and save time to someone trying to find the solution...

**Comment by tomspilman** [comment]
> seems that textures on iOS have to be power of two to work as parameters on shaders

@dellis1972 @KonajuGames - Is that accurate?  Or is that just a compression thing?  Could MonoGame detected this and warned the user in some way?
