### ISSUE TITLE
New custom pipeline project failed after first build

### ISSUE THREAD

**Issue by GrafSeismo** [mono/MonoGame#4356]
I test the current development build of MG 3.5.x use Windows 10 with VS 2015.1 and its current SDK 10.0.10586.15.

1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3274: The primary reference "MonoGame.Framework" could not be resolved because it was built against the ".NETFramework,Version=v4.5" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.0".
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3275: The primary reference "MonoGame.Framework.Content.Pipeline" could not be resolved because it has an indirect dependency on the assembly "MonoGame.Framework, Version=3.5.0.1045, Culture=neutral, PublicKeyToken=null" which was built against the ".NETFramework,Version=v4.5" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.0".
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1819,5): warning MSB3274: The primary reference "MonoGame.Framework.Content.Pipeline" could not be resolved because it was built against the ".NETFramework,Version=v4.5" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.0".
1>e:\documents\visual studio 2015\Projects\SpriteAnimation\SpriteAnimation\ContentImporter1.cs(2,17,2,20): error CS0234: The type or namespace name 'Xna' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
1>e:\documents\visual studio 2015\Projects\SpriteAnimation\SpriteAnimation\ContentProcessor1.cs(2,17,2,20): error CS0234: The type or namespace name 'Xna' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
1>e:\documents\visual studio 2015\Projects\SpriteAnimation\SpriteAnimation\ContentImporter1.cs(20,37,20,60): error CS0246: The type or namespace name 'ContentImporter<TInput>' could not be found (are you missing a using directive or an assembly reference?)
1>e:\documents\visual studio 2015\Projects\SpriteAnimation\SpriteAnimation\ContentProcessor1.cs(21,38,21,71): error CS0246: The type or namespace name 'ContentProcessor<TInput, TOutput>' could not be found (are you missing a using directive or an assembly reference?)
1>e:\documents\visual studio 2015\Projects\SpriteAnimation\SpriteAnimation\ContentProcessor1.cs(20,6,20,22): error CS0246: The type or namespace name 'ContentProcessor' could not be found (are you missing a using directive or an assembly reference?)
1>e:\documents\visual studio 2015\Projects\SpriteAnimation\SpriteAnimation\ContentProcessor1.cs(20,23,20,34): error CS0246: The type or namespace name 'DisplayName' could not be found (are you missing a using directive or an assembly reference?)
1>e:\documents\visual studio 2015\Projects\SpriteAnimation\SpriteAnimation\ContentImporter1.cs(19,6,19,21): error CS0246: The type or namespace name 'ContentImporter' could not be found (are you missing a using directive or an assembly reference?)
1>e:\documents\visual studio 2015\Projects\SpriteAnimation\SpriteAnimation\ContentImporter1.cs(19,30,19,41): error CS0246: The type or namespace name 'DisplayName' could not be found (are you missing a using directive or an assembly reference?)
1>e:\documents\visual studio 2015\Projects\SpriteAnimation\SpriteAnimation\ContentImporter1.cs(19,60,19,76): error CS0246: The type or namespace name 'DefaultProcessor' could not be found (are you missing a using directive or an assembly reference?)
1>e:\documents\visual studio 2015\Projects\SpriteAnimation\SpriteAnimation\ContentProcessor1.cs(23,55,23,78): error CS0246: The type or namespace name 'ContentProcessorContext' could not be found (are you missing a using directive or an assembly reference?)
1>e:\documents\visual studio 2015\Projects\SpriteAnimation\SpriteAnimation\ContentImporter1.cs(23,56,23,78): error CS0246: The type or namespace name 'ContentImporterContext' could not be found (are you missing a using directive or an assembly reference?)
1>e:\documents\visual studio 2015\Projects\SpriteAnimation\SpriteAnimation\ContentProcessor1.cs(23,33,23,40): error CS0115: 'ContentProcessor1.Process(string, ContentProcessorContext)': no suitable method found to override
1>e:\documents\visual studio 2015\Projects\SpriteAnimation\SpriteAnimation\ContentImporter1.cs(23,32,23,38): error CS0115: 'ContentImporter1.Import(string, ContentImporterContext)': no suitable method found to override

**Comment by Tzenchor** [comment]
I had a similar problem the first time i tried to upgrade a XNA project to MonoGame.
To create a library for MonoGame, use the game project and change its output type to library

**Comment by GrafSeismo** [comment]
Well a component pipeline is not a library at all...

**Comment by tomspilman** [comment]
When you say "New custom pipeline project" do you mean you created a MonoGame Content Pipeline Extension Project from a VS template?

The pipeline extension should just be a plan Windows C# library project.  It could be that the existing template doesn't work out of the box on VS 2015.

@mattiascibien - Do you have some time to investigate?

**Comment by GrafSeismo** [comment]
>When you say "New custom pipeline project" do you mean you created a MonoGame Content Pipeline Extension Project from a VS template?

yes, exact that.

**Comment by mattiascibien** [comment]
@tomspilman At the moment I am away from my dev machine but I Will surely do that.

**Comment by mattiascibien** [comment]
As a quick fix you can try to change the MonoGame reference to the one targeting .NET 4.0. Unfortunately I do not have MonoGame installed in my tablet. As soon as I get some time (maybe this afternoon GMT+1) I will try to find the correct reference. @tomspilman did I add the wrong ref when doing the PR?

**Comment by mattiascibien** [comment]
@GrafSeismo are you doing a UWP project? As A quick fix you can try to upgrade your project to use .NET 4.5 instead of 4.0. I think that the ContentImporter project should not include the MonoGame UWP but the Windows dedkstop one as that project is a DLL that will be loaded from MGCB (which is built with MonoGame desktop).

**Comment by GrafSeismo** [comment]
i created a new MonoGame content pipeline extension project from a VS template using VS 2015 update 1 cummunity version.
It seems .NET 4.x is not an option anymore when using .NET Core as new standard since update 1 for universal windows applications. To include a custom pipeline you need to have the dll UWP/UAP/.NETCore ready. There are major differencies between .NET 4.x and .NET Core (For e.g. Serialization/Reflection, File/StorageFile, etc.).

**Comment by mattiascibien** [comment]
Are you adding the content pipeline extension project to your game project? 

If this is your case you should not do this and instead add your compiled dll to the references of the monogame content file (the one you edit with Pipeline.exe).

**Comment by GrafSeismo** [comment]
>Are you adding the content pipeline extension project to your game project?
yes indeed, i have a runtime and a pipeline dll. The runtime dll is the base of pipeline and offers the basic API. In the game project i need the runtime dll for the specific datatypes. I am not able to mix .NET 4.x with .NET Core. I can not reference a .NET 4.x Framwork dll to an UAP/.NET Core project.

**Comment by mattiascibien** [comment]
Unfortunately I think it is not possible to mix code between UAP and Desktop as Pipeline.exe is a Desktop app and therefore cannot load a .NET core dll @tomspilman am I right?

**Comment by GrafSeismo** [comment]
Maybe this enlighten a bit: http://blogs.msdn.com/b/dotnet/archive/2014/12/04/introducing-net-core.aspx

**Comment by mattiascibien** [comment]
@GrafSeismo let's hear from the devs what they think.

**Comment by mattiascibien** [comment]
@GrafSeismo as a quick fix can you make your base Runtime dll a Portable Class Libraries so it can be referenced by .NET 4.0 and .NET Core? I am not sure if this is possible as I cannot check it now but PCLs can be referenced by both .NET core and .NET framework. The main problem is actually that MonoGame.Framework is not a PCL and therefore cannot be referenced (in my experience) by a PCL. 

You can try to create two Runtime projects (one NetCore and one .NET 4.0) and add files in one of them and link them with the Others by using Add Exsisting FIle... -> Add as Link (which is in the context menu of the Add split button)

**Comment by GrafSeismo** [comment]
.Net Core is not a part of .Net Framework. You can use .Net Core not in any combination with .net framework. The only similarity is the similar api which might be a subset of net. framework but is not in detail. So currently there is no way out without compiling a pipeline dll unter .Net Core conditions. That means that some parts need to be re-developed. My suggestion is that you split universal windows support (which supports now .Net Core only) from rest as a new project.

**Comment by mattiascibien** [comment]
I am sorry but I do not get your last post. What I told you before was to clone tour project in two so one runtime will be used by the pipeline (.net 4.0) and one used by your game (.net core).

Building a pipeline plugin under .net core is not actually possible as the content pipeline builder is a .NET 4.0 desktop app to ensure compatibility with Mono and therefore providing a cross-platform solution. 

The content pipeline project does not have sense under .NET core as it is not intended to run as a Windows UAP. 

I understand what happens in your case as you intend to use a base library that is needed by both your pipeline and your game. 

What I do not get is why you need to have content builders under .NET core.

Please tell me if I got your issue right, cause maybe I am messing up.

**Comment by GrafSeismo** [comment]
The point is that you can not add any dll that is not based on .net core to an existing UAP project. So how do i extend the pipeline in a windows universal project then without beeing part of .net core? 

XNA could do the separation of portable and framework (game<--->pipeline) because of portable was a subset of .net framework. So you can use ".net 4.x" in combination with ".net 4.x client". But the .net core is not a subset of .net framework. This leads me to you to provide us a pipeline which can be added to an universal windows app project.

**Comment by tomspilman** [comment]
This is just going to be a pain with UWP and .NET Core until all our platforms move to .NET Core.

If your pipeline extension requires a runtime data assembly with some data types you need to have both a .NET Core build and a regular .NET framework build.  The .NET Core version is used with the UWP game project at runtime and the .NET framework version is used from the pipeline extension assembly.

The only other work around to this is not needing this runtime data assembly to begin with.  I've done this myself before to avoid having an extra project.  I would link the same code in the pipeline assembly and in the game assembly then use the overload in `ContentTypeWriter`:
```
public override string GetRuntimeReader(TargetPlatform targetPlatform)
{
     // The name of the content type reader in my game EXE.
     return "MyGame.MyContentReader, MyGameAssembly";
}
```
This way the pipeline and game code are independent of each other.

**Comment by GrafSeismo** [comment]
i thought Mono is working with Microsoft together on that .net core topic....

**Comment by tomspilman** [comment]
> i thought Mono is working with Microsoft together on that .net core topic

I believe they are... but I expect it will still take a year or more before every platform moves to .NET Core.

**Comment by hach-que** [comment]
> I believe they are... but I expect it will still take a year or more before every platform moves to .NET Core.

This also won't impact old platforms as far as I know; things like MonoMac.  And no word on whether or not the Xamarin APIs will end up on .NET Core either, since they aren't standard .NET at all.

On the Protobuild side, we're only planning on switching the desktop platforms to .NET Core, with other platforms using what the target platform requires (since desktop is the only place where you can meaningfully change the framework).

**Comment by GrafSeismo** [comment]
here some others having hit the same issue: http://weblogs.asp.net/fbouma/%E2%80%9C-net-core-is-the-future%E2%80%9D-but-who%E2%80%99s-future-is-that

to gain .net core compatibility seems to become a big challenge...

**Comment by GrafSeismo** [comment]
i would like to sell my game on microsofts store as an universal app, but i can not do so because of no one provides a proper .net core support and monogame will not provide a running monogame core ready within one year, right? Do you know any alternative solution for my challenge?

**Comment by hach-que** [comment]
As far as I know, MonoGame does support Windows Universal, and you can use the current platform support to deploy apps to the Windows Store.

**Comment by GrafSeismo** [comment]
>As far as I know, MonoGame does support Windows Universal, and you can use the current platform support to deploy apps to the Windows Store.
But not a monogame with cutstom content pipeline!

**Comment by hach-que** [comment]
You can, you just need the implementation in two assemblies; one for .NET Core and one for .NET Full.

**Comment by GrafSeismo** [comment]
How do i call a .net framework dll from a .net core project?
As far as i know it is not possible...

at least one piece of both assemblies need to call pipeline internals which then try to deliver assets per .net framework into .net core game, right?

**Comment by tomspilman** [comment]
> How do i call a .net framework dll from a .net core project?

You don't.

As we've said there are two solutions:

 1. Create 2 different projects...  one for .NET Core and one for .NET Framework.
 2. Avoid needing a the runtime data assembly all together.

Both allow you to have a custom pipeline extension in a UWP application.

**Comment by GrafSeismo** [comment]
I will try this next year. I wish you all the best for the new Year 2016!

**Comment by GrafSeismo** [comment]
I got it to run by using .Net Framework and .Net core code in that combination you said. It did the job, but drop some funtionality i had under real XNA.
