### ISSUE TITLE
Version number on MonoGame installer ?

### ISSUE THREAD

**Issue by KakCAT** [mono/MonoGame#4365]
Hi,

all MonoGame installers share the same name, MonoGameSetup.exe . I don't know if this is this way on purpose, or just very difficult to get/maintain, but It would be great if the installer (at least for development builds) would include some kind of version in its name.

**Comment by cra0zy** [comment]
Right click > Properties should give you the version of the installer.

Alternatively just running it will give you it's version on the first screen.

**Comment by KakCAT** [comment]
Hi cra0zy

thanks, I'll rename the files accordingly when downloading them.

**Comment by tomspilman** [comment]
I also would prefer if the installer would include the version number in the filename, but it is surprisingly difficult to do that.  The most complex issue being having the website download link update to point to the new file name on each build.

**Comment by cra0zy** [comment]
You know, on Linux I actually get to see the version of .dll and .exe files in the thumbnail :)

![mgversion](https://cloud.githubusercontent.com/assets/6773302/12036274/b3925d78-ae44-11e5-8b53-d335236aac38.png)

**Comment by KakCAT** [comment]
thanks @tomspilman , that's what I meant. If the process was easy it'd be a lot better having a version, but being difficult it's best for users like me to just rename it.

Another question... how can I access to old development build installers?

Right now I'm having a problem with an UWP project with VS2015 recently updated to update 1 which freezes, and I'd like to discard monogame checking an old installer.


is this icon with version an OS feature, @cra0zy ?

**Comment by cra0zy** [comment]
Yes and No.

For Linux .exe isn"t a runable extension, to run Windows software on Linux you have to install Wine(or mono if it't .NET exe).

With wine you also get .exe thumbnailer by default on Ubuntu. Fedora doesn"t have this package.

**Comment by tomspilman** [comment]
> how can I access to old development build installers?

You can get them from the TeamCity build history:

http://teamcity.monogame.net/viewType.html?buildTypeId=MonoGame_DevelopWin&tab=buildTypeHistoryList&branch_MonoGame=__all_branches__&guest=1

The oldest we currently have is from July of this year.
