### ISSUE TITLE
MonoGame WindowsUAP install doesn't match source

### ISSUE THREAD

**Issue by bsimser** [mono/MonoGame#4367]
I think I've confirmed this on a clean machine now, the WindowsUAP.zip file that contains the universal files doesn't match what's in the repo. This is from the official 3.4 build available from the download page.

I checked a new copy of the WindowsUAP.zip file in \Documents\Visual Studio 2015\Templates\ProjectTemplates\Visual C#\MonoGame and found two problems:

1. The .csproj file template uses the wrong TargetPlatformVersion and TargetPlatformMinVersion values. They're 10.0.10069.0 for both values and should be at least 10.0.10240.0 but if you're using the latest SDK then the TargetPlatformMinVersion should be 10.0.10240.0 and TargetPlatformVersion should be 10.0.10586.0. This is correct in the github source but the 3.4 zip file contains an old version.

2. The project.json file is missing in the zip file. This will fail the build if you get past the version check by manually editing the .csproj file and reloading. The .json file is in the github folder.

I think it's just a distribution/packaging error somewhere as the code in the repo is correct.

**Comment by tomspilman** [comment]
>  the WindowsUAP.zip file that contains the universal files

Well that is the first red flag...  that should be named `WindowsUniversal.zip` as of the latest MonoGame 3.5 development build.

Are you installing MonoGame 3.4 or the latest MonoGame 3.5 development build?

**Comment by bsimser** [comment]
This is from the 3.4 build from the download page not the development build. Maybe the zip name and updated files didn't make it into that build? I thought they did as it was some time ago but I haven't looked at the histories. In any case, the "official" 3.4 release is broken so something to keep informed about for others having problems. Might be fixed in the dev build so not something that needs action if that's the case.

**Comment by bsimser** [comment]
Just an update, this is fixed in the 3.5 development build (with the new .zip filename). As I mentioned in another defect, while it is fixed most regular users might only download the 3.4 build and not download the development build. Anyone having issues with the official release either needs to fix this manually or grab the 3.5 development build until it gets released if they're building on Windows 10 and UAP projects. Thanks for the info and help!

**Comment by tomspilman** [comment]
We're working on getting the 3.5 release out soon which should address this.

I do worry however for the future when the VS team changes what SDK is installed by default and suddenly we stop working because of a dumb version number.

**Comment by BrianPeek** [comment]
AFAIK, VS will always default to the latest Windows 10 SDK, but previous editions will (should?) also be available to install.  As it stands today, VS2015 (Update 1) will install the 10586 SDK by default, but there's an additional checkbox to install the 10240 SDK as well.

**Comment by tomspilman** [comment]
>  As it stands today, VS2015 (Update 1) will install the 10586 SDK by default, but there's an additional checkbox to install the 10240 SDK as well.

Right... but people are leaving that unchecked.  So after the 30-40 minute install process and reboot you find out your MonoGame project isn't working.  Also I could be wrong...  but I think the error message that appears in these cases isn't very clear as to what the problem is.

We will just have to tightly chase the SDK versions to ensure new people don't get confused.

**Comment by BrianPeek** [comment]
I don't have a clean machine handy to test....not sure if it asks you to upgrade the project or download the SDK.  Or some combination thereof...

**Comment by bsimser** [comment]
The PR I submitted makes it work so new projects created will either work with the RTM SDK or the current (November 2015) release. If a new version comes along, people would manually have to update their .csproj file to support new(er) versions of the SDK but as long as they have either of these versions installed they're fine. If a new version of the SDK came along and we added it to the TargetPlatformVersion and users didn't have it installed it would still work as long as they had the minimum version (10240) and if they had nothing installed then it would just tell them they would need to install it (a dialog that provides a link to the download).

**Comment by BrianPeek** [comment]
That's not entirely true (or at least it shouldn't be).  TargetPlatformMinVersion suggests what version of the OS the app will **run** on...it has nothing to do with compilation.  VS uses it as a hint, but doesn't actually enforce it. TargetPlatformVersion is the required SDK to compile.  If it's set to 10240, it requires 10240 to be installed.  If it's set to 10586, it requires 10586 to be installed.

**Comment by hach-que** [comment]
Alright, that sounds like a scenario Protobuild should handle (for MonoGame and the project creation going forward). 

For Windows Universal platform, we should detect the highest SDK installed and use that when generating C# projects, since it sounds like all the APIs are compatible anyway.

**Comment by hach-que** [comment]
Protobuild as of 6dfc542 now detects the Windows 10 SDK version that's installed and uses that in the generated projects.

**Comment by bsimser** [comment]
So protobuild runs when a user chooses File | New | Monogame or when they install Monogame? If its when they install Monogame not sure the value of having the detection other than getting it right at that moment in time but once they upgrade the SDK they're back to square one. They'll install the new version and not leverage it (unless they remember and manually update the .cspro file).

**Comment by hach-que** [comment]
It runs when you create a new MonoGame project from the Visual Studio project creation dialog.

**Comment by hach-que** [comment]
To add:

* If you use the "Standard Projects" option when creating your MonoGame project, then yes the version number will be embedded in the C# project based on the SDK you have installed at the time.  This is how Standard C# Projects behave with the way Microsoft implements the SDK.
* If you use the "Protobuild" option to manage your projects, then the C# projects are generated when you open the project in the Protobuild Manager, and thus it will use the SDK version you currently have installed.  When you use Protobuild to manage projects, you shouldn't commit the C# projects or solutions to your repository (instead just commit Protobuild.exe and the Build folder).

**Comment by bsimser** [comment]
Sounds good. Having it run as the wizard fixes the problem of what version of the SDK the user has installed and supports future ones (since I'm assuming it reads from some registry or the file system to determine the installed version). Thanks.

**Comment by hach-que** [comment]
Yup, the latest version of Protobuild reads the installed SDK version from the registry so that it always uses the version that the developer has installed.

**Comment by BrianPeek** [comment]
If the goal here is to just get the latest SDK into the csproj at project creation time, then there is likely an easier way.  If this is going into a project template (vstemplate), this is built into the project template system:

<TargetPlatformVersion>$targetplatformversion$</TargetPlatformVersion>
<TargetPlatformMinVersion>$targetplatformminversion$</TargetPlatformMinVersion>

The macros should expand properly to whatever is on the user's system at project creation time.  The built-in templates use these macros already...see here:

C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\ProjectTemplates\CSharp\Windows Root\Windows UAP\1033\BlankApplication

**Comment by hach-que** [comment]
The new project creation system uses the cross-platform Protobuild template format, which doesn't use the Visual Studio templating system at all.

**Comment by bsimser** [comment]
@BrianPeek where were you about 100 messages about on all this? :) Just tried this and it works correctly (I have two versions of the SDK installed and it picked up the latest version). This is the right way to fix this so I'll do a PR later incorporating it.

**Comment by BrianPeek** [comment]
With all of the ProtoBuild changes, project creation, etc. etc. etc. my brain got lost in the shuffle.  :)
