### ISSUE TITLE
Development build and WindowsUniversal project version issues

### ISSUE THREAD

**Issue by bsimser** [mono/MonoGame#4369]
Creating an issue here and will be submitting a pull request against it shortly as the WindowsUniversal project template isn't quite right.

The problem is that it currently uses 10.0.10240.0 as the version number. This is fine if you have the old SDK installed but the current SDK is 10.0.10586.0. Without the old version installed you cannot create a new Windows 10 project. The dependency versioning is complicated and probably the cause of some issues people are having so here's what I'm seeing:

The 3.4 build uses an old TargetPlatformVersion in the .csproj template as well it's missing the project.json file (the zip file it installs is also named WindowUAP.zip and should be WindowsUniversal.zip)

The 3.5 build uses the 10240 TargetPlatformVersion and has the extra files with the correctly named zip file.

If you go to the SDK archive page and download the RTM version (https://dev.windows.com/en-us/downloads/sdk-archive) it will install version 10.0.10240 of the SDK which works with the 3.5 build (the version displayed on the screen says 10.0.26624 whcih installs to the 10.0.10240.0 folder which works with the 3.5 build). Confused?

You have to download the current SDK (https://dev.windows.com/en-us/downloads/windows-10-sdk) to get version 10586 so I'm going to submit a pull request that sets the minimum version to 10240 and the target version to 10586. This works for people that have the old SDK installed and the new one.

**Comment by hach-que** [comment]
If the SDK version is in the C# project file, you should submit a PR
against the Protobuild repo to change how the project generation works.

**Comment by bsimser** [comment]
The file is in the ProjectTemplates folder in this repo so I'm just modifying the Application.csproj file. What is this Protobuild repo you're talking about?

**Comment by hach-que** [comment]
Protobuild is the project generation system that MonoGame uses to generate
it's projects. Presumably the Windows 10 project format that MonoGame
itself uses also needs to be updated, but also in 4.6 and beyond it's
proposed that Protobuild will be used to generate new projects (see #4295 I
think).

You can find Protobuild at https://github.com/hach-que/Protobuild or
http://protobuild.org. It is the Protobuild.exe file that resides in the
root of this repository.

**Comment by bsimser** [comment]
Gotcha, I'm just going to leave my PR to fix the current template and let @tomspilman and others decide on the whole project generation as #4295 has a long thread and is a big overhaul (that looks like it'll come after 3.5). Thanks.

**Comment by tomspilman** [comment]
> This works for people that have the old SDK installed and the new one.

I see what you mean... that seems to make sense to me.

**Comment by tomspilman** [comment]
@hach-que - After @BrianPeek verifies for us that the fix in #4370 is safe, do you think we should do the same thing from Protobuild generation?
