### ISSUE TITLE
OpenTK requirements for gamepad support?

### ISSUE THREAD

**Issue by mrhelmut** [mono/MonoGame#4372]
Hello :)

It appears that gamepads are not working out of the box on MacOS. While we didn't had problems with most Linux distro, our Mac users can't use their gamepads (being Xbox360, PS3 or PS4) and the mono console prints "Number of joysticks: 0" when a game is started.

Does this have something to do with some missing dependencies? SDL?

**Comment by hach-que** [comment]
Are you using the latest development version, and do you have Xamarin Mac? In the latest development version we had to drop gamepad support for the moment because Xamarin removed the input APIs from OpenTK, but this will only impact you if you're building MonoGame from source on Mac with Xamarin Mac installed.

**Comment by mrhelmut** [comment]
I'm using the latest DesktopGL (built from VS), not the Xamarin Mac version. Was the sdl driver removed in the vanilla OpenTK too?

**Comment by hach-que** [comment]
No, that change only impacts people building the latest MonoGame from source on Mac, with Xamarin.Mac.  It does not impact any other scenario (but for that scenario it is the expected result at the moment).

**Comment by tomspilman** [comment]
> mono console prints "Number of joysticks: 0" when a game is started.

That looks to be coming from here:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Input/GamePad.OpenTK.cs#L31

Which means to me you are executing the right code path which includes GamePad support.

@cra0zy @dellis1972 ???

**Comment by mrhelmut** [comment]
I can confirm that this is related to SDL. GamePad driver is not initialized when SDL is missing and returns no gamepad. Everything works as expected when SDL is present.

It is only related to the vanilla OpenTK / DesktopGL, not MacOS (Xamarin powered) projects.

I'm currently working on DesktopGL projects deployment, I'll try to document that as well as shipping projects with MonoKickstart and all the correct dependencies for both OS X & Linux.

**Comment by dellis1972** [comment]
@mrhelmut I've messed with mac deployment for osx let me know if you need help with the docs
