### ISSUE TITLE
Generating installer for the game

### ISSUE THREAD

**Issue by cra0zy** [mono/MonoGame#4373]
I recently remembered that XNA had an option to generate an installer for the game (https://msdn.microsoft.com/en-us/library/bb464156.aspx), thought it might be interesting to implement this.

**Comment by tomspilman** [comment]
We have no reason to get into the installer business in this project.  There are lots of installers out there which people can use....  InstallShield, NSIS, InnoSetup, InstallBuilder, BitRock, etc.

What is more important is making it easy for developers to include all the dependencies required for MonoGame on Mac/Linux/Windows.  We could start by including a `redist` folder in the installed SDK which includes any assemblies and installers required on the player's system.  We can follow that up with a documentation page detailing the dependencies and what should be done at install time.

**Comment by raistlinthewiz** [comment]
@tomspilman :+1: 
and i'm back guys :)

**Comment by cra0zy** [comment]
Well, I still think this might be interesting, my reasoning is that in order for end user to make an installer for the game, they would need to learn 3 tools, 1 for each platform(not counting the fact that Linux actually has different packagers).

My idea is just to make it easy for the end user to make several installers without having to learn about each OS.

Also I would still use something like NSIS for installer generation on Windows, there would be no point in bothering to create an entire installer creation tool.

**Comment by tomspilman** [comment]
I guess i'm not totally opposed to this existing...  but it should likely be in a separate repo in the [MonoGame organization](https://github.com/MonoGame).

Let me know if you want me to create something like a `MonoGameInstaller` repo.

**Comment by cra0zy** [comment]
> Let me know if you want me to create something like a MonoGameInstaller repo.

Do it.

**Comment by tomspilman** [comment]
Is that what we want to call this project?  MonoGameInstaller?  Any other suggestions?

@KonajuGames @dellis1972 - Any comments on this?

**Comment by cra0zy** [comment]
I would name it MonoGamePackager, it could also provide an option to just generate an archive with MonoKickstart bundled.

**Comment by KonajuGames** [comment]
That wasn't an install builder that XNA shipped.  It was part of Visual Studio.  The MSDN documentation just describes how to use it with XNA.

Is there a standard installer for OS X?  I've seen several types in my limited use of OS X, same as there are a variety of installers for Windows.  That is aside from the App Store package.

There is no standard installer for the many different splinters of Linux, so I'm not sure what would be done for that.

As Tom suggested earlier, I think a `redist` folder and documentation, similar to the MSDN page that was linked, would be better than trying to make a one-installer-fits-all.

**Comment by tomspilman** [comment]
> I think a  redist  folder and documentation, similar to the MSDN page that was linked, would be better than trying to make a one-installer-fits-all.

I think regardless if @cra0zy takes on himself this official MonoGame installer/packager project we should still add a `redist` folder and docs on what is needed to distribute a MonoGame game.  Those same docs could then also link people to @cra0zy's tool for this.

**Comment by hach-que** [comment]
> could also provide an option to just generate an archive with
MonoKickstart bundled

fyi I was floating some idea around in my head about having some way of
generating kickstart bundles from a Protobuild module as something to do in
the far future, just to make it easier to ship Linux applications.  Not
sure if I even want to do it, no concrete plans in the area and even if I
did I'd want to do something general rather than tying it to kickstart.

**Comment by dellis1972** [comment]
For Mac we need to create a .pkg file (which we do in our build scripts as an example). 
A .dmg is effectively just a collection of pkg(s) (1 or more) into a image that can be mounted, like a .iso really. At the heart if the .pkg(s) which to the actual installation. 

For mac there are two steps, a  <applicaton>.app folder structure needs to be created with all the Info.plist stuff and the various contents (including mono runtimes) then a .pkg needs to be built from that. 
Xamarin.Mac projects will have the .app created automatically in the output dir so we can just package it like we do for the Pipeline tool. For games using DeksktopGL the .app would need to be created then the .pkg  all of which can be scripted :) @cra0zy I can help you with that stuff :D

MonoGamePackager is probably a better name than MonoGameInstaller as the "Installer" might give the impression its the actual installer for MG.. not the game :)

**Comment by dellis1972** [comment]
Docs for KickStart Mac deployment is on my todo list :)

**Comment by tomspilman** [comment]
Note that I expect this packager/installer is only for desktop platforms that lack official packaging standards.  So for Windows and DesktopGL.  I would expect this system would work for people deploying vita Steam and other PC centric stores.

> as the "Installer" might give the impression its the actual installer for MG.. not the game :)

Yeah...  that was my concern as well.  Making it not sound like an installer for the MonoGame SDK.

**Comment by cra0zy** [comment]
> For games using DeksktopGL the .app would need to be created then the .pkg all of which can be scripted :) @cra0zy I can help you with that stuff :D

Yey :D

> Note that I expect this packager/installer is only for desktop platforms that lack official packaging standards. So for Windows and DesktopGL. I would expect this system would work for people deploying vita Steam and other PC centric stores.

That is my idea.

**Comment by mrhelmut** [comment]
FYI, I've forked flibitijibibo/MonoKickstart and added the dependencies required by DesktopGL projects here: mrhelmut/MonoKickstart
Still a work in progress, I haven't thoroughly tested it on Linux, but it works just fine on OS X.

There are also some dependencies which could be added directly to project templates, like openal_soft.

A documentation regarding desktop platforms runtime requirements would be interesting IMO, as well as one regarding how to package apps (and :+1: for the packager idea). I have some docs written for our games, I'll try to reformat them when I have the time to.

**Comment by dellis1972** [comment]
we should have our own MonoGame fork of KickStart (if we don't already) it needs upgrading to 4.5

**Comment by tomspilman** [comment]
> we should have our own MonoGame fork of KickStart (if we don't already) it needs upgrading to 4.5 

We do...

https://github.com/MonoGame/MonoKickstart

**Comment by mrhelmut** [comment]
Oh, didn't even noticed it. flibitijibibo updated it to support .Net 4.5. If you pull his latest updates, I'd be glad to push the dependencies.

**Comment by cra0zy** [comment]
@tomspilman What GUI toolkit do you want me to use?
1) Eto Forms
2) Xwt
3) Per Platform

**Comment by tomspilman** [comment]
> If you pull his latest updates, I'd be glad to push the dependencies.

Someone have time to submit a PR to do that?


> What GUI toolkit do you want me to use?

I'm assuming this tool will be a simple single dialog sort of thing.  Probably no property grids or tree views.  I don't see a problem making it Xwt or GTK plus on all platforms.

**Comment by mrhelmut** [comment]
> Someone have time to submit a PR to do that?

Will do tomorrow.

**Comment by cra0zy** [comment]
> I'm assuming this tool will be a simple single dialog sort of thing. Probably no property grids or tree views. I don't see a problem making it Xwt or GTK plus on all platforms.

Turns out Xwt has some nasty bug with events right now... I'll go with Eto unless you want me to go with Gtk#

**Comment by tomspilman** [comment]
I know nothing of Eto vs Gtk#.  @dellis1972 @KonajuGames ?

**Comment by cra0zy** [comment]
Eto Forms: https://github.com/picoe/Eto

Basically Xwt with few extra backends.

**Comment by KonajuGames** [comment]
I'd never heard of Eto before.  I don't really mind which GUI framework it
uses.

**Comment by cra0zy** [comment]
In the end I am using Gtk#... turns out Eto had problems with treeview...

**Comment by mrhelmut** [comment]
MonoKickstart update: [MonoGame/MonoKickstart#1](https://github.com/MonoGame/MonoKickstart/pull/1)

I'll the dependencies in the separate commit, so they can't be verified independently.

**Comment by cra0zy** [comment]
@hach-que Do you have some way of disabling generation of xml documentation for assembly? I ask since I noticed bott MG Pipeline Tool and Protobuild.Manager are generating .exe.xml files for no reason...

**Comment by hach-que** [comment]
It originally didn't generate XML documentation unless you set the
property, and then a while ago (like 8-12 months) it unintentionally
changed to always do it after merging some XSLT changes in.

Not sure I want to change the default again here - what issue is it
causing?

**Comment by cra0zy** [comment]
> Not sure I want to change the default again here - what issue is it
> causing?

Besides pointlessly generated .exe.xml file it also makes IDE create pointless warning for public methods that don't have xml documentation(and they shouldn't, since it is an .exe, not a .dll).

**Comment by hach-que** [comment]
The way I solve those warnings is by declaring the classes internal (which
is the technically correct solution since you can add an .exe as a
reference to a project and call any of it's public methods, just as if it
was a DLL).

**Comment by cra0zy** [comment]
Can you pleeeeaaasseee try and add an option to disable xml documentation generation?

**Comment by hach-que** [comment]
If you want to submit a PR then okay, but I probably can't get to it until
the weekend.

**Comment by tomspilman** [comment]
@cra0zy - I think I will be submitting a PR to Protobuild for some other stuff i'm working on.  I can try to include an option for that.  Or maybe we should just disable doc generation on Executable projects in general.

**Comment by cra0zy** [comment]
> @cra0zy - I think I will be submitting a PR to Protobuild for some other stuff i'm working on. I can try to include an option for that. Or maybe we should just disable doc generation on Executable projects in general.

:D Thank you.

**Comment by cra0zy** [comment]
@tomspilman Can you create the "MonoGamePackager" repo? I am almost done with the base.

**Comment by tomspilman** [comment]
Is "MonoGame.Packager" ok?

**Comment by cra0zy** [comment]
> Is "MonoGame.Packager" ok?

Fine by me.

**Comment by tomspilman** [comment]
@cra0zy - Done....

https://github.com/MonoGame/MonoGame.Packager

You have write access to that repo, so you can merge things as needed.

**Comment by tomspilman** [comment]
Closing this issue... new discussions should occur in the new project.

**Comment by cra0zy** [comment]
> I'll push the dependencies in a separate commit, so they can be verified independently.

Any chance you have time to submit a PR for those dependencies now?

**Comment by mrhelmut** [comment]
Done: [MonoGame/MonoKickstart#2](https://github.com/MonoGame/MonoKickstart/pull/2)
