### ISSUE TITLE
xap: error: Failed to create importer 'XactImporter'

### ISSUE THREAD

**Issue by GrafSeismo** [mono/MonoGame#4376]
E:/Documents/Visual Studio 2015/Projects/MyProject/Content/Audio/XACT/Main.xap: error: Failed to create importer 'XactImporter'
What can i do?

**Comment by tomspilman** [comment]
I'm not sure what specifically you were doing at the time this error came up...  but MonoGame has nothing to do with XAP files.  XAP files are an Xbox and Windows Phone packaging thing.

That said MonoGame hasn't implemented any of the XACT pipeline features:

https://github.com/mono/MonoGame/issues/2661

**Comment by GrafSeismo** [comment]
Xaudio files are xap files that is not exclusivly bound to Xbox and Windows Phone.

**Comment by GrafSeismo** [comment]
So i do have a XAP file and no way to use it?

**Comment by GrafSeismo** [comment]
Ok i can integrate the final XAudio2 .xgs files but hat to build them external due to missing support by monogame.

**Comment by tomspilman** [comment]
> So i do have a XAP file and no way to use it?

Ahh... I see what you mean.  Yes XAct has a .xap file which is the XAct project file...  different than the WP and Xbox .xap packaging file.

You can build your content using the XAct Tools yourself then simply include the output xgs and xwb files in your content.

Hopefully in the near future someone will get the XAct processing working via the content pipeline.
