### ISSUE TITLE
Missing public API to query maximum number of game pads

### ISSUE THREAD

**Issue by hach-que** [mono/MonoGame#4379]
Currently the GamePad API does this internally:

```
if (index < 0 || index >= PlatformGetMaxNumberOfGamePads())
    throw new InvalidOperationException();
```

When you call GetState on an index outside the platform's maximum number of game pads, it throws an exception.  However, there's no public API for getting the value of `PlatformGetMaxNumberOfGamePads` (it is fully private), which means there's no way for a game to enumerate the list of supported gamepads without just cycling up to some number (e.g. 16) and catching exceptions.

**Comment by tomspilman** [comment]
We could add something like that specifically for the max gamepads supported by the platform.  This is all beyond XNA which only supported 4 via the `PlayerIndex` enum.
