### ISSUE TITLE
Split MonoGame.Framework into Seperate Assemblies

### ISSUE THREAD

**Issue by dellis1972** [mono/MonoGame#438]
This is a big job. We need to split the Framework up into seperate assemblies to help cut down on bloat when deploying applications on devices. 

Currently all the code is in one assembly MonoGame.Framework. This has a hard dependency on Lidgren which still has to be deployed even if you dont use networking. 

the plan is to split it out to 

MonoGame.Framework
MonoGame.Framework.Game
MonoGame.Framework.Net
MonoGame.Framework.GamerServices
MonoGame.Framework.Graphics

note there are some internal properties that are being used (to get the game instance for example) this problem needs to be resolved by either using the gameservices stuff or by using "Friend Assemblies" which requires signing.

Note that the existing MonoGame.Framework.<Platform> projects should be left as they are for now, so that if does not affect other teams working on the 3d stuff.

**Comment by Shqrdx** [comment]
I dont like this idea, The Mono in MonoGame means "United" and library should be unified in one assembly.

**Comment by tomspilman** [comment]
We moved to Protobuild which makes managing multiple project files much easier.

We did split `Xna.Framework.Net` `Xna.Framework.GamerServices` into a separate `MonoGame.Framework.Net` assembly so it doesn't get in the way anymore.

What the next split could be i'm not sure, but we should start a new issue to discuss it if someone has a suggestion.
