### ISSUE TITLE
OpenAL and maximum playing instances

### ISSUE THREAD

**Issue by mrhelmut** [mono/MonoGame#4403]
Hello,

It looks like the maximum of playing instances on all OpenAL platforms is set to 32 (```OpenALSoundController.MAX_NUMBER_OF_SOURCES```).

However, this limit is not considered in ```SoundEffect``` which has its own ```SoundEffect.MAX_PLAYING_INSTANCES``` set to ```int.MaxValue``` (DesktopGL) or ```256``` (XamMac).

There is yet another constant in ```SoundEffectInstancePool.MAX_PLAYING_INSTANCES```, but this one is never used. The ```SoundEffectInstancePool``` size is ```SoundEffect.MAX_PLAYING_INSTANCES```.

Fix proposal:
- set ```SoundEffect.MAX_PLAYING_INSTANCES``` to ```OpenALSoundController.MAX_NUMBER_OF_SOURCES``` on all OpenAL platforms and cleaning the duplicated / unused values;

P.S.: unless explicitly documented, it is advised to set ```OpenALSoundController.MAX_NUMBER_OF_SOURCES``` to 32 (most modern hardware do 64, but for compatibility it is safer to stick to 32, and there is no way to query this limit by code).

P.S. 2: ```MediaPlayer``` uses 1 unchecked source too, which means that the limit of 32 is wrong if the real hardware limit is 32 too.

**Comment by SirusDoma** [comment]
May I ask something regarding this issue?
I could understand that MonoGame (or OpenAL) can only handle 32 playing sounds at the same time.

But can a game have more than 32 **instances** of sounds?

**Comment by mrhelmut** [comment]
Yes, as many as you want, but there's a limit regarding the number of simultaneously **playing** instances, which depends on both the hardware and the audio backend.

There's nothing much we can do about this because we can't query the hardware capabilities. Hence we have to set this max to an arbitrary safe value, unless it is documented (like on mobile or Mac OS).

**Comment by pzgulyas** [comment]
OpenAL Soft has no limit in this regard (beyond the available RAM of course). One can have thousands of simultaneous sound sources.

**Comment by mrhelmut** [comment]
I was wondering about that, thanks for clarifying.

To sum up:
- Windows: "unlimited"
- MacOS: 256
- iOS: 32
- Android: 32
- Linux: maybe @cra0zy knows about that (I wonder if there are multiple implementations with different limits?)

Does using 256 for all DesktopGL platforms sound like a safe value?

**Comment by cra0zy** [comment]
> maybe @cra0zy knows about that (I wonder if there are multiple implementations with different limits?)

Usually 256

**Comment by pzgulyas** [comment]
OpenAL Soft doesn't throw an exception when reaching the limit with alGenSources() function, just it must be checked if the source ID had been really created, and if not, throwing the warning. There is no need to maintain a hard limit.

**Comment by KonajuGames** [comment]
It makes sense to keep a hard limit because MonoGame also has to keep track
of everything that is currently playing.  Keeping the maximum number to
within reasonable limits is a good thing.  Besides, what is the point of
having hundreds of concurrently playing sound instances when in reality you
will never reach that amount?  Have you ever tried to play more than 64
sounds at the same time?  It is an auditory mess.​

**Comment by SirusDoma** [comment]
> OpenAL Soft doesn't throw an exception when reaching the limit with alGenSources() function, just it must be checked if the source ID had been really created, and if not, throwing the warning.

agreed, newly generated source can be checked via `AL.IsSource` to determine whether the source was successfully created.

But..
> There is no need to maintain a hard limit.
What is "hard limit" actually? I know usually in Desktop, Sources instance limited to 256 and in Mobile 32, is this what you meant?

if so, I agree.
I don't really know the MonoGame mechanism, but since already being said that we can have as many sound instances as we want, I could guess that Source is being generated before the actual sound is being played (and i would guess that it will be destroyed / recycled after it's stopped or no longer in use)

**Comment by KonajuGames** [comment]
> I could guess that Source is being generated before the actual sound is being played (and i would guess that it will be destroyed / recycled after it's stopped or no longer in use)

There is a pool of SoundEffectInstance objects that is used before trying to create a new instance when the sound is played through SoundEffect.Play().

**Comment by mrhelmut** [comment]
There are many MonoGame internals bound to a hard limit (depending on platforms) and a lot of pooled elements to avoid pressure on the GC.

XNA has a limit of 16 playing instances, while MonoGame has a minimum of 32. It's already bigger than XNA. =P

FYI #4407

**Comment by pzgulyas** [comment]
> Have you ever tried to play more than 64 sounds at the same time?  It is an auditory mess.​
Although not related to MonoGame, but actually yes. Just think of e.g. a train simulator, where each car has 5-10 sound sources configured for various events, there are 20-30 cars audible at the same time, and guess what happens on a station with multiple trains, not even speaking about the ambient sounds. :)

Not all sounds have to be actually played at the same time, OpenAL sound sources are like a pool, that are created at loading time, for pre-buffering the wave data. I wonder (don't know actually), if you are buffering data into a source just before trying to play them, how it doesn't lead to delays in trying to play the sound in sync.

**Comment by KonajuGames** [comment]
> XNA has a limit of 16 playing instances, while MonoGame has a minimum of 32. It's already bigger than XNA.

For Windows Phone, XNA apparently has 16, though on Windows Phone 7 this was 64.  On Windows it has no hard limit, but too many concurrent sounds will cause performance degradation.  On Xbox 360 it had a total limit of 300 sounds loaded *or* playing.  From XNA's [SoundEffectInstance](https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.audio.soundeffectinstance.aspx).

> If you are thinking in small, then 64 is probably enough, but in large, not even close. :-)

I think you might be getting this discussion confused between the number of sounds loaded and the number of sound instances currently playing.  A `SoundEffect` represents the wave data.  This is loaded into memory when the `SoundEffect` object is created at load time.  A `SoundEffectInstance` is an instance of that sound effect being played.  A `SoundEffect` could be used as the source for zero or more `SoundEffectInstance`s at any one time.
