### ISSUE TITLE
GL VertexElementFormat.Short4 Bug?

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#4415]
I happened to find this...

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/GraphicsExtensions.cs#L70

Which looks like a bug...  shouldn't that be 4?  @dellis1972 @KonajuGames ?

**Comment by dellis1972** [comment]
It looks like it should be..

**Comment by KonajuGames** [comment]
That is definitely a typo.
