### ISSUE TITLE
Creating new MonoGame Windows 10 Universal project in VS 2015

### ISSUE THREAD

**Issue by SamTheDev** [mono/MonoGame#4435]
I am having the following error message when attempting to create a new MonoGame project using the  Windows 10 Universal project template in visual studio 2015 :

---------------------------
Microsoft Visual Studio
---------------------------
Error: this template attempted to load component assembly 'Microsoft.VisualStudio.Universal.TemplateWizards, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. For more information on this problem and how to enable this template, please see documentation on Customizing Project Templates.
---------------------------
OK   
---------------------------

I've installed the MonoGame 3.4 for VisualStudio, and the MonoGame Windows Project template works fine, here a shot for the template that's causing the issue 

![image](https://cloud.githubusercontent.com/assets/2827220/12383021/1ca04cc4-bda1-11e5-98d1-83821ac8ff1f.png)

**Comment by tomspilman** [comment]
I believe that suggests something is wrong in your VS2015 install.

 https://connect.microsoft.com/VisualStudio/feedback/details/1740696/new-windows-uap-project-wizards-fails
 http://stackoverflow.com/questions/31983150/windows-universal-app-development-template-load-error

Can you create regular C# Windows 10 Universal Projects... non-MonoGame that is?  If that doesn't work then I suggest re-installing VS2015.

**Comment by SamTheDev** [comment]
That indeed was related to an issue in my installation of VS 2015, i was able to fix it by reinstalling the Universal Windows App Development Tools.
Thx.

**Comment by tomspilman** [comment]
Thanks for reporting back @SamTheDev !

**Comment by maelruanaidh** [comment]
Also receiving this error, going to reinstall VS2015 per the advice here and report back.

![hfkz2oz 1](https://cloud.githubusercontent.com/assets/16568153/14269015/6d67a5f4-faae-11e5-80f0-2137d51e2212.png)

**Comment by JranZu** [comment]
Same issue here, however uninstalling & reinstalling the Universal Windows App Development Tools did NOT solved the issue.  I am able to create & publish normal windows 10 apps without any issue.

**Comment by BrianBergh** [comment]
I have same issue in Visual Studio 2017 (Professional) - I can create Windows 10 apps, and Universal Apps, but Monogame for Windows 10 / Universal, doesnt work. I get same dialog as above. Since noone reacts to this, i give up on mono, and go Unity.

**Comment by Jjagg** [comment]
Your issue is fixed in the development version of MonoGame, more specifically by #5546. You can get the latest development build from the downloads page on the website (under 'Development Builds): http://www.monogame.net/downloads/

 > Since noone reacts to this, i give up on mono, and go Unity.

This issue was fixed a long time ago. The issue you're having is different and occurs because of differences between 2015 and 2017 that were not yet taken into account in the MG 3.6 release. Also, Mono is a .NET runtime and not actually related to MonoGame.

**Comment by kriswd40** [comment]
I am seeing this same issue on VS 2015. I installed the latest version of MonoGame (3.6 for Visual Studio) and installed Universal Windows App Development Tools (it wasn't previously installed). 

Anything else I can try?
