### ISSUE TITLE
How can I create MonoGameSetup.exe from Monogame.develop distribution?

### ISSUE THREAD

**Issue by adggithub** [mono/MonoGame#4441]
I want to increase the number of bones in the skinnedmodels.cs, and in general I'd like to become able to collaborate in the monogame development. Once I run protobuild and created the dll with visual studio 2015, how can I install the packages in the right directories. Monogame distributions use MonoGameSetup.exe, but I cannot find how I can build it in the Monogame-develop distribution.

Thank you,
Alessandro

**Comment by tomspilman** [comment]
I answered this issue for @adggithub on the community site:

 http://community.monogame.net/t/monogame-installation/6892/2

... going to close this issue now.
