### ISSUE TITLE
Model renders black with SkinnedEffect

### ISSUE THREAD

**Issue by Jankamp** [mono/MonoGame#4443]
I have a skinned fbx model which renders perfectly using BasicEffect. But as soon as I select the SkinnedEffect in the pipeline tool (and in my code), it turns completely black. (using default lighting, specular power 16 and white color).

On my previous laptop it worked perfectly, but now for some reason it doesn't want to render properly anymore. I've tried to run it on another pc, but sadly I'm getting the same result. This laptop supports DX12 so that shouldn't be a problem.

When I use alphablend BlendState the model doesn't render at all. And when I use opaque, it renders black.

I'm using the latest code from the development branch.

Could this be a bug? Or is there something I should supply to the SkinnedEffect to make it work.
I can supply more info if needed, but I hope someone knows an easy fix for this.

**Comment by Helikin** [comment]
> When I use alphablend BlendState the model doesn't render at all. And when I use opaque, it renders black.

This happens if the alpha (transparency) value is 0. Please check if SkinnedEffect.Alpha is 1.

**Comment by Jankamp** [comment]
Hi Helikin, thank you for your response.
The alpha was set to 0.6f, but setting it to 1.0f doesn't help either. The thing is, it does render properly with the BasicEffect, just not with SkinnedEffect.

**Comment by Jankamp** [comment]
I found out what the problem is. I was using a testing model which didn't have any textures. I manually assigned a white texture to the skinnedeffect, and now it draws fine :-)
