### ISSUE TITLE
Platform Identifer Bug

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#4444]
Looks like we have a mismatch in `TargetPlatform`  and the platform identifiers written to the XNBs.

The enumeration for `TargetPlatform` has no OUYA anymore:
  https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework.Content.Pipeline/TargetPlatform.cs#L68

Yet the platform identifiers written to the XNB does include OUYA:
 https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework.Content.Pipeline/Serialization/Compiler/ContentWriter.cs#L53

This means everything after native client in that list has the wrong platform identifier written to the XNBs.

**Comment by tomspilman** [comment]
@dellis1972 @cra0zy @KonajuGames 

I think some of you have been working in this area...  what is the right fix here?

We should fix it ASAP for the 3.5 release.

**Comment by cra0zy** [comment]
Tada: #4445

**Comment by cra0zy** [comment]
PS. Ironically enough I wasdoing something with 4444 few minutes ago: http://mathforum.org/ruth/four4s.puzzle.html
