### ISSUE TITLE
SoundEffect.Play does nothing on Android

### ISSUE THREAD

**Issue by dellis1972** [mono/MonoGame#4452]
Latest unstable release, Music seems to play ok but sounds effects seem to do nothing. 
We probably should fix this (if its an issue and not must me) before the 3.5 release.

**Comment by mrhelmut** [comment]
It must be something wrong with ```OpenALSoundController```. Is there anything in the console output?

I can't debug on Android, can anyone try this branch and tell what's in the console output: https://github.com/mrhelmut/MonoGame/tree/OpenALCheck

It adds error checks on every AL calls, if there's something wrong it will either crash or print errors in the console.

**Comment by tomspilman** [comment]
@mrhelmut - Could we do something like we do for OpenGL where the error checking conditional for debug builds:

https://github.com/mono/MonoGame/blob/50a348a6ce7dae4e397353b7459c37d906dce587/MonoGame.Framework/Graphics/GraphicsExtensions.cs#L910

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/GraphicsDevice.OpenGL.cs#L291

**Comment by mrhelmut** [comment]
Sure, I'll do a pass on all AL calls. Let me know if you prefer that I submit a PR now to help resolve this issue or if you wish to wait until it is resolved for future maintenance.

**Comment by tomspilman** [comment]
> Sure, I'll do a pass on all AL calls.

Great... the sooner the better. It can't hurt in finding this and other potential bugs.

**Comment by dellis1972** [comment]
@mrhelmut ok.. nothing in the log :( it probes and finds the openal end points without any issue. Just no sound. neither SoundEffect or SoundEffectInstance works. AL.SourcePlay is not returning any errors either.  @KonajuGames have we updated the openal_soft stuff for android recently?

**Comment by dellis1972** [comment]
OK scratch that.AL.GenBuffers(1, out openALDataBuffer); is failing with IllegalCommand...

**Comment by dellis1972** [comment]
Probably because the OpenALSoundController is not being initialised BEFORE the content is loaded. So it can't create an buffers

**Comment by dellis1972** [comment]
SoundEffectInstance.OpenAL.cs has a method InitializeSound which creates the OpenALSoundContoller in PlatformInitialize. SoundEffect.OpenAL.cs does not it just creates a OALSoundBuffer. adding a call to OpenALSoundContoller.GetInstance in the SoundEffect.OpenAL.cs PlatformInitialize method (just before we create the OALSoundBuffer instance fixes the issue.. Just not sure its the right place for it.

**Comment by dellis1972** [comment]
PR is up :) Works on Mac.
