### ISSUE TITLE
OpenTK and Steam aren't good friends

### ISSUE THREAD

**Issue by mrhelmut** [mono/MonoGame#4466]
When DesktopGL games are launched from Steam, a couple issues can happen (tested on Windows only):
- mouse coordinates have the top left corner of the screen for origin when using windowed mode;
- ```Viewport``` (or possibly the backbuffer) size is 50% smaller (most probably related to the DPI issue);

This is not related to the overlay. Launching the exact same build from the install folder instead of the Steam client resolves these issues.

**Comment by mrhelmut** [comment]
This is due to SDL2 being used when a game is launched from Steam because Steam has SDL2.dll in its execution environment.

This expose two OpenTK issues when using SDL2 on Windows:
- mouse coordinates are incorrect when windowed
- it doesn't use DPI scaling despite the ```WindowFlags.ALLOW_HIGHDPI``` being active

**Comment by cra0zy** [comment]
Maybe we should have merged #4397 instead of me closing it?

**Comment by mrhelmut** [comment]
This would expose #4484

I'd prefer to keep SDL2 on Windows. Regarding DPI scaling, that's another issue which I believe is not openTK related.

**Comment by mrhelmut** [comment]
I found that, even if you don't distribute SDL2.dll with a game, Steam still inject it (most probably linked to its execution environment and/or the overlay) and makes OpenTK to use it.

The SDL2 backend is the one which works the best on Windows and since OpenTK is being replaced by SDL2, I'm assuming this issue isn't relevant anymore.
