### ISSUE TITLE
Texture2D.FromStream cannot load tga files

### ISSUE THREAD

**Issue by trommlbomml** [mono/MonoGame#4479]
Reproducable with no problems in MonoGame 3.4. Take a tga file and try to load it with Texture2D.FromStream. You will get a SharpDX exception:

HRESULT: [0x88982F50], Module: [SharpDX.WIC], ApiCode: [WINCODEC_ERR_COMPONENTNOTFOUND/Componentnotfound], Message: Component not found

I need FromStream() as I have a system to load data asynchronous and transparent from local and server, so I need byte arrays.

Any chance of fixes? My workaround is using png as this seems to work properly.

**Comment by KonajuGames** [comment]
PNG and JPG are the two image formats supported by FromStream, as they are more widely supported by the host systems.  Support for TGA could be added, but it would need to be written in C# as most of the host platforms do not have native support for TGA.

**Comment by trommlbomml** [comment]
Ok this is reasonable. I just fall over it because I tried to load the sponza model from crytek as a first big model loading test.

When just png and jpg are supported I would like at least to have a better error msg of type NotSupportedException if possible.

**Comment by tomspilman** [comment]
We should add some unit tests for `FromStream` specifically including some failure cases.

**Comment by trommlbomml** [comment]
I think even document this method that these two formats are supported only would help a lot. Unit-Test is also a good idea of course.

**Comment by Tzenchor** [comment]
With the changes done in the merged pull I think this can be closed

**Comment by tomspilman** [comment]
Thanks @Tzenchor !
