### ISSUE TITLE
Floating point values for Color do not work?

### ISSUE THREAD

**Issue by energyuser** [mono/MonoGame#4481]
Hello, I have found a strange issue with the `Color` class. I'm using the latest dev build of MonoGame and made an entirely new Windows Game project to make sure something from my current project does not conflict with my code and cause this issue. Consider this code in `Game1.Draw(GameTime gameTime)`:

`GraphicsDevice.Clear(new Color(231.0f, 214.0f, 90.0f, 1.0f));`

Although there are `float` overloads for `Color`, when I debug the program the color is not similar to light yellow, but it is entirely white. But if I make these `int`egers, it works fine. [Here is a side-by-side comparison in a screenshot.](http://i.imgur.com/vlm17ZM.png) Is this actually a bug or an intended behavior? I'm not so familiar with MonoGame's code implementation for `Color`, but correct me if I'm wrong, aren't `float` Color values just rounded to match `int` values, e.g. `243.2f = 243`?? This could be useful if you are getting a `float` value from arithmetic division and the framework will convert it to `int` for you, but again I'm not sure what your code implementation is, and I'm assuming that was the purpose of the `float` overloads?

**Comment by tomspilman** [comment]
Hi @energyuser .

> Is this actually a bug or an intended behavior?

You are just misunderstanding how to use the `Color` class.

The `Color` constructor which takes floats expects scalar 0 to 1 values as mentioned in the docs:

  http://www.monogame.net/documentation/?page=M_Microsoft_Xna_Framework_Color__ctor_1

**Comment by energyuser** [comment]
Oh, that's so unfortunate, I haven't drank my coffee while writing that code... I had no idea it was just like pre-multiplied alpha.

**Comment by tomspilman** [comment]
No problem... it happens.
