### ISSUE TITLE
Remove VertexPosition2ColorTexture add VertexPosition

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#4494]
I think we can remove the unused `VertexPosition2ColorTexture` type...

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/Vertices/VertexPosition2ColorTexture.cs

This I think is a legacy type left around from some old "optimization" in `SpriteBatch`.  I don't think anything uses it anymore.

At the same time we should consider adding a `VertexPosition` type.  This is the most basic type supported by `BasicEffect`:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/Effect/Resources/Structures.fxh#L11

And there has never been a built in type in XNA for this, but I think there should be.

@KonajuGames  @dellis1972 ?

**Comment by KonajuGames** [comment]
If BasicEffect supports it, it makes sense to add it. And I see no harm in
removing that other type.

**Comment by dellis1972** [comment]
:+1:

**Comment by tgjones** [comment]
This can be closed now.

**Comment by tomspilman** [comment]
Leave a comment
