### ISSUE TITLE
NuGet Automation Failing

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#4515]
Looks like our NuGet packaging has been failing since December and no one has noticed or reported it.  You can see here how the last updated package was December 15th:

  http://teamcity.monogame.net/guestAuth/app/nuget/v1/FeedService.svc/Packages

The error in the logs show is:

```
Starting NuGet.exe 2.8.60318.667 from C:\BuildAgent\tools\NuGet.CommandLine.DEFAULT.nupkg\tools\NuGet.exe
Attempting to build package from 'MonoGame.Framework.WindowsUAP.nuspec'.
File not found: 'WindowsUAP\AnyCPU\Release\SharpDX.XInput.dll'.
Process exited with code 1
```

http://teamcity.monogame.net/viewLog.html?guest=1&buildId=14560&buildTypeId=MonoGame_Automation_NuGetDevelop&tab=buildLog

I'm not sure if this is something wrong with the build or something wrong with the NuGet package definition.

Secondarily we need to make errors in NuGet packaging more visible.  Might need to have that specific email myself and @KonajuGames to alert someone of the issue.

**Comment by tomspilman** [comment]
@DDReaper  @BrianPeek - Any ideas?

**Comment by KonajuGames** [comment]
Silent errors are bad.

**Comment by BrianPeek** [comment]
I don't know how the package is put together on the server (the automated process), but it's looking for SharpDX.XInputl.dll in that directory listed and it's not there.  Should it be?  I would assume so.  Seems like it's just a simple "file not found"...

**Comment by tomspilman** [comment]
> Silent errors are bad.

I just made a change to the build server to do the same sort of reporting as we do for the normal build for the NuGet packaging.  On the next merge to develop we'll see how thing work.

The complication is that the NuGet Packaging happens after we merge to the Develop branch.  So it isn't reported till later.  So I guess we'll see what sort of issues that brings up.

Or maybe we should do Nuget packaging as part of the normal build from now on?  It takes a couple of minutes to run and it was easier to just make its own step when I added it.

**Comment by tomspilman** [comment]
>  it's looking for SharpDX.XInputl.dll in that directory listed and it's not there. Should it be?

That is the question... should it be?  I don't know for sure off the top of my head, but I suspect so.

**Comment by BrianPeek** [comment]
Hm...thinking back, didn't somebody write a UAP input "driver" that works against Windows.Gaming.Input instead of XInput?  If so, then no, XInput SharpDX.XInput probably isn't needed anymore...so long as all of XInput code was gutted from UAP.

**Comment by tomspilman** [comment]
> didn't somebody write a UAP input "driver"

Yep... that seems to be it.  This is where that occurred:

https://github.com/mono/MonoGame/pull/4077/files

... and you can see the reference to `XInput SharpDX.XInput` was removed under UWP

So the issue here then is that that .nuspec file still references this assembly I guess.

https://github.com/mono/MonoGame/blob/develop/NuGetPackages/MonoGame.Framework.WindowsUniversal.nuspec#L35

**Comment by dellis1972** [comment]
@tomspilman is that line isn't needed anymore I can fix that up if you like.

**Comment by tomspilman** [comment]
> is that line isn't needed anymore

Not 100% sure... waiting for someone else to confirm.

**Comment by BrianPeek** [comment]
If the ref is gone from the csproj, then it should be removed from the nuspec as well...it's no longer referenced, won't show up in output file, and is no longer needed.

**Comment by tomspilman** [comment]
@BrianPeek is correct.  Who ever has time please submit a PR removing that assembly from the nuspec.

**Comment by Tzenchor** [comment]
Just did the change and seems to work with my local copy

**Comment by tomspilman** [comment]
Thanks @Tzenchor!

**Comment by tomspilman** [comment]
Thanks for the PR @Tzenchor !

You can see the nuget build step is now working again:

http://teamcity.monogame.net/viewType.html?buildTypeId=MonoGame_Automation_NuGetDevelop&branch_MonoGame=%3Cdefault%3E&tab=buildTypeStatusDiv&guest=1

**Comment by BrianPeek** [comment]
I apparently fixed this months ago but it never got integrated.  Oh well.  :)

https://github.com/BrianPeek/MonoGame/commit/20792266fbb8d21a8d21f0b6deb640993cc76a87

**Comment by tomspilman** [comment]
> I apparently fixed this months ago but it never got integrated.

It happens to me more a lot too.  I have so many abandoned branches and stashed changes that will never see the light of day.
