### ISSUE TITLE
Keep or Remove PerformanceCounter

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#4518]
I ran into this random class in MonoGame tonight `PerformanceCounter`:

https://github.com/mono/MonoGame/blob/0b25f56e861fb602db884c40267b99ea947bae15/MonoGame.Framework/PerformanceCounter.cs

Should we remove this?  Should we keep it and improve it?

IMO the class needs to be good enough to be used within MonoGame itself if we want to keep it.  It has to be easy to turn on/off... ideally at runtime... with zero cost when off.

**Comment by prime31** [comment]
That is such a basic class that I just dont see any point in keeping it. Anyone doing performance testing already has that and much more implemented in their game. I just dont see the value in keeping the class.

**Comment by MichaelDePiazzi** [comment]
I agree with @prime31. Some other points in favour of getting rid of it:

- It's not part of XNA
- It probably needs a bit of work to get it to an acceptable standard

**Comment by tgjones** [comment]
+1 for removing it. MonoGame has [GraphicsMetrics](https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/GraphicsMetrics.cs) now, which is a nice addition, but there's no need for a general-purpose performance metrics framework.

**Comment by tomspilman** [comment]
Yeah... likely any performance metrics system we would develop would be subpar to professional C# profiler or tools like PIX or NVPerfHud.  We have plenty of more important projects.

If someone submits a PR to remove this we will merge it before 3.5 is released.
