### ISSUE TITLE
[SDL2/OpenTK] Mouse blocked after button down on OS X

### ISSUE THREAD

**Issue by mrhelmut** [mono/MonoGame#4529]
Hello,

I'm encountering some heavy mouse stuttering on OS X.

Whenever a mouse click (only on button down) is made, SDL2 doesn't return any mouse movement events for about 500ms. There's really no movement at all, being through ```SDL_PollEvents()``` (no event triggered) or ```SDL_GetMouseState()``` (coordinates haven't changed despite movements).

All other events are fine, it's only mouse movement which are "blocked" whenever a click is made.

I thought that it was linked to some trackpad palm detection, but it happens on all Mac with any kind of mouse (and trackpads are not affected by this issue).

@dellis1972 @cra0zy, would you happen to have any clues?

**Comment by dellis1972** [comment]
@mrhelmut is this using OpenTK's SDL2 back end?

**Comment by mrhelmut** [comment]
Yes.

**Comment by dellis1972** [comment]
I've not seen that. it sounds like something is locking the UI thread though.
I don't use SDL2 with OpenTK anymore on Mac. It seems to work ok without it since we forked OpenTK and fixed a bunch of stuff.

**Comment by mrhelmut** [comment]
Gamepads don't work with the native backend on both OS X & Linux in our situation, SDL2 is the most stable backend across all OS for our game.

I'll take a look at the OpenTK window's events to see if anything could block the UI thread.

**Comment by mrhelmut** [comment]
UI thread doesn't get blocked, event polling is still executing, it just doesn't return any mouse move events for ~500ms after a click.

**Comment by dellis1972** [comment]
@mrhelmut sounds like an SDL2 bug.

How come the native stuff doesn't work? seems to work ok for me.

**Comment by cra0zy** [comment]
No idea what is causing this. I was not able to reproduce it on Linux

**Comment by mrhelmut** [comment]
It seems to be OS X only, I don't have it on Windows too.

I have several problems with the native backends:
- Windows: keyboard recognized as 2 gamepads
- OS X: gamepad not recognized, retina not working correctly, mouse position always 0 (may be retina related)
- Linux: gamepad not recognized, fullscreen issues

SDL2 works fine everywhere for me, minus this current  issue.

**Comment by cra0zy** [comment]
> Linux: fullscreen issues

I forgot about that... I had a fix for it for so long... submitted in #4530

**Comment by dellis1972** [comment]
@cra0zy merged :P

**Comment by mrhelmut** [comment]
Fixed by #4755
