### ISSUE TITLE
Selecting child node in Monogame pipeline tool does not update property grid 3.5.0.1169 Windows

### ISSUE THREAD

**Issue by ascorbius** [mono/MonoGame#4531]
When I click on one of my assets in the pipeline tool, the property grid does not change to show the available options and settings for the file.

This means that I cannot select build options.

I have tested this on multiple mgbc files for different projects, all exhibit the same problem.

**Comment by cra0zy** [comment]
It has been fixed in a newer build #4432

The code was already merged, so download the newest develop version from: http://teamcity.monogame.net/repository/download/MonoGame_DevelopWin/latest.lastSuccessful/Windows/MonoGameSetup.exe?guest=1, it will have the fix.

**Comment by ascorbius** [comment]
Awesome, thanks for the tip. I installed the latest dev version and confirm it to be fixed. Keep up the good work ;-)
