### ISSUE TITLE
FullScreen Viewport Broken on Native OpenTK on Mac

### ISSUE THREAD

**Issue by dellis1972** [mono/MonoGame#4538]
When using native OpenTK (not SDL) on Mac. The GraphicsDevice Viewport is not updated correctly to reflect the screen resolution when in full screen mode. As a result it draw the game in the bottom right corner of the screen. This was working "something" changed to break this. 

@cra0zy @mrhelmut any ideas 

<img width="1440" alt="screen shot 2016-02-14 at 22 39 14" src="https://cloud.githubusercontent.com/assets/810617/13036944/6e95e5f8-d36c-11e5-893a-1975d1343307.png">

**Comment by cra0zy** [comment]
What happens when you use SDL backend?

**Comment by dellis1972** [comment]
@cra0zy it kinda works but the window state is weird.
When toggling between full and windowed it changes the viewport to windowed but the window ends up in the bottom left and you get a full black screen. Using the menu "Enter Full screen" works, but toggling in code has some weird behaviour.

Oddly this was working perfectly a while back (28th Jan)

<img width="1440" alt="screen shot 2016-02-14 at 23 07 55" src="https://cloud.githubusercontent.com/assets/810617/13037070/faf553a0-d36f-11e5-94bb-59ce6e8dfaf8.png">

**Comment by dellis1972** [comment]
Just can't nail down the commit which caused it :/

**Comment by dellis1972** [comment]
Hmm ChangeClientBounds is not being called when switching to FullScreen anymore

**Comment by cra0zy** [comment]
It's probably something with OpenTKWindow, try going threw https://github.com/mono/MonoGame/commits/develop/MonoGame.Framework/Desktop/OpenTKGameWindow.cs

**Comment by dellis1972** [comment]
Yup that's what I've been doing.

**Comment by mrhelmut** [comment]
Are you on a Retina display? (or changed the DPI settings of your Mac?) This looks quite similar to what's happening on Retinas.

**Comment by dellis1972** [comment]
@mrhelmut I am.. what confused me is it worked a few weeks ago.. and I still have the binaries of the working version.

**Comment by dellis1972** [comment]
I might do a monodis on the two versions and see what changed

**Comment by mrhelmut** [comment]
If it worked before, that sounds interesting because I've been trying hard to figure out this without much luck. I've only been using SDL on OS X, though.
Looks like I've started working with Retinas after that change (about a month ago).

**Comment by dellis1972** [comment]
tracked it down to this commit https://github.com/mono/MonoGame/commit/b668e0ae4ad336d9d6c370f4e4668fa2034cc6f4#diff-0868bcaf63f47b7a6d356a4eab48bed8

**Comment by dellis1972** [comment]
I have a fix will open a PR in a bit

**Comment by cra0zy** [comment]
#4398 #4436

**Comment by dellis1972** [comment]
Its really weird. SDL2 is really bad on my mac. The native OpenTK is much better.

**Comment by mrhelmut** [comment]
SDL2 has some problems on OS X Retina (e.g. cropped / too small image when the resolution is different from ```GraphicsAdapter.DefaultAdapter.CurrentDisplayMode.Width / Height```), but I've worked around this by rendering our game in a RenderTarget and stretching it to the desktop resolution... This was the least time consuming method I've come up with while OpenTK is being replaced.

As far as I have looked into fixing OpenTK viewport resizing to work on any OS / DPI, I felt like everything (i.e. backends & platform specific resizing) is too deeply entangled together. Everything I tried to fix ended up breaking something else on another OS.

**Comment by dellis1972** [comment]
@mrhelmut  this works for me (on Native) https://github.com/mono/MonoGame/pull/4540

**Comment by cra0zy** [comment]
@dellis1972 I think Windows needs to do the same thing Linux does.

**Comment by dellis1972** [comment]
ok, I'll boot my win box and test :)

**Comment by mrhelmut** [comment]
I'll test that asap, but I won't be able to test it on OS X / SDL2 until next week. :)

**Comment by dellis1972** [comment]
@cra0zy can you test #4540 on linux? make sure I didn't break anything

**Comment by cra0zy** [comment]
> @cra0zy can you test #4540 on linux? make sure I didn't break anything

Tested and it didn't break anything.
