### ISSUE TITLE
Sound issues with MonoGame 3.5.0.1381

### ISSUE THREAD

**Issue by endimilojkoski** [mono/MonoGame#4539]
After moving to latest dev build I am having strange issues with sound on Windows 8.
When I Start the game in VS the sound works. If I start the game by opening exe there is no sound.
But then I got cases when there was no sound even when Starting it from VS.

I tried older build of the game and the sound was working fine. When I replaced the Mono Game dll with latest the sound stopped working.

I tried the latest build on another PC with Windows 10 and the sound was OK, no issues.

This is what I logged on Windows 8:

External component has thrown an exception.;    at Microsoft.Xna.Framework.Audio.OpenALSoundController.ReserveSource()
   at Microsoft.Xna.Framework.Audio.OggStream..ctor(String filename, Action finishedAction, Int32 bufferCount)
   at Microsoft.Xna.Framework.Media.Song.PlatformInitialize(String fileName)
   at Microsoft.Xna.Framework.Media.Song..ctor(String fileName)
   at Microsoft.Xna.Framework.Media.Song..ctor(String fileName, Int32 durationMS)
   at Microsoft.Xna.Framework.Content.SongReader.Read(ContentReader input, Song existingInstance)
   at Microsoft.Xna.Framework.Content.ContentTypeReader`1.Read(ContentReader input, Object existingInstance)
   at Microsoft.Xna.Framework.Content.ContentReader.InnerReadObject[T](T existingInstance)
   at Microsoft.Xna.Framework.Content.ContentReader.ReadObject[T](T existingInstance)
   at Microsoft.Xna.Framework.Content.ContentReader.ReadObject[T]()
   at Microsoft.Xna.Framework.Content.ContentReader.ReadAsset[T]()
   at Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T](String assetName, Action`1 recordDisposableObject)
   at Microsoft.Xna.Framework.Content.ContentManager.Load[T](String assetName)
   at RainingBlobs.SongLoader.LoadSong(String song) in c:\_Work\VisualStudio2013\MonoGame3.5_unofficial_2\RainingBlobs\RainingBlobs\Code\Sound\BackgroundMusic.cs:line 124
   at RainingBlobs.BackgroundMusic..ctor(Single volume) in RainingBlobs\Code\Sound\BackgroundMusic.cs:line 171; MonoGame.Framework

Attempted to divide by zero.;    at Microsoft.Xna.Framework.Audio.OALSoundBuffer.BindDataBuffer(Byte[] dataBuffer, ALFormat format, Int32 size, Int32 sampleRate)
   at Microsoft.Xna.Framework.Audio.SoundEffect.PlatformInitialize(Byte[] buffer, Int32 sampleRate, AudioChannels channels)
   at Microsoft.Xna.Framework.Audio.SoundEffect..ctor(Byte[] buffer, Int32 sampleRate, AudioChannels channels)
   at Microsoft.Xna.Framework.Content.SoundEffectReader.Read(ContentReader input, SoundEffect existingInstance)
   at Microsoft.Xna.Framework.Content.ContentTypeReader`1.Read(ContentReader input, Object existingInstance)
   at Microsoft.Xna.Framework.Content.ContentReader.InnerReadObject[T](T existingInstance)
   at Microsoft.Xna.Framework.Content.ContentReader.ReadObject[T](T existingInstance)
   at Microsoft.Xna.Framework.Content.ContentReader.ReadObject[T]()
   at Microsoft.Xna.Framework.Content.ContentReader.ReadAsset[T]()
   at Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T](String assetName, Action`1 recordDisposableObject)
   at Microsoft.Xna.Framework.Content.ContentManager.Load[T](String assetName)
   at RainingBlobs.GameSounds..ctor() in RainingBlobs\Code\Sound\GameSounds.cs:line 95; MonoGame.Framework

Hope this can be fixed quickly since it is blocking the Windows version update.
I pushed Linux and Mac updates with latest build and I did not have this issue there.

@mrhelmut @cra0zy

**Comment by tomspilman** [comment]
@endimilojkoski - I assume you are using the WindowsGL platform?

**Comment by endimilojkoski** [comment]
@tomspilman yes, the game is built in WindowsGL project but I replaced MonoGame, OpenTK and NVorbis with DesktopGL versions. Is there something else that I am missing?

**Comment by mrhelmut** [comment]
First thought would that openal32.dll is missing, but that would end up in a different crash.

Taking a look...

**Comment by endimilojkoski** [comment]
OpenAL is installed and the dll exists in the game's folder.

**Comment by mrhelmut** [comment]
Do you have anything else in the console output? Like "Failed to fill buffer" or "Failed to generate buffers"?
These exceptions are typical to early OpenAL fails where it couldn't get initialized.

**Comment by endimilojkoski** [comment]
No error and nothing extra in the output.
I can't even get the above error again.
I Start it from VS and sound plays. I run the exe and there is no sound and no error logged and the game don't crash. Really strange.

I will continue testing. But this don't happen with older MonoGame dll so it must be something in latest build or my machine got crazy :)

**Comment by mrhelmut** [comment]
Try to clean/rebuild everything, including contents with the latest pipeline tool. Some errors may be hidden by cached stuff.

**Comment by endimilojkoski** [comment]
I have done that. Cleaned/deleted everything, rebuilt the ogg songs for DesktopGL platform and still same issue. I Start it from VS and sound works. Start without debugging or open the exe and there is no sound and no errors.

One thing that I noticed that is different from before is when I add raw png image it is not being displayed in game. But I assume this is done intentionally.

I pushed the update for windows without updating MonoGame. Hope we get to the bottom of this soon.

**Comment by Tzenchor** [comment]
> One thing that I noticed that is different from before is when I add raw png image it is not being displayed in game. But I assume this is done intentionally.
I have seen the same said at the end of #1946. And I think the problem might be coming from #4487

**Comment by endimilojkoski** [comment]
I found another issue in this version.
When moving Down on Left Stick on xbox 360 controller it also moves Up at the same time.
This issue does not exist in Windows version.

**Comment by tomspilman** [comment]
>  On Mac, when moving Left Stick Up on xbox 360 gamepad it also moves Down. Dpad is OK.

@dellis1972 ???

**Comment by dellis1972** [comment]
@mrhelmut ?? ^

**Comment by dellis1972** [comment]
@endimilojkoski I'm guessing that is an OpenTK issue. @cra0zy @mrhelmut any ideas?

**Comment by endimilojkoski** [comment]
I will try with latest develop OpenTK and let you know right away.

**Comment by endimilojkoski** [comment]
I just tried on Mac with develop OpenTK and it is same.
Left Stick Up acts as Left Stick Up and Down.
On Windows and Linux this does not happen.

**Comment by dellis1972** [comment]
@endimilojkoski this is going to be something to do with the gamepad mapping changes in this commit https://github.com/opentk/opentk/commit/f996c8d2c7f2a074050d6ee7b34cead18e55e35e I think

**Comment by endimilojkoski** [comment]
And this was not happening before I went to MonoGame and OpenTK that came with this version.

**Comment by dellis1972** [comment]
or this one https://github.com/opentk/opentk/commit/d0efd76edf69f8662bd5f7e63d8fe83d86077f7c

**Comment by endimilojkoski** [comment]
I inverted Y axis in my code after these changes and it works fine on Windows and Linux.

**Comment by mrhelmut** [comment]
I'll take a look at this, I don't have these issues with the SDL2 backend but I think I know where the problem is, I've already encountered it with PS4 controllers (it seems to be specific to some gamepad brands and how they map hat states).

**Comment by endimilojkoski** [comment]
I am testing with xbox360 wired controller if I haven't mentioned.

**Comment by dellis1972** [comment]
@mrhelmut I have noticed that the Y value is positive until it goes above 1 then it goes negative. So if you push the stick all the way up you get a - value.. but part of the way its positive. Looks like an overflow issue?

**Comment by endimilojkoski** [comment]
@dellis1972 you are right. If I don't move the left stick all the way up it works fine.

**Comment by dellis1972** [comment]
I think OpenTK inputs are overflowing the short range and are wrapping.

**Comment by dellis1972** [comment]
@mrhelmut  I think we need to change the code in OpenTK GamePadState

https://github.com/opentk/opentk/commit/d0efd76edf69f8662bd5f7e63d8fe83d86077f7c#diff-119308f4c7bc6b41126761ac99110d38R174

to use the following when setting the axis values.
```
foo =  (short)MathHelper.Clamp(value, short.MinValue+1, short.MaxValue-1);
```
for some reason just using short.MinValue/MaxValue doesn't work. We need to be +/- 1 on each..

**Comment by dellis1972** [comment]
Oh and make use we use the - version where needed

```
(short)-MathHelper.Clamp(value, short.MinValue+1, short.MaxValue-1);
```

**Comment by dellis1972** [comment]
@mrhelmut  this seems to fix the issue for me 
https://gist.github.com/dellis1972/671fd03d5c92c18993d0
not sure is the right way to go though.

**Comment by mrhelmut** [comment]
Thanks, I'll try that tomorrow and will report back!

**Comment by cra0zy** [comment]
short has a range of -2^15 to 2^15 - 1, minus side has one more number than plus side, so the correct fix should be:
```c#
value > 0 ? -value - 1 : -(value + 1)
```

**Comment by endimilojkoski** [comment]
Thanks @cra0zy this solves the problem. I tested and already updated the game on Steam.

But what about the strange sound issue? Any ideas?
I updated Steam Windows version to latest MonoGame and now I don't have sound but other have.
This happened to me with latest version of MonoGame and I hope it is just me :)

**Comment by endimilojkoski** [comment]
About the sound issue.
Since it was working fine for others and not working for me I assumed there must be something wrong with my OpenAl. Tried reinstalling it and nothing changed.
Tried adding the OpenAl32.dll to the root of the game and still no difference.

Then I started looking at other openal DLLs. Took @mrhelmut 's openal from Neuro Voider and the sound now works for me!
My openal dll was around 100KB and the working one is 825KB!
Not sure what went wrong on my side and why such big difference between the files but I finally solved my mystery :)

**Comment by cra0zy** [comment]
What issues are left in here?

If everything is resolved do close this.

**Comment by mrhelmut** [comment]
That's interesting. OpenAL is a specification and therefore multiple implementation exist. There are two common OpenAL implementations (on Windows):
- the original OpenAL from Creative (which is the one installed by MonoGame on Windows)
- "OpenAL Soft", which implements the specs to do all the mixing on the CPU

The thing is that the Creative's one is outdated and not maintained anymore. OS X has its own implementation too. The major problem is that every implementation may have its own small deviation from the specification, which make the sound to render differently on each platform...

This is discussed in #4639, and OpenAL Soft will most probably be used on all platforms in the future. This will make sounds to have homogeneous rendering across all platforms.

(I'm using OpenAL Soft dll instead of the Creative's one in NeuroVoider.)

**Comment by endimilojkoski** [comment]
But how was it working when I press RUN in VS and not working when I start the exe?? :)
How was it working for other players on Steam and it is not working for me?? :)
Maybe others have the correct OpenAL installed probably from other games/programs?

QQ before I close this one.
Hori Real Arcade Pro 4 Stcik (for PS3 I think), wrong mappings: down=left, up=right.
Issue reported on Windows. Other gamepads working fine for the player.
Do you want me to open new issue for this?

**Comment by mrhelmut** [comment]
> But how was it working when I press RUN in VS and not working when I start the exe?? :)
> How was it working for other players on Steam and it is not working for me?? :)

dll mess when you have a version installed in your system and another one in the execution path... it's safer to add the dll to your project and ship it with the game than relying on another installer.

Regarding the Hori stick mapping, better opening an issue on the opentk repository. The mappings are handled there (the GUID of the stick would greatly help).

**Comment by endimilojkoski** [comment]
OK, thanks guys!
Will create an issue for the arcade stick on OpenTK and close this.
