### ISSUE TITLE
Can't Install monogame 3.5 (or pipeline) after new installer change (Mac)

### ISSUE THREAD

**Issue by VinnieH01** [mono/MonoGame#4543]
After the new change to the installer : https://github.com/mono/MonoGame/commit/1ba57c9b34fd25a63f2f1c74d23d780d515a7473

When I installed the newest version everything seamed fine but when I started Xamarin Studio the package wasn't installed and when trying to open the pipeline tool it says : "Cannot open file". I tried reinstalling Xamarin but that didn't work and I've reinstalled monogame probably about 5 times.

**Comment by tomspilman** [comment]
@dellis1972 - Something to consider when you investigate this...  it could also be something broken in the new automated build process.

**Comment by dellis1972** [comment]
Sounds like the .mpack is missing/didn't install. I'll investigate.

**Comment by dellis1972** [comment]
ok Problem 1) the Pipeline script in /Pipeline.app/Contents/MacOS does not have executable privilege 

'sudo chmod +x /Applications/Pipeline.app/Contents/MacOS/Pipeline '

fixes that issue

**Comment by dellis1972** [comment]
looks like its mainly a permissions issue. form some reason the post install script isn't updating them

'sudo chmod u+x /Applications/Pipeline.app/Contents/MacOS/Pipeline '
'sudo chmod u+x /Applications/Pipeline.app/Contents/MonoBundle/ff* '

**Comment by dellis1972** [comment]
Possible fix in https://github.com/mono/MonoGame/pull/4544

**Comment by dellis1972** [comment]
i.e works on my machine :)

**Comment by VinnieH01** [comment]
Good, but does this also fix the problem with the .mpack?

**Comment by dellis1972** [comment]
@VinnieH01 I'm not seeing the problem with the .mpack. The extension installs correctly into XS here. 
Can you post your installer logs? 

When you run the installer goto Window->Installer Log and change the view to Show All Logs then post the results once the installer is complete.

**Comment by VinnieH01** [comment]
@dellis1972 Im not good at the stuff you do but Im thinking it has to do with line 53 on this file : https://github.com/dellis1972/MonoGame/blob/f6fa323f9946ea6cc0c21a19ee43cea44f7cd42a/Installers/default.build It's copying it to some MonoDevelop folder and not XS. Ok sure I'll post the log, wait a sec

**Comment by dellis1972** [comment]
@VinnieH01 the actual installation happens in the post install script. that line in the default.build just builds the Mac .pkg for the Addin.

https://github.com/dellis1972/MonoGame/blob/f6fa323f9946ea6cc0c21a19ee43cea44f7cd42a/Installers/MacOS/Scripts/Addin/postinstall#L5

**Comment by VinnieH01** [comment]
@dellis1972 [Installationslogg 17-Feb-2016.txt](https://github.com/mono/MonoGame/files/135085/Installationslogg.17-Feb-2016.txt)

**Comment by VinnieH01** [comment]
@dellis1972 some stuff in the log seems to be in swedish, I can see if I can change a setting on my computer and post it again if you want. (If its hard to understand)

**Comment by dellis1972** [comment]
@VinnieH01 looks like the .mpack issue is 

`sudo: unknown user: /Applications/Xamarin Studio.app/Contents/MacOS/mdtool`

can you save the following and run it (you might need to chmod +x it first)

`#!/bin/bash
CONSOLE_USER=$(ps aux | grep console | grep -v grep | cut -d' ' -f1)
echo $CONSOLE_USER`

on my machine it outputs my user name

**Comment by VinnieH01** [comment]
@dellis1972 Im sorry but what should I save it as and how should I run it?

**Comment by dellis1972** [comment]
@VinnieH01 actually just run the following from a terminal

`sudo ps aux | grep console | grep -v grep | cut -d' ' -f1`

and post the results.

**Comment by VinnieH01** [comment]
It does nothing.. It just asks for my password and then nothing happens

**Comment by dellis1972** [comment]
@VinnieH01 hmm ok thats the issue then. That code tells us which user to install the addin into do otherwise it gets installed as the root user.
We'll have to research to see if there is another way.

**Comment by VinnieH01** [comment]
@dellis1972 ok, hopefully you can find another way :)

**Comment by dellis1972** [comment]
@VinnieH01 does 

`sudo stat -f '%Su' /dev/console`

work?

**Comment by VinnieH01** [comment]
@dellis1972 It prints VinnieH01

**Comment by dellis1972** [comment]
ok much better :) will try to add that to the PR. that should fix it. Thanks for the bug report :)

**Comment by VinnieH01** [comment]
@dellis1972 No problem, glad to help. Ive been looking forward to you fixing the installer so it dosn't install v. 3.3 :)
