### ISSUE TITLE
Pipeline log: missing newline after an (Assimp) exception encountered

### ISSUE THREAD

**Issue by InfiniteProductions** [mono/MonoGame#4556]
(Pipeline version 3.4.0.456)
When an exception is encountered while building content, here with Assimp, the newline AFTER last exception character is missing (see below, "pipelineEvent)***Z:/MonoGame/"  *** where the missing newline should be) if it occurred before build report.

Build started 21/02/2016 11:45:01

[...]
Z:/MonoGame/test1/Content/box-fbx2012a.FBX: error: Importer 'FbxImporter' had unexpected failure!
Assimp.AssimpException: Error importing file: FBX-Parser (TOK_DATA, line 319, col 7) unexpected token, expected TOK_KEY
   … Assimp.AssimpContext.ImportFile(String file, PostProcessSteps postProcessFlags)
   … Microsoft.Xna.Framework.Content.Pipeline.OpenAssetImporter.Import(String filename, ContentImporterContext context)
   … Microsoft.Xna.Framework.Content.Pipeline.ContentImporter`1.Microsoft.Xna.Framework.Content.Pipeline.IContentImporter.Import(String filename, ContentImporterContext context)
   … MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent(PipelineBuildEvent pipelineEvent)Z:/MonoGame/test1/Content/box-fbx2013a.FBX
------------------|------------------- HERE

Z:/MonoGame/test1/Content/box-fbx2010a.FBX
[...]
Build 3 succeeded, 2 failed.

Time elapsed 00:00:00.39.

**Comment by nkast** [comment]
Probably fixed with https://github.com/mono/MonoGame/pull/4366
Please download and verify with latest build from http://www.monogame.net/downloads/

**Comment by InfiniteProductions** [comment]
I've tried with the develop branch, the new pipeline tool is quite better and the new tree structure display prevent the issue to happened any more.

**Comment by nkast** [comment]
If you switch off the filter view you will see the full output. So is this good?

**Comment by InfiniteProductions** [comment]
Yes, without the filter, output are clean and there is the newline after the last line of assimp exception. This issue is good to close :).

**Comment by KonajuGames** [comment]
Thanks for confirming it. Closing.
