### ISSUE TITLE
Can't render '█'

### ISSUE THREAD

**Issue by cra0zy** [mono/MonoGame#4557]
During the DrawString instead of drawing '█', it draws a ' ' instead.

**Comment by KonajuGames** [comment]
What character code is that?  Is the character code specified in the .spritefont file?  Is the glyph for that character code in the font listed in the .spritefont file?

**Comment by cra0zy** [comment]
> What character code is that? Is the character code specified in the .spritefont file? Is the glyph for that character code in the font listed in the .spritefont file?

I specified the character code by doing:
```
<CharacterRegion>
  <Start>█</Start>
  <End>█</End>
</CharacterRegion>
```

It's not crashing with Glyph not found error so it did compile it.

**Comment by Tzenchor** [comment]
Keep in mind that when a character is not included in the font it is replaced with the first glyph of the font.
That character has the code 9608 in decimal, or 2588 in hexadecimal

**Comment by cra0zy** [comment]
> Keep in mind that when a character is not included in the font it is replaced with the first glyph of the font.
> That character has the code 9608 in decimal, or 2588 in hexadecimal

That's probably it, the first character included is space so it makes sense.

Maybe there should be an error saying that the font does not contain a specified character.

**Comment by cra0zy** [comment]
Yup, the font didn't contain that character... tho the character I was planing on using was 219, they look almost identical...

I'll look into adding a warning for this a bit later.

**Comment by Tzenchor** [comment]
> That's probably it, the first character included is space so it makes sense.

Not exactly, the first glyph in the font is the default glyph, usually a square.

> I'll look into adding a warning for this a bit later.

I have a pull request in progress as #4545 that is touching that part of the process, so I can add that warning, but I don't think I should, as it can be many characters. For example, if using any font from the XNA redistributable font pack, you'll have to show that warning for every character outside the standard ASCII

**Comment by cra0zy** [comment]
> Not exactly, the first glyph in the font is the default glyph, usually a square.

The first character I included was 32(aka. space).

**Comment by Tzenchor** [comment]
I know, but when SharpFont can't find the glyph for the requested character it returns the first glyph in the whole font, the one with index 0.
