### ISSUE TITLE
Missing VS iOS project template

### ISSUE THREAD

**Issue by RecursiveCall** [mono/MonoGame#4562]
The current VS project templates include Windows and Android. There is a noticeable absence of iOS/Mac OS.

**Comment by dellis1972** [comment]
Can anyone help on this one? @DDReaper any changes you have time?

IOS we can do as VS supports Xamarin iOS projects. But it does not support Mac OS. That said the "MonoGame Cross Platform Desktop Project" has you covered on Windows, Linux and Mac :) It is available in the development builds and will be available in 3.5.

**Comment by DDReaper** [comment]
It certainly has been a gap for a while, I believe it was only in the MD project templates.
Crazy thing is, I could have sworn thee was one (looked back when I did the Win10 presentation) but couldn't find it so put it down to senility :D
Will have a look this weekend and see if I can pull one together @dellis1972

**Comment by dellis1972** [comment]
@DDReaper awesome thanks :) I would do it myself but I'm busy this weekend :(

**Comment by DDReaper** [comment]
Yeah, filling in your CV for the merger and crying over the loss of your new MVP :S @dellis1972

**Comment by tomspilman** [comment]
I think this could wait till after 3.5...  is it really that critical?  @dellis1972 @KonajuGames ?

**Comment by DDReaper** [comment]
Especially with the recent announcement of Xamarin entering MS and the fact that Xamarin templates are now already built in to VS2015 it would be prudent.
But I'm not going to waste effort putting this in now if it's not for the 3.5 timeline.  It's needed but I'll let you discuss whether it's suitable for 3.5.

Let me know what you decide.

**Comment by dellis1972** [comment]
@tomspilman personally this has been missing for a while now. If someone can get it done this weekend then I think it should go in to 3.5. 
@KonajuGames ?

**Comment by KonajuGames** [comment]
I can give it a go.

**Comment by DDReaper** [comment]
Nice work @KonajuGames 
I started but then got swept up with the weekend.  Did you also add a MAC template?

**Comment by dellis1972** [comment]
You can't build Mac apps in VS yet. So there is no point.

On 1 March 2016 at 11:02, Simon (Darkside) Jackson <notifications@github.com
