### ISSUE TITLE
Pipeline tool and PNG with transparency (windows)

### ISSUE THREAD

**Issue by InfiniteProductions** [mono/MonoGame#4575]
Adding a PNG file without transparency is ok and all three options are available (copy, add link, skip).
Adding a PNG WITH transparency is not ok and the first option is not available (copy radio button is disabled).
Adding item with link doesn't work at all as Content.Load() raise an exception.

PNG created with Gimp 2.8.16 (last stable binary release) with the exact same options (only "save creation time", "save color values for transparent pixels", compression level 8), saved to a directory outside the solution.
the PNG without transparency have a single colour background, the PNG with it doesn't have any background colour at all.

If option "save color values for transp. pixels" is not used, PNG import have the "copy" option enabled.
But it looks like image doesn't have transparency (transparent background replaced by black background).

Tested on both pipeline version 3.4.0.56 and recent dev version, same behaviour.

**Comment by cra0zy** [comment]
It has nothing to do with transparency, it has to the with the fact that you already have a file with the same name in the folder...

**Comment by InfiniteProductions** [comment]
Weird, I only use pipeline tool to add and delete files, delete is suppose to remove file from content AFAIK.
Thanks for the info cra0zy

**Comment by cra0zy** [comment]
> Weird, I only use pipeline tool to add and delete files, delete is suppose to remove file from content AFAIK.

It's currently just removing from the .mgcb file, and leaving the source file intact. I have a PR that changes that but I doubt it will get merged before 3.5 release.
