### ISSUE TITLE
Window class has no effect

### ISSUE THREAD

**Issue by UDXS** [mono/MonoGame#4576]
Both Window.Is Borderless and Window.Position do not change the window

**Comment by tomspilman** [comment]
@UDXS - What platform were you testing on...  Windows, Mac, or Linux? 

Also if you look at the `MonoGame.Framework` reference in your project is it coming from the `DesktopGL` folder or from `Windows`?

**Comment by UDXS** [comment]
It's on windows.
I think the path is ProgramFiles(x86)/monogame/v3.0/assemblies/windows

**Comment by UDXS** [comment]
I also have this problem with graphics.PerferredBackBufferWidth/Height

**Comment by UDXS** [comment]
And entering full screen (I know it isn't implemented) but even pseudo full screen doesn't work

**Comment by UDXS** [comment]
@tomspilman the full path is C://ProgramFiles(x86)/Monogame/v3.0/Assemblies/Windows/Monogamy.Framework.dll
