### ISSUE TITLE
graphics.ApplyChanges() exiting app in monoMac

### ISSUE THREAD

**Issue by ambs** [mono/MonoGame#4578]
I have a function to load a level, and change the window accordingly:

`````
 void loadLevel(int n) {
    // compute things, height, width, etc

   graphics.PreferredBackBufferHeight = height;
   graphics.PreferredBackBufferWidth  = width;
  graphics.ApplyChanges();
````

first time this is called, is from initialize, and it works pretty well.
But when I call it again (from Update) the app just "exits".

Will try to give more details, if I can.

(not a big issue at the moment, just registering the issue)

**Comment by ambs** [comment]
This doesn't help much (at least, I do not think so), but is the few I could find for now.

``````
Call apply changes
Calling base update
entering Draw
Calling base.Draw
Calling base update
entering Draw
Calling base.Draw
`````
That is, after applying changes on graphics, it ends the call to update, goes for draw, and is able to run yet one more complete cycle (update/draw)

**Comment by LithiumToast** [comment]
hi @ambs, I be willing to look into this tonight

Can I ask what branch you are working with?

**Comment by ambs** [comment]
Hi! I installed from this link, yesterday: 
http://teamcity.monogame.net/repository/download/MonoGame_PackageMacAndLinux/latest.lastSuccessful/MonoGame.pkg?guest=1

Let me know if I can help debugging somehow (well, if I do not need Xamarin Indie, as did not buy it yet!)

**Comment by LithiumToast** [comment]
@ambs It's my understanding that MonoMac does not require any Xamarin license. However I do use Xamarin for iOS and would be willing to get a trial of Xamarin.Mac if it's possible.

**Comment by ambs** [comment]
I mean, to compile Monogame. I think. But I am a newbie on this :)

**Comment by LithiumToast** [comment]
@ambs Yeah, I tried to open MonoGame using Xamarin Studio 6.0 and it complains that MonoMac is not supported. I activated a trial version of Xamarin.Mac so I can debug.

**Comment by LithiumToast** [comment]
well, I found an issue just trying to run `MonoGame.Tests.MacOS`

<img width="1440" alt="screen shot 2016-02-29 at 8 35 11 pm" src="https://cloud.githubusercontent.com/assets/519592/13417818/1a0f2c74-df24-11e5-89a7-db1f42aeeaa9.png">

I tried commenting out that line and the tests run. Here are my results.

[test_results.html.zip](https://github.com/mono/MonoGame/files/152159/test_results.html.zip)

**Comment by LithiumToast** [comment]
removed `XamMac.dll` and replaced it with `MonoMac.dll` for all projects: `NsAutoreleasePool` doesn't complain anymore

I am getting the same problem described in though #3581

**Comment by LithiumToast** [comment]
see #4286 for fix

**Comment by ambs** [comment]
Will close this, and vote on #4286.
