### ISSUE TITLE
ffmpeg quality value not working on Mac

### ISSUE THREAD

**Issue by ambs** [mono/MonoGame#4588]
Hi

I can't test this in other arch at the moment. But using full quality on Pipeline doesn't work to create a ogg file (libvorbis).

As far as I could tell, this is the default call to ffmpeg on Mac:
``````
ffmpeg -y -i input.mp3 -vn -c:a libvorbis -b:a 192000 -f:a ogg -strict experimental output.ogg
``````
I kept trying to find a suitable bitrate, and the higher i could find was 180k
``````
ffmpeg -y -i input.mp3 -vn -c:a libvorbis -b:a 180000 -f:a ogg -strict experimental output.ogg
``````

So, probably better to check if this happens with othr versions, and probably adapt `QualityToBitRate` function to return different values accordingly with encoder. Even not being able to compile, I can try to create a patch.

Using the .xnb file generated when creating a Mac m4a, and the .ogg file created above, I still get
````
Failed to get buffer bits: Invalid Value, format=Stereo16, size=0, sampleRate=22050
````

Let me know how/if I can help debugging this.
Best,
Alberto

**Comment by ambs** [comment]
Seems this was related to the source sound file. Weirdly. Closing ticket. Will reopen if i understand what kind of files is giving trouble.

**Comment by prime31** [comment]
@ambs did you ever figure out what was causing this? I am seeing the same thing with wav and mp3 files and the SongProcessor. The XNB files created are always 130 bytes so they definitely dont have the audio data. 

The SoundEffectProcessor does work but only on Best quality. Any other quality causes a divide by 0 error when processing.

**Comment by KonajuGames** [comment]
The SongProcessor always produces two files: a small XNB file and a
WMA/M4A/OGG (depending on platform). The XNB is a link to the compressed
audio file, plus contains other information such as song length.

**Comment by prime31** [comment]
That makes sense. In this case the issue is then just as reported. When you call MediaPlayer.Play with the song you get the error:

```Failed to get buffer bits: Invalid Value, format=Stereo16, size=0, sampleRate=22050```

I tried loading up raw wav files (not processed via the Pipeline tool) and they did work.

**Comment by Tzenchor** [comment]
I run into the same problem as @ambs in #4591. The problem is caused when trying to increase the bitrate of a variable bitrate file. In my case the origin file had an average of 120 kbps and when trying to convert it to best quality ogg (192kbps), ffmpeg was failing, setting the quality to medium (128kbps) made it work

**Comment by KonajuGames** [comment]
It's good to know a set of circumstances that leads to the issue. Now I've got something to go on.

**Comment by prime31** [comment]
I just tried with lower bitrate files and both low and medium quality and I end up with this error:

```
/Users/desaro/Documents/dev/MonoGame/Nez/MacTester/Content/AudioScene/POL-chakra-short.wav: error: Processor 'SoundEffectProcessor' had unexpected failure!
System.DivideByZeroException: Attempted to divide by zero.
  at Microsoft.Xna.Framework.Content.Pipeline.Audio.AudioContent.ConvertFormat (ConversionFormat formatType, ConversionQuality quality, System.String saveToFile) <0x2fed128 + 0x00c87> in <filename unknown>:0 
  at Microsoft.Xna.Framework.Content.Pipeline.Processors.SoundEffectProcessor.Process (Microsoft.Xna.Framework.Content.Pipeline.Audio.AudioContent input, Microsoft.Xna.Framework.Content.Pipeline.ContentProcessorContext context) <0x2fecf98 + 0x00083> in <filename unknown>:0 
  at Microsoft.Xna.Framework.Content.Pipeline.ContentProcessor`2[TInput,TOutput].Microsoft.Xna.Framework.Content.Pipeline.IContentProcessor.Process (System.Object input, Microsoft.Xna.Framework.Content.Pipeline.ContentProcessorContext context) <0x2fece78 + 0x00087> in <filename unknown>:0 
  at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent (MonoGame.Framework.Content.Pipeline.Builder.PipelineBuildEvent pipelineEvent) <0x2feb790 + 0x004df> in <filename unknown>:0 

Build 0 succeeded, 1 failed.
```

@KonajuGames if you need some example files that fail let me know. I have plenty of them ;)

**Comment by KonajuGames** [comment]
@prime31, please do make them available.

**Comment by prime31** [comment]
@KonajuGames here is one wav and one mp3 that illustrate the issue
[Archive.zip](https://github.com/mono/MonoGame/files/224290/Archive.zip)

**Comment by Tzenchor** [comment]
Tried the mp3 against the bundled ffmpeg to generate an ogg file on Windows. It worked in high (192kbps) and medium (128kbps).
When converting the wav file to osx format (ima_adcpcm) there might be a problem, varying the quality gives me files with the same size but different durations, also the original bit depth was 8, but the converted ones are 4 bits.

**Comment by prime31** [comment]
I haven't tried on Windows. I can only confirm the issue on Mac.

**Comment by KonajuGames** [comment]
ADPCM is a 4-bit format, so that is expected.
