### ISSUE TITLE
Issues converting a WindowsDX project to DesktopGL

### ISSUE THREAD

**Issue by Tzenchor** [mono/MonoGame#4591]
I am trying to convert a project I did in XNA, that I have converted to WindowsDX succesfully, but now when trying to use DesktopGL, while it compiles without changing anything in the code, i'm having the following problems (using latest development installer):

- First try to run the game showed that the `OpenAL` installer is included with the installer but not run.
- If content is set for Windows platform or DesktopGL I get a `InvalidDataException` from NVorbis.dll with message "Could not determine container type!"
- If content is set for DesktopGL it fails to compile a mp3 file with the "lame" codec (it's a different file from the one of the previous post), the other mp3 files work

This is trace when converting the mp3 file:
System.InvalidOperationException: ffmpeg exited with non-zero exit code: 

ffmpeg version N-63930-g1c5aa64 Copyright (c) 2000-2014 the FFmpeg developers
  built on Jun 12 2014 22:22:05 with gcc 4.8.3 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-decklink --enable-zlib
  libavutil      52. 89.100 / 52. 89.100
  libavcodec     55. 66.100 / 55. 66.100
  libavformat    55. 43.100 / 55. 43.100
  libavdevice    55. 13.101 / 55. 13.101
  libavfilter     4.  8.100 /  4.  8.100
  libswscale      2.  6.100 /  2.  6.100
  libswresample   0. 19.100 /  0. 19.100
  libpostproc    52.  3.100 / 52.  3.100
Input #0, mp3, from 'C:\Users\Arneeklawn\AppData\Local\Temp\tmp344.tmp':
  Metadata:
    TYER            : 1998-11-17
    Engineer        : xx
    encoded_by      : dBpoweramp Release 13.3
    artist          : Mateo Pascual
    album           : Commandos: Beyond the Call of Duty
  Duration: 00:02:42.46, start: 0.050113, bitrate: 134 kb/s
    Stream #0:0: Audio: mp3, 22050 Hz, stereo, s16p, 133 kb/s
    Metadata:
      encoder         : LAME3.98r
[libvorbis @ 0000000004c5a2c0] encoder setup failed
Output #0, ogg, to 'C:\Users\Arneeklawn\AppData\Local\Temp\tmp345.tmp':
  Metadata:
    TYER            : 1998-11-17
    Engineer        : xx
    encoded_by      : dBpoweramp Release 13.3
    artist          : Mateo Pascual
    album           : Commandos: Beyond the Call of Duty
    Stream #0:0: Audio: vorbis, 0 channels, 128 kb/s
    Metadata:
      encoder         : Lavc55.66.100 libvorbis
Stream mapping:
  Stream #0:0 -> #0:0 (mp3 (native) -> vorbis (libvorbis))
Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height

   en Microsoft.Xna.Framework.Content.Pipeline.Audio.AudioContent.ConvertFormat(ConversionFormat formatType, ConversionQuality quality, String saveToFile)
   en Microsoft.Xna.Framework.Content.Pipeline.Processors.SongProcessor.Process(AudioContent input, ContentProcessorContext context)
   en Microsoft.Xna.Framework.Content.Pipeline.ContentProcessor`2.Microsoft.Xna.Framework.Content.Pipeline.IContentProcessor.Process(Object input, ContentProcessorContext context)
   en MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent(PipelineBuildEvent pipelineEvent)

**Comment by Tzenchor** [comment]
An update, the second problem (the NVorbis exception) is caused because when running the program from Visual Studio the pipeline generates wma files for songs, while when running the pipeline manually generates the ogg ones.

After reading the csproj file it seems that Visual Studio gets the content platform from it instead of reading the value from the MGCB file. Changing the `MonoGamePlatfrom` value from Windows to DesktopGL solves the problem.

With the previous change, and replacing the failing file of the content, I can now run the game from Visual Studio, but the result is completely wrong compared to the WindowsDX version:

- Background does not fill the window
- Mouse coordinates are relative to the screen, and not the window like in WindowsDX

**Comment by Tzenchor** [comment]
I have diagnosed why it is behaving like it is.
I'm setting the `GraphicsDeviceManager.PreferredBackBufferWidth` and `GraphicsDeviceManager.PreferredBackBufferHeight` to 1280x720 in the `Game` constructor and then in `Initialize` I create each game window, that relays in the `GameWindow` to set their size. In WindowsDX the `GameWindow` has the correct size at this point, but in DesktopGL it is still 640x480 and is not extended at least until getting to `Game.Update`

**Comment by mrhelmut** [comment]
The OpenAL issue is known (#4329).
It is safer to add the dll to your project and ship it with your game than relying on the installer.

Regarding the windowing issues, DesktopGL has currently the drawback to sometime initialize window size after ```Initialize``` and ```LoadContent```. DesktopGL windowing is currently being rewritten, and this should fix that once and for good (no ETA though).

**Comment by Tzenchor** [comment]
> Regarding the windowing issues, DesktopGL has currently the drawback to sometime initialize window size after Initialize and LoadContent. DesktopGL windowing is currently being rewritten, and this should fix that once and for good (no ETA though).

Good to know, thank you.
I was just converting the project to test how good was my interface library, and apart from this seems to be working.

**Comment by Tzenchor** [comment]
Today I have tried to diagnose why only that mp3 file was failing to be converted to Vorbis.
In the project I have 5 songs in mp3 with the following qualities:

- 1 problematic file with variable bitrate with an average bitrate of 126 bps
- 2 other files with variable bitrate with an average of 190 bps or more
- 2 other files with a constant bitrate of 192 bps

All files are set to high quality.

If I lower the quality to medium it works, but converting a file with constant bitrate with 128bps to high quality also works. (Note that the problem is only when converting to Vorbis, to other formats there is no problem).

To fix this i don't know if the best option is overriding the bitrate (with an accompanying message) or maybe look at updating ffmpeg. I have another converter installed that can handle the file without problems, so it is possible that ffmpeg updating ffmpeg may solve the problem. Tomorrow i'll try the latest stable version to see if it works or not

**Comment by tomspilman** [comment]
> so it is possible that updating ffmpeg may solve the problem

That should be easy to test.  I don't know when we last updated it, but it surely isn't the latest version.

We probably want to get some conversions of mp3s with different bitrates into the unit tests regardless.

**Comment by KonajuGames** [comment]
Is it possible to get those problematic MP3 files so we can have a look as well?

**Comment by Tzenchor** [comment]
> Is it possible to get those problematic MP3 files so we can have a look as well?

The original one is copyrighted, so I have taken another one that the creator permits its use and converted it with the same settings as the original one (and this one also fails to work).

[song.zip](https://github.com/mono/MonoGame/files/218559/song.zip)

The song comes from here: [http://dig.ccmixter.org/files/mindmapthat/52174](http://dig.ccmixter.org/files/mindmapthat/52174)

**Comment by Tzenchor** [comment]
Tested with current ffmpeg version and it keeps failing. After checking the converted file from the other tool the bitrate is still 120 kbps (in previous posts I said bps, but I meant kbps) instead of the requested 192 kbps, that leads me to think that libvorbis can't oversample files
