### ISSUE TITLE
Window.Title has no effect in a UWP project

### ISSUE THREAD

**Issue by rohdester** [mono/MonoGame#4598]
Setting of Window.Title in e.g. the Initialize method has no effect in a Universal Windows project.
It does work though in a Windows OpenGL project, so I reckon it has to do with the UWP SDK.

So steps to reproduce:

1. Open Visual Studio
2. Create new project choosing "MonoGame Windows 10 Universal Project"
3. In Game1.Initialize set Window.Title to "My Title";
4. Run the app, and we expect the window title to be "My Title" while it is in fact still the project title.

**Comment by tomspilman** [comment]
I think at the time we ported to Win10 we didn't know the solution or it was available...

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/WindowsUniversal/UAPGameWindow.cs#L242

... anyone know the right UWP call to set the window title and want to submit a PR for it?

**Comment by rohdester** [comment]
I can do a PR for it.

**Comment by tomspilman** [comment]
Fantastic... thanks @rohdester !
