### ISSUE TITLE
DX version keeps the game running after Exit()

### ISSUE THREAD

**Issue by fjeandinot** [mono/MonoGame#4604]
The stable 3.4 version keeps the game running in background after performing Exit() or by closing the windows. If you add a breakpoint on the Exit() and skip it, the game will stop after a while.
It occurs even in a new empty solution.

I have tried the daily build but this version seems broken as the windows.xna.framework seems unreachable...

Feel free to ask me more details.
Thanks ans regards.

**Comment by KonajuGames** [comment]
I tried this with the latest version and the process is terminated immediately on close of the window or calling Exit().  Closing as fixed in the upcoming 3.5 release.
