### ISSUE TITLE
Monogame Has all Visual Studio Templates grayed out..

### ISSUE THREAD

**Issue by Myhand91** [mono/MonoGame#4612]
I have windows 10 and visual studio 2015 community. I tried installing monogame 3.4 and this what showed up
![screenshot 2016-03-07 06 48 39](https://cloud.githubusercontent.com/assets/17702943/13569948/da57424e-e430-11e5-93aa-09439de2bd54.png)
 can and one help me?

**Comment by Tzenchor** [comment]
I also have Windows 10 and Visual 2015 Community and when I installed this I had no problem.
The only things I can think that may interfere with the installer are:
Have you installed C# part of Visual Studio?
Have you installed Visual Studio for another user?
Have you run Visual Studio at least once?

Also you can try with the [latest installer from develop](http://teamcity.monogame.net/repository/download/MonoGame_PackagingWindows/latest.lastSuccessful/MonoGameSetup.exe?guest=1). If this also fails, try reinstalling Visual Studio.

**Comment by KonajuGames** [comment]
Where are your VS2015 project templates stored on your PC?  Are they in `My Documents/Visual Studio 2015/Templates/ProjectTemplates`?  If not, where else are they?  We've seen several times how VS2015 will sometimes put them elsewhere, and I'm trying to work out what leads to this.

**Comment by Myhand91** [comment]
Yes, I have the C# part. This is my personal computer I'm the only user. I been using VS for a few weeks I started a Class online for Monogame in Visual Studio 2015. I've tried uninstalling it several time, also.

**Comment by KonajuGames** [comment]
The installer looks for `My Documents/Visual Studio 2015/Templates/ProjectTemplates\Visual C#` which is why it is important to know where that folder is on your machine.

**Comment by Myhand91** [comment]
the installer won't let me install any templates. My problem is trying to figure out why the install doesn't detect my Visual Studio Community 2015.

**Comment by KonajuGames** [comment]
That's why I'm asking where that folder is on your machine.

**Comment by Myhand91** [comment]
Oh I apologize, I don't have that directory but nothing is in the folder.

**Comment by KonajuGames** [comment]
It is somewhere on your machine.  Is it in One Drive, or on another hard drive?

**Comment by Myhand91** [comment]
I have a ssd as my boot drive and a hdd as my storage. I moved all my Libraries (downloads, documents, pictures, etc.) to the hdd. In short, it on my storage drive but my Visual Studio 2015 is on my boot drive

**Comment by KonajuGames** [comment]
That seems to be it.  The moving of the Documents folder, but asking the Documents folder that the NSIS installer finds is still in the original location.

**Comment by Myhand91** [comment]
I've always had my Storage set up this way and its never gave me any problems before

**Comment by Tzenchor** [comment]
I have changed the `my documents` location to another drive and the installer found it.
If it helps, the registry entry for where to find the templates for Visual 2015 is: `HKEY_CURRENT_USER\SOFTWARE\Microsoft\VisualStudio\14.0` `UserProjectTemplatesLocation`.

**Comment by KonajuGames** [comment]
Maybe that's what we need to do.  I don't trust the $DOCUMENTS token in the NSIS script, especially when admin privileges are requested.  Looking in the NSIS source, it can use either CSIDL_PERSONAL or CSIDL_COMMON_DOCUMENTS (the CSIDL approach was deprecated back in Windows Vista in favour of the KnownFolder approach).  I think what is happening here is that CSIDL_COMMON_DOCUMENTS might be used when run at admin level, and this is what is returning different values for some users depending on how they have set things up.

**Comment by KonajuGames** [comment]
@Myhand91 If you would like to give this installer a try, it should fix the issue with the missing templates.
http://teamcity.monogame.net/repository/download/MonoGame_PackagingWindows/5275:id/MonoGameSetup.exe
Let me know if it fixes the issue and we'll merge it into the main branch.

**Comment by KonajuGames** [comment]
No, hang on.  There's still an issue.

**Comment by Tzenchor** [comment]
Both versions worked for me, but I did not have the problem

**Comment by KonajuGames** [comment]
That one I linked showed the VS options available, but the templates never ended up in the folder.

**Comment by KonajuGames** [comment]
@Tzenchor, there have been several people report this issue, so it's common enough that we have to do something about it.

**Comment by Myhand91** [comment]
OK so deleting the documents folder in my SSD boot drive I got it to allow me to check the the Visual Studio 2015. I ran it and the monogame fold is now in a new Documents fold in the SSD Boot drive. I just moved them to the right documents fold and it worked. Thanks guy for all the help and sorry it took so long for replies. It's morning so i had class. Thanks for all the help again.

**Comment by KonajuGames** [comment]
Ok, I got it now.  The installer now uses the registry key setup by Visual Studio.  It no longer assumes the templates are in the user's Documents folder, wherever that may be.

Most of the time was just trying to get NSIS installer script working.  Give this installer a try if you can.
http://teamcity.monogame.net/repository/download/MonoGame_PackagingWindows/5501:id/MonoGameSetup.exe

**Comment by KonajuGames** [comment]
Deleted the previous PR because I tried to use git rebase to squash commits, and that ended badly.  Created a new PR.

**Comment by Tzenchor** [comment]
I have just tried it, now it only finds Visual 2010 and Visual 2015 (which is good, because previously it would detect 2013 that is not installed anymore).
Comparing the templates with what I had before:
On Visual 2010 now I have access to the IOS template that was not available before (not sure if it works or not)
On Visual 2015, I have lost the Linux template, but that might have been a residue of an older Monogame installation

**Comment by KonajuGames** [comment]
> On Visual 2010 now I have access to the IOS template that was not available before (not sure if it works or not)

Yes, it's new and works if you have Xamarin.iOS.

> On Visual 2015, I have lost the Linux template, but that might have been a residue of an older Monogame installation

I don't recall there ever being a Linux template for Visual Studio.  There's the DesktopGL template which will work across Windows, Mac and Linux.

**Comment by KonajuGames** [comment]
> Yes, it's new and works if you have Xamarin.iOS.

Except that Xamarin don't support VS2010 any more, so it should probably go in VS2012 and higher only.  Same with Android.

**Comment by KonajuGames** [comment]
And thanks for testing it so quickly.

**Comment by Tzenchor** [comment]
> I don't recall there ever being a Linux template for Visual Studio. There's the DesktopGL template which will work across Windows, Mac and Linux.

I had both, so probably that one came from Monogame 3.4

**Comment by TickyAnarch** [comment]
A lot of people may still have this issue I fixed it by simply creating a folder named VIsual C# in Documents\Visual Studio 2017\Templates\ProjectTemplates  

In ProjectTemplates directory I noticed the folder didn't exist and the folder is what the installer is looking for and wants to install the templates to that folder. It is an easy fix instead of messing with registry entries or anything else someone tells you to do to fix this. This worked for me I hope it helps anyone else confused

**Comment by cs15kkn** [comment]
What @TickyAnarch wrote, worked for me.

**Comment by alban316** [comment]
@TickyAnarch trick worked for me. But, obviously installer is looking for something it shouldn't. On a clean install of both Windows 10 and VS 2017, this folder does _not_ exist unless manually created.

**Comment by Agrair** [comment]
@TickyAnarch didn't work for me, any other tips?

**Comment by Timmeey86** [comment]
If @TickAnarch 's solution doesn't work for you and you are on a multi-user machine and are not using the Admin account for daily work:

1.  Create the folder structure for the Admin account: in C:\Users\<AdminAccountName>\Documents\Visual Studio 2017\Templates\Project Templates\Visual C#
2. Install MonoGame
3. Copy the Visual C# folder from the admin account over to your own user at the same path
4. Start Visual Studio, create a new project and you should see the solutions.

**Comment by msdogra** [comment]
This worked for me https://github.com/MonoGame/MonoGame/issues/4612#issuecomment-480354949 
After that when I ran VS in administrator mode, I saw the templates in the VS. Later I copied the templates from the AdminAccount …. ProjectTemplates\Visual C# to non admin folder (...ProjectTemplates\Visual C#) and then I started seeing the templates in the standard user VS too.

**Comment by Sehyho** [comment]
What @TickyAnarch wrote, worked for me too. ;D
