### ISSUE TITLE
Sound effects are corrupt in Windows

### ISSUE THREAD

**Issue by SteveDunn** [mono/MonoGame#4626]
When playing sound effects on Windows (10), the sound effect plays but it plays for too long.

**Comment by SteveDunn** [comment]
A partial fixed is mentioned in this thread: http://community.monogame.net/t/created-soundeffect-plays-corruption-at-end/1644/11

But that fix didn't cover all areas where sound effects could be created.

**Comment by tomspilman** [comment]
What does too long mean?  What happens after the sound plays?  Can you share the sound effect file that causes the problem?

**Comment by SteveDunn** [comment]
By 'too long', I mean it, say you have a sound effect that should last for .3 seconds, it'll play for .6 seconds.  The last .3 seconds are random noise depending on what bytes are in memory after the sound buffer.  I've fixed this, I'm just creating a PR

**Comment by SteveDunn** [comment]
https://github.com/mono/MonoGame/pull/4627
