### ISSUE TITLE
[Xamarin addin] Error on building new project

### ISSUE THREAD

**Issue by Dawnkeeper** [mono/MonoGame#4628]
I used the Monogame Addin for Xamarin to create a new project (Cross-Platform Desktop).
While building the unchanged project I get the error : 
    ` Error MSB4066: The attribute "Conditon" in element <Import> is unrecognized.`    
for the line    
`<Import Project="$(MSBuildExtensionsPath)\MonoGame\v3.0\MonoGame.Common.props"  Conditon="Exists('$(MSBuildExtensionsPath)\MonoGame\v3.0\MonoGame.Common.props')"/>`     
in the csproject file.

**Comment by tomspilman** [comment]
@Dawnkeeper - Is this with the 3.4 release of MonoGame or are you using a development build of 3.5?

**Comment by cra0zy** [comment]
This was fixed in #4579

It was missing an 'i' > "Condition"

**Comment by Dawnkeeper** [comment]
@tomspilman The addin says its version 3.5.0.1433 but the hint from @cra0zy solved the problem.
I totally missed that missing I =)

**Comment by tomspilman** [comment]
@Dawnkeeper - Yeah that fix was introduced in 3.5.0.1542... so you were 100 versions behind that fix.  Still thanks for letting us know.
