### ISSUE TITLE
Broken templates in Xamarin Studio. SDL.dll not found

### ISSUE THREAD

**Issue by iFaxity** [mono/MonoGame#4629]
Hello. I've used XNA 4.0 in the past and now i have gotten some interest in creating a little game. However i've got a MacBook that i program on and would like to use the machine to create a Monogame project. I've installed the latest Mono MDK, Xamarin Studio and Monogame.

However no matter which one i choose (OpenGL or Xamarin.Mac project), **it won't run**.

I looked up on the internet for a solution to this. But none of them work. i've tried reinstalling everything multiple times. But the same error happens. The error is something like 

> SDL.dll not found

I can't give full stack trace right now though.
**How do i solve these broken templates?**

**Comment by dellis1972** [comment]
Hi 

Which version of MonoGame are you using? 
It sounds like the latest stable release since we removed the requirement for SDL in the develop branch afaik.

You might want to try the lasted development release, and create yourself a new "MonoGame Cross Plaform Desktop Project"

**Comment by iFaxity** [comment]
Yes i'm using the recommended 3.4 build. I've not yet tried to downgrade. I'm sorty but can you guide me to how i dowload the latest ones? Is it on the NuGet?

**Comment by dellis1972** [comment]
goto http://www.monogame.net/downloads/
and grab  the latest "Development Build"

**Comment by iFaxity** [comment]
I tried to build from the latest from the develop branch. But i couldn't get the templates working. Instead i tried one more time in Xamarin with the 3.4 installer. The OpenGL template and Xamarin.Mac didn't work. Both had different dll exception errors.

Then i tried MonoMac and it worked (for now). So i guess MonoMac will do until MonoGame 3.5 or 3.6 comes out.

**Comment by Tzenchor** [comment]
> Then i tried MonoMac and it worked (for now). So i guess MonoMac will do until MonoGame 3.5 or 3.6 comes out.

Monogame 3.5 is out. Also be sure you are not using an outdated template (in Windows the old templates are not removed when installing a new version, but I'm not sure if this applies also to Mac)

**Comment by iFaxity** [comment]
Oh right i 3.5 is out but not on the website i mean. I updated to 3.5 from nuget.

I'm not so good with Xamarin on Mac yet so installing templates did not work.

**Comment by dellis1972** [comment]
The Latest templates are bundled with the Mac Installer. The new Xamarin
Studio Templates rely on your installing via the installer as they now use
the local assemblies rather than Nuget.

http://www.monogame.net/downloads/

You are probably on an old version of the Addin. check your version with
the latest it should be 3.5.0.1678

**Comment by iFaxity** [comment]
Oh the new installer came out today. Nice. I will try it when i get back home today.
I thank you both until then.

**Comment by iFaxity** [comment]
Yeah the new 3.5 installer works perfectly. The installer does also remove the old templates in Xamarin Studio.
Cross Platform also works. I just tried to debug it in Xamarin Studio.

Thanks for the help. I'll also close the issue now as it's solved in the new version. I've got to say that MonoGame has an amazing community.
