### ISSUE TITLE
Color.LerpPrecise - what does the description tell?

### ISSUE THREAD

**Issue by energyuser** [mono/MonoGame#4634]
Hello, I've been playing around with colors and I got to `Color.LerpPrecise`. Now the description states the following:

> Performs linear interpolation of Microsoft.Xna.Framework.Color using Microsoft.Xna.Framework.MathHelper.LerpPrecise(System.Single,System.Single,System.Single) on MathHelper. Less efficient but more precise compared to Microsoft.Xna.Framework.Color.Lerp(Microsoft.Xna.Framework.Color,Microsoft.Xna.Framework.Color,System.Single). See remarks section of Microsoft.Xna.Framework.MathHelper.LerpPrecise(System.Single,System.Single,System.Single) on MathHelper for more info.

What did you guys mean "less efficient"? I know `LerpPrecise` ensures the color gets properly calculated but how is `Lerp` more efficient than it? I tried to search the internet for this but couldn't find much...

**Comment by tomspilman** [comment]
It was added in https://github.com/mono/MonoGame/pull/4294.

The remarks on `MathHelper.LerpPrecise()` explain it better...

http://www.monogame.net/documentation/?page=M_Microsoft_Xna_Framework_MathHelper_LerpPrecise

Basically XNA's normal lerp methods are optimized for performance and loose precision if the min and max values are really far apart.

That said...  I suspect it was a mistake to add `Color.LerpPrecise()` as by definition the color values cannot be far apart and I doubt the precise version returns anything different from the original lerp method.

@KonajuGames ?  @hede ?

**Comment by energyuser** [comment]
But it shouldn't be a problem when working with `1.0f` and `0.0f` which covers majority of the cases... I'll test both `Lerp` and `LerpPrecise` and see if they give any different colors.

**Comment by hede** [comment]
Yes, it shouldn't be a problem when the range is just [0,1], and there is a Clamp() in there making sure the range is indeed [0,1].

I guess adding Color.LerpPrecise was unnecessary.
Shall I mark it as obsolete so it can be removed in a future version?

Probably it can be removed right away, but since it's a public method, it might be better practice to keep it as obsoleted for a while?

**Comment by KonajuGames** [comment]
It would need to be marked as deprecated for at least one official release
before being removed in the next release.

**Comment by BrianBergh** [comment]
This is not working , the Lerp is never getting even close to the value (it stops) unless i set the amount to something crazy! Which ruins the whole point of using this. So, removing LerpPrecise was a mistake imo! - I have implemented my own and im good for now, but, just telling you.

Try this code:
public void Update(GameTime gameTime)
    {
      float gt = (float)gameTime.ElapsedGameTime.TotalSeconds;
      curColor = Color.Lerp(curColor, lColor, 10 * gt);
      var c1 = (curColor.R + curColor.G + curColor.B);
      var c2 = (lColor.R + lColor.G + lColor.B);
      var diff = Math.Abs(c1 - c2);
      System.Diagnostics.Debug.Print(diff.ToString());
      if (diff  <= 5)
      {
When lerp is from green to white for instance, we never get the value diff below 5, actually not even close. If we raise the speed (amount), we need to raise it until the color are so fast it flickers. This is useless :(
          // switch to next color...
      }
