### ISSUE TITLE
DesktopGL not working anymore on OS X

### ISSUE THREAD

**Issue by mrhelmut** [mono/MonoGame#4637]
There seems to be a problem with a recent commit and Mono on OS X... it crashes at launch.

I don't know which commit did that, but Mono won't work and simply exit with the following error:

```
ERROR:    2948: DoMakeDisconnection failed with error -10860
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

```

I've already excluded recent OpenTK changes from the problem.

cc @cra0zy @dellis1972

**Comment by cra0zy** [comment]
Want to hear some bad news? no? https://github.com/mono/MonoGame/releases

**Comment by dellis1972** [comment]
@mrhelmut I just installed the latest.. created a new Cross Platform Desktop project and ran it up fine in XS. This is on 3.5.0.1678

Xamarin Studio
Version 5.10.2 (build 56)
Installation UUID: 73482b7c-d581-42db-ac92-785f3f766e6b
Runtime:
	Mono 4.3.2 (mono-4.3.2-branch/ba2e5e4)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 403020467

**Comment by dellis1972** [comment]
@mrhelmut the only change That was added was to look for Content in the ../Resources directory if it existed on Mac. This is to handle .app bundles created using Xamarin.Mac where the Content is placed in the Resouces directory (which is where they should be in an .app bundle anyway). 

Wonder if that is causing you a problem?

**Comment by mrhelmut** [comment]
I'm using MonoKickstart to create the .app bundle. I'm currently rolling back commits to look for the problem.

**Comment by KonajuGames** [comment]
Mac projects were tested over the last few days, but we don't test with
MonoKickstart.

**Comment by dellis1972** [comment]
@mrhelmut its more that likely you have a Resources directory in your bundle.. and now the content manager is looking for content in it.. Move your Content directory to Resources. e.g change
```
Foo.app/Contents/MacOS/Foo.exe
                /MacOS/Content/*.xnb
```

to 
```
Foo.app/Contents/MacOS/Foo.exe
                /Resources/Content/*.xnb
```

**Comment by dellis1972** [comment]
This came about because we switched Xamarin.Mac and XamMac over to using DekstopGL and as part of the build process they automatically put Content in Resources.

**Comment by dellis1972** [comment]
https://github.com/mono/MonoGame/commit/0f4794d92040e9fe1d902fe0526c3dda491ae1aa#diff-9147095805358590687014b740c1f53cR32

**Comment by mrhelmut** [comment]
It's exactly that, I just found that ```TitleContainer.OpenStream()``` is failing.

Thanks a ton @dellis1972 ! Closing!

**Comment by dellis1972** [comment]
@mrhelmut  np.. BTW DesktopGL works beautifully with Xamarin.Mac :) Checkout the new templates if you get a chance.

**Comment by tomspilman** [comment]
So there is no crisis here right?  3.5 is ok?

**Comment by cra0zy** [comment]
No crisis here, but, #4638 is needed for gamepad up axis to function correctly, so if you can refresh the 3.5 package from current develop.

**Comment by mrhelmut** [comment]
All good! Sorry for the false alarm. :) There were also a couple outdated dependencies in MonoGame/MonoKickstart, but that's not a concern.
