### ISSUE TITLE
Suggestion: using OpenAL Soft on OS X

### ISSUE THREAD

**Issue by mrhelmut** [mono/MonoGame#4639]
Following a couple tweets with Ethan (https://twitter.com/mrhelmut/status/710056044500807681), it may be interesting to update ```OpenTK.dll.config``` (and the future MonoGame.Framework.dll.config once OpenTK is replaced) to look for OpenAL Soft dylib instead of the OS X system library (and then push the dependencies to MonoGame/MonoKickstart, and make sure that it works on XamMac).

This would help maintaining the OpenAL implementation across the DesktopGL platforms in the future.

I've already seen the Apple implementation having differences (e.g. different return values than oal soft) and some 8-22khz sounds don't render the same than on other platforms.

**Comment by tomspilman** [comment]
I think this was the plan for some mobile platforms... don't see why we wouldn't do the same with desktops too.  @KonajuGames ?

**Comment by KonajuGames** [comment]
Creative stopped development of their OpenAL drivers for Windows a long time ago.  openal-soft is a drop-in replacement and from what I've heard, it works just fine and does not need a separate install.  We could remove oalinst.exe.

**Comment by mrhelmut** [comment]
I'm referencing #4329 as well.

**Comment by mrhelmut** [comment]
Fixed in #4874
