### ISSUE TITLE
PlatformSetPan on XAudio causes serious degradation of sound quality.

### ISSUE THREAD

**Issue by akaza-akari** [mono/MonoGame#4648]
On a stereo setup, `SoundEffectInstance.PlatformSetPan` is sending a bad routing matrix to XAudio:

```csharp
// https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Audio/SoundEffectInstance.XAudio.cs#L147
// Default to full volume for all channels/destinations   
for (var i = 0; i < _panMatrix.Length; i++)
    _panMatrix[i] = 1.0f;
```

```csharp
// https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Audio/SoundEffectInstance.XAudio.cs#L183
case Speakers.Stereo:
case Speakers.TwoPointOne:
case Speakers.Surround:
    _panMatrix[0] = lVal;
    _panMatrix[1] = rVal;
    break;
```

Apparently, on a stereo setup the function would have produced `[lVal, rVal, 1.0f, 1.0f]`, which according to [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/microsoft.directx_sdk.ixaudio2voice.ixaudio2voice.setoutputmatrix(v=vs.85).aspx) means the following:

* Send `lVal * left source + rVal * right source` to left output.
* Send `1.0f * left source + 1.0f * right source` to right output.

... which causes clipping and distortion, and failure of panning. Other speaker setups are likely in a similar situation, and should be inspected as well.

**Comment by akaza-akari** [comment]
On closer inspection, from the same function:

```csharp
// https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Audio/SoundEffectInstance.XAudio.cs#L144
if (_panMatrix == null || _panMatrix.Length < dstChannelCount)
    _panMatrix = new float[Math.Max(dstChannelCount, 8)];
```

This is also troublesome. The matrix should have the size `srcChannelCount * dstChannelCount`, not `dstChannelCount` or some arbitrary constant like `8`. I have zero idea where the latter could have came from, and imagine that it will cause problems in environments with more channels.

Handling all the possible combinations of surround source / destination would be quite a mess, and I don't have the means to test them. I might be able to make a PR for this if we could just map the front channels and forget about the rest though.

**Comment by akaza-akari** [comment]
Nevermind. At least my stuff is working.

**Comment by KonajuGames** [comment]
Is there a possible here that needs to be fixed? If so, why close it?

**Comment by akaza-akari** [comment]
No. There is only a non-problem.
