### ISSUE TITLE
Dropping .deb linux installer

### ISSUE THREAD

**Issue by cra0zy** [mono/MonoGame#4652]
Reasons to drop:
 - It's Ubuntu only
 - Ubuntu Software Center will say "Package of bad quality", some evil stuff would need to be done on the Mac build box to avoid this
 - I see people not keeping mono repo enable, and then asking why they can't install the package
 - Would be able to setup an ability to keep multiple MonoGame versions installed and a way to switch between them

We do have .run installer, which works on all Linux distros, including Ubuntu.

CC. @dellis1972 @KonajuGames

**Comment by KonajuGames** [comment]
I'm not familiar with Linux installers, but all of those sound like good reasons to drop the .deb installer.

**Comment by tomspilman** [comment]
I'm good with this I guess...  if it doesn't work then why have it.

@cra0zy - So should I unreferenced the .deb installer from the 3.5 release?  Just have people use the .run installer?

**Comment by cra0zy** [comment]
> @cra0zy - So should I unreferenced the .deb installer from the 3.5 release? Just have people use the .run installer?

Do it, in the meantime I'll submit a PR removing .deb installer from the repo.

**Comment by cra0zy** [comment]
Also remove it from "Downloads" > "Development Builds" section as well.

**Comment by tomspilman** [comment]
Done!

**Comment by cra0zy** [comment]
> Done!

"MonoGame for Linux" would make more sense then "MonoGame for all Linux distros" :P

**Comment by tomspilman** [comment]
Fixed!

**Comment by cra0zy** [comment]
#4665 is ready

**Comment by cra0zy** [comment]
#4665 has been merged.
