### ISSUE TITLE
Set LoopLength and LoopStart to Songs

### ISSUE THREAD

**Issue by neofuji** [mono/MonoGame#4667]
Related to #4666, I want to set loop points in samples.
It is a simpler way than using XACT.

**Comment by KonajuGames** [comment]
Songs don't have a loop start and loop length in the same way that sound
effects do.  The media APIs we use don't support it.  If songs are set to
loop, it loops the whole song not just a section of it.

**Comment by neofuji** [comment]
Then may I request as new APIs?

**Comment by KonajuGames** [comment]
We use the media player APIs from the operating system where possible, and they do not support loops in compressed streaming audio.
