### ISSUE TITLE
[DesktopGL] Heavy Song volume fluctuation

### ISSUE THREAD

**Issue by mrhelmut** [mono/MonoGame#4672]
Hello,

First, I should note that I don't know if the problem comes from the ```OggStreamer``` / NVorbis, OpenAL, or my own code.

When playing ```Song``` for an extended time (from 5 to 10 minutes, and it doesn't matter if it is the same song or a queue of different ones), it happens very often that the ```Song``` playing volume changes by itself without any call to ```MediaPlayer``` in the last couple minutes, and it can go from plain 0 to 1.

This happens on all platforms, with OpenAL-Soft or Apple/Creative's one, and only affects ```Song```, not ```SoundEffect```.

Our game can be very ```SoundEffect``` intensive, and ```Song``` are cross-faded by code. At first I thought that I was putting to much pressure on the OpenAL command buffer, but even adding locks to have a max of 10 AL calls per second doesn't change anything, and the problem can happen in moments when absolutely no ```SoundEffect``` is playing for several seconds.

Any thoughts?

**Comment by Tzenchor** [comment]
I have a version of my xna game using the code from #4555 (but it is not up to date) and I could not note any random variation on music volume. For the record it's using the DesktopGL dll, the game code only handles the change of the song once the previous one has ended

**Comment by mrhelmut** [comment]
I found the problem. It's a combination of ```OpenALSoundController``` and ```SoundEffectInstancePool``` issues. An AL source can be reserved multiple times by different ```SoundEffectInstance``` and ```OggStream```, and since playing a ```SoundEffectInstance``` sets the volume to its source, it can happen that a ```Song``` is affected if they share the same source.

There are two problems: ```OpenALSoundController``` not being thread safe enough, and ```SoundEffectInstancePool``` not cleaning/reusing AL sources correctly.

Trying to figure out a fix.
