### ISSUE TITLE
Loading PNG Images

### ISSUE THREAD

**Issue by stringPuppet** [mono/MonoGame#4680]
Hi,

Yesterday I have updated MonoGame and my project to the latest version of MonoGame (3.5).
For some reason, all png images are loaded with different colors as shown at the image below (reddish color).
https://gyazo.com/cec4a7a9b12782f66f726876ab085d70

Also, this bug doesnt seem to occur if I loaded the PNG images differently: "Texture2D.FromStream();"
seems to work.. (Content.Load<>(""); does not).

Would appreciate if you guys could help me asap :)

**Comment by tomspilman** [comment]
@stringPuppet - What platform do you dev on... Windows, Mac, or Linux?

Is your content built with the MonoGame content pipeline or the XNA pipeline?  If using the MonoGame content pipeline be sure to try to rebuild it with the 3.5 pipeline.

@KonajuGames ?

**Comment by energyuser** [comment]
You can also try to set the `Texture`'s `TextureFormat` from the Content Pipeline app to `NoChange`. I once had problems with my `SpriteFont` being blurred so I set them to `NoChange` and they were OK.

**Comment by cra0zy** [comment]
About the textures getting blurred, I experienced it with `DXTCompression` yesterday. I think we should use `Color` as default

**Comment by tomspilman** [comment]
> About the textures getting blurred, I experienced it with  DXTCompression  yesterday.

That is a bug... there is no reason for the texture to look blurry under compression.


> I think we should use `Color` as default 

It is the default.

**Comment by cra0zy** [comment]
> It is the default.

Sorry, was talking about `SpriteFont`

**Comment by tomspilman** [comment]
> Sorry, was talking about `SpriteFont`, not `Texture`

I'd like to see https://github.com/mono/MonoGame/issues/2853#issuecomment-178852801 resolved before we make that choice.

**Comment by stringPuppet** [comment]
Hi guys, 
thanks for the replys, though, I still cant fix this bug.

@tomspilman The platform im dev'ing on is Windows, I'm using MonoGame Content Pipeline 3.5

**Comment by cra0zy** [comment]
@stringPuppet Can you give us the original image?

**Comment by stringPuppet** [comment]
![stone](https://cloud.githubusercontent.com/assets/6305838/14067334/b604b12e-f46b-11e5-87c2-6ed8a2717753.png)

**Comment by cra0zy** [comment]
@stringPuppet For now set `TextureFormat` to `NoChange`, it should work around the bug
![untitled](https://cloud.githubusercontent.com/assets/6773302/14067420/e531b5c0-f464-11e5-9fca-10c77465b9df.png)

@tomspilman The bug happens with the default `Color` format.

**Comment by stringPuppet** [comment]
@cra0zy 
Thanks for the reply,
but it doesn't seem to be working..

**Comment by Tzenchor** [comment]
I have been testing this and the problem might be coming from `Microsoft.Xna.Framework.Graphics.PackedVector.RGBA64.cs`, the data is inverted, what was RGBA data is returned as ABGR. Other formats like `Color` for example returns it in the same order as was in the byte array

**Comment by Tzenchor** [comment]
Changing the Pack and unpack method improves the results, but the colors are switched. Disabling the switch of the Red and Blue channels fixes the remaining issues
