### ISSUE TITLE
Broken MonoKickstart compatibility since 3.5.1

### ISSUE THREAD

**Issue by mrhelmut** [mono/MonoGame#4692]
PR #4534 broke MonoKickstart compatibility which is now throwing this error, on both OS X and Linux:
> Fontconfig error: Cannot load config file

It looks like the method used to test libgdiplus triggers a font search in the Mono font cache, which doesn't exist with MonoKickstart (and only exist if the Mono SDK is installed, which is why it doesn't fail on a dev environment).

This most probably also affects projects packaged with Xamarin.

@hach-que @cra0zy

**Comment by mrhelmut** [comment]
This is triggered by GDIPlus static initializer (https://github.com/mono/mono/blob/b7a308f660de8174b64697a422abfc7315d07b8c/mcs/class/System.Drawing/System.Drawing/gdipFunctions.cs), and all extern methods which could be used to avoid it are private.

Damn GDIPlus. ^^

**Comment by cra0zy** [comment]
Well that was unexpected... I am sorry for not inviting you into the conversation :(

On the bright side SDL version won't be using that part of the code at all, so maybe it's not even worth fixing right now.

CC. @tomspilman @dellis1972

**Comment by mrhelmut** [comment]
GDIPlus side effects, hard to predict (I couldn't have).

(Damn GDIPlus ^^)

The problem seems to be coming from Mono GDIPlus static initializer. I tried to search another method / code patch to get libgdiplus loaded without triggering the static initializer, but couldn't find any, beside ```new Icon(stream)```...

**Comment by tomspilman** [comment]
> PR #4534 broke MonoKickstart compatibility which is now throwing this error, on both OS X and Linux:

So basically...   our 3.5 release is broken on the two platforms we want to feature.  Fantastic!  :(

>  so maybe it's not even worth fixing right now.

No we want to fix it...  I want to push out a 3.5.2 build as soon as possible to correct this.   If not the stable release will be broken till June.

**Comment by cra0zy** [comment]
Can we modify mono kickstart to allow launching, that is include what's missing, this may be a better solution then releasing 3.5.2

**Comment by tomspilman** [comment]
Oh... didn't realize we do not ship MonoKickstart as part of the Mac/Linux SDKs.  That could maybe work as long as it is a good fix.

**Comment by cra0zy** [comment]
Haha, due to the face that mono got relicenced we no longer need mono kickstart, we can use mkbundle :D

**Comment by tomspilman** [comment]
Is that true?  I guess I don't know how any of that works.

**Comment by cra0zy** [comment]
I am gonna record a video to show you, one sec

**Comment by cra0zy** [comment]
I am having some trouble right now with trying to link mono statically:
```
/usr/bin/ld: cannot find -lmono-2.0
collect2: error: ld returned 1 exit status
ERROR: [Fail] 256
```

Anyway, will post a video tomorrow once I figure out what's wrong.

**Comment by mrhelmut** [comment]
The quickest fix would be to revert #4534. Both monogame/MonoKickstart and mkbundle bundle libgdiplus, hence this issue shouldn't be that frequent.

IMO, fixing it for good can wait for the System.Drawing calls to be removed.

**Comment by cra0zy** [comment]
I agree with @mrhelmut

**Comment by mrhelmut** [comment]
@tomspilman Would you agree on reverting #4534 ? (I can setup a PR)

**Comment by tomspilman** [comment]
@mrhelmut - Isn't this a non-issue now that we can use `mkbundle` and not MonoKickstart?

**Comment by mrhelmut** [comment]
I still have a personal preference for MonoKickstart because dll's / content can be easily swapped and it doesn't require a Mono install (on Windows).

Should both be supported or mkbundle become the official packager?  Though this question may not be relevant past 3.6.

**Comment by cra0zy** [comment]
mkbundle is totally broken right now :( someone broke it upstream...

**Comment by mrhelmut** [comment]
@tomspilman do you mind if I push a revert PR?

**Comment by cra0zy** [comment]
I agree with @mrhelmut on reverting the PR.

**Comment by cra0zy** [comment]
On the other hand #4755 fixes this as well.

**Comment by KonajuGames** [comment]
Fix or revert. I'll leave it up to both of you to decide which way is best as neither Tom or myself use MonoKickstart.

**Comment by tomspilman** [comment]
Yeah go ahead.

**Comment by sourceskyboxer** [comment]
Sorry It can decompile to newest version of mono?
