### ISSUE TITLE
SoundEffect.Play throws NullReferenceException when loading raw wav.

### ISSUE THREAD

**Issue by poohshoes** [mono/MonoGame#4694]
Using a DesktopGL project in MonoGame 3.5.0.

Tested with SoundEffect.FromStream and Content.Load and both crash.

[Here ](http://www.hernblog.com/SoundBug.zip)is an example project demonstrating the issue.  Press Z or X to play a sound.

The game crashes because the SoundEffect.SoundBuffer (in SoundEffect.OpenAL.cs) is not set
Theres only one assignment anywhere and it's in SoundEffect.PlatformInitialize but this is only ever called from one of the two SoundEffect constructors. The other constructor is empty and thats the one that gets called when you load the sound effect.

Without having any real understanding of the code path I copied the lines:
```
    SoundBuffer = new OALSoundBuffer();
    SoundBuffer.BindDataBuffer(_data, Format, Size, (int)Rate);
```
into SoundEffect.PlatformLoadAudioStream (in SoundEffect.OpenAL.cs) and it seems to have solved the issue. It would be great if someone who has some knowledge of the system could take a look at this and determine the optimal way of fixing this for the official branch (if it hasn't already been fixed).

**Comment by Quinn-L** [comment]
Hey poohshoes, looks like it has already been fixed in the latest develop branch at commit 1649df617fdb0dab035e060230c3c3d40343f671

**Comment by mrhelmut** [comment]
Mind trying the 3.5.1 to test if it got correctly fixed?

**Comment by Quinn-L** [comment]
Unless I've misread the history tree, it hasn't been merged with the master branch yet, so it's not in 3.5.1

**Comment by Jjagg** [comment]
I just tried @poohshoes 's project and can confirm this is fixed on develop branch and can be closed. @tomspilman

**Comment by poohshoes** [comment]
Thanks!
