### ISSUE TITLE
MonoGame UWP on XBox One Fixes

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#4697]
I ran into a few issues porting a quick test to Xbox One under UWP.

 https://www.youtube.com/watch?v=JWzwNUGr9Tk

 - It doesn't want to create a 1920x1080 back buffer....  it is like 1832x1023 or something weird.
 - There is a thick white border around the display area... might be why I am not getting a 1080p back buffer.
 - For some reason XB1 doesn't like how our static VBs and IBs are created... it fails to copy data into them, however dynamic buffers work fine.

The first two i'm told are new features that MS added to make apps seamlessly work on TVs within the safe area.   There are APIs to disable these things which I think we would want to do at the platform level...  games deal with the safe area on their own.

The last one i'm still trying to figure out.  We don't have issues with static VBs or IBs on any other UWP platform...  Windows 10, Windows 10 Mobile, or even Rasberry Pi 2/3.  So either we're doing something wrong that all the other platforms are tolerant of and let slip by...  or the XB1 Win10 OS has a bug in this area.

**Comment by brianost** [comment]
To remove the safe area border and use the full size of the window on Xbox One, the ApplicationView.DesiredBoundsMode property needs to be set to ApplicationViewBoundsMode.UseCoreWindow. Otherwise the XAML framework will restrict layout to what it believes is the visible area of the window, which is just the safe area in the middle.

**Comment by tomspilman** [comment]
> the ApplicationView.DesiredBoundsMode property needs to be set to ApplicationViewBoundsMode.UseCoreWindow. 

Great to know!  Thanks @brianost !

I guess we should toggle this as part of the normal "IsFullScreen" state.

**Comment by brianost** [comment]
I think for the purposes of MonoGame it is safe to leave it set to UseCoreWindow all the time. Games are generally going to want to use the entire window area.

I'd keep IsFullScreen tied to the ApplicationView.IsFullScreenMode. On Xbox One that'll represent whether there is a snap app next to the game, or it is really fullscreen. ApplicationView.TryEnterFullScreenMode will attempt to kick out the snap app and make the game fullscreen if possible.

**Comment by tomspilman** [comment]
> I think for the purposes of MonoGame it is safe to leave it set to UseCoreWindow all the time.

Maybe then I misunderstood what it did.  I assumed that on a Windowed UWP game that if UseCoreWindow was set we would loose the title bar on the window.  But I guess you're saying we would not.

**Comment by brianost** [comment]
Right, you shouldn't loose the title bar of the window.

**Comment by stonstad** [comment]
Here is a similar discussion I started earlier regarding XB1 UWP resolution behavior.  ([Link](https://social.msdn.microsoft.com/Forums/en-US/91792404-14c0-43d4-9c44-2ef1f8d068d8/uwpxbox-xb1-window-size?forum=wpdevelop))

`Windows.UI.ViewManagement.ApplicationViewScaling.TrySetDisableLayoutScaling(true);`

It didn't work for me due but perhaps it will for you.

**Comment by tomspilman** [comment]
> It didn't work for me but perhaps it will for you.

I actually independently found that post too on my first try fixing this.  It didn't work for me either... it seemed to make things worse.

I will be trying the `UseCoreWindow` change in a bit and if it works i'll submit a PR for it.

**Comment by stonstad** [comment]
> the ApplicationView.DesiredBoundsMode property needs to be set to ApplicationViewBoundsMode.UseCoreWindow. 

> I guess we should toggle this as part of the normal "IsFullScreen" state.

I have game which combines XAML with MonoGame.  In my scenario I needed to keep the window bounds at their default setting to prevent content from appearing off screen.  Keeping this setting at its default value seemed to adjust the screen bounds form me to ensure content at the fringes appeared properly.   For developers who did not account for television dead space they may actually want this UWP feature.

**Comment by tomspilman** [comment]
>  For developers who did not account for television dead space they may actually want this UWP feature.

I understand their predicament, but you really cannot depend on UWP for this.  If you plan to only ship to MS platforms that might be ok for you I guess... but the second you go to PS4 or OUYA you suddenly have to account for the safe zone again.

The game has to be written to account for the safe zone.  In fact there are XNA features to help do so:

http://www.monogame.net/documentation/?page=P_Microsoft_Xna_Framework_Graphics_Viewport_TitleSafeArea

It was always something the developer had to account for.

**Comment by stonstad** [comment]
That is a very good point Tom!  I am probably the outlier who did things backwards.  I use XAML with embedded 3D user controls.  It's a civilization-like strategy game, so lots of UI.    I think in my scenario I want the XAML to be bounded by safe space.  Either way, I can make it work!    Can't please everyone all the time.  :smile:

**Comment by tomspilman** [comment]
Ok first PR fix up... this is in the VS template and not within MonoGame to allow people like @stonstad  more flexibility.

**Comment by brianost** [comment]
Looks good to me.

**Comment by stonstad** [comment]
Thank you!

**Comment by tomspilman** [comment]
Closed this and moved remaining issue to https://github.com/mono/MonoGame/issues/4829.

**Comment by walbourn** [comment]
One quick note on the XNA ``ComputeTitleSafeArea``: The original XNA code is quite conservative:

    #if XBOX360
                int safeW = (w + 9) / 10;
                int safeH = (h + 9) / 10;

                x += safeW;
                y += safeH;

                w -= safeW * 2;
                h -= safeH * 2;
    #endif
                return new Rectangle(x, y, w, h);

For [DirectX Tool Kit](https://github.com/Microsoft/DirectXTK) I originally used the same computation for my version and it was really far in on the Xbox One. With modern monitors, you don't need quite that much safe area. I changed it to do effectively the following so it would work without eating up tons of space:

                int safeW = (w + 19) / 20;
                int safeH = (h + 19) / 20;

                x += safeW;
                y += safeH;

                w -= safeW * 2;
                h -= safeH * 2;
                return new Rectangle(x, y, w, h);
