### ISSUE TITLE
Implement DynamicSoundEffectInstance and Tests

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#4700]
We need to once and for all implement `DynamicSoundEffectInstance` across all platforms.

There was an effort 3 years ago that we were too dumb to get merged:  https://github.com/mono/MonoGame/pull/1982

We should use the ideas from it to help implement the feature for OpenAL and give the skeleton of the feature for XAudio platforms.

Note how the unit tests were written for this.  We should do the same... yes it won't tell us if the audio sounds right, but at least it will catch crashes or state problems.

**Comment by polsys** [comment]
I've made some work on this, I can look into finishing it and sending a PR in the coming days. At least I have quite good unit test coverage on the feature.

**Comment by tomspilman** [comment]
> I've made some work on this

Do you have a branch we can look at?


> I can look into finishing it and sending a PR in the coming days

That would be fantastic...  just be sure to submit a clean PR without any other mixed in features or fixes.

> I have quite good unit test coverage on the feature.

Even better!

**Comment by polsys** [comment]
I haven't pushed the branch yet to Github, there are some holes I'd rather fix first. I'm aiming to have it working on both WindowsGL and DX, and at the moment it's incomplete on either.

**Comment by tomspilman** [comment]
> I haven't pushed the branch yet to GitHub

Ok... we will just have to wait until you're done then.

> I'm aiming to have it working on both WindowsGL and DX

Sounds good.
