### ISSUE TITLE
Automatic building of Content fails in monogame Ouya project (Visual Studio 2015)

### ISSUE THREAD

**Issue by BaseCrosser** [mono/MonoGame#4722]
I am developing on a 64-Bit Windows 10 Home machine in Visual Studio 2015 and I get the following error when I try to build my Ouya test game.

`The command ""C:\Program Files (x86)\MSBuild\MonoGame\v3.0\Tools\MGCB.exe" 
/@:"C:\OuyaTest\Content\Content.mgcb" 
/platform:Ouya 
/outputDir:"C:\OuyaTest\Content\bin\Ouya" 
/intermediateDir:"C:\OuyaTest\Content\obj\Ouya" 
/quiet" exited with code -1.`

I think that the problem is that there is no 'Ouya' platform in the content pipeline to build with.
When I open the content file in the content pipeline and try to select a platform only these show up:
* Android
* DesktopGL
* iOS
* MacOSX
* NativeClient
* Playstation4
* PlaystationMobile
* RaspberryPi
* Windows
* WindowsPhone
* WindowsPhone8
* WindowsStoreApp
* Xbox360

As you can see there is no 'Ouya' platform and the command does try to use it.
Is there maybe a way to alter the command that gets run so that I could build for the 'Android' platform instead of the 'Ouya' one.

**Comment by Tzenchor** [comment]
> As you can see there is no 'Ouya' platform and the command does try to use it.
Is there maybe a way to alter the command that gets run so that I could build for the 'Android' platform instead of the 'Ouya' one.

When building content from Visual Studio directly the platform is taken from the .csproj
Look for the tag `MonoGamePlatform` and change it

**Comment by KonajuGames** [comment]
Ouya is Android.

**Comment by BaseCrosser** [comment]
Thanks @Tzenchor that did it, though the issue still remains but for now I can code further. Thanks!

**Comment by Tzenchor** [comment]
@BaseCrosser left it open so it is clear that the template has to be fixed

**Comment by BaseCrosser** [comment]
Thanks, I didn't want to close it actually. I guess I pressed the wrong button xD
