### ISSUE TITLE
Add a way to ckeck modifier keys

### ISSUE THREAD

**Issue by cra0zy** [mono/MonoGame#4729]
It would be useful if we provided some way of checking caps/scroll/num lock status.

**Comment by tomspilman** [comment]
This is how you normally do modifier keys:
```
var ctrlDown = state.IsKeyDown(Keys.LeftControl) || state.IsKeyDown(Keys.RightControl);
if(ctrlDown && state.IsKeyDown(Keys.C))
{
}
```
What is it about this technique that doesn't work?

**Comment by tomspilman** [comment]
Or maybe you mean the toggled state specifically of `Keys.CapsLock`, `Keys.Scroll`, and `Keys.NumLock`?

**Comment by cra0zy** [comment]
> Or maybe you mean the toggled state specifically of Keys.CapsLock, Keys.Scroll, and Keys.NumLock?

Yup.

**Comment by Tzenchor** [comment]
Shouldn't this be closed?

**Comment by cra0zy** [comment]
@Tzenchor You are right.
