### ISSUE TITLE
Make sure Pipeline tool starts even if Settings.XML is corrupted.

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#4733]
Looks like if the Settings.XML for the Pipeline GUI tool is screwed up the application silently fails to start.

 http://community.monogame.net/t/pipeline-exe-not-opening-resolved

We should protect against those cases and ensure the tool always starts no matter if the settings are corrupted or even if a command line option is incorrect.

**Comment by cra0zy** [comment]
@KonajuGames Ups, I just realized that you made a PR for this... anyway I'll keep mine open since it fixes Save and Constructor methods.

**Comment by KonajuGames** [comment]
No worries. I must have missed yours.  I'll have a look at it soon and may
well close mine if it makes sense.

**Comment by cra0zy** [comment]
> No worries. I must have missed yours

Oh, no no, I am the one that missed yours, you submitted it before me.
