### ISSUE TITLE
Thumbstick virtual buttons don't always behave correctly

### ISSUE THREAD

**Issue by MichaelDePiazzi** [mono/MonoGame#4741]
I'm using the thumbstick "virtual buttons" (e.g. `Buttons.LeftThumbstickUp`) for navigation of my menu system when using a controller. I noticed that it was quite difficult to move up/down without accidentally also triggering left/right movement (and vice versa).

Looking into it further, I found it was because I was using a circular dead-zone mode. If I changed to the independent axes mode, then it was much less sensitive and easier to use. However, I need the circular dead-zone mode for player movement so this wasn't a practical solution.

When I compared this behaviour to XNA, I found that XNA seems to always use the independent axes mode when determining the "virtual buttons" state regardless of the dead-zone mode you specify. This would make sense as you need the independent axes mode to properly separate up/down from left/right movement.

So I believe the solution to this is to always use the independent axes mode when determining the thumbstick virtual buttons state. This should make MonoGame behave similarly to XNA in this respect. I'm currently working on a PR which does this and will submit it shortly.

**Comment by tomspilman** [comment]
> When I compared this behaviour to XNA, I found that XNA seems to always use the independent axes mode when determining the "virtual buttons" state regardless of the dead-zone mode you specify.

Interesting...   that is a great find!
