### ISSUE TITLE
[DesktopGL / OpenTK / SDL2] GamePad crahes with some joystick

### ISSUE THREAD

**Issue by mrhelmut** [mono/MonoGame#4743]
Hello,

There is a bug in OpenTK SDL2 joystick driver (reported at opentk/opentk#377) which makes MonoGame to crash when some joystick are plugged. For instance, Saitek X55 (HOTAS joystick) is recognized as a gamepad but its value range are not compatible with a gamepad use and result in a crash when trying to ```GamePad.GetState(int index)```.

**Comment by tomspilman** [comment]
So can we patch this into the 3.5 release?

I guess we need a fix in the OpenTK assembly?

**Comment by mrhelmut** [comment]
Yes, it's an OpenTK issue, just opened an issue here to keep track of it and remember to eventually update the OpenTK assembly if it gets resolved soon enough.

**Comment by cra0zy** [comment]
How about I split the SDL2 branch in two and we merge all the changes related to replacing Windowing/Input system?

**Comment by mrhelmut** [comment]
Sounds interesting, these two are the biggest OpenTK concerns, and I think it's better to spend time helping you & dellis on this than trying to maintain the OpenTK path.

**Comment by tomspilman** [comment]
Want to hear from @dellis1972 on that first.  Not sure if a partial removal of OpenTK is a good thing or not.

**Comment by mrhelmut** [comment]
#4755 made this no longer relevant.
