### ISSUE TITLE
Cue.SetVariable is not implemented with instance variables

### ISSUE THREAD

**Issue by SeriousMartin** [mono/MonoGame#4745]
The method should do the following:
> Sets the value of a cue-instance variable based on its friendly name.

The current implementation does something else:
```
		public void SetVariable (string name, float value)
		{
            if (name == "Volume")
            {
                _volume = value;
                if (_curSound != null)
                    _curSound.SetCueVolume(_volume);
            }
            else
            {
				_engine.SetGlobalVariable (name, value);
			}
		}
```

This needs to be changed to a per instance list of variables that are used with the XAct presets when playing the sound. 

I'm not sure where the "Volume" variable name comes from - as far as I know there is not default variable to adjust the volume. 

I'll have a deeper look at this and try to implement it correctly. I couldn't find any other matching issue or pull request - has someone already been working on this?

**Comment by tomspilman** [comment]
It would be great to have help in making our XAct implementation more correct, however we need to figure out how to unit test the system first.  Without unit tests I am very hesitant to change anything in XAct as it is complex enough that one simple change can cause unintended side effects.


> has someone already been working on this?

Pretty much I've been the only one doing work on Xact in the last few years.  As you can see in the change history:

https://github.com/mono/MonoGame/commits/develop/MonoGame.Framework/Audio/Xact

**Comment by tomspilman** [comment]
The first thing that comes to mind is the basics we can do just testing the API to behave correctly:

 http://programmers.stackexchange.com/a/135891

However for us the major thing is if the system is actually playing the right content.

In theory on a Windows PC we could call Win32 APIs to record or redirect audio to a memory buffer or file on disk then compare that waveform to a previously recorded correct result from like Microsoft's XAct.  This would be a fantastic testing feature, but i worry it would be tricky to write and get working reliably.

Also could be we just need to implement a set of manual unit tests which prompt the listener as to what to expect, let them listen to the result, and then mark the test as pass or failed.  I covered this in https://github.com/mono/MonoGame/issues/3793 aiming to write a framework for manual tests for MonoGame.

**Comment by SeriousMartin** [comment]
Testing the resulting sound would be awesome, but I think this has to be done independently from the XAct implementation. In my view this is a general test to make sure SoundEffect is working as expected. Does it matter whether the SoundEffect is created by a WaveBank or somehow else?

As far as I can see there is currently no implementation that updates volume and pitch of underlying SoundEffectInstance instances based on the XAct RPC presets. That is what I would like to focus on.

Unit tests for this could be done by using RPC presets, adjusting cue variables and checking whether the resulting volume and pitch values of SoundEffectInstance are correct.

**Comment by tomspilman** [comment]
> Does it matter whether the SoundEffect is created by a WaveBank or somehow else?

For sure we are separately looking at unit testing `SoundEffect`s and have some work on that already happening.

What matters is if the `WaveBank` or `Cue` plays any sound effect at all or the right sound effects at right times.  I want to be sure XAct behaves correctly which means being able to test exactly what sounds are playing and when.

> based on the XAct RPC presets

Right... we have volume and pitch changes on the clip randomizations:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Audio/Xact/PlayWaveEvent.cs

... but while we load the RPC data we don't actually do anything with it.


What matters is if a cue has to play more than one sound effect with specific timing...  that we can test that the cue actually does that correctly.

> checking whether the resulting volume and pitch values of SoundEffectInstance are correct.

That could work for MonoGame....  unfortunately we can't test XNA this way which makes it harder to verify things are working correctly.

**Comment by SeriousMartin** [comment]
> unfortunately we can't test XNA this way which makes it harder to verify things are working correctly.

I'm not sure if XNA is a perfect reference. For example I just discovered that changing the pitch to less than -1.2 by adjusting it on multiple levels (sound pitch and rpc preset) just leads to no sound played at all (instead of an exception or the pitch being clamped).

I'm currently working on a basic XAct implementation for RPC presets. I'd suggest that I create a pull request once I'm done. Next we can decide on what else needs to be tested to make the pull request acceptable.

**Comment by tomspilman** [comment]
> I'm not sure if XNA is a perfect reference.

Since replicating XNA behavior is still one of our primary goals...  I would say it is a pretty reliable reference in almost all cases in that regard.  In the few instances where XNA does something "wrong" we look to fix it in a way that tries to not break behavior in existing games.

**Comment by SeriousMartin** [comment]
I have experimented some hours with this now.

First I tried to implement XAct based on the existing code. Unfortunately SoundBank.GetCue is not working the way it should. It always returns the same cue instead of a new instance (this is what it should do according to XNA). As far as I can tell changing this would require to rewrite most of the code.

So I decided to simply take the current FNA implementation of XACT which is working quite well (though the code isn't as clean as I would have liked it to be). 

I have created some unit tests based on this. They are capturing audio using WASAPI and comparing the result.

Finally, I decided to get rid of XACT in our game, so I'm not going to work on this anymore. In retrospect the XACT-less audio solution is much cleaner and easier to maintain than the XACT audio library. XACT has tons of options to adjust audio which introduced a lot of possible (and real) audio problems into our game.

I can provide a patch or pull request with the working XACT code and unit tests if anyone is interested.

**Comment by tomspilman** [comment]
> It always returns the same cue instead of a new instance (this is what it should do according to XNA). As far as I can tell changing this would require to rewrite most of the code.

That was on purpose when it was implemented.... the goal being reducing unnecessary garbage from playing cues.  In the games I've tested with it this wasn't an issue, but I know we've ever tested it exhaustively.

> I have created some unit tests based on this. They are capturing audio using WASAPI and comparing the result.

If you could share some of that it would be tremendously useful to us getting a full Xact implementation working reliably.  If you have a branch with this code it in you can just point me at it and I can take care of pulling it over in a way we can use it.

**Comment by SeriousMartin** [comment]
Here is the corresponding commit: https://github.com/SeriousMartin/MonoGame/commit/be9d35eec675c778adddfba7b384b07c368bd9e2

I suppose the unit tests are the most interesting part of it. They need a reference to NAudio. The xact code is simply taken from FNA with some small fixes (sadly I didn't use a separate commit for these fixes).

Hope this helps.

**Comment by tomspilman** [comment]
Thanks @SeriousMartin ...  that is great.  I'll certainly be pulling out your unit tests and running with that as we do various XAct and SoundEffect fixes.

**Comment by tomspilman** [comment]
FYI.  This was fixed by https://github.com/mono/MonoGame/pull/4961.
