### ISSUE TITLE
MonoGame Pipeline tool on Windows uses the "Delete" word when it really means "Remove"

### ISSUE THREAD

**Issue by vchelaru** [mono/MonoGame#4756]
To reproduce:

1. Create a MonoGame Pipeline project
2. Save the MonoGame project in a folder
3. Create a new folder in Windows Explorer named "ToBeRemoved"
4. In the MonoGame Pipeline tool, add the newly-created ToBeRemoved folder
5. Right-click on the folder

Observe: The right-click menu includes a "Delete" folder, which Visual Studio users will understand to mean that the folder will both be removed from the MonoGame Pipeline project *and* deleted from disk. 
Actual: The "Delete" menu item does not delete the folder from disk, it merely removes it from the MonoGame content project. The "Delete" word may make users nervous that the file will be deleted, and they may search for an alternative option to preserve the file on disk.

This menu item should be renamed to say "Remove" or "Exclude from Project" (to match the terminology of Visual Studio).

Note that Xamarin Studio uses the "Remove" word as well, and selecting this option then asks the user if the file should just be removed from the project or if it should also be deleted.

**Comment by cra0zy** [comment]
Haha, my next PR fixes this... O o

**Comment by InfiniteProductions** [comment]
Just for the record, I've been in trouble because of this: "delete" an asset, try to re-import it but only able to add link (not copy) file, because it physically exists but not in the list of pipeline tool, which is pretty annoying behaviour  IMHO :/.

**Comment by Jjagg** [comment]
This is fixed, there is now an exclude from project and a delete option.
