### ISSUE TITLE
Content Pipeline - Unhandled MS .NET Framework exception

### ISSUE THREAD

**Issue by energyuser** [mono/MonoGame#4764]
"An unhandled Microsoft .NET exception occurred in MGCB.exe [3376]"

What I see is that nothing suspicious is displayed in the build logs... My OS is Windows 10 although I'm not developing on UAP but on Windows DirectX project. Could it also be that my .NET framework installation is buggy? I can "Repair" it using the installer but I don't know which version should that be... Maybe the default project version (4.5)??

**Comment by KonajuGames** [comment]
Can you paste the log here?  What file and asset type was it processing at the time?

**Comment by energyuser** [comment]
I just did Build -> Build (F6)...
What log? It just builds the files with no further errors so nothing I could really show. The assets that were being processed are: `.wma` songs, `.png` textures. That's all I have in my Content.

**Comment by Tzenchor** [comment]
@energyuser open the content file in the pipeline tool and select the build option. If the log contains color squares disable the `filter output` option

**Comment by energyuser** [comment]
@Tzenchor I disabled `filter output` and I saw the exception again. What I hadn't noticed was that the logs said it skipped all my assets...

**Comment by KonajuGames** [comment]
Select Rebuild from the menu. It is skipping the assets because it has
already built them and they haven't changed.

**Comment by energyuser** [comment]
`Rebuild` - again, the same exception...

**Comment by Tzenchor** [comment]
@energyuser can you make a screenshot of the pipeline tool when the exception occurs?

**Comment by energyuser** [comment]
@Tzenchor [Here's a screenshot.](http://i.imgur.com/WKROzLh.png)

**Comment by Tzenchor** [comment]
Now I undestand, disable `Debug Mode` in the `Build` menu.
The exception you are seeing is simply to allow the debugging of the content builder
