### ISSUE TITLE
Make SpriteEffect public

### ISSUE THREAD

**Issue by Jjagg** [mono/MonoGame#4766]
I'm doing some stuff for which I need to render sprites with custom vertices. Right now I'm using BasicEffect, but it'd be nice if I could use SpriteEffect since it has everything I need. Is there any good reason for it not being public other than that's the way it is in XNA?

**Comment by prime31** [comment]
Why don't you just make your own shader and process the verts in their? I don't really see how SpriteEffect being public would allow you to do that. It doesnt actually do anything besides set the projection matrix.

**Comment by Jjagg** [comment]
I don't need to process the verts in any special way, just drawing primitives (that's what i mean by custom verts, not just a texture). So sprite effect was sufficient to do the rendering and it got me wondering why it isn't public since the other built-in effects are. IMO it could be nice when drawing some basic 2d textured primitives to have the shader built-in, so you don't have to write your own.

**Comment by tomspilman** [comment]
I see no issue with doing this.  @KonajuGames ?

**Comment by KonajuGames** [comment]
I've got no issue with making it public for those who want use it.
