### ISSUE TITLE
StorageContainer OpenFile throwing exception

### ISSUE THREAD

**Issue by ricardosabino** [mono/MonoGame#4772]
Just noticed that calling OpenFile on a container with FileMode.Open is throwing an AccessDenied exception. After checking the MonoGame code:
`folder.CreateFileAsync(filePath, CreationCollisionOption.OpenIfExists).AsTask().GetAwaiter().GetResult().OpenAsync(FileAccessMode.ReadWrite).AsTask().GetAwaiter().GetResult().AsStream();
var f = folder.CreateFileAsync(filePath, CreationCollisionOption.OpenIfExists).AsTask().GetAwaiter().GetResult();
                return f.OpenAsync(FileAccessMode.ReadWrite).AsTask().GetAwaiter().GetResult().AsStream();
`

I found that this code is causing the problem as the first line is gaining access to the file (basically doing what the next two lines do) and when the next 2 lines come in there is an access denied due to file being already in use by the first line.

**Comment by cra0zy** [comment]
XNA Storate stuff has been removed in develop, see #4311 for more info.

**Comment by ricardosabino** [comment]
Thanks, didn't know you were deprecating this.
