### ISSUE TITLE
Pipeline Tool: exception on new/open/import project

### ISSUE THREAD

**Issue by InfiniteProductions** [mono/MonoGame#4780]
Using dev snapshot of the pipeline tool, since almost last week, I got this exception when using open (also new or import):

System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
à Eto.WinForms.Forms.WindowsFileDialog2.<>c.<SetFilters>b__9_0(FileDialogFilter f)
à System.Linq.Enumerable.WhereSelectEnumerableIterator2.MoveNext()
à System.String.Join(String separator, IEnumerable1 values)
à Eto.WinForms.Forms.WindowsFileDialog2.SetFilters()
à Eto.WinForms.Forms.WindowsFileDialog`2.ShowDialog(Window parent)
à MonoGame.Tools.Pipeline.MainView.AskOpenProject(String& projectFilePath) dans M:\c#\MonoGame\MonoGame\MonoGame-develop\MonoGame\Tools\Pipeline\Eto\MainWindow.cs:ligne 67
à MonoGame.Tools.Pipeline.PipelineController.OpenProject() dans M:\c#\MonoGame\MonoGame\MonoGame-develop\MonoGame\Tools\Pipeline\Common\PipelineController.cs:ligne 221
à MonoGame.Tools.Pipeline.MainView.OnOpenProjectClick(Object sender, EventArgs e) dans M:\c#\MonoGame\MonoGame\MonoGame-develop\MonoGame\Tools\Pipeline\Windows\MainView.cs:ligne 509
à System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
à System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
à System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
à System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
à System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
à System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
à System.Windows.Forms.Control.WndProc(Message& m)
à System.Windows.Forms.ToolStrip.WndProc(Message& m)
à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Pipeline tool from official MG 3.5.1 build works (fortunately for me).
Projects are build using protobuild for WinDx platform on win7 64b.

Using VS 2015 to debug, I got:
Exception occured in AskOpenProject (MainWindow.cs) method on line:
var result = dialog.ShowDialog(null) == Eto.Forms.DialogResult.Ok;

[Comment from Alkher on the forum](http://community.monogame.net/t/pipeline-tool-dev-open-a-project-exception/7499/2?u=infiniteproductions):
>  have looked into the code.A call to Init() in MainWindow.cs is missing, so dialog.CurrentFilter = _mgcbFileFilter; filters with a null value... and ShowDialogFails

**Comment by tomspilman** [comment]
Thanks for reporting this @InfiniteProductions !

@cra0zy ?

**Comment by cra0zy** [comment]
Yup, people on forum are right, I missed adding a `Init()` to the https://github.com/mono/MonoGame/blob/develop/Tools/Pipeline/Windows/MainView.cs#L39

I think I'll finish the Eto.Froms Main Window for the Pipeline Tool by tomorrow so the fix will be in that.

**Comment by tomspilman** [comment]
Thanks @cra0zy !

**Comment by ed022** [comment]
Has this been fixed? Where can I obtain the updated version?

**Comment by cra0zy** [comment]
#4786 fixes it.

**Comment by ed022** [comment]
Pardon my ignorance; I'm new to the Mono and GitHub scenes. Is there an executable update, or do I have to manually build from this code repository?

**Comment by cra0zy** [comment]
If you want to test out the PR above, you can grab the installer from the build bot: http://teamcity.monogame.net/viewLog.html?buildId=12315&buildTypeId=MonoGame_PackagingWindows&tab=artifacts&guest=1

**Comment by ed022** [comment]
Cool, thank you very much! =)

**Comment by Jjagg** [comment]
With #4786 merged, this is fixed.
