### ISSUE TITLE
[DesktopGL] Fullscreen always set to 800x600

### ISSUE THREAD

**Issue by mrhelmut** [mono/MonoGame#4783]
Hello,

When entering fullscreen (using ```graphics.HardwareModeSwitch = true;```), ```SDLGameWindow``` always resets the ```Viewport``` and backbuffer size to 800x600.

This is due to SDL triggering a ```Sdl.Window.Event.Id.Resized``` (which is correct) but with ```ev.Window.Data1``` & ```ev.Window.Data2``` always returning 800 & 600.

As far as I have tested, this happens on Windows and OS X.

Everything is fine on windowed or ```graphics.HardwareModeSwitch = false;``` fullscreen modes (the event values are the intended ones).

@cra0zy any thoughts? I don't know if this is the normal ```Sdl.Window.State.Fullscreen``` behavior.

**Comment by cra0zy** [comment]
Works fine on Linux for me.

**Comment by mrhelmut** [comment]
If I set a backbuffer of 1280x720, it seems that ```Sdl.Window.Show(Window.Handle);``` changes the resolution to 800x600.

```
            var displayIndex = Sdl.Window.GetDisplayIndex(Window.Handle);
            Sdl.Rectangle displayRect;
            Sdl.Display.GetBounds(displayIndex, out displayRect);
            Console.WriteLine("- before show " + displayRect.Width + ";" + displayRect.Height); // will output 1280x720

            Sdl.Window.Show(Window.Handle);

            Sdl.Display.GetBounds(displayIndex, out displayRect);
            Console.WriteLine("- after show " + displayRect.Width + ";" + displayRect.Height); // will output 800x600
```

Still searching, but my SDL knowledge is limited.

**Comment by cra0zy** [comment]
Sounds like a bug, well at least that is easily fixed by adding a set size after show event, right?

**Comment by mrhelmut** [comment]
Yes, but not quite. There are a few odd things, bounds end up being 1368x912 after a ```Sdl.Window.Size(Window.Handle, 1280, 720)```.

Everytime ```Sdl.Window.Size``` is called, it adds something to bounds. So with the one in ```EndScreenDeviceChange```, plus another to workaround this, the final bounds are 1400x1050.

Good thing is that SDL doesn't raise the resize event twice for showing + size right after.

Maybe ```Sdl.Window.Size``` and ```ClientResize()``` shouldn't use the bounds (or the event data), but something like ```SDL_GL_GetDrawableSize()``` ?

**Comment by cra0zy** [comment]
I was able to reproduce the bug wuhu!!!

**Comment by cra0zy** [comment]
I have a fix for this, will post a PR later :)

**Comment by mrhelmut** [comment]
Awesome, let me know if I can of any help.

**Comment by cra0zy** [comment]
Test it out if you can.

**Comment by mrhelmut** [comment]
@cra0zy works great, thanks. :+1: 

Now I can work on adding Hi-DPI support. Should be straightforward.
