### ISSUE TITLE
Improve AssemblyInfo

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#4799]
If you look at our current assembly info files:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Properties/AssemblyInfo.cs

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework.Content.Pipeline/Properties/AssemblyInfo.cs

we need to make improvements to them.

First for some reason the `AssemblyDescription` which we seem to be setting correct doesn't appear in the final executable:

![assinfo](https://cloud.githubusercontent.com/assets/103522/14770975/59bb5a2e-0a43-11e6-89f0-5994395aa376.PNG)

That needs to be fixed.... could be the build server is at blame here, but i don't know.

We should remove the `#if`s in there too and instead go with something like the partial class technique with new files `AssemblyInfo.Windows.cs`, `AssemblyInfo.iOS.cs`, `AssemblyInfo.Android.cs` etc.  This allows for PS4 and other platforms to add their own custom assembly attributes.

The `Copyright © 2011-2016` should be changed to `Copyright © 2009-2016 MonoGame Team` which matches when the MonoGame project started.

We should set `AssemblyCompany` to `MonoGame Team`.

We should set the `AssemblyTrademark` to `MonoGame® is a registered trademark of the MonoGame Team`.

Also everything discussed here should be done for the pipeline assembly info as well.  We should be sure that the new PCL portable assemblies have their info modified to mark them clearly as PCL and not for a particular platform.

Any other cleanups we need to do here?

**Comment by Tzenchor** [comment]
> First for some reason the AssemblyDescription which we seem to be setting correct doesn't appear in the final executable

It appears that the description was hidden in Vista or Windows 7 as stated [here](http://www.codeproject.com/Articles/118909/Windows-7-File-properties-Version-Tab-Shell-Extens). Also the [MSDN](https://msdn.microsoft.com/en-us/library/system.reflection.assemblydescriptionattribute(v=vs.110).aspx) remarks section sounds like it is deprecated.
I have also noted that what it shown in the explorer tooltips is the file description that is set with `AssemblyTitle`.

I'm readying a pull request to change this, the first commit will have only the new data, and the next will get rid of the `#if`s
