### ISSUE TITLE
SDL2 2.0.5?

### ISSUE THREAD

**Issue by angrywasp** [mono/MonoGame#4809]
Not really an issue, just looking for some info from people in the know.

i am on Linux (Ubuntu 16.04) using the latest develop branch with SDL2. MG warns of SDL2 2.0.4 and cites a global mouse issue, which is exactly what i am currently facing.

So i am looking at where this sdl2 2.0.5 comes from. Latest release is 2.0.4 (bugged version) which is on their site and in the Ubuntu repos. I have also tried cloning their hg repo on a number of occasions and had it fail every time.

If someone could point me in the direction of the source used to fix this issue i would really appreciate it.

**Comment by mrhelmut** [comment]
SDL2 2.0.5 isn't out yet, but will contain important fixes, like mouse coordinates and window resizing. The current source code is getting prepared for this release.

@cra0zy may have more details to share about SDL2 2.0.5 and possibly code of a development build that may be used while waiting for the stable release.

**Comment by cra0zy** [comment]
MonoGame will work without SDL 2.0.5, I added some legacy code to make sure, but if you want to get the most out of it I would suggest downloading SDL from source (http://hg.libsdl.org/SDL/), and the following patches:
 - http://flibitijibibo.com/resizable.diff
 - https://bugzilla-attachments.libsdl.org/attachment.cgi?id=2390

**Comment by angrywasp** [comment]
No worries. I was aware there was no official release, but couldn't determine if this 2.0.5 version mentioned was being built from somewhere i didn't know about or if it was just an indicator that the current version is bugged. 

In any case, i have worked around my problems. Only had to change a couple of lines in the MG code. Just wanted to check if there was a new SDL version to use before making changes to the MG code.

Thanks

**Comment by cra0zy** [comment]
> Only had to change a couple of lines in the MG code.

You shouldn't have to do any modifications, it should work out of the box with the earlier versions of SDL, what modifications did you do?

**Comment by angrywasp** [comment]
I made a couple of changes in Mouse.SDL.cs

I changed line 23 to use Sdl.Window.GetGlobalState. This fixed mouse presses (previously weren't working in windowed mode)

than at line 39 reassigned x and y with Sdl.Window.GetState.

it seems that GetGlobalState is needed for mouse events (button presses etc) but GetState returns the right mouse coordinates

I need to look into this further and figure out what is going on. My code changes are the result of 2 minutes of investigation, so i may find the fix actually doesn't fix the problem. I'll get around to it some time today.

The changes are in PlatformGetState

```
        private static MouseState PlatformGetState(GameWindow window)
        {
            int x, y;
            var winFlags = Sdl.Window.GetWindowFlags(window.Handle);

            //use GetGlobalState
            var state = Sdl.Mouse.GetGlobalState (out x, out y);
            var clientBounds = window.ClientBounds;

            if (clientBounds.Contains(x, y) && winFlags.HasFlag(Sdl.Window.State.MouseFocus))
            {
                //set mouse button states and scroll value
            }
            
            //Need to use GetState to get mouse position correctly
            Sdl.Mouse.GetState (out x, out y);

            window.MouseState.X = x;
            window.MouseState.Y = y;

            return window.MouseState;
        }
```

**Comment by cra0zy** [comment]
Global state is bugged out on Linux with SDL 2.0.4, you shouldn't use that if you are using < 2.0.4 version of SDL.
