### ISSUE TITLE
Content Pad Extension

### ISSUE THREAD

**Issue by cra0zy** [mono/MonoGame#4816]
Image does say a 1000 words:
![content](https://cloud.githubusercontent.com/assets/6773302/14967826/cb2e03c4-10b9-11e6-892a-ebbe287dfa0a.png)

Anyway I created this because I found it easier to work with that than switching with the Pipeline Tool window, properties currently aren't editable. It's just using the code from: #4786 so it just embeds the Pipeline Tool project view component.

@tomspilman @dellis1972 @KonajuGames Thoughts?

**Comment by Jjagg** [comment]
This is really convenient! Could the same thing be done for VS?

**Comment by cra0zy** [comment]
It can, it would also have the exact same code reuse.

**Comment by tomspilman** [comment]
IMO we don't want to add this to MonoGame officially.

We specifically built the Pipeline tool as a separate stand alone GUI tool that could be used independent of Visual Studio or Xamarin Studio.  This was determined to be easier to maintain, document, and support.

I would rather focus on finishing the Pipeline tool we have now.

**Comment by cra0zy** [comment]
I'll add this extension unofficially once MG 3.6 goes out. Closing...
