### ISSUE TITLE
Have IBoundingVolume interface for Bounding Frustum/Box/Sphere etc?

### ISSUE THREAD

**Issue by UncleThomy** [mono/MonoGame#4819]
Hi guys,

I was wondering if we could just go ahead and implement an interface for the Bounding Frustum/Box/Sphere class, which would dictate stuff like Intersect(), Contain(), etc

I don't see any downside and on the upside we can just cast all of these for generic comparisons like
 ((IBoundingVolume) myBoundingVolume).Contains(myVector3);
 or (myBoundingVolume as IBoundingVolume) for that matter

What do you think?

**Comment by tomspilman** [comment]
The reason we avoid interfaces in C# is specifically because they are one of the slowest of call types you can make in C#.

http://www.dotnetperls.com/interface-virtual-performance
http://tips.x-tensive.com/2008/10/method-call-performance.html

On a PC with a 3GHz CPU this barely matters, but MonoGame has to support much lower end CPUs too (think phones, some consoles, etc.).  For this reason we generally avoid it unless absolutely necessary.

Getting back to your suggestion...  what are you trying to solve here?

**Comment by prollin** [comment]
@UncleThomy As someone who went deep down the rabbit hole that is OOP and back, this type of abstraction is a red flag, especially in game development.

Assuming you want to perform some containment test on many "entities", I would recommend to sort/bin your data (actually a custom structure specific for this would be best) per type of bounding volume that need to be tested. As @tomspilman mentioned you will not only suffer the cost of Interface calls but also you are more likely to make better use of the cache (less cache misses); good cache aware code can be an order of magnitude faster than one riddled with cache misses (and also makes it a lot easier to parallelize).

**Comment by UncleThomy** [comment]
I understand, was just trying to generalize Bounding Volumes so I can test different shapes (which exactly I don't know beforehand) against each other and just have it work without necessarily needing to do switch statements depending on the type.

But I understand, thanks for the replies guys. My involvement with c# was usually business applications not related to speed, and everything was very much coordinated to be "perfect OOP". Interfaces, abstract classes, no arrays only IEnumerables, use Events everywhere etc etc.

I guess I have to change my ways a whole lot more for efficient game design. 

I think I can close this.

**Comment by cra0zy** [comment]
> The reason we avoid interfaces in C# is specifically because they are one of the slowest of call types you can make:
> 
> http://www.dotnetperls.com/interface-virtual-performance
> http://tips.x-tensive.com/2008/10/method-call-performance.html

I thought I would run the test to see what's the difference now since the articles are a bit outdated and... interfaces were faster than virtual methods for me O o

**Comment by tomspilman** [comment]
> I thought I would run the test to see what's the difference now since the articles are a bit outdated

How interfaces work has not changed since C# 1.0.

> interfaces were faster than virtual methods for me

Under some conditions the JIT can optimize things a bit... it is easy to make a test that falls into one of these cases giving you a false result.
