### ISSUE TITLE
No MonoDevelop project templates install on the Linux version

### ISSUE THREAD

**Issue by SoundGoddess** [mono/MonoGame#4821]
Unlike Visual Studio on Windows and Xamarin on Mac, if you install the Linux version (at least by using the Ubuntu install instructions) no project templates install into MonoDevelop so you're stuck using another operating system to create an empty project and then opening that project in Linux.  You should just be able to select a MonoGame template when you create a new MonoDevelop project.

This seems like an easy enough fix so I'm happy to try to tackle it myself if nobody else is working on it.

**Comment by tomspilman** [comment]
Interesting...  @cra0zy did the installer for Linux, so lets see what he says first.

**Comment by cra0zy** [comment]
Ubuntu install instructions? We deprecated .deb installer, and .run should install the templates...

Please uninstall the existing MonoGame and follow http://www.monogame.net/documentation/?page=Setting_Up_MonoGame_Linux and if the templates are not install, copy the terminal output here so I can look at it.

**Comment by SoundGoddess** [comment]
Yeah those are the instructions I used.  I never installed any previous versions, but I'm really unclear as to if the "please uninstall" message is supposed to be some sort of error or just means that I already have 3.5 installed.  http://i.imgur.com/ZZSGTgE.png

**Comment by cra0zy** [comment]
Run `/opt/MonoGameSDK/uninstall.sh`

**Comment by SoundGoddess** [comment]
Ok that seemed to fix the problem on my end.  Most likely the issue then is that the instructions were a bit confusing so I probably ran the installer before having MonoDevelop installed.  And then when I ran the installer again after MonoDevelop was installed, it didn't work because the installer detected that the MonoGame SDK was already installed.  I realize that this is user error on my end, but if it happened to me it can happen to someone else and that may make the difference between them playing with MonoGame and eventually using it for their projects, or seeing that it doesn't work as expected and simply moving on to another framework.

**Comment by tomspilman** [comment]
>  it didn't work because the installer detected that the MonoGame SDK was already installed.

@cra0zy - Can the installer be a little more careful here and do an optional re-install in that case?

**Comment by SoundGoddess** [comment]
The way the current instructions are written, and the way the current installer is set up, if you just go line-by-line it doesn't tell you to install anything before MonoGame.  So if you don't pay close enough attention to the "please make sure that the following packages are installed:" line when executing the installer, you're going to end up with a broken dev environment with no clear idea of what to do to get it working.

**Comment by cra0zy** [comment]
> The way the current instructions are written, and the way the current installer is set up, if you just go line-by-line it doesn't tell you to install anything before MonoGame. So if you don't pay close enough attention to the "please make sure that the following packages are installed:" line when executing the installer, you're going to end up with a broken dev environment with no clear idea of what to do to get it working.

I got to disagree.. both the installer and the documentation page tell you the list of dependencies and request that you install them, if you manage to skip both it's your fault for not reading. 

> @cra0zy - Can the installer be a little more careful here and do an optional re-install in that case?

Nope... it's an installer... if you run MonoGame installer on Windows before installing Visual Studio you won't get an option to install Visual Studio Templates...

On the side note I do plan on making MonoGame manager for Linux to allow multiple versions to be installed at the same time so that should allow reinstallation of stuff. (When I say MonoGame manager I just mean an application with listbox of currently installed monogame versions with set default and uninstall buttons)

**Comment by SoundGoddess** [comment]
The documentation should mention the dependencies before telling you to execute the installer.

**Comment by tomspilman** [comment]
>  if you run MonoGame installer on Windows before installing Visual Studio you won't get an option to install Visual Studio Templates

Of course.  But if you run the MonoGame installer again after you install VS it will run and fix the install.  That is all i'm asking about here.

**Comment by SoundGoddess** [comment]
Instead of saying "Please uninstall any previous versions of MonoGame SDK" it could say something like "MonoGame SDK is already installed, press R to repair or U to uninstall".

**Comment by cra0zy** [comment]
> Of course. But if you run the MonoGame installer again after you install VS it will run and fix the install. That is all i'm asking about here.

It's just requesting an uninstall, don't think that's so unreasonable... I should be able to include the automatic uninstallation for 3.5 and newer.

> Of course. But if you run the MonoGame installer again after you install VS it will run and fix the install. That is all i'm asking about here.

The reason I am detecting if the previous version is installed and not giving any instructions is because earlier version of MonoGame could have gotten installed anywhere, it had an option to pick location.

**Comment by cra0zy** [comment]
@SoundGoddess What desktop enviorment do you use, and does running `pkexec echo test` give you a native dialog for entering password?

**Comment by SoundGoddess** [comment]
Here's the thing though.  If someone already has a previous version of MonoGame installed then they're probably actively using MonoGame and have the motivation to get it working.  If someone who has never used MonoGame before ends up with a broken install, they're way more likely to move on to a different framework rather than trying to diagnose why the install was broken.

**Comment by SoundGoddess** [comment]
http://i.imgur.com/7FAc1ZM.png

**Comment by tomspilman** [comment]
> It's just requesting an uninstall, don't think that's so unreasonable

Well if on Linux a "repair" would be an uninstall then reinstall that is fine.  On Windows if you run the installer a second time it just runs again overwriting files and changes from before.  We have discussed fixing that to run an uninstall first, but haven't done that yet.

**Comment by cra0zy** [comment]
> Here's the thing though. If someone already has a previous version of MonoGame installed then they're probably actively using MonoGame and have the motivation to get it working. If someone who has never used MonoGame before ends up with a broken install, they're way more likely to move on to a different framework rather than trying to diagnose why the install was broken.

Just paying a bit attention to the installer will result in getting everything installed correctly. You are overreacting over something simple :|

**Comment by SoundGoddess** [comment]
If it's so simple, it should be no big deal to fix the issue.  I'm not saying this needs to be a high-priority item.  But you'll want help with improving the documentation and I'm pointing out where it could be improved.  What's the issue with re-ordering the install instructions to mention the dependencies prior to telling someone to open up a terminal and execute the installer?  I'm willing to fix nitpicky details like this myself, I'm not asking you to do it.  But your community instructions say to post issues here to discuss first rather than posting PRs and not getting them approved.

**Comment by Jjagg** [comment]
Fixed by #4877, this can be closed.
