### ISSUE TITLE
3.6 template DesktopGL / vs2013-2015 

### ISSUE THREAD

**Issue by oldteen** [mono/MonoGame#4830]
Hello,

I am trying 3.6 Dev Build with vs2013 or 2015 and the template DesktopGL.
- The project is created, perfect.
- I press F5, compile, launch the program, and get the message "SDL2.dll missing"
- ok, I copy sdl2.dll in my debug folder
- Press F5 again and get a "vshost32 stop to run" message (but in french :) )

Did I forgot something? I didn't modify the code created by the template. Maybe my sdl2.dll is wrong version (2.0.4.0) ?

In my debug folder I've got :
- monogame.framework.dll
- nvorbis.dll
- openTK.dll
- openTK.dll.config
- test1.exe
- test1.exe.config
- test1.pdb
- test1.vshost.exe
- test1.vshost.exe.config
- test1.vshost.exe.manifest

I have added : sdl2.dll and openal32.dll (to try...)

I hope I don't push at open doors and sorry for my english!
Thanks for all your job
oldteen

**Comment by Tzenchor** [comment]
Does the SDL version match the Windows version bitness? If so, can you put the error message?

**Comment by mrhelmut** [comment]
With recent changes to DesktopGL, there is a couple changes which makes MonoGame sensitive to whether native dlls are 32 or 64bit. Try using the latest 64bit binary of SDL2 and add it to your project (as well as openal32.dll,  use the 64bit version of [OpenAL-Soft](http://kcat.strangesoft.net/openal.html) if you can, and rename it openal32.dll).

We're going to fix that by auto-deploying the good dlls to output folders and adding a mechanism that detects the good version to load at runtime. But for now, manually adding 64bit dlls is the way to go...

**Comment by oldteen** [comment]
Thanks a lot. My new tests :
- in 64 bits it's okay
- but still the error in 32 bits with 32 bits sdl library.

It's me or the DesktopGL template start directly in 32 bits mode ?

WindowsFormsApplication : platform target -> any CPU + Prefer 32-bit checkbox
DesktopGL : platform target -> x86

But for me it's okay :)
Thanks,
oldteen

**Comment by mrhelmut** [comment]
Yes, currently it is not well configured. It should be Any CPU and reference the correct native dlls depending on the process mode (the choice should be up to the .net runtime). I'll try to come up with this by 3.6, it also affects my own dev pipeline.
