### ISSUE TITLE
Fix TitleSafeArea

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#4840]
Looks like we've not implemented TitleSafeArea in MonoGame:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/Viewport.cs#L145
https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/DisplayMode.cs#L6
7

In XNA it was 20% of the screen, but see the notes Chuck Walbourn (XNA dev) that he left for us on this: https://github.com/mono/MonoGame/issues/4697#issuecomment-217779403.

We should be able to do 10% now as no one uses CRTs.

**Comment by willmotil** [comment]
it doesn't work right if i remember. i just tested it in win dx 
its even more messed up the the client bounds.
In xna it was used i think for letterboxing or wide screens that did that cutting of the top and bottom of the screen, or even under certain aspect ratios.
For windows on pc's and such it just basically was set to the application windows bounds.
