### ISSUE TITLE
Why is EffectResource internal? This would be helpful

### ISSUE THREAD

**Issue by Thraka** [mono/MonoGame#4842]
I was trying to go through basic 3d tutorials the other night (mostly old xna ones) and I keep running into the problem of having to build out my own effect. Why can't we have basic ones provided by monogame directly? It's an annoying pain to do it yourself when the framework already has some basics for you when you don't want to do anything special but render a simple object to the screen.

**Comment by tomspilman** [comment]
> Why can't we have basic ones provided by monogame directly?

I don't understand.  You can create a `BasicEffect` or any of the effects provided by MonoGame already.

**Comment by Thraka** [comment]
Ahh didn't realize that. Thanks.
