### ISSUE TITLE
Garbage reduction: GraphicsDevice.SetRenderTarget

### ISSUE THREAD

**Issue by KonajuGames** [mono/MonoGame#4843]
Add a `RenderTargetBinding[1]` member to `GraphicsDevice`.  In the implementations of `GraphicsDevice.SetRenderTarget(RenderTarget2D)` and `GraphicsDevice.SetRenderTarget(RenderTargetCube, CubeMap)`, populate the array with 'new RenderTargetBinding` and the parameters passed, then pass that array to the internal call to `SetRenderTargets()`.

This eliminates the garbage generated by the compiler-generated code to handle the `params`-style parameter lists.

**Comment by MichaelDePiazzi** [comment]
I actually came across this recently also, but I just haven't gotten around to submitting a PR for it. I'll get this submitted shortly.
