### ISSUE TITLE
Eto.Forms missing in Windows Solution

### ISSUE THREAD

**Issue by ralfjansson** [mono/MonoGame#4851]
Just updated my fork from the develop branch and tried rebuild the latest. All Projects build except the pipeline.windows tool. There seem to be two missing reference to Eto libs in this Project.

![missing ref](https://cloud.githubusercontent.com/assets/11855807/15255785/6592aef6-193e-11e6-8a91-cf62c7708e1e.png)

**Comment by cra0zy** [comment]
You need to update submodules... `git submodule update`

**Comment by ralfjansson** [comment]
Thank you. That worked.
