### ISSUE TITLE
I guess Memory is leaked in VideoPlayer or Video of DX

### ISSUE THREAD

**Issue by Daramkun** [mono/MonoGame#4860]
When I played Video, Memory is allocation large memory. It is good. but after video play, I tried play Same Video. Last Video's memory is not free and Current Video allocate another memory.
 
![a](https://cloud.githubusercontent.com/assets/1378304/15286021/bc0f1fb8-1b95-11e6-9c06-0d030837f641.png)

Test Project is [here](https://github.com/Daramkun/Liqueur).

Garbage Collection is running when Begin of Video play.

**Comment by Tzenchor** [comment]
Should be solved in #4811. There was a missing call to `Dispose`

**Comment by Daramkun** [comment]
Oh, I missed that issue. Thank you.
