### ISSUE TITLE
fxaa.fx(439,16) : Unexpected token ',' found. Expected Semicolon - This was working previously.

### ISSUE THREAD

**Issue by Linchy** [mono/MonoGame#4864]
Hi after upgrading to the latest Monogame, my FXAA shader no longer compiles. I get this output from the pipeline tool:

```
Build started 20/05/2016 16:17:34

C:/Users/a/Content/Shaders/fxaa.fx
C:/Users/a/Content/Shaders/fxaa.fx: C:\Users\a\Content\Shaders\fxaa.fx(80,18) : Unexpected token ',' found. Expected Semicolon
C:\Users\a\Content\Shaders\fxaa.fx(439,18) : Unexpected token ',' found. Expected Semicolon


Build 0 succeeded, 1 failed.

Time elapsed 00:00:00.87.
```

From the shader, these are the locations it references:

```
float4 FxaaPixelShader_PC(
    float2 pos,
    sampler2D tex, // <-- this comma
    float2 fxaaQualityRcpFrame,
    float fxaaQualitySubpix,
    float fxaaQualityEdgeThreshold,
    float fxaaQualityEdgeThresholdMin)
{
```

and

```
float4 FxaaPixelShader_Console(
    float2 pos,
    float4 fxaaConsolePosPos, 
    sampler2D tex, // <-- this comma
    float4 fxaaConsoleRcpFrameOpt,
    float4 fxaaConsoleRcpFrameOpt2,
    float fxaaConsoleEdgeSharpness,
    float fxaaConsoleEdgeThreshold, 
    float fxaaConsoleEdgeThresholdMin) 
{
```

**Comment by tomspilman** [comment]
Nothing has recently changed in this area that I remember.

What version of FXAA are you using?  The one we've used was FXAA 3.11.

The only thing I can think of is that you're trying to use legacy syntax in a 4.0 shader maybe.  HLSL 4.0 doesn't support `sampler2D` and the versions of FXAA I've used support that.

This all sounds like maybe you switched from using the OpenGL version of MonoGame (the DesktopGL platform) to the Windows DirectX version.

**Comment by Linchy** [comment]
I'm using the same I think, `NVIDIA FXAA 3.11 by TIMOTHY LOTTES`. Previosuly I was using Monogame Windows 3.4, and updated to Monogame.WindowsDX 3.5 via nuget.

I'm also getting a runtime error when trying to load another shader too:

`ContentManager.Load<Effect>(@"Shaders\ClearGBuffer");`

HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

```
struct vs_input
{
    float3 LocalPos : SV_Position0;
};
struct vs_output
{
    float4 Position : POSITION0;
};
struct ps_output
{
    float4 Colour : COLOR0;
    float4 Normal : COLOR1;
    float4 Depth : COLOR2;
};
vs_output VertexShaderFunction(vs_input input)
{
    vs_output output;
    float4 LocalPos = float4(input.LocalPos, 1);
    output.Position = LocalPos;
    return output;
}
ps_output PixelShaderFunction(vs_output input)
{
    ps_output output;
    output.Colour.argb = 0.0f;
    output.Normal.rgb = 0.5f;
    output.Normal.a = 0.0f;
    output.Depth = 1.0f;
    return output;
}
technique standard
 {
    pass Pass0
    {
        VertexShader = compile vs_4_0 VertexShaderFunction();
        PixelShader = compile ps_4_0 PixelShaderFunction();
    }
}
```

**Comment by tomspilman** [comment]
> I'm using the same I think,  NVIDIA FXAA 3.11 by TIMOTHY LOTTES .

Then define the following at the top of the fxaa file:
```
#define FXAA_HLSL_4 1
```
That tells it to use SM 4.0 syntax and not the legacy syntax.


> I'm also getting a runtime error when trying to load another shader too:

That is a different issue.  It was probably caused by this...

https://github.com/mono/MonoGame/pull/4195

Change your `SV_Position0` to just `POSITION0` in your input vertex structure.

Also in your output vertex structure you should be using `SV_Position0` and not `POSITION0`.

**Comment by Linchy** [comment]
Thanks that #define fixed it!

For the second shader I swapped the semantics as you said but no change. I did enable debug info though and got this in the output window `D3D11 ERROR: ID3D11Device::CreatePixelShader: Invalid shader version provided: ps_4_0 [ STATE_CREATION ERROR #193: CREATEPIXELSHADER_INVALIDSHADERTYPE]`.
