### ISSUE TITLE
Index/VertexBuffer.OpenGL GetBufferData

### ISSUE THREAD

**Issue by Jjagg** [mono/MonoGame#4876]
I came across GetBufferData in [Index](https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/Vertices/IndexBuffer.OpenGL.cs#L77) and [VertexBuffer](https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/Vertices/VertexBuffer.OpenGL.cs#L79) for OpenGL and noticed it's copying incorrectly.

    byte[] buffer = data as byte[];
    Marshal.Copy(ptr, buffer, 0, buffer.Length); 
should be

    byte[] buffer = data as byte[];
    Marshal.Copy(ptr, buffer, startIndex * elementSizeInByte, elementCount * elementSizeInByte);
right? Something similar is being done in VertexBuffer.OpenGL. This seems so obvious that it's a bit suspicious that it persisted in the codebase without anyone noticing, so that's why I'm double checking. If anyone can confirm I'll put up a PR.

**Comment by KonajuGames** [comment]
Most people don't get data from vertex or index buffers, especially
segments of the buffer. They're generally treated as write only. So that
function is not exercised a lot. That could be why the bug has existed for
so long.

**Comment by Jjagg** [comment]
That makes sense. I'll set up a PR tomorrow.

**Comment by Jjagg** [comment]
Fixed in #4882
