### ISSUE TITLE
Pipeline tool do NOT allow to change the ColorKeyColor property of any image

### ISSUE THREAD

**Issue by vcrobe** [mono/MonoGame#4887]
The pipeline tool **do not** allow to change the _ColorKeyColor_ property of any image.

![image](https://cloud.githubusercontent.com/assets/7717678/15616747/b597ec74-2413-11e6-88a9-2474956691c2.png)

**Comment by Tzenchor** [comment]
See #4885

**Comment by tomspilman** [comment]
This got broken in the develop branch with @cra0zy doing work on the Pipeline tool's GUI implementation.  It should be fixed soon.

**Comment by cra0zy** [comment]
That's the screenshoot from 3.5, develop branch already fixed this, also #4885 improves it even further.

**Comment by vcrobe** [comment]
Thank you guys for your quick response.

Keep working on this framework I love it!

**Comment by tomspilman** [comment]
Thanks @vcrobe !
