### ISSUE TITLE
GamePad does not return some properties for steelseries controller

### ISSUE THREAD

**Issue by vchelaru** [mono/MonoGame#4889]
I have tested this on an Apple TV with a steelseries controller. The following properties do not work. The steelseries controller does have appropriate hardware to return these values, but they return 0 or false despite the hardware being pressed:

- Buttons.LeftShoulder
- Buttons.RightShoulder
- ThumbSticks.Left
- Thumbsticks.Right
- Triggers.Left
- Triggers.right

The following properties are reporting values as expected:

- Buttons.A
- Buttons.B
- Buttons.X
- Buttons.Y
- DPad.Down
- DPad.Left
- DPad.Right
- DPad.Up

**Comment by tomspilman** [comment]
@dellis1972 - What is the status of Xamarin's tvOS support?

**Comment by vchelaru** [comment]
I have verified by looking in the code that only the buttons and dpad values are being assigned in GamePad.tvOS.cs.

**Comment by tomspilman** [comment]
Yeah... clearly it isn't even being set:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Input/GamePad.tvOS.cs#L134

Just something not addressed in the original PR.
