### ISSUE TITLE
EffectParameter.SetValue(string) not implemented

### ISSUE THREAD

**Issue by Jjagg** [mono/MonoGame#4893]
I just noticed [XNA's SetValue(string)](https://msdn.microsoft.com/en-us/library/bb198904.aspx) for an EffectParameter is not implemented in MonoGame. I don't know why you would want to pass data to a shader as a string, and it sure doesn't seem useful, but I came across it and saw it was implemented in XNA so here we are :)

**Comment by tomspilman** [comment]
Right...  I have no idea what `SetValue(string)` actually does in XNA or how it is used.

If it makes sense for MonoGame I don't mind adding it...  but it has to be something that can be beneficial to all platforms.
