### ISSUE TITLE
Pipeline Tool: rotation/scale of object cannot be modifed

### ISSUE THREAD

**Issue by InfiniteProductions** [mono/MonoGame#4905]
FBX object (at least) rotation & scale cannot be modified using Pipeline tool UI from dev branch.

double click on property didn't pop-up a way to edit value like ColorKeyColor for instance.

(editing content.mgcb, or whatever its name is, is the only way to do it for now)

**Comment by KonajuGames** [comment]
@cra0zy Some more property editors to add back in.
