### ISSUE TITLE
Remove GamePadDPad(params Buttons[] buttons) Ctor

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#4910]
We need to remove the constructor `internal GamePadDPad(params Buttons[] buttons)` and replace any usages of it with a non-param array constructor:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Input/GamePadDPad.cs#L77

This ctor only serves to generate array garbage and from what I can tell is unused in MonoGame.

**Comment by 06needhamt** [comment]
See PR #4970
