### ISSUE TITLE
Modifying default bound states

### ISSUE THREAD

**Issue by rds1983** [mono/MonoGame#4915]
Greetings,

Right now it is not possible to modify default bound state, i.e. if you do
`GraphicsDevice.BlendState.BlendFactor = Color.Red`
it'll throw an exception ("You cannot modify the blend state after it has been bound to the graphics device!").
So if you want to modify only blend factor(keeping other blend state parameters), you have to do following:
```
var state = GraphicsDevice.BlendState.Clone();
state.BlendFactor = Color.Red;
GraphicsDevice.BlendState = state;
```

Probably more correct approach is to mark the bound blend state(or any other state such as RasterizerState) as dirty on any parameter change and then reapply it before next render call.

I.e. solution that will allow changing BlendFactor of bound state would involve following steps:

1. Add method invalidating blend state to GraphicsDevice:

	    internal void InvalidateBlendState()
	    {
			_blendStateDirty = true;
	    }
2. Make sure BlendState.GraphicsDevice is set when the state is bound.
3. Call InvalidateBlendState when BlendFactor is changed:

	    public Color BlendFactor
	    {
	      get { return _blendFactor; }
              set
              {
                if (value == _blendFactor) {
                  return;
                }

                _blendFactor = value;
                GraphicsDevice.InvalidateBlendState();
              }
	    }

**P.S. Thanks for your work! MonoGame is great not only because it is game engine, but also because it is unique source of experience of how to operate the gaming hardware on C#.**

**Comment by KonajuGames** [comment]
Here is Shawn Hargreaves' [excellent explanation](https://blogs.msdn.microsoft.com/shawnhar/2010/04/02/state-objects-in-xna-game-studio-4-0/) of why XNA changed to state objects in XNA 4.0.

**Comment by tomspilman** [comment]
Hi @rds1983.

The reason `GraphicsDevice.BlendState.BlendFactor = Color.Red` doesn't work is because we specifically disabled that ability to match XNA and DirectX behavior.  I don't foresee any scenario where we will be changing this behavior.
