### ISSUE TITLE
DesktopGL doesn't run on some 32bit Windows

### ISSUE THREAD

**Issue by mrhelmut** [mono/MonoGame#4929]
We have some users which are unable to run our game on 32bit Windows systems.

The problem seems to be the OpenGL bindings. Every functions throw a ```PInvokeStackImbalance```.

@dellis1972 any clue?

**Comment by tomspilman** [comment]
This is pretty critical...  not surprised we missed this as few 32bit systems developers use these days.

A little googling shows the common culprit here is the `CallingConvention` on the Pinvoke being wrong.  Looking at our implementation it seems to be the correct `CallingConvention.Cdecl`...  that makes me thinking maybe the 32bit openal-soft DLL might be built using the `WinApi` calling convention and not cdecl.  The right fix here would be rebuilding the openal-soft to use cdecl to match the other platforms.

**Comment by mrhelmut** [comment]
It's the calls to GL which fail, not sure if we can do anything about the calling convention (is opengl bound to driver vendors or to the system?). But Cdecl works on 64bit Windows...
However, by replacing the calling convention, some functions work, but some other are throwing the exception (```GL.DepthRange()``` for instance) no matter the calling convention.

**Comment by endimilojkoski** [comment]
Yes, I can confirm that it is not working.
I had issues making Steamworks.NET working with x86 + x64 libs so I decided that I don't need x64 and tried to go with 32 bit only but I could not make it work.

And I just figured out what was the problem with Steamworks.NET for x64. In x64 folder I had to leave "steam_api64.dll" as is and not rename it to "steam_api.dll". Now everything is working for me in 64bit.

**Comment by mrhelmut** [comment]
>Yes, I can confirm that it is not working.
I had issues making Steamworks.NET working with x86 + x64 libs so I decided that I don't need x64 and tried to go with 32 bit only but I could not make it work.

>And I just figured out what was the problem with Steamworks.NET for x64. In x64 folder I had to leave "steam_api64.dll" as is and not rename it to "steam_api.dll". Now everything is working for me in 64bit.

This is how Steamworks.NET works, unrelated to MonoGame. :)
But if you force 32bit, you'll most probably run into the described issue.

**Comment by endimilojkoski** [comment]
Yes, I am not blaming MonoGame, just letting you know :)

**Comment by tomspilman** [comment]
> It's the calls to GL which fail,

Sorry... E3 crunch has me brain fried... saw OpenAL when you wrote GL. :)

> However, by replacing the calling convention, some functions work, but some other are throwing the exception ( GL.DepthRange()  for instance) no matter the calling convention.

Hum...   could we maybe not be defining the function signature for that correctly?

**Comment by mrhelmut** [comment]
You're right, ```GL.DepthRange(float, float)``` should be ```GL.DepthRange(double, double)```.

I'm going to take a closer on this issue.

**Comment by mrhelmut** [comment]
Found the answer here: http://www.mono-project.com/docs/advanced/pinvoke/

> The default CallingConvention is platform-specific. Under Windows, Winapi is the default, as this is used for most Win32 API functions. (Winapi is equivalent to Stdcall for Windows 9x and Windows NT.) Under Unix platforms, Cdecl is the default.

Setup'ing a PR!

**Comment by tomspilman** [comment]
Great!  Thanks @mrhelmut !

**Comment by cra0zy** [comment]
Till now, I always thought `Cdecl` was the default for all the OSs, I guess I learned something new :)

**Comment by mrhelmut** [comment]
The annoying thing is that Visual Studio only checks stack consistency when debugging 32bit processes. Which is why we never caught it...
