### ISSUE TITLE
Issue with Development monogame.run

### ISSUE THREAD

**Issue by Bulmanator** [mono/MonoGame#4933]
There is a problem with the current development .run installer on Linux. The standard one for MonoGame 3.5 works fine but when I try to run the development one it continuously spams './postinstall.sh: 10: ./postinstall.sh: line+=.: not found'
into the terminal and does not install. The only way to stop it is by using Ctrl+C

I am running Ubuntu Gnome 16.04. I have installed the latest version of Mono and MonoDevelop

**Comment by cra0zy** [comment]
@Bulmanator If you can, try out the installer from: http://teamcity.monogame.net/repository/download/MonoGame_PackageMacAndLinux/16547:id/Linux/monogame-sdk.run?guest=1

**Comment by Bulmanator** [comment]
This one seems to work, however when its trying to echo the dependencies it just comes up with
./postinstall.sh: 57: ./postinstall.sh: echodep: not found.
Does anyone know which package echodep is from, if it is a typo or which dependencies it's supposed to be asking for?

**Comment by cra0zy** [comment]
> Does anyone know which package echodep is from, if it is a typo or which dependencies it's supposed to be asking for?

https://github.com/cra0zy/MonoGame/blob/73b95c09c862cd4fffab76117c1be74f647d3b65/Installers/Linux/RUN/postinstall.sh#L4

**Comment by Bulmanator** [comment]
This is the output from running the run script:

Verifying archive integrity... All good.
Uncompressing Monogame Pipeline Installer.........................................................................................
./postinstall.sh: 4: ./postinstall.sh: function: not found
-e  - ...............................................\e[32m[Found]\e[0m
Dependencies:
./postinstall.sh: 52: ./postinstall.sh: echodep: not found
./postinstall.sh: 53: ./postinstall.sh: echodep: not found
./postinstall.sh: 54: ./postinstall.sh: echodep: not found

Optional Dependencies:
./postinstall.sh: 57: ./postinstall.sh: echodep: not found
./postinstall.sh: 58: ./postinstall.sh: echodep: not found
./postinstall.sh: 59: ./postinstall.sh: echodep: not found
./postinstall.sh: 60: ./postinstall.sh: echodep: not found

Continue (Y, n): Y
Installing MonoGame SDK...
Installing Rider files...
cat: found: No such file or directory
dirname: missing operand
Try 'dirname --help' for more information.
dirname: missing operand
Try 'dirname --help' for more information.
Installing MonoDevelop Addin...
Creating launcher items...
gtk-update-icon-cache: Cache file created successfully.
Adding mimetype...
To uninstall MonoGame SDK you can run "monogame-uninstall" from terminal.

I'm not too sure if this is the intended output however it installed fine regardless so thank you very much for your help. As this fixes the issue I will close it now
