### ISSUE TITLE
Stencil buffer is not working with OpenGL on NVIDIA graphics cards.

### ISSUE THREAD

**Issue by SzymonKatra** [mono/MonoGame#4960]
I've asked a question on MonoGame community forum and i was sent here to report an issue - http://community.monogame.net/t/opengl-stencil-buffer-problem-on-nvidia-graphics-card/7811

I tried to use stencil buffer in my game to do alpha masking. I followed this tutorial: https://medium.com/@sfranks/i-originally-wrote-this-for-the-best-way-to-mask-2d-sprites-in-xna-game-development-stack-949cf7bd7421#.wji9zxbjd

Using MonoGame Cross Platform Desktop Project (OpenGL) it worked only when I'm using integrated Intel's graphics card (Intel HD Graphics 5500).
When I tried to run it on NVIDIA card (tested with GeForce 940M, GeForce 220M and GeForce 7300GT) the whole image is displaying instead of masked parts.

On MonoGame Windows Project (DirectX) it works okay on Intel's card as well as on NVIDIA card.

I don't have an ATI card to check it on it.

Additionally, I've build an Android project and here it was working okay. (Samsung Galaxy Mini 2 - GT-S6500, Gingerbread 2.3.6, GPU Adreno 200 enhanced).

Source code used to test: http://pastebin.com/9zkUCiPt
Full Visual Studio solutions with OpenGL, DirectX and Android projects: https://www.dropbox.com/s/ivaz58j8omhd3nw/stenciltest.zip?dl=1

Screenshot of valid result: http://i.imgur.com/mryF0W8.png
Invalid: http://i.imgur.com/eswi8N8.png

**Comment by InfiniteProductions** [comment]
I've tested the project with my hardware (NV GTX 780M) same issue.

win 7 64b, MG 3.5.1
Note: I can't test with MG dev (build 29/05/2016, source may be one, two days max older) as it failed because of a missing SDL2.dll (I've never use MG winGL)

**Comment by tomspilman** [comment]
@dellis1972 @cra0zy @mrhelmut 

This might be a bug from the switch to new bindings.

**Comment by mrhelmut** [comment]
Tested on latest develop with AMD and Intel hardware, and it works fine (same result as DX). I'll try on NVIDIA later today.

**Comment by SzymonKatra** [comment]
@mrhelmut Thanks. The sample provided by you works fine on my NVIDIA card and integrated Intel. The M shape is displaying correctly.

So it means that the next release will have fixed this bug?

**Comment by mrhelmut** [comment]
@SzymonKatra Yes, you can consider this fixed. :)

**Comment by SzymonKatra** [comment]
@mrhelmut Okay, thanks for help :) Should I close an issue or leave it as is it now?

**Comment by mrhelmut** [comment]
You can close it. Thanks.

**Comment by InfiniteProductions** [comment]
@mrhelmut : thanks, I'll need to check against latest dev, I guess some fix has been made after my snapshot, I'll give it a try soon.

**Comment by mrhelmut** [comment]
@InfiniteProductions all the GL/AL bindings have been changed in favor of SDL2, you will have to check the new template because the dependencies and libraries folders have changed (which is probably why you had a missing SDL when trying it).

**Comment by InfiniteProductions** [comment]
@mrhelmut: yes thanks, I figured this out before, I have just start by downloading official SDL2 build.

Did the test again (with MG dev sync'ed and rebuilt just a few minutes ago), it work as expected.
