### ISSUE TITLE
Weird fullscreen behavior on DesktopGL platform with multi-montor setup

### ISSUE THREAD

**Issue by artganify** [mono/MonoGame#4973]
I'm trying to launch a monogame application targeting the *DesktopGL* package (OpenTK) in fullscreen mode with a custom resolution. This works all fine as long as I have only a single monitor enabled. However when I enable a second one, the resolution of the first one gets set while the actual game is rendered on the second monitor in borderless windowed mode.

Here's a screenshot to clarify what's happening:

![wtf](https://i.imgur.com/aVHGePO.png)

The code to setup the fullscreen:

    _graphics.CreateDevice();
    _graphics.IsFullScreen                                    = _gameSettings.IsFullScreen;
    _graphics.SynchronizeWithVerticalRetrace     = _gameSettings.EnableVerticalSync;
    _graphics.PreferredBackBufferWidth              = _gameSettings.Resolution.Width;
    _graphics.PreferredBackBufferHeight             = _gameSettings.Resolution.Height;
    _graphics.ApplyChanges();

This is invoked in the `Initialize()` method right before the call to `.base.Initialize()`, however I've tried various different combinations (e.g. initializing the `GraphicsDeviceManager` in the .ctor, with or without calling `GraphicsDeviceManager.ApplyChanges();` etc.)

Is this a known problem? Does fullscreen even work on that platform?

**Comment by tomspilman** [comment]
@artganify - Are you using the MonoGame 3.5 release?  Or are you using one of the development releases?

**Comment by artganify** [comment]
@tomspilman I am using `3.5.1.1679`.

**Comment by tomspilman** [comment]
We should test this on the current development build of 3.6.  We've completely replaced OpenTK with SDL2 so the behavior is likely completely different now.

**Comment by cra0zy** [comment]
This is an issue with OpenTK, and the new SDL backend in devel does fix it. This should probably be closed.

**Comment by artganify** [comment]
I can confirm this doesn't happen with the 3.6 pre-release of MonoGame using SDL. Can be closed.
