### ISSUE TITLE
Pipeline: renaming effect => invalid leading '\' added in Content.mgcb

### ISSUE THREAD

**Issue by InfiniteProductions** [mono/MonoGame#4976]
Having an effect file.fx, rename it, with pipeline tool (build from today MG source update):

file.fx become => **\**file.fx as the example below

```
#begin \PPDepthNormalMod.fx
/importer:EffectImporter
/processor:EffectProcessor
/processorParam:DebugMode=Auto
/build:\PPDepthNormalMod.fx
```
(effect PPDepthNormal.fx renamed to PPDepthNormalMod.fx from pipeline itself)

Then, there is an error when building project using this content (kind of "filepath format no handled", damned MS with their translate-everything-madness) from both pipeline itself and VS.

Win7 64b, VS 2015 Com. Ed., MG dev windows(DX) platform, x86 arch, tools and libs build for anycpu arch.

**Comment by cra0zy** [comment]
@tomspilman #4986 fixed this, this should be closed.
