### ISSUE TITLE
Bug at project build

### ISSUE THREAD

**Issue by Thejuster** [mono/MonoGame#4981]
Error		exit command  ""C:\Program Files\MSBuild\MonoGame\v3.0\Tools\MGCB.exe" /@:"c:\users\*****\documents\visual studio 2015\Projects\Mire\Mire\Content\Content.mgcb" /platform:DesktopGL /outputDir:"c:\users\*******\documents\visual studio 2015\Projects\Mire\Mire\Content\bin\DesktopGL" /intermediateDir:"c:\users\giovanni\documents\visual studio 2015\Projects\Mire\Mire\Content\obj\DesktopGL" /quiet" on code -1.	Mire			

How to fix?

**Comment by cra0zy** [comment]
You should have an output console which will tell you what's wrong.

Alternative way is to open up .mgcb file and try and build it from the tool.

**Comment by Thejuster** [comment]
Hello cra0zy i have try whit prompt.

console say same error and this:

The MonoGame content tools only work on a 64bit.

Monogame is only for 64bit?

**Comment by tomspilman** [comment]
> The MonoGame content tools only work on a 64bit.

Yes...  the MonoGame content tools only work on 64bit systems.  

MonoGame itself runs on 32bit or 64bit.

**Comment by Thejuster** [comment]
Oh tanks.
Now need to install a 64bit OS for convert my project.
Tanks to all

**Comment by cra0zy** [comment]
Close the issue.

**Comment by flexo717** [comment]
![image](https://user-images.githubusercontent.com/70512071/96858892-8460f380-1469-11eb-8879-ef8aaaff1d25.png)
umh... how about that?

**Comment by harry-cpp** [comment]
You've installed 32 bit dotnet sdk instead of a 64 bit.

**Comment by flexo717** [comment]
no, net core SDK is installed
![image](https://user-images.githubusercontent.com/70512071/96893519-73c57300-1493-11eb-8890-541bb0e39d6a.png)

**Comment by Apostolique** [comment]
What do you get when you enter: `(gcm dotnet).Path` in powershell?
