### ISSUE TITLE
Can't create new Windows 10 UWP app

### ISSUE THREAD

**Issue by JranZu** [mono/MonoGame#4983]
Similar issue to: https://github.com/mono/MonoGame/issues/4435 however uninstalling & reinstalling the Universal Windows App Development Tools did NOT solved the issue.  I am able to create & publish normal windows 10 apps without any issue.

Running the latest version of MonoGame 3.5.1

_Error: the vstemplate file references the wizard class 'Microsoft.VisualStudio.WinRT.TemplateWizards.ApplicationInsights.Wizard' which does not exsist in the assembly 'Microsoft.VisualStudio.WinRT.TemplateWizards, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'._

**Comment by cra0zy** [comment]
Can you create a normal UWP application?

**Comment by JranZu** [comment]
> I am able to create & publish normal windows 10 apps without any issue.<

**Comment by tomspilman** [comment]
Likely MS changed the templates for UWP in their latest release.  Someone will need to compare our template with a default UWP template and look for the differences.

**Comment by kuromiaika** [comment]
in template(WindowsUniversal.vstemplate) remove this >>>
![pic0_mgwup_](https://cloud.githubusercontent.com/assets/20325950/16632180/27b62dae-43ed-11e6-8461-d7888a12b634.jpg)
![pic1_mgwup_](https://cloud.githubusercontent.com/assets/20325950/16632181/27bed2a6-43ed-11e6-8522-5d95e651174f.jpg)

<WizardExtension>
    <Assembly>Microsoft.VisualStudio.WinRT.TemplateWizards, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a</Assembly>
    <FullClassName>Microsoft.VisualStudio.WinRT.TemplateWizards.ApplicationInsights.Wizard</FullClassName>
  </WizardExtension>

**Comment by bilamjad** [comment]
Hi @PumpkinPudding, 

Can you please suggest where this template file is located so I may remove it as I am facing this error.

**Comment by GrantMeStrength** [comment]
Hi @bilamjad 

The template is not where you might expect. It's actually:

C:\Users\<your account>\Documents\Visual Studio 2015\Templates\ProjectTemplates\Visual C#\Visual C#\MonoGame

**Comment by BrainSlugs83** [comment]
Any chance this will be back ported to the current release? -- It's impossible to create Windows 10 UWP projects without this fix. -- It's literally just updating one zip file in the installer...
