### ISSUE TITLE
IsButtonDown(Buttons.RightTrigger) always returning false on Cross Platform project

### ISSUE THREAD

**Issue by Saliken** [mono/MonoGame#4995]
As the title states, when I attempt to use the isButtonDown method of a GamePadState to check if Buttons.RightTrigger or Buttons.LeftTrigger are down it always returns false. The trigger values report accurate amounts however.

This occurs in the Cross Platform Project specifically, and does not appear to happen in any of the windows projects.

**Comment by tomspilman** [comment]
@Saliken - This is fixed in the develop branch now.
