### ISSUE TITLE
XML doc for Matrix.Add contradicts what the code actually does

### ISSUE THREAD

**Issue by prime31** [mono/MonoGame#5017]
The XML doc says it creates a new Matrix but the code actually just puts the result in matrix1 and returns it.

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Matrix.cs#L425

Is this method supposed to create a new Matrix (code is incorrect) or is it supposed to put the result in matrix1 (XML doc is incorrect)?

**Comment by prime31** [comment]
Duh. Face palm. I was just debugging a matrix *class* that someone else wrote and forgot to switch my brain back to struct.

**Comment by tomspilman** [comment]
It happens all the time to me too.
