### ISSUE TITLE
RenderTarget2D throws SharpDXException when width and/or height is great enough

### ISSUE THREAD

**Issue by StunGunStudios** [mono/MonoGame#5019]
After switching from the stable 3.5 release to the latest development build of Monogame, I ran into a few problems. One of them has been resolved already, another has an open issue, #4740, and the last is this.

In my game, in order to avoid drawing a lot of tiles at once, which was eating up CPU, I set it up so that the tiles are drawn to a RenderTarget2D and the RenderTarget2D itself is drawn instead, and only updated as needed when tiles are added or removed. I initialized the RenderTarget2D something like this:

`blocks = new RenderTarget2D(graphics.GraphicsDevice, 10000, 10000);`

With 3.5, this works fine. But with the latest build, it throws a SharpDXException, with the following information (I edited out the irrelevant parts of the stack trace):

> SharpDX.SharpDXException was unhandled
>   HResult=-2147024809
>   Message=HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.
> 
>   Source=SharpDX
>   StackTrace:
>        at SharpDX.Result.CheckError()
>        at SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
>        at Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
>        at Microsoft.Xna.Framework.Graphics.RenderTarget2D.GenerateIfRequired()
>   InnerException: 

Further experimentation showed that the exception is directly related to the size of the RenderTarget2D being initialized. Constructing it at a much smaller width and height works fine. I did some testing and found the point where the exception is thrown.

This constructor works fine.

`blocks = new RenderTarget2D(graphics.GraphicsDevice, 4096, 4096);`

This constructor throws the exception.

`blocks = new RenderTarget2D(graphics.GraphicsDevice, 4097, 4096);`

4096 is a very binary number... That doesn't seem like a coincidence. Is this a bug or a correct limit to the size of a RenderTarget2D?

**Comment by InfiniteProductions** [comment]
Not showing the inner exception is unfortunate, as it is the one which gives more info.

Then, RenderTarget2D ARE Texture2D (declared as: `public class RenderTarget2D : Texture2D, IRenderTarget`).
This means the exact same limitations/requirements applied: texture MUST BE power of 2 (hardware requirement AFAIK followed by software, OpenGL & DirectX).
4097 or 10000 are not power of 2 numbers (not "binary") this may explain the "issue" (`Message: The parameter is incorrect.` as given by SharpDX)

**Comment by nkast** [comment]
4096. That's the Max Texture Dimension limit of your GPU. 
https://msdn.microsoft.com/en-us/library/windows/desktop/ff476876(v=vs.85).aspx

**Comment by StunGunStudios** [comment]
@InfiniteProductions There was no inner exception, that's why it's blank. Also, 4095 by 4095 works just as well as 4096 by 4096, as well as any number combination below 4096, so I don't think it's strictly a power of two issue. But yes, something must have changed in SharpDX.

@nkast Why did my maximun texture dimension decrease with the newer version of Monogame?

**Comment by StunGunStudios** [comment]
I figured it out, it's related to the graphics profile. When I programmatically set the profile to HiDef, I could initialize the RenderTarget2D to 10000 by 10000 again, so I guess 3.5 was defaulting to HiDef, whereas now it's defaulting to Reach.
