### ISSUE TITLE
Text rendering glitched with non black color

### ISSUE THREAD

**Issue by maxlothaire** [mono/MonoGame#5036]
Hello.

My problem is simple : 

Text in black :  
![capture_monogame_bug_text_noir](https://cloud.githubusercontent.com/assets/8596650/17182362/8990c246-5423-11e6-9b1c-e19e8eab33be.png)

Same text and same font in White : 
![capture_monogame_bug_text_blanc](https://cloud.githubusercontent.com/assets/8596650/17182422/b8ecf172-5423-11e6-899e-41c034ab76ee.png)

You can see, the white text is a little glitched.

Am I the only one who encountered this problem ? 

I am on Ubuntu 16.04 and i installed monogame 3.5 sdk from the [official download page](http://www.monogame.net/downloads/).

**Comment by KonajuGames** [comment]
The artifacts are from the DXT compression.  I would suggest changing the TextureFormat property in the SpriteFont Processor in the content project to Color.  This will prevent any compression being used, at the cost of a larger texture.  We do know how this can be fixed for DXT compression (a customized compressor for font textures), but it is not yet implemented and we also need to be able to do the same for other platforms that use different texture compression (ETC1, PVRTC, etc).

**Comment by maxlothaire** [comment]
That worked !

Thanks a lot ! :)
