### ISSUE TITLE
Initalizing Texture2D from a background thread => lock

### ISSUE THREAD

**Issue by WaaghMan** [mono/MonoGame#515]
When loading a Texture2D from a thread (via ContentManager.Load<>), that thread gets locked.

I've checked a bit the internals and it looks like Threading.BlockOnUIThread() is called, resulting in the action added to a pending action list (so the UI thread can perform them later), but this never happens ( Threading.Run() is not even called once in MonoGame? )

**Comment by Shqrdx** [comment]
@tomspilman I guess he tried initialize OpenGL content in separate thread. Of course it fails. Does this issue is neccessary or should be closed ?

**Comment by tomspilman** [comment]
I think this is fixed/hacked to work on OpenGL with the resource creation being done on the main thread under the hood.

**Comment by tomspilman** [comment]
This is fixed for OpenGL and DirectX.

**Comment by Mindfulplays** [comment]
Thanks for fixing this in OpenGL / DirectX. I found this doesn't work yet for iOS #7520
