### ISSUE TITLE
PreferredBackBufferWidth/Height has no effect on Linux.

### ISSUE THREAD

**Issue by AmonTessin** [mono/MonoGame#628]
I'm using the develop3d brach on Linux and the PreferredBackBufferWidth/Height properties have no effect on windowed mode. I also tried modifying the presentation parameters directly, with no effect.

I've been wandering through the GraphicsDeviceManager's source code and I saw it's a little messed up. I think I could do some refactor, but it has no comments and I won't be able to rewrite the cross-platform code. Anyway, I'd like to help to track down the issue.

**Comment by cra0zy** [comment]
#3315 fixed this

**Comment by made-pvale** [comment]
This Just happened with me today on Ubuntu 20.04 using Monogame 3.8 but changing the order from
```
_graphics.IsFullScreen = false;
_graphics.PreferredBackBufferWidth = 300;
_graphics.PreferredBackBufferHeight = 420;
```

to
```
_graphics.PreferredBackBufferWidth = 300;
_graphics.PreferredBackBufferHeight = 420;
_graphics.ApplyChanges();
_graphics.IsFullScreen = false;
```

Fixed it. Had to add the _graphics.ApplyChanges in my Game Constructor.

**Comment by harry-cpp** [comment]
@made-pvale already fixed in develop https://github.com/MonoGame/MonoGame/pull/7299
