### ISSUE TITLE
Texture2d GetData throws Not implemented exception

### ISSUE THREAD

**Issue by rsolberg1** [mono/MonoGame#644]
Issue is in the 3d branch. I am currently porting a game from WP7 XNA to WIndows 8 Metro using MonoGame With SharpDX.

Exception is thrown by the following line:
graphicsDevice._d3dContext.CopySubresourceRegion(_texture, level, null, stagingTex, 0, 0, 0, 0);

Seems like the implementation of CopySubresourceRegion is missing in the SharpDX 2.2.0.7 build implementation (SharpDX.Direct3D11.dll) and not in the MonoGame framework itself. Strange, because whoever did the job first time would have the SharpDX implementation correct.

I am using the MonoGame GetData Method to pick a texture area from a sprite:
Texture2DSpriteSheet.GetData(0, rec1, col1, 0, scoreNumber.Width * scoreNumber.Height);

**Comment by Shqrdx** [comment]
@tomspilman I guess this issue is obsolete. SharpDX is about 3.0.0 version already and I have not problems with GetData on Windows 8.
