### ISSUE TITLE
GraphicsDevice.ApplyChanges leads to a blank, black screen in Win8

### ISSUE THREAD

**Issue by aschearer** [mono/MonoGame#649]
I have a handler which responds to Game.ApplicationViewChanged and:

  1. Updates the desired back buffer width and height to match the window size
  2. Applies changes

I'm finding when I call ApplyChanges the screen goes black (I'm clearing screen with CornflowerBlue so black is definitely not from me).

**Comment by tomspilman** [comment]
Win8 is old.
