### ISSUE TITLE
Develop3d Building Texture on second thread might cause crash

### ISSUE THREAD

**Issue by Eversor** [mono/MonoGame#655]
I am constructing a Texture2d on a secondary thread while the main one is sleepy
the texture2d constructor calls  Threading.BlockOnUIThread
that in short stops current thread and performs the argument's action in the main thread
this causes a hangup of the whole application since the main thread cannot perform the request
This is not appening on original xna implementation from MS

**Comment by tomspilman** [comment]
This should work now.
