### ISSUE TITLE
Screen resizing no longer working after Game.Initialize() call with ApplyChanges().

### ISSUE THREAD

**Issue by Inverness** [mono/MonoGame#669]
After updating to the most recent version of the develop3d branch, I'm no longer able to resize the game window using the following code in my game class Initialize() method if placed after the base.Initialize() call. It does still work when placed before the base.Initialize() call however.
```C#
Graphics.PreferredBackBufferWidth = 1024;
Graphics.PreferredBackBufferHeight = 768;
Graphics.ApplyChanges();
```

**Comment by cra0zy** [comment]
@tomspilman I've tested this and it seems that it has been fixed.
