### ISSUE TITLE
Error trying to load a 3D Model "Unknown vertex element usage!"

### ISSUE THREAD

**Issue by SniperED007** [mono/MonoGame#733]
My 3D model is looking at trying to load this Microsoft.Xna.Framework.Graphics.VertexElementUsage.Binormal but it doesn't appear to be supported yet? (Windows Metro)

Is this something that's going to be supported later on or do I need to do something to my model files to prevent this from happening?

Here is the file im trying to load https://dl.dropbox.com/u/74231/Grenades.zip
The mesh is GrenadePickup_mesh.xnb

Thanks,
ED

**Comment by tgjones** [comment]
This can be closed - the two lines suggested above are now in VertexElement.DirectX.cs:
https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/Vertices/VertexElement.DirectX.cs#L48

**Comment by KonajuGames** [comment]
Thanks for checking. Closing.
