### ISSUE TITLE
Wrong parameter used in BeginShowMessageBox

### ISSUE THREAD

**Issue by horeaper** [mono/MonoGame#739]
Original discussion thread: http://monogame.codeplex.com/discussions/392571

Version: 2.5.1
File: MonoGame.Framework\Windows\GamerServices\Guide.cs
Method: BeginShowMessageBox
Platform: Windows/iOS/Android
Line: 172-176 

This parameter get ignored: Object state.
Problem possibly caused by code: return smb.BeginInvoke(title, text, buttons, focusButton, icon, callback, smb);

The returned IAsyncResult.AsyncState will not have the correct value since MonoGame used it internally for a ShowMessageBoxDelegate.

Suggestion fix is create a custom class which implement IAsyncResult, and also has an IAsyncResult as field.  Assign the return value of "smb.BeginInvoke" (Line 176) and "smb" variable to the custom class. Then return this class to the caller.
The implementation of that custom class just extract all value from it's IAsyncResult field and return to the user. By this way "EndShowMessageBox" can easily get the ShowMessageBoxDelegate without the need to mess around IAsyncResult.AsyncState.

Code here:

class BeginShowMessageBoxAsyncResult : IAsyncResult
{
 internal IAsyncResult result;
 internal ShowMessageBoxDelegate smb;

 public object AsyncState
 {
  get { return result.AsyncState; }
 }

 public WaitHandle AsyncWaitHandle
 {
  get { return result.AsyncWaitHandle; }
 }

 public bool CompletedSynchronously
 {
  get { return result.CompletedSynchronously; }
 }

 public bool IsCompleted
 {
  get { return result.IsCompleted; }
 }
}

public static IAsyncResult BeginShowMessageBox(
   PlayerIndex player,
   string title,
   string text,
   IEnumerable<string> buttons,
   int focusButton,
   MessageBoxIcon icon,
   AsyncCallback callback,
   Object state
 )
{ 
 isVisible = true;

 ShowMessageBoxDelegate smb = ShowMessageBox;

 IAsyncResult asyncResult = smb.BeginInvoke(title, text, buttons, focusButton, icon, callback, state);

 BeginShowMessageBoxAsyncResult result = new BeginShowMessageBoxAsyncResult();
 result.result = asyncResult;
 result.smb = smb;
 return result;
}

public static Nullable<int> EndShowMessageBox (IAsyncResult result)
{
 if (!(result is BeginShowMessageBoxAsyncResult)) {
  throw new ArgumentException();
 }
 
 try
 {
  BeginShowMessageBoxAsyncResult customResult = (BeginShowMessageBoxAsyncResult)result;
  return customResult.smb.EndInvoke(customResult.result);
 } 
 finally 
 {
  isVisible = false;
 }
}

**Comment by tomspilman** [comment]
This API is going to be depreciated... closing.
