### ISSUE TITLE
Stretched images after start the game in portrait mode

### ISSUE THREAD

**Issue by mfpereira** [mono/MonoGame#759]
I have a small project that only draws a small circle (60px of radius) on the screen.

If i start the game on the simulator in landscape mode, everything works fine. I can change the orientation from landscape to portrait mode, and vice versa, without problems. 

The problem happens if I start the game in portrait mode. The circle is not shown as a circle, but as an ellipse and never goes back to normal.

[Expected]

The circle should appears like a circle. (radius = 60px)

[Result]

The circle appears like an ellipse.

**Comment by tomspilman** [comment]
Win8 is old... closing.
