### ISSUE TITLE
SoundEffect causes crash when exiting Windows 8 app

### ISSUE THREAD

**Issue by KonajuGames** [mono/MonoGame#786]
From codeplex http://monogame.codeplex.com/discussions/396015

Just added sound effects to my game and they work great, however, when I exit(); with the escape key, the app crashes the debugger. The program '[4108] Geared.exe: Managed (v4.0.30319)' has exited with code -1073610751 (0xc0020001).

If I comment out:

soundEffect = Content.Load<SoundEffect>("chime");

Then the app does not crash on exit.  Again, the sound effect works during gameplay, but appears to add a crash to exit();

**Comment by Shqrdx** [comment]
@tomspilman This issue is fixed.
