### ISSUE TITLE
Add PrimitiveBatch from DirectXTK

### ISSUE THREAD

**Issue by amerkoleci** [mono/MonoGame#871]
Add PrimitiveBatch from DirectXTK.
Reference: http://blogs.msdn.com/b/shawnhar/archive/2012/10/12/directxtk-primitivebatch-helper-makes-it-easy-to-draw-user-primitives-with-d3d11.aspx

**Comment by Shqrdx** [comment]
I would like to see PrimitiveBatch. Imagine you could create cubes, triangles or spheres in few line of code from box. It is definitly a good addition.

**Comment by killerrin** [comment]
@Shqrdx There is a PrimitiveBatch made in the same style as SpriteBatch over on http://xbox.create.msdn.com/en-US/education/catalog/sample/primitives

Its pretty basic, but with a few minutes one could add in a few helper methods to easily create specific shapes.

**Comment by tgjones** [comment]
This seems like a great fit for an extension library (perhaps @craftworkgames's MonoGame.Extended?), but at this point, I think this can be closed, unless anybody strongly disagrees and is willing to submit a PR.

**Comment by craftworkgames** [comment]
Yep. We've talked about adding this to MonoGame.Extended for a while now. We added some basic [shapes drawing using SpriteBatch extensions](https://github.com/craftworkgames/MonoGame.Extended/issues/31) but I think a `PrimitiveBatch` implementation would be a better way to go.

I've raised an issue to get it included in MonoGame.Extended so you can close this one.

**Comment by KonajuGames** [comment]
Thanks guys.  Closing.
