### ISSUE TITLE
Colored triangle (using vertex colors) renders white

### ISSUE THREAD

**Issue by vchelaru** [mono/MonoGame#894]
I have a simple-to-reproduce case where a simple triangle does not render properly. Here is the source code which can be pasted into a Game class to reproduce the error:

http://pastebin.com/HbW0PVif

This exact code in XNA 4 (on the PC) results in a triangle with the verts being red/green/yellow. On Android (specifically Motoroal Droid Razr) renders the triangle correctly for 1 frame.  The next frame the triangle renders, but it renders white instead of colored.  I suspect something is not being preserved in the states frame-to-frame; however in my investigation of the code it looks like we're using pixel shaders, which I'm not as familiar with in open GL - were it fixed function I may have been able to identify the issue.

Anyway, given the relatively easy repro steps I don't think it'll be hard for those more knowledgeable with OGL to figure out what's going on.

**Comment by Shqrdx** [comment]
@tomspilman I think this issue should be closed. The amount of work that should be done for fixing it is huge. The XNA shares one technique whereas MonoGame shares 32 technique within one BasicEffect. And as you look into
http://pastebin.com/HbW0PVif you could observe 
> foreach (var pass in _effect.Techniques[0].Passes)

 is incorrect, there must be

 > foreach (var pass in _effect.CurrentTechnique.Passes)

**Comment by tomspilman** [comment]
> is incorrect

Yeah... does XNA even allow rendering of passes that are outside the current technique?  It seems dangerous and unnecessary really.  Switch techniques if you need to switch techniques.

**Comment by Shqrdx** [comment]
The code above draws colored triangle correctly on XNA, but it is incorrect by nature.

**Comment by tomspilman** [comment]
Yeah... I say it is invalid even in XNA.  It just happens to work.
