### ISSUE TITLE
Can't install project templates

### ISSUE THREAD

**Issue by biscuitWizard** [mono/MonoGame#898]
I've compiled the Linux project templates and copied the MonoDevelopment.MonoGame folder into /usr/lib/monodevelop/AddIns/. MonoDevelop 3.1 just crashes on startup aftwards.

**Comment by cra0zy** [comment]
The new monodevelop/xs addon is being worked on: #3361

**Comment by cra0zy** [comment]
@tomspilman This can be closed, it has been fixed with #3698
