### ISSUE TITLE
GL ES 2.0 bad performances 

### ISSUE THREAD

**Issue by johnHolmes** [mono/MonoGame#909]
It seems that MG 3.0 is performing bad than MG 2.0 with GL ES 1.1. 

Forum topic
http://monogame.codeplex.com/discussions/401025

I've prepared as mall test app which test performances of GL ES 1.1 (MG2.0) and GL ES 2.0 (MG 3.0)

you can find here the app

https://dl.dropbox.com/u/40411013/MonoGame/MGPerfTest.zip

The zip contains:

  - A simple small app for iOS built with MonoDevelop and MT (You need a valid MT license to deploy to real device). Well commented.
  - Our version of MG 2.0 which contains billions of fixes (this makes the MG 2.0 quite stable on iOS and Android ONLY, we currently use this for production)
  - The latest version of MG 3.0 (branch3d) downloaded from github

To test performances just run the application (on real device please). To change from MG 2.0 to MG 3.0 just change project reference.

Tests have been made using ARMV7 optimized compilation (no thumb-2) iOS min version is 4.0

Our results are:

- MG 2.0 (GL ES 1.1) on iPhone4 with iOS6, 200 sprites 64x64: 60 FPS
- MG 3.0 (GL ES 2.0) on iPhone4 with iOS6, 200 sprites 64x64: ~44 FPS 

Any help will be appreciated!

Francesco - Ad Maiora Studio

**Comment by tgjones** [comment]
Is this still relevant? Looks like GL float precision was switched from `highp` to `mediump` shortly after this issue was raised.

> FPS are now ~=55 but not stable as MG2 More over, the render update is not fluid. I suspect this is related to the other issue where MG3 drop some draw frames.

Given the amount of time that has elapsed between then and now, it's going to be hard to test comparisons between MG2 and MG3.

**Comment by tomspilman** [comment]
Yea... This is not relevant anymore.
