### ISSUE TITLE
3D depth buffer seems stuck at 16 bits on Windows

### ISSUE THREAD

**Issue by SaintGimp** [mono/MonoGame#920]
My 3D app, originally written in XNA, needs a 24-bit depth buffer and it worked fine in XNA.  After porting to MonoGame it's behaving as though the depth buffer is locked at 16-bits because I get a lot of z-fighting that looks pretty much like what I get with the XNA version if I request a 16-bit depth buffer.  With MonoGame, even if I request DepthFormat.None it still behaves like it's using a 16-bit buffer rather than no buffer at all.

Using 3.0 beta (updated 10/25) on Windows 7, Visual Studio 2010.

**Comment by tgjones** [comment]
Looks like this can be closed - it was fixed by #2398.
