### ISSUE TITLE
Visual Studio 2012 Express Projects Not Appearing

### ISSUE THREAD

**Issue by MichaelTFamiglietti** [mono/MonoGame#925]
I installed MonoGame with the Visual Studio 2012 templates on. I see that it made a folder in my "Visual Studio 2012\Templates\ProjectTemplates\Visual C#\MonoGame" folder, but Visual Studios 2012 Express doesn't see them when creating a new project. 

I then put the Visual Studios 2010 templates from "Visual Studio 2010\Templates\ProjectTemplates\Visual C#\MonoGame" into the 2012 folder. It worked and they appeared in Visual Studios 2012 Express.

**Comment by Shqrdx** [comment]
@tomspilman This issue is obsolete, unnecessary, fixed and outdated.

**Comment by tomspilman** [comment]
@Shqrdx - Thanks for helping identify closed issues...  it helps!
