### ISSUE TITLE
MonoGame and Lidgren.Network assemblies not copied to output folder from the project templates.

### ISSUE THREAD

**Issue by 7sharp9** [mono/MonoGame#970]
In the project templates for Mac (Both C# and the F# one I added ) the MonoGame and Lidgren.Network dll's are not copied to the output folder.

I know there is the code in:
`PopulateSupportFileList(FileCopySet list, ConfigurationSelector solutionConfiguration){...}`
to address MD not local-copying package references.   [MonoDevelop bug 4030][1]

I also have been using a package config file that points to my compiled dlls's so that the project references don't show up as missing in MD:

```
Name: monogame
Description: MonoGame.Framework.MacOS
Version: 2.0.0.0
Libs: -r:/Users/dave/code/7sharp9MonoGame/MonoGame.Framework/bin/Release/MonoGame.Framework.MacOS.dll -r:/Users/dave/code/7sharp9MonoGame/MonoGame.Framework/bin/Release/Lidgren.Network.dll
```

Maybe this will be all resolved when the installer is complete for the Mac, but it would be nice to get this working in a development environment as the v3.0 build will probably be in flux for some time and I think getting the starter project simple to installed and use would drive adoption and experimentation

[1]: https://bugzilla.xamarin.com/show_bug.cgi?id=4030

**Comment by cra0zy** [comment]
#3361

**Comment by cra0zy** [comment]
@tomspilman This has been fixed with new project templates.
